### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [ChordPro/chordpro#100]
... and probably a not-the-brightest one.

I was thinking about putting up my personal hymn (re-)translations up on GitHub, and thought chordpro format would be a idea. I can have chord-ed song, and comments that don't render out in the `pdf`. And I was beginning to wonder if we could have multiple languages for the same song in chordpro. That would be greatly beneficial to churches, and song/hymn translators. I understand that chordpro might not be the tool designed for the job. If so, could someone please guide me to the correct one? Something better suited for song translations?

I'm thinking I can have some thing like
```
# Original Lyrics In Language A
Translated Lyrics in Language B
# Comments, translators notes, etc.
# Original Lyrics in Language A (line 2)
Translated Lyrics in Language B (line 2)
# Comments, translators notes, etc.
```

It is my hope that many linguistically and technically savvy people could collaborate on creating the best of translations using GitHub.

Also, I think it'd be really neat if we could have something like the layout as requested in #99 but for different languages per 'stanza' thing. So it'd go like a 'verse'-like section of only the first line in 3 languages. And then the 2nd line in 3 languages in the next verse like section [something like what is seen in the pdf linked to in #99].

On the same thought, I wonder if chordpro could have GNU/Guile or Scheme extensibility. I've been trying to learn lilypond and it seems that everything is extensible in lilypond. Perhaps the same could be done with chordpro?

But then again, I might be sharpening a knife to cut down a tree. If so, please do point me to something better. I'd be very grateful. Thank you.

Oh, and BTW, here's how I think it'd work.
```
{lang: Nepali}
Song in Nepali
{end lang: Nepali}
```
```
{lang: English}
Song in English
{end lang: English}
```
Only rule: they ought to be chord-ed (if they are) in the same key. And Perhaps something like `--section=lang_Nepali` etc. could be used? Essentially, not `lang`s but `sections`. And selective rendering/printing of certain sections. Perhaps that could be used to do all sorts of crazy things.

Or, as I pointed out in the beginning, I might be asking a stupid question. :)

**Comment by sciurius** [comment]
The [user community](https://groups.google.com/forum/#!forum/chordpro) is a better place to discuss this.
The issue tracker is for bugs and issues.

**Comment by peanutbutterandcrackers** [comment]
Sorry about this. I will put this question on the community forum. Thank you.
