### ISSUE TITLE
On Mac user config file not read from some paths

### ISSUE THREAD

**Issue by phatmann** [ChordPro/chordpro#102]
On the Mac, the user config was not read at either of these paths:

~/.config/chordpro.json
~/.chordpro/chordpro.json

However, this path worked fine:

~/.config/chordpro/chordpro.json

Should the documentation be updated accordingly?

**Comment by sciurius** [comment]
Thanks for pointing this out. I've updated the documentation on the github wiki, and this will propagate to the ChordPro site.
