### ISSUE TITLE
Short form for start_of_verse

### ISSUE THREAD

**Issue by phatmann** [ChordPro/chordpro#103]
I am also embarrassed to ask, but why are there no short forms for "start_of_verse" and "end_of_verse"? It seems that {sov} and {env} should be supported for consistency with the other "start_of_xxx" and "end_of_xxx" directives.

**Comment by sciurius** [comment]
Questions like this are better asked on the forum, https://groups.io/g/ChordPro .
Please use the issue tracker for bugs and features only.

**Comment by phatmann** [comment]
Let me reword this: I consider this a feature that should be implemented. I am happy to submit a PR. Any reason not to?

**Comment by sciurius** [comment]
Let me reword this: You ask questions. "Why are there...?" "Any reason not to?". Questions and answers (a.k.a. discussions) are better done on the forum; other users can participate.
Note that I don't want to discourage you, I just want to involve other users as well. Should we decide on the forum that this would be a useful feature to add, then it's time for issue trackers and PRs.

**Comment by phatmann** [comment]
https://groups.io/g/ChordPro/message/23
