### ISSUE TITLE
Song numbers

### ISSUE THREAD

**Issue by chriswep** [ChordPro/chordpro#105]
i would like the songs to be numbered automatically and the TOC to use those numbers instead of page numbers. this seems to be more intuitive for songs-books and it would allow different versions of a songbook to be compatible when used in a group and numbers are shared directly.

as far as i could see this is not possible. would this be difficult to include?

**Comment by sciurius** [comment]
See also issue #86

**Comment by chriswep** [comment]
> See also issue #86

i have looked at it before, however (unless i am wrong) it doesn't mention the concept of song numbers?

**Comment by sciurius** [comment]
Sorry, this was intended to be a reminder that there are some enhancements needed for the toc handling in general.

**Comment by sciurius** [comment]
In the dev version there is now a meta variable `songindex` that contains the song index. You can use it in your chordpro file, e.g.

````
{title: %{songindex}. My First Song}
...
````

or in the formats in the config:

````
{ "pdf" : {
    "formats" : {
      "title" : {
        "title"     : [ "", "%{songindex}. %{title}", "" ],
      },
    },
  }
}
````
