### ISSUE TITLE
Win 10 only {title} directive works

### ISSUE THREAD

**Issue by amamm66** [ChordPro/chordpro#106]
On Win 10, with ChordPro-GUI-installer-0-974-0-1-msw-x64.exe, only {title} and  {subtitle} directives work correctly. The rest of meta-directives are probably skipped and missing in the pdf preview.

I have tried different formats for these:
{artist: Leonard Cohen}
{meta: artist Leonard Cohen}
or 
{composer: Leonard Cohen}
{meta: composer Leonard Cohen}
or
{lyricist: Leonard Nijgh}
{meta: lyricist Leonard Nijgh}

...and I didn't achieve they work correctly with native configuration. 

In the pdf I'm getting only the {title} and {subtitle}.

**Comment by sciurius** [comment]
Only the meta-directives `title` and `subtitle` are shown in the pdf by default.
In the config file you can specify the exact format of page headers and footers, including all of the meta-data. See https://www.chordpro.org/chordpro/ChordPro-Configuration-PDF.html#page-headers-and-footers .

All information about the ChordPro file format and how to use it can be found on the web site: https://www.chordpro.org .

A user community discussing ChordPro can be found at https://groups.io/g/ChordPro . Please join us there.

**Comment by amamm66** [comment]
Sorry, Sciurius, but it is still not working from the GUI preferences on Windows 10. 

Even when changing the Custom Config like this:

	// Formats.
	"formats" : {
	    // Titles/Footers.

	    // Titles/footers have 3 parts, which are printed left,
	    // centered and right.
	    // For even/odd printing, the order is reversed.

	    // By default, a page has:
	    "default" : {
	        // No title/subtitle.
	    	"title"     : [ "", "%{title}", "" ],
	    	"subtitle"  : [ "", "%{subtitle}", "" ],
	    	"artist"  : [ "", "%{artist}", "" ],
		// Footer is title -- page number.
	    	"footer"    : [ "%{title}", "", "%{page}" ],
	    },
	    // The first page of a song has:
	    "title" : {
	        // Title and subtitle.
	    	"title"     : [ "", "%{title}", "" ],
	    	"subtitle"  : [ "", "%{subtitle}", "" ],
	    	"artist"  : [ "", "%{artist}", "" ],
		// Footer with page number.
	    	"footer"    : [ "", "", "%{page}" ],
	    },
	    // The very first output page is slightly different:
	    "first" : {
	    	"title"     : [ "", "%{title}", "" ],
	    	"subtitle"  : [ "", "%{subtitle}", "" ],
	    	"artist"  : [ "", "%{artist}", "" ],
	    	// It has title and subtitle, like normal 'first' pages.
		// But no footer.
	    	"footer"    : null,
	    },
	},

For the ChordPro's sake it would better that all meta-directives worked straightforwardly without the need to add them in Titles/Footers section of the Custom Config. 

On the other hand, I have also some objections whether the GUI Preferences option on Windows reads correctly the Custom Config. I attach a screen shot on how I have configured the Custom Config option in GUI. However, I've never succeeded to get working, e.g., the "include" : [ "modern3", "guitar"] presets.

![2020-05-01 190646](https://user-images.githubusercontent.com/64640275/80825503-d4f54380-8be0-11ea-9f1f-7f1a06805f64.jpg)

**Comment by sciurius** [comment]
A page has a header with two lines: **title** and **subtitle**. You can define what goes in each.
Is also has a single line **footer**. Adding extra lines like **artist** has no effect.

For example, this it what I often use (see the "subtitle" of the "title" page):

        // Formats.
        "formats" : {
            "default" : {
                // No title/subtitle.
                "title"     : null,
                "subtitle"  : null,
                // Footer is title -- page number.
                "footer"    : [ "%{title}", "", "%{page}" ],
            },
            // The first page of a song has:
            "title" : {
                // Title and subtitle.
                "title"     : [ "%{title}", "", "" ],
                "subtitle"  : [ "%{composer|%{}%{artist| / }}%{artist}", "", "%{capo|CAPO %{}}" ],              // Footer with page number.
                "footer"    : [ "", "", "%{page}" ],
            },
            // The very first output page is slightly different:
            "first" : {
                // It has title and subtitle, like normal 'first' pages.
                // But no footer.
                "footer"    : null,
            },
        },

> For the ChordPro's sake it would better that all meta-directives worked straightforwardly without the need to add them

Seriously? You wouldn't want all of them crapped on the page by default...

If you want to do more than just trivial things with config files it is better to use the ChordPro command line program instead. It has options to trace what is going on with your config files and may be helpfull to find mistakes.

_**Please join the user community. That's the place to discuss usage issues.**_
