### ISSUE TITLE
I get chordpro 0.974.1 instead of 5.xx.xx

### ISSUE THREAD

**Issue by andb0t** [ChordPro/chordpro#108]
The issue tracker is for bug reporting.
Please use the [ChordPro user group](https://groups.google.com/forum/#!forum/chordpro) for general questions on how to use ChordPro.

**Describe the bug**
I do `cpan install chordpro` and get version 0.974.1 instead of version 5, which is mentioned as the latest version in the README.

**To Reproduce**
On Ubuntu 18.04.3 LTS WSL (windows subsystem for Linux):
```
sudo apt-get update -y && apt-get install --no-install-recommends -y libwx-perl
sudo cpan upgrade
sudo cpan install chordpro
chordpro --version
# This is ChordPro version 0.974.1
```

**Expected behavior**
Getting the newest version:
```
# This is ChordPro version 5.xx.xx
```

**Sample files and screenshots**
Adding a small example ChordPro file that shows the problem often helps. If you use custom configuration include that as well.

**Please complete the following information:**
 - OS: Ubuntu 18.04.3 LTS WSL (windows subsystem for Linux)
 - Perl version: This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
 - ChordPro version: 0.974.1
 - Where did you get ChordPro from: CPAN

**Comment by sciurius** [comment]
ChordPro version 5 denotes version 5 of the ChordPro file standard.
The chordpro tool will eventually be released as version 5 as well. The documentation was a bit optimistic ;).
Version 0.974.1 is the latest official release (and it supports ChordPro file standard version 5 -- getting confused already?).
For the bleeding edge checkout ChordPro from git and use the `dev` branch.

**Comment by andb0t** [comment]
Great, then I guess I'm fine :)
