### ISSUE TITLE
Inversions for roman chords

### ISSUE THREAD

**Issue by scottselberg** [ChordPro/chordpro#109]
Hi, is this project still active?  There is some incredible work here - but I was struggling with a few issues.

In one of the songs I was trying to make a chordpro lead sheet for, there was a chord for Ab/C.  I was able to define a custom chord for it, but when I transcoded it to roman all I got for it was "V" rather than "V/vii" or some way to indicate the alternate bass note.  I know perl very well, so I was hoping to have a dialog with the owner to get some idea on how you think this should be handled.

I also found that when trying to use a custom font, I had to create a key called "file" in the json file otherwise it was not found.

Lastly, I understand the choice of using "b" and "#" for the defaults, but how does one get it to pick the unicode flat and sharp symbols as they just look better?

**Comment by sciurius** [comment]
> Hi, is this project still active?

You bet!

May I invite you to join the user community at https://groups.io/g/ChordPro and ask your questions there? Other users can benefit from the 'dialog' and participate.

Looking forward to see you there!
