### ISSUE TITLE
wrap long comment lines

### ISSUE THREAD

**Issue by wolftune** [ChordPro/chordpro#11]
Rendering a long comment line such as

```
{comment: ©2011 Aaron Wolf, permission for free sharing and modification granted under terms of the Creative Commons Attribution Share-Alike 3.0 license}
```

results in words getting cut off instead of getting wrapped to multiple lines in the PDF

**Comment by Gajusbonus** [comment]
This seems not only to occur in comments, but also in the lyrics when I use a two columns setting on a a5 pdf
"columns" : 2,
"lyrics-only" : true,
"papersize" : "a5",
[myconfig-json.txt](https://github.com/sciurius/chordpro/files/1565729/myconfig-json.txt)
[Days of Elijah.txt](https://github.com/sciurius/chordpro/files/1565726/Days.of.Elijah.txt)

**Comment by sciurius** [comment]
Currently there is no support for the wrapping of lines. Hence the 'enhancement' label.

**Comment by sciurius** [comment]
Basic line wrapping has been implemented since.

**Comment by ChordPro** [comment]
Can you confirm and close the issue?

**Comment by wolftune** [comment]
confirmed
