### ISSUE TITLE
directive {+pdf.diagrams.show: xyz} not working with columns

### ISSUE THREAD

**Issue by stratmaster** [ChordPro/chordpro#110]
**Describe the bug**
When using the directive `{+pdf.diagrams.show: xyz}` in conjunction with columns, the columns are getting squeezed.

**To Reproduce**
Compile this document:

```
{title: Heroes}
{st: David Bowie – Heroes (1977)}
{columns: 2}
{+pdf.diagrams.show: below}
{textsize: 10}

{c:Intro}
{start_of_grid 1x4}
| D | G | D | G |
{end_of_grid}

{start_of_verse: Verse 1}
[D]I
I will be [G]king
And [D]you
You will be [G]queen
Though [C]nothing will
Drive them [D]away
We can [Am]beat them[Em]
Just for one [D]day
We can be [C]Heroes[G]
Just for one [D]day
{end_of_verse: Verse 1}

{start_of_verse: Verse 2}
And you[D]
You can be [G]mean
And I[D]
I'll drink all the [G]time
'Cause we're [D]lovers
And that is a [G]fact
Yes we're [D]lovers
And that is [G]that
{end_of_verse: Verse 2}

{start_of_chorus}
Though [C]nothing
Will keep us [D]together
We could steal time[Am] [Em]
Just for one [D]day
We can be [C]Heroes[G]
For ever and [D]ever
What d'you say
{end_of_chorus}

{c:Instrumental}
{start_of_grid 1x4}
| D | G | D | G |
{end_of_grid}

{start_of_verse: Verse 3}
[D]I wish you could swim[G]
Like the [D]dolphins
Like dolphins can [G]swim
Though [C]nothing
Will keep us [D]together
We can beat [Am]them[Em]
For ever and [D]ever
Oh we can be [C]Heroes[G]
Just for one [D]day
{end_of_verse: Verse 3}
```

**Expected behavior**
The columns should not be squeezed.

**Sample files and screenshots**
[David Bowie - Heroes.pdf](https://github.com/ChordPro/chordpro/files/4824055/David.Bowie.-.Heroes.pdf)

**Please complete the following information:**
 - OS: [macOS Catalina, 10.15.5]
 - Perl version [v5.18.4]
 - ChordPro version [0.974]
 - Where did you get ChordPro from [CPAN]

**Comment by sciurius** [comment]
Short answer: Don't use `{+pdf.diagrams.show: below}` (or other `pdf` settings). It is not documented (or should not be, I have to check).

Longer answer: The `{+pdf...}` is handled _after_ the PDF building framework has been set up. Different parts of the PDF generator then see different margins, which causes the behaviour you see.

`chordpro --define pdf.diagrams.show=below` does work.

**Comment by stratmaster** [comment]
Ok, thank you for your quick reply.
Using `chordpro --define pdf.diagrams.show=below` does the trick for me!
