### ISSUE TITLE
Pango markup not working when the text contains [Chords]

### ISSUE THREAD

**Issue by lpinner** [ChordPro/chordpro#111]
It seems like Pango markup is not working when the text contains [Chords]. The open tag seems to be getting closed at the first square bracket.

test.pro
```
# A simple ChordPro song.
{title: Swing Low Sweet Chariot}

{start_of_chorus}
Swing [D]low, sweet [G]chari[D]ot,
<i>Comin' for to carry me [A7]home.</i>
Swing [D7]low, sweet [G]chari[D]ot,
<i>Comin' for to [A7]carry me [D]home.</i>
{end_of_chorus}

```

```
chordpro -V
This is ChordPro version 0.975_001

chordpro -X -o test.pdf test.pro

Markup error: "<i>Comin’ for to carry me  home.</i>"
  Closing <i> but no markup is open
  ...

```
![image](https://user-images.githubusercontent.com/4827816/90295582-ba638380-decc-11ea-937a-34767e330cfd.png)

**Comment by sciurius** [comment]
Screwed by a last-minute fix to support perl 5.10.1... 
Fixed, thanks.
