### ISSUE TITLE
CSV file enhancements

### ISSUE THREAD

**Issue by AnniePerson** [ChordPro/chordpro#112]
When the --csv option is used while creating a PDF output file, ChordPro creates a CSV file that can be used to import the songs in the PDF into MobileSheetsPro or into other database applications. Currently the CSV file contains only "title" and "pages"
It would be great if other metadata like keys, artists, composers, years would also be written as additional columns into the CSV file

**Comment by sciurius** [comment]
Nice suggestion. What subset of metadata do you think is relevant? Or should it be configurable?

**Comment by AnniePerson** [comment]
keys, artists, composers, years as mentioned in my first post are the ones that I would like to use. For my personal habits keys is the most important one. I usually set albums to the book's title in case of fakebook PDFs. But that's not essential. CSV entries that are the same for all songs are really fast and easy to edit later. That's also the reason, why I think iT#s not worth the effort to make it configurable. Unwanted columns can be easily deleted or renamed (MobileSheetsPro ignores columns withh unsupported names)

**Comment by sciurius** [comment]
I have added sorttitle artist composer collection key year to the columns of the csv.
