### ISSUE TITLE
File size of exported PDF file

### ISSUE THREAD

**Issue by AnniePerson** [ChordPro/chordpro#113]
The PDF created with 0.975 is MUCH bigger (37 MB) than the one created with 0.974 (3 MB)
0.975 adds PDF bookmarks, but that shouldn't cause such a big difference.

**Comment by sciurius** [comment]
The culprit is 3rd party module Text::Layout that fails to cache the fonts needed. As a result, all fonts are included in the PDF several times.
I have a fix in place for Text::Layout that will solve the issue.

**Comment by AnniePerson** [comment]
Thanks. Fast and reliable as always.
