### ISSUE TITLE
chordpro --a2crd raises "Can't use an undefined value as a HASH reference"

### ISSUE THREAD

**Issue by lpinner** [ChordPro/chordpro#115]
**Describe the bug**
chordpro --a2crd raises "Can't use an undefined value as a HASH reference"

**To Reproduce**
```
cat >test.txt <<EOL
Title: Swing Low Sweet Chariot
 
      D          G    D
Swing low, sweet chariot,
                       A7
Comin’ for to carry me home.
      D7         G    D
Swing low, sweet chariot,
              A7       D
Comin’ for to carry me home.
EOL

chordpro --a2crd -o test.pro test.txt
```
**Output**
`Can't use an undefined value as a HASH reference at App/Music/ChordPro/Chords/Parser.pm line 76.`

**Please complete the following information:**
 - OS: Ubuntu 18.04
 - Perl version 5.26.1
 - ChordPro version 0.975_002 (Github) and 0.975 (CPAN)

**Comment by sciurius** [comment]
Thanks, fixed.
