### ISSUE TITLE
Issues with PDF Backend

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [ChordPro/chordpro#117]
Hey there,

I'm trying to fix a package definition I wrote for chordpro `v. 0.974_017`, but I'm getting the following error:
```
No backend for PDF
No PDF backend App::Music::ChordPro::Output::PDFClassic::PDF at (eval 47) line 1.
Compilation failed in require at (eval 47) line 1.
```
[Here is what PDF.pm looks like](https://github.com/ChordPro/chordpro/files/5212572/PDF.txt).

I am not entirely sure why it is complaining. Any pointers will be much appreciated.

P. S: Yes, I do plan on updating the package definition to a newer version. But I'd like to make this work first and foremost.

**Comment by sciurius** [comment]
Without additional information it is not possible to say anything. Your PDF.pm looks okay except for a weird first `#!` line.
However, `0.974_017` is an undefined snapshot from the git development, so it is not even possible to reconstruct your exact situation. When I reconstruct what _I think_ is your situation it passes all tests.

Every bit of PDF processing had changed between snapshot `0.974_017` and current `0.977`. So please upgrade and if you encounter issues send them to the community forum. We are there to help.

**Comment by peanutbutterandcrackers** [comment]
@sciurius - Hey there,

Please excuse me for not mentioning this earlier: I'm using this commit: 03c72e8e651bca0f24ee6d8b59e61750fe10f8b7

I understand that upgrading the entire package altogether might fix this. But since this is a polishing-up of the package definition, I really want to understand what I am doing incorrect this time around.

Also, it does pass all the tests during build-time. And `chordpro --help` gives me all the help options. It really seems to be a PDF rendering issue.

Further information:
1. The weird line is because I am using [GNU Guix](https://guix.gnu.org/) a functional, distro-agnostic package manager.
2. Here is the environment that `chrordpro` runs in:
```
#!/gnu/store/pwcp239kjf7lnj5i4lkdzcfcxwcfyk72-bash-minimal-5.0.16/bin/bash
export PERL5LIB="/gnu/store/y84hsb3hxaq1d6j7xwfwyl3cbhz26sd7-perl-cairo-1.107/lib/perl5/site_perl:/gnu/store/0la8qpx7mv4n8pkyxf1kh1gsi1zfk6ji-perl-pango-1.227/lib/perl5/site_perl:/gnu/store/52jpxi1lz7cin6ydbjy1jiscnlc4kyd5-perl-app-packager-1.430.1/lib/perl5/site_perl:/gnu/store/a5ilxi4zvkrir78xngdbnmlanpgam1hi-perl-file-loadlines-0.02/lib/perl5/site_perl:/gnu/store/9drpad3mjq4p07ya29l3fwnhvmslw37l-perl-pdf-api2-2.036/lib/perl5/site_perl:/gnu/store/nhg508jn9avqncl790y5fsx2v26ldc5f-perl-image-info-1.42/lib/perl5/site_perl:/gnu/store/03sjddfmm840622ig98rf6k1cj3fs4xj-perl-string-interpolate-named-0.05/lib/perl5/site_perl:/gnu/store/89vcp32zn3fg4sq7my4x1d16d6b1nvql-chordpro-0.974_017/lib/perl5/site_perl${PERL5LIB:+:}$PERL5LIB"
exec -a "$0" "/gnu/store/89vcp32zn3fg4sq7my4x1d16d6b1nvql-chordpro-0.974_017/bin/.chordpro-real" "$@"
```

**Comment by peanutbutterandcrackers** [comment]
Update: Introducing `perl-io-string` to the environment of the program did kinda' push me further. And it does render PDFs. But they don't have any Devanagari text in them.... strange.....

**Comment by peanutbutterandcrackers** [comment]
Okay... I think this might be something entirely specific to the build system that I am using. There is nothing wrong PERL-wise here, as far as I can see. So please ignore this issue for the moment (unless you can see a glaring PERL-related error that I can not). I will try to fix the dependency chain in my build environment and try again.

**Comment by sciurius** [comment]
IO::String is a dependency registered with ChordPro. If it is not installed during the ChordPro install there is definitely something wrong with your build environment.

To get correctly rendered Devanagari fonts you need special tweaks. Forget it with that version.

If your build environment is anything decent, 0.977 should build and run w/o problems.

**Comment by peanutbutterandcrackers** [comment]
@sciurius - I managed to get the `0.974` version working. It turned out to be an issue with the build system. GNU Guix is pretty great, it's just my skills that aren't the greatest.

Anyways, currently I'm trying to upgrade the package definition to `0.977`, and I've got all the package dependencies as reported by `Makefile.PL`, and yet, for some reason, the output rendered does not have any visible Devanagari letters. Latin letters seem to work just fine.

Here is the output pdf for [this chordpro file](https://github.com/peanutbutterandcrackers/music/blob/master/Hymns/%E0%A4%B8%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%9F%E0%A4%BF%E0%A4%95%E0%A4%B0%E0%A5%8D%E0%A4%A4%E0%A4%BE%20%E0%A4%B8%E0%A4%BF%E0%A4%82%E0%A4%B9%E0%A4%BE%E0%A4%B8%E0%A4%A8%E0%A4%AE%E0%A4%BE.chordpro):
[सृष्टिकर्ता सिंहासनमा.pdf](https://github.com/ChordPro/chordpro/files/5213197/default.pdf)

Is there something that I might be missing?

**Comment by sciurius** [comment]
There were some changes in the font config settings. Can you add the `--debug` option to chordpro, run again, and send the pdf?

**Comment by peanutbutterandcrackers** [comment]
Here is the output of `--debug`:
[debug.log](https://github.com/ChordPro/chordpro/files/5213291/debug.log)

The pdf: 
[सृष्टिकर्ता सिंहासनमा.pdf](https://github.com/ChordPro/chordpro/files/5213295/default.pdf)

**Comment by peanutbutterandcrackers** [comment]
Update:

`chordpro --text-font=/absolute/path/to/devanagari/aware/font.ttf ...` produces this result:
[सृष्टिकर्ता सिंहासनमा.pdf](https://github.com/ChordPro/chordpro/files/5213579/default.pdf)

`chordpro --text-font=Just-The-Font-Name ...` threw this error:
```
$ chordpro --text-font="Lohit Devanagari" सृष्टिकर्ता\ सिंहासनमा.chordpro 
Unknown font property: devanagari at /gnu/store/6k697rrd9idkk31rpawwi8cqfmvy18gp-chordpro-0.977/lib/perl5/site_perl/5.30.2/App/Music/ChordPro/Output/PDF/Writer.pm line 460.
Can't call method "isvirtual" on an undefined value at /gnu/store/9drpad3mjq4p07ya29l3fwnhvmslw37l-perl-pdf-api2-2.036/lib/perl5/site_perl/5.30.2/PDF/API2/Content.pm line 1578.
```

**Comment by peanutbutterandcrackers** [comment]
Update II:

I just repackaged the newer chordpro as `chordpro-next` and kept the old definition intact, so as to compare the differences in rendering, and realized that [the PDF that the **newer** chordpro produces](https://github.com/ChordPro/chordpro/files/5213579/default.pdf) has some rendering issues. It does not render the Devanagari glyphs correctly. The old chordpro renders it just fine: 
[सृष्टिकर्ता सिंहासनमा.pdf](https://github.com/ChordPro/chordpro/files/5213616/default.pdf)

Here is a comparison of the output from `chordpro` (the old version) on the left and `chordpro-next` (the newer one) on the right:
![image](https://user-images.githubusercontent.com/26764547/93010107-7d141380-f5a8-11ea-9a00-3d4f6b5a95df.png)

**Comment by sciurius** [comment]
I may assume then that you have the devanagari fonts visible again.

For correct rendering of Devanagari, you need to install (or verify) Text::Layout version 0.019 and HarfBuzz::Shaper version 0.023. To build/install HarfBuzz::Shaper you probably need to install the harfbuzz package (I'm pretty sure it is already on your system).

In your config, you must use the newer fontconfig method to specify fonts. See https://www.chordpro.org/chordpro/chordpro-fonts/. This will become something similar to:

````
      "fontconfig" : {
         "devanagari" : {
            "" : { "file" : "/absolute/path/to/devanagari/aware/font.ttf",
                    "shaping" : true },
         },
        ....
      "fonts" : {
         "text" : {
            "description" : "devanagari",
            "size" : 12
         },
         ....

The attached config produces the desired results on my system. You may need to update the location of the font files.

I hope this will make it work for you as well.
[deva.json.txt](https://github.com/ChordPro/chordpro/files/5213771/deva.json.txt)

As a general advice: Do not use --text-font and similar on the command line. The results are not always what you would expect...

**Comment by sciurius** [comment]
For completeness, this version of ChordPro does no longer require Pango and Cairo (I think 0.974 used Pango for the Devanagari rendering).

**Comment by peanutbutterandcrackers** [comment]
I am trying to make `HarfBuzz::Shaper` to the build but it fails during the build with the following test-errors:
```
starting phase `check'
"/gnu/store/8zvc5mvk0xm3ygrxsgpyy5ilxb5rzjry-perl-5.30.2/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Shaper.bs blib/arch/auto/HarfBuzz/Shaper/Shaper.bs 644
PERL_DL_NONLAZY=1 "/gnu/store/8zvc5mvk0xm3ygrxsgpyy5ilxb5rzjry-perl-5.30.2/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t

#   Failed test 'use HarfBuzz::Shaper;'
#   at t/00_load.t line 7.
#     Tried to use 'HarfBuzz::Shaper'.
#     Error:  Can't load '/tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/arch/auto/HarfBuzz/Shaper/Shaper.so' for module HarfBuzz::Shaper: /tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/arch/auto/HarfBuzz/Shaper/Shaper.so: undefined symbol: hb_font_set_ptem at /gnu/store/8zvc5mvk0xm3ygrxsgpyy5ilxb5rzjry-perl-5.30.2/lib/perl5/5.30.2/x86_64-linux-thread-multi/DynaLoader.pm line 193.
#  at t/00_load.t line 7.
# Compilation failed in require at t/00_load.t line 7.
# BEGIN failed--compilation aborted at t/00_load.t line 7.
Undefined subroutine &HarfBuzz::Shaper::hb_version_string called at t/00_load.t line 9.
# Looks like your test exited with 255 just after 1.
t/00_load.t .... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 

#   Failed test 'use HarfBuzz::Shaper;'
#   at t/10_basic.t line 10.
#     Tried to use 'HarfBuzz::Shaper'.
#     Error:  Can't load '/tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/arch/auto/HarfBuzz/Shaper/Shaper.so' for module HarfBuzz::Shaper: /tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/arch/auto/HarfBuzz/Shaper/Shaper.so: undefined symbol: hb_font_set_ptem at /gnu/store/8zvc5mvk0xm3ygrxsgpyy5ilxb5rzjry-perl-5.30.2/lib/perl5/5.30.2/x86_64-linux-thread-multi/DynaLoader.pm line 193.
#  at t/10_basic.t line 10.
# Compilation failed in require at t/10_basic.t line 10.
# BEGIN failed--compilation aborted at t/10_basic.t line 10.
Undefined subroutine &HarfBuzz::Shaper::hb_version_string called at /tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/lib/HarfBuzz/Shaper.pm line 93.
# Looks like your test exited with 255 just after 1.
t/10_basic.t ... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests 

#   Failed test 'use HarfBuzz::Shaper;'
#   at t/20_shaper.t line 11.
#     Tried to use 'HarfBuzz::Shaper'.
#     Error:  Can't load '/tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/arch/auto/HarfBuzz/Shaper/Shaper.so' for module HarfBuzz::Shaper: /tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/arch/auto/HarfBuzz/Shaper/Shaper.so: undefined symbol: hb_font_set_ptem at /gnu/store/8zvc5mvk0xm3ygrxsgpyy5ilxb5rzjry-perl-5.30.2/lib/perl5/5.30.2/x86_64-linux-thread-multi/DynaLoader.pm line 193.
#  at t/20_shaper.t line 11.
# Compilation failed in require at t/20_shaper.t line 11.
# BEGIN failed--compilation aborted at t/20_shaper.t line 11.
Undefined subroutine &HarfBuzz::Shaper::hb_version_string called at /tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/lib/HarfBuzz/Shaper.pm line 93.
# Looks like your test exited with 255 just after 1.
t/20_shaper.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests 

#   Failed test 'use HarfBuzz::Shaper;'
#   at t/30_kern.t line 10.
#     Tried to use 'HarfBuzz::Shaper'.
#     Error:  Can't load '/tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/arch/auto/HarfBuzz/Shaper/Shaper.so' for module HarfBuzz::Shaper: /tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/arch/auto/HarfBuzz/Shaper/Shaper.so: undefined symbol: hb_font_set_ptem at /gnu/store/8zvc5mvk0xm3ygrxsgpyy5ilxb5rzjry-perl-5.30.2/lib/perl5/5.30.2/x86_64-linux-thread-multi/DynaLoader.pm line 193.
#  at t/30_kern.t line 10.
# Compilation failed in require at t/30_kern.t line 10.
# BEGIN failed--compilation aborted at t/30_kern.t line 10.
Undefined subroutine &HarfBuzz::Shaper::hb_version_string called at /tmp/guix-build-perl-harfbuzz-shaper-0.023.drv-0/HarfBuzz-Shaper-0.023/blib/lib/HarfBuzz/Shaper.pm line 93.
# Looks like your test exited with 255 just after 1.
t/30_kern.t .... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/4 subtests 

Test Summary Report
-------------------
t/00_load.t  (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
t/10_basic.t (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 1.
t/20_shaper.t (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 1.
t/30_kern.t  (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 4 tests but ran 1.
Files=4, Tests=4,  1 wallclock secs ( 0.04 usr  0.01 sys +  0.47 cusr  0.08 csys =  0.60 CPU)
Result: FAIL
Failed 4/4 test programs. 4/4 subtests failed.
make: *** [Makefile:1041: test_dynamic] Error 255

Test suite failed, dumping logs.
```
Could you please tell me what dependencies I should make available to `HarfBuzz::Shaper`? The [dependency graph at cpan](https://cpandeps.grinnz.com/?dist=HarfBuzz-Shaper) isn't all that helpful.

Thank you

**Comment by sciurius** [comment]
HarfBuzz::Shaper does not have any CPAN dependencies, but expects the harfbuzz library to be available on the build system. 
Can you share the HarfBuzz::Shaper build log (not the test log)?

**Comment by sciurius** [comment]
So far all apparent problems were related to the build environment.
Closing this issue since it is not related to ChordPro.
For questions about ChordPro please use the [forum](https://groups.io/g/ChordPro/topics).
Build problems related to HarfBuzz::Shaper should go to its own issue tracker, https://github.com/sciurius/perl-HarfBuzz-Shaper/issues
