### ISSUE TITLE
Fix for A2CRD, new chord extensions

### ISSUE THREAD

**Issue by weltyj** [ChordPro/chordpro#118]
The current (0.977) a2crd fails immediately on the first text file I tried.   Not recognizing a single chord to classify a line as normal text is too restrictive.    

I rewrote the logic so it computes the percentage of words on a line recognized as a chord, if it's > 40% then the line is classified as a chord line.   Otherwise, it checks for the % of whitespace, (same as the original a2crd.c), if the whitespace is > 50% then the line is classified as a chord line, otherwise the line is classified as text.   This, I believe,  is pretty robust logic now.

I also caught and fixed two other issues with A2CRD
    -- tabs were not expanded which would cause misplacement of the chords in the output.
    -- in sub maplines(), a blank line preceding a normal text line should just output the blank line and fall through, same as a blank line preceding a chord line

---

New chord extensions:
I have a lot of *.txt files with "-" used to indicate flatted notes, i.e. "A7-9" instead of "A7b9", so I added those versions to the Parser.pm module.   Similar with "o" used for a diminished chord instead of "dim" or "0".

I built a test file for A2CRD, and test files for the new chord extensions.

I have a git branch (a2crd_new_chord_ext) pushed to my github acct, and if I can remember how will make a pull request for you if you would like to see the changes.

**Comment by sciurius** [comment]
Fixed in 0.978.
