### ISSUE TITLE
Use of uninitialized value in string eq at /usr/local/share/perl/5.30.0/App/Music/ChordPro/Chords/Parser.pm line 194.

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#121]
**Describe the bug**
When {settings}->{chordnames} is not present in the config, chordpro produces this error.
I upgrade chordpro from an older version, which did not contain that setting yet and since then, I'm getting this error.

**To Reproduce**
Remove {settings}->{chordname} from the config and run chordpro.

**Expected behavior**
I would expect chordpro to use a sane default for the setting mimmiking the previous behaviour if possible.

**Please complete the following information:**
 - OS: Ubuntu 20.04
 - Perl version 5.30.0
 - ChordPro version 0.977
 - Where did you get ChordPro from CPAN

**Additional context**
Line of Code where the error happens:
`      if $self->{c_rpat} && $::config->{settings}->{chordnames} eq "relaxed";
`

**Comment by sciurius** [comment]
Can you run `chordpro --debug ...` in a setting that shows this error, and attach the resultant PDF?

**Comment by sciurius** [comment]
Solved in 0.978.
