### ISSUE TITLE
Chordpro needs a docker image!

### ISSUE THREAD

**Issue by andb0t** [ChordPro/chordpro#124]
Hi everyone, 

this is **not a bug report but a PR proposal**.

with the advent of docker, we can spare the user base the installation of perl and all the hastle that comes with it. Wouldn't it be great to `docker pull chordpro` and then have it available via `docker run chordpro [ARGUMENTS]`?

If I'd start implementation of a PR for a docker image and add it to the `travis-ci.yml` would you accept? Is that of interest?

**Comment by sciurius** [comment]
As long as it doesn't get in the way I welcome a docker image. But would it be very different from the standalone binary that we already can build (for Linux, Windows and MacOS)?

**Comment by andb0t** [comment]
It wouldn't get in the way. It's one more file `Dockerfile1 in the root directory and some lines in `travis.yml`. It would then create the docker image. You can call it a cross-platform binary since everybody who has docker (Windows, Mac, Linux, Android, whatever) user can just run it using `docker run chordpro`

**Comment by sciurius** [comment]
Well, let's give it a go, then!

**Comment by ChordPro** [comment]
I've given this some extra thoughs and I'm not sure. What is the problem you are trying to address?

> we can spare the user base the installation of perl and all the hastle that comes with it.

The only platform currently without perl is Windows. The 'hassle' to install perl on WIndows is limited. Moreover, we have a ready to use ChordPro installer for Windows.

All Linux distros are capable of install/run chordpro with a simple `cpan chordpro` command. It *may* be advantageous to pre-install a couple of standard packages first, e.g. `libpdf-api2-perl`. For the ChordPro GUI, `libwx-perl` is required. All these packages are available for all mainstream Linux distros.

MacOS can install/run the command line ChordPro just like Linux. No hassle. Also, we have a ready to use ChordPro kit for MacOS.

On Linux platforms docker could be interesting although the amount of overhead is considerable; docker is not really intended for small, single shot programs like ChordPro.

On MacOS and Windows, using docker involves installing a Linux environment so the overhead is even more.

So I'm not sure this is a feasible approach, especially given the alternatives.

**Comment by sciurius** [comment]
Some more input to the discussion:

> Whereas Docker is focusing on containers for servers operated by “devops”, AppImage is focusing on desktop applications operated by end users.
> 
> Whereas Docker puts everything (besides the Kernel) into a container and shields it from the host, AppImages use the host OS and do not shield the application from it.

So for a typical desktop application like ChordPro, a docker image would not have advantages over an AppImage. 
Moreover, the AppImage for ChordPro is ready and available.

**Comment by andb0t** [comment]
Hi everyone, please excuse the long silence. Real life got in the way.

After reading your arguments I have some doubts as well. Maybe this is just a corner case? Afterall for Cordpro to fully function from within docker, a volume might need to be mounted for chordpro to read from and write to. While this is not a problem for an experienced developer, the unexperienced, for whom this feature was intended, will fail. Until we find a way around this volume mount, I think we can pause this MR.

**Comment by JohannesWiesner** [comment]
Hi everyone,

I really would love to have a Docker image for Chordpro! I would not have to install a bare-metal version of Perl on my machine and I could also avoid common installation problems :)

**Comment by sciurius** [comment]
There's a Windows installer on the release page.
Could it be more simpler?

**Comment by sciurius** [comment]
I think it is sufficiently robust already.
Thousands of users install and run without problems.
If not, the community (https://groups.io/g/ChordPro/) is here to help.

**Comment by andb0t** [comment]
Installing the GUI on windows is one aspect, which is certainly fine for most users, but if you want to use chordpro in a devops setting (e.g. for automated CI pipelines) you need it installed on your runner, which is most likely Linux. Then it's quite a hassle to install perl and chordpro from scratch.

**Comment by sciurius** [comment]
I'd say it is a big jump from GUI-using end user on Windows, to automated CI pipelines on Linux.

Please explain: How do you need ChordPro in an automated CI pipeline? How would a Docker help?

**Comment by andb0t** [comment]
I agree, it's totally different worlds. And as far as I'm concerned my personal issue is totally fixed. It took me an afternoon though, so I thought maybe we can spare others that time invest.

So for my usecase I'm using a docker image where I installed chordpro for Linux amongst a lot of other software to use as a runner in my gitlab CI. So the CI jobs can just use the `chordpro` executable and create my little songbook. I have the image saved in my gitlab docker registry. It took me some hours to get chordpro running in there and if there would have been an official docker image with chordpro preinstalled I could have just taken that and installed my other software in there or looked at the official `Dockerfile` to see how chordpro is installed.

But as I said, that's my CI pipeline usecase. Maybe @JohannesWiesner has a different application in mind.

**Comment by andb0t** [comment]
@JohannesWiesner check [this issue](https://github.com/ChordPro/chordpro/issues/107), I just posted the Dockerfile I use for my gitlab runner. If you remove the lines specific to the gitlab runner above the chordpro installation and add an ubuntu18 base it should work.

**Comment by JohannesWiesner** [comment]
@andb0t perfect! Maybe you want to upload an image of that docker file on DockerHub? :)

**Comment by ChordPro** [comment]
Unless the docker image provides full ChordPro functionality, including GUI and embedding, I'd rather not see it spread around.

If you really, really, really want a ChordPro docker, why not create a full functional version?

**Comment by andb0t** [comment]
I wouldn't have any use for a docker image with full functionality. I don't need a GUI in my CD pipeline. The aim is to have a minimal docker image that offers the command line utilities of chordpro. I think those are two entirely disjunct user groups: GUI centered users on Windows or maybe Mac on one side and command cline centered power users on the other side. I'm part of the latter and they're who the docker image is intended for.

**Comment by ChordPro** [comment]
It requires just a couple of Dockerfile commands to build a ChordPro docker. There are several on the Docker hub. I tried them, but unfortunately none of them actually works to a useful level. Nevertheless it can be done but requires some work.

What end users (e.g. @JohannesWiesner) want is a painless button push install of the full functionality, most notably the GUI part. Even though this can be packaged as a docker container, deploying it is tricky since the application runs in a fully isolated environment and several tricks are required to give the program access to your config files, temporary files, the display and PDF viewer.

The currently provided installer packages do a great job, and if some users still encounter problems with installing, I think it is better to improve the installers than start a complete new alternative traject. Especially since resources are limited.

**Comment by ChordPro** [comment]
`docker pull chordpro/chordpro:version5.987` will give you something to play with.

**Comment by cadethacker** [comment]
I'm super grateful for this. This is EXACTLY what I needed.  I'm creating a shared database of songs and need to be able to format them and produce a PDF on demand programatically. This docker image is exactly what I needed. Thank you!

**Comment by sciurius** [comment]
See https://hub.docker.com/repository/docker/chordpro/chordpro/general .
