### ISSUE TITLE
key_actual metatata missing when no {transpose: } directive

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#132]
**Describe the bug**
When a song has no {transpose: } directive, key_actual metadata appears to be missing, evidenced by not printing in PDF (although key metadata works ok). I've only recently discovered and started using actual (which is v. useful), so don't know whether or not this is a changed behaviour.

**To Reproduce**
1. Set up chordpro.json to reference key_actual metadata. 
For instance, I have the title set up to show key|time|tempo|capo left and title right
`"title"     : [ "%{key_actual|%{}  \\|  }%{time|%{}  \\|  }%{tempo|~%{}bpm  \\|  }%{capo|capo %{}}", "", "%{title}" ],`
2. Create a skeleton song, with key, time and tempo, but no transpose directive
3. Generate PDF of song [shows only time|tempo but not key]
4. Add a {transpose: } directive to song (even if no value)
5. Generate PDF again [shows key|time|tempo]

**Expected behavior**
I'd expect key_actual to exist and equal key even when no {transpose: } directive is present. I'm assuming it's not printing because it doesn't exist or has no value assigned, unless {transpose:} is in the song. 
Otherwise I'll need separate config files for songs with and without transposition (or would need to add empty transposition directive to all songs)

**Sample files and screenshots**
Sample config line included above

**Please complete the following information:**
 - OS: Debian testing (Bullseye)
 - Perl version: v5.32.0
 - ChordPro version: 0.977
 - Where did you get ChordPro from: CPAN

**Comment by sciurius** [comment]
The key metadata is currently being reworked, I'll take this into account. Thanks.

Added example program to show the problem.

[key_actual.cho.txt](https://github.com/ChordPro/chordpro/files/5812922/key_actual.cho.txt)

**Comment by gwyndaf** [comment]
Ah, sorry. Didn't occur to me to use metadata variables in a song, which would have been a simpler example.

**Comment by sciurius** [comment]
Fixed in git.
