### ISSUE TITLE
Windows start menu shortcut has wrong location

### ISSUE THREAD

**Issue by sciurius** [ChordPro/chordpro#135]
When installed using the Windows installer, the desktop shortcut points to C:\Program Files (x86)\ChordPro.ORG\ChordPro\wxchordpro.exe (which is ok) but the start menu shortcut points to C:\Program Files (x86)\ChordPro.ORG\ChordPro\bin (and cannot be used to start ChordPro).

See also the discussion in https://github.com/ChordPro/chordpro/issues/114 .

![109360275-d209c480-787e-11eb-92d4-ef75966ff6dc](https://user-images.githubusercontent.com/1118804/109383583-a0791380-78e7-11eb-9406-41afe28d9e36.png)
![109360276-d2a25b00-787e-11eb-817a-b6e7ac418dea](https://user-images.githubusercontent.com/1118804/109383588-a53dc780-78e7-11eb-945c-d9c0ec259b34.png)

**Comment by jashearwood** [comment]
ChordPro-installer-0-977-0-3-msw-x64.exe gives the correct start menu shortcut.
