### ISSUE TITLE
How to compile ChordPro

### ISSUE THREAD

**Issue by Porrumentzio** [ChordPro/chordpro#138]
I'm trying to get ChordPro running on Manjaro Linux and the AUR packages exit with GNUMake error 2. So I want to compile the program from source, but I don't know how to.
Any instructions?

**Comment by sciurius** [comment]
Did you follow the instructions in https://www.chordpro.org/chordpro/chordpro-install-on-linux/ ?

If that doesn't work, please indicate exactly what goes wrong.

**Comment by Porrumentzio** [comment]
After installing most dependencies I could and installing with cleanbuild from AUR, it worked (only for commandline version)
