### ISSUE TITLE
Not possible to print key metadata info when using nashville transcode style in config

### ISSUE THREAD

**Issue by suiluj** [ChordPro/chordpro#139]
The issue tracker is for bug reporting.
Please use the [ChordPro user group](https://groups.google.com/forum/#!forum/chordpro) for general questions on how to use ChordPro.

**Describe the bug**

It is not possible to print the *key* metadata when using *nashville* transcode. (key and the calculated _key metadata both do not work.)

**To Reproduce**

When i use the following config.json it does print the Key metadata in the subtitle when using transcode *common*.  
But it does not show the Key when using transcode *nashville*.  

example config json:

```

// General settings, to be changed by legacy configs and
// command line.
"settings" : {
  // Transcoding.
  "transcode" : "nashville", // instead of common
  // Always decapoize.
  "decapo" : true,
},
.
.
.
// The first page of a song has:
"title" : {
	  // Title and subtitle.
	  "title"     : [ "", "%{title} - %{artist}", "" ],
	  "subtitle"  : [ "", "%{_key|Key: %{}}", "" ],
	  // Footer with page number.
	  "footer"    : null
},
```
**Expected behavior**
They key information should be printed below the title when using nashville chord type style.

**Please complete the following information:**
 - OS: macOS Big Sur 11.2.3
 - Perl version This is perl 5, version 28, subversion 2 (v5.28.2) built for darwin-thread-multi-2level
 - ChordPro version: This is ChordPro version 0.978
 - Where did you get ChordPro from: mac install instruction, section system perl: https://www.chordpro.org/chordpro/chordpro-install-on-macos/

**Comment by sciurius** [comment]
Thanks for the report. As far as I know the Nashville Notation System is keyless. By using numerals instead of pitches it is possible to play a piece in any key. So I am a bit confused why you'd want a key in NNS.

**Comment by suiluj** [comment]
@sciurius hi, yes that is exactly right. But i want to have the key information so i know in which key to play the song.

Of course i could change the key but in case i want to play in the original key of the song it would be nice to have this information printed (below the title for example).

**Comment by sciurius** [comment]
The key is available while the song is being parsed, but not after it's transcoded.
Probably easiest is to insert a comment line at the beginning of the song:

````
{title: My Song}
{key: G}
{comment: We're going to play this song in the key of %{key}}
...
````
