### ISSUE TITLE
decapo setting does not transpose key or _key info

### ISSUE THREAD

**Issue by suiluj** [ChordPro/chordpro#140]
**Describe the bug**

When generating a pdf files with the setting `"decapo": true` every chord in the song gets transposed but the `key` ( or `_key` ) property does not get transposed. So when i print the key or _key metadata it is wrong.

**To Reproduce**

minimal example config json:

```

// General settings, to be changed by legacy configs and
// command line.
"settings" : {
  // Transcoding.
  "transcode" : "common",
  // Always decapoize.
  "decapo" : true,
},
.
.
.
// The first page of a song has:
"title" : {
	  // Title and subtitle.
	  "title"     : [ "", "%{title} - %{artist}", "" ],
	  "subtitle"  : [ "", "%{_key|Key: %{}}", "" ],
	  // Footer with page number.
	  "footer"    : null
},
```
**Expected behavior**
They actual key information should be printed.

**Please complete the following information:**
 - OS: macOS Big Sur 11.2.3
 - Perl version This is perl 5, version 28, subversion 2 (v5.28.2) built for darwin-thread-multi-2level
 - ChordPro version: This is ChordPro version 0.978
 - Where did you get ChordPro from: mac install instruction, section system perl: https://www.chordpro.org/chordpro/chordpro-install-on-macos/

**Comment by sciurius** [comment]
Good catch. There was a bug that caused the config setting of `decapo` to be ignored in some cases. Setting decapo on the command line always worked.

Fixed in git.

**Comment by suiluj** [comment]
ah wow fast reaction time! :) Thanks for the solution.
