### ISSUE TITLE
Feature Request: Page Background Color

### ISSUE THREAD

**Issue by kevin-corcoran-dev** [ChordPro/chordpro#144]
As a musician who uses ChordPro PDFs primarily on tablet and laptop screens rather than as printouts, I would like the option to specify a background color for the page.  This would allow users like me to create "dark mode" pdfs by editing the config file to specify a dark background and light text.

I propose the following be added to the to the `"pdf": {}` section of the config json:

```
"pagecolor" : {
"display": true,
"color": "black"
},
```

And that in `generate_song()` in PDF.pm, after `$pr->newpage()` is called,`rectxy()` would be called to draw a background of the desired color using the full `papersize` rectangle.

**Comment by sciurius** [comment]
Interesting suggestion. There are a few complications, though... IIRC some drawing is done with explicit black and white so this must be investigated first.

In general I think this feature can be generalized to specify a default foreground colour (for all fonts and drawings) and a background colour for the page as a whole.

I'm not sure what your idea is of having a `"display"` setting.

I would appreciate it if you put this feature suggestion on the forum, so other people can feedback.

**Comment by kevin-corcoran-dev** [comment]
Thank you for your feedback.  

The `display` parameter was meant simply to disable the background rectangle if no color is desired. Even if the color were set to `white`, I was unsure if there would be side effects of sending it to a printer.  Maybe 'display' is the wrong name.

Yes, I did note that chord diagrams were hard-coded as black and white.  

But other than the diagrams, my modified local code is producing white text on a black background and it looks good for my purposes. 

But you are right, maybe the idea should be "workshopped" on the forum. Thanks for pointing me there.

**Comment by sciurius** [comment]
Implemented in 'dev'.
