### ISSUE TITLE
Text overflows into chord diagrams

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#145]
The issue tracker is for bug reporting.
Please use the [ChordPro user group](https://groups.google.com/forum/#!forum/chordpro) for general questions on how to use ChordPro.

**Describe the bug**
If a lyrics line is too long, it is word-wrapped at the edge of the page, sometimes flowing into the chord diagra,s

**To Reproduce**
Process this song:
```
{t: A long song}
{artist: nomike}
{start_of_verse: Verse}
[Em]I don't [G]know what to [A]sing about and I [F#m]honestly didn't [D]give it much though as [Bb]this song is just for [C]demonstration [Am]purposes.
{end_of_verse}
```

**Expected behavior**
Text should be wrapped neatly before the chords.

**Sample files and screenshots**
[A long song - nomike.pdf](https://github.com/ChordPro/chordpro/files/6795819/A.long.song.-.nomike.pdf)

**Please complete the following information:**
 - OS: Ubuntu 21.4
 - Perl version: v5.32.1
 - ChordPro version: 0.978
 - Where did you get ChordPro from: CPAN

**Additional context**
Not applicable.

**Comment by sciurius** [comment]
Fixed in git.
