### ISSUE TITLE
Preview function causes crash

### ISSUE THREAD

**Issue by SirElismyer** [ChordPro/chordpro#146]
The issue tracker is for bug reporting.
Please use the [ChordPro user group](https://groups.google.com/forum/#!forum/chordpro) for general questions on how to use ChordPro.

**Describe the bug**
Selecting "Preview" while using the GUI platform causes a crash.

**To Reproduce**
1. Select "Preview" from File Menu
2. Fatal Crash

**Expected behavior**
A PDF window should preview the song sheet.

**Please complete the following information:**
 - OS: Windows 10
 - Perl version: 5.32.1
 - ChordPro version: 0.979
 - Where did you get ChordPro from: Github Releases

**Additional Info**
This crash is not present in 0.978

**Comment by sciurius** [comment]
You mention the Perl version, may I assume you have StrawberryPerl installed and you are running from the source kit (App-Music-ChordPro-0.979.tar.gz)?

Have you tried the Windows Installer version (ChordPro-installer-0-979-0-1-msw-x64.exe)?

**Comment by SirElismyer** [comment]
I happen to have Perl installed as I first tried to install through the Strawberry Perl cpan install. This crashed on preview. I then uninstalled and then used the .exe installer. This also crashed.

Finally I used the .exe installer for 0.978 and no crashes.

**Comment by sciurius** [comment]
Can you include the ChordPro file you are trying to process and the config files that you use?

**Comment by sciurius** [comment]
Closed due to lack of response.
