### ISSUE TITLE
Wish: support ^/v ups and downs notation with a specific rendering style

### ISSUE THREAD

**Issue by wolftune** [ChordPro/chordpro#150]
https://en.xen.wiki/w/Ups_and_Downs_Notation is a way to indicate tunings. So Cv7 (C down seven) is different from C^7 (C up seven). And vC is itself different. Some chords: vC^m7  and ^Cv9 and so on. In Roman Numerals, it's like vVI^m and so on. There's never lower-case Roman Numerals since v is used for "down".

Especially with Roman Numerals, the ideal is to render the Roman Numerals with Serif font but to use a narrow sans-serif for the v and ^ symbols.

This stuff works somewhat as is, but it would be ideal to be able to specify the rendering style. The ultimate dream would be for the chords to actually be semantically understood so they could be transposed and so on.

**Comment by sciurius** [comment]
Either I don't understand, or I don't see the problem.

You can define a vC^m7 (whatever it means) in the config file, and use the `display` property to define how it must be printed.

I think you can define the 'notes' that make the EDO, e.g. a 14-EDO
````
    "notes" : {
	"system" : "14-EDO",

	"sharp" : [ "C", "C#",
		    "D", "D#",
		    "E", "E^",
		    "F", "F#",
		    "G", "G#",
		    "A", "A#",
		    "B", "B^",
		  ],

	"flat" :  [ "C",
		    "Db", "D",
		    "Eb", "E",
		    "vF", "F",
		    "Gb", "G",
		    "Ab", "A",
		    "Bb", "B",
		    "vC",
		  ],
    },
````
This should make ChordPro 'understand' the chords so you can transpose etc.

**Comment by wolftune** [comment]
oh nice, that does make sense. I'll have to test more what the limits of this are. I'm mostly concerned about whether I'd need to generate an enormous list of all possible chords vs being able to set a display rule that will know how to display a novel particular chord combination. But I'll just have to try more before reporting if anything breaks or is too tedious.

**Comment by sciurius** [comment]
I'd suggest to take this to [the community](https://groups.io/g/ChordPro).
