### ISSUE TITLE
Missing slash chord support

### ISSUE THREAD

**Issue by xeruf** [ChordPro/chordpro#152]
**Describe the bug**

Slash chords are not supported.

**Sample files and screenshots**

```sh
❯ cat test.cho
Test song

This is a [A]täst
Going to a [A/C#]chord
❯ chordpro test.cho
PDF: Unknown chord A/C# in song starting at line 1 in test.cho
```

Besides, the chord is definitely not in line 1 ^^

**Comment by xeruf** [comment]
The same chord can also be written as C#6 which is not recognized either. I am not expecting a fret diagram for every exotic chord, but it messes up the whole pdf output because it does not typeset anything until that line properly.

**Comment by sciurius** [comment]
Your example renders fine here. There is no pre-defined chord diagram for A/C# but you can easily add that yourself.

The message reads: "in song starting at line 1 in test.cho". The input to ChordPro is a songbook that can contain many songs. The offending song starts at line 1 in the songbook.

Also, it is better to start a song with a `{title}` directive.

If you still encounter problems, run your example with `chordpro --debug` and include the resultant PDF.

The issue template on GitHub kindly asks for details like whoch chordpro version, where you got it from, what platform you are running on. This could help tracking down problems.

**Comment by AnniePerson** [comment]
I did not check the given example, but I use slash chords all the time and it works flawlessly

**Comment by xeruf** [comment]
Adding a title directive fixed the output, thanks.
