### ISSUE TITLE
Silent failure

### ISSUE THREAD

**Issue by xeruf** [ChordPro/chordpro#154]
```sh
❯ cat test.cho
This is a [A]test
Going to a [C#]chord
❯ chordpro test.cho
❯ file test.pdf
test.pdf: cannot open `test.pdf' (No such file or directory)
```

When the file is wrongly formatted, chordpro in some cases such as above exits with 0 and does nothing. That is extremely confusing.

**Comment by sciurius** [comment]
I have added a warning if no songs were found in the input.
