### ISSUE TITLE
Support multiple verses without specifying sections explicitly

### ISSUE THREAD

**Issue by xeruf** [ChordPro/chordpro#155]
```cho
Test Song

This is a [Bm]test
Going to a [A]chord

I [Bm]dunno
but this is [G]good
```

I am really confused as to why this is typeset like this, rather than treating each paragraph as a verse:

![image](https://user-images.githubusercontent.com/13354331/128787627-703c848a-c922-4e4f-b95c-16d19f4b21ef.png)

**Comment by sciurius** [comment]
Please start your song with a `{title}`.

If you still encounter problems, run your example with `chordpro --debug` and include the resultant PDF.

The issue template on GitHub kindly asks for details like whoch chordpro version, where you got it from, what platform you are running on. This could help tracking down problems.

**Comment by sciurius** [comment]
@weltyj Is this a case you can catch in the a2crd importer?

**Comment by xeruf** [comment]
> Please start your song with a `{title}`.

I thought the point of the ChordPro format was that simple use-cases could be written in plain text, with the first line interpreted as title (if it contains no chord directives) and the remaining paragraphs as parts of the song.
Yet it somehow interprets parts as comments.

As for the issue template, I am on Arch and thus always on the latest version. It was quite unwieldy as well, that's why I submitted the PR ;)

**Comment by sciurius** [comment]
> I thought the point of the ChordPro format was that simple use-cases could be written in plain text, with the first line interpreted as title ...

I can't see that anywhere in the documentation. Maybe you are confusing one of the several other ChordPro-like tools?

ChordPro files use `{directives}`, and `[chords]` in the text. This has been so from the very start in 1992. There is an alternative format that is plain ASCII with chords on top of the lyrics. See e.g. the *.crd files in the t/a2crd directory. When an input file does not contain directives, ChordPro tries to interpret it in the alternative format. This format is often ambiguous so results vary.

**Comment by xeruf** [comment]
Well, is there any reason _not_ to support such a simple plain-text use-case?

**Comment by sciurius** [comment]
As I tried to explain, this is already mostly supported by automatically converting text input to ChordPro if necessary. However, the conversion is sometimes ambiguous.

In the next version you can suppress the automatic conversion with command line option `--noa2crd` so you (often) get better results.

**Comment by sciurius** [comment]
As I tried to explain, this is already mostly supported by automatically converting non-ChordPro input to ChordPro. However, this conversion sometimes misses certain parts due to input ambiguity.

The next version will have a command line option `--no-a2crd` that can be used to suppress automatic conversion, which may give better results in some cases.
