### ISSUE TITLE
%{page} in TOC is wrong

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#158]
## Describe the bug
The `%{page}` value in the TOC does not correspond to the actual page numbers.

### To Reproduce
1. Download and extract [test.tar.gz](https://github.com/ChordPro/chordpro/files/6978887/test.tar.gz)
2. Run "make"

### Expected behavior
According to the [documentation](https://www.chordpro.org/chordpro/chordpro-configuration-format-strings/) the `%{page}` directive should print 'The starting page number of the song.'.

### Actual behavior
It looks like chordpro puts the ending page number of the song in the TOC.

### Sample files and screenshots
[test.pdf](https://github.com/ChordPro/chordpro/files/6978885/test.pdf)

## Please complete the following information
 - OS: Ubuntu 21.4
 - Perl version: This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-gnu-thread-multi
 - ChordPro version: Latest git commit (77e85477ba4ad04578375e98e5fe90521fc97de1), This is ChordPro version 0.979_021
 - Where did you get ChordPro from: GitHub

**Comment by sciurius** [comment]
Thanks. Fixed in git.
