### ISSUE TITLE
Config file referenced via CHORDPRO_LIB path can use only lowercase letters

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#161]
## Describe the bug
ChordPro doesn't find config file in CHORDPRO_LIB when the filename includes uppercase characters.

### To Reproduce
Place a valid instrument config such as `ukulele_G-ly.json` in `~/.config/chordpro/config` (i.e. default `CHORDPRO_LIB/config` subfolder)

Run ChordPro specifying a 'short-form' name for the config file:
```
chordpro --config ukulele_G-ly Drink_Up_Thy_Zider.cho 
ukulele_G-ly: No such file or directory
```
Changing name of config file to all lowercase makes the above command work, regardless of whether upper- and lowercase 'G' in config name specified on command line.

### Expected behavior
ChordPro should locate instrument config, and run successfully.

## Please complete the following information
 - OS: Linux Debian Buster/10 (as LMDE4)
 - Perl version: 5.32.1
 - ChordPro version: 5.980
 - Where did you get ChordPro from: CPAN

## Additional context
More detailed account at [https://groups.io/g/ChordPro/message/803](https://groups.io/g/ChordPro/message/803)

**Comment by gwyndaf** [comment]
**Workaround**
Simple workaround solution is to ensure that letters in config filenames are lowercase only.

**Comment by sciurius** [comment]
Yes. They can be referred (used) in any case. The physical file needs to have a all-lowercase name.

**Comment by sciurius** [comment]
Added documentation https://www.chordpro.org/beta/chordpro-configuration-presets/#user-library
