### ISSUE TITLE
Segmentation fault on 10.14.6

### ISSUE THREAD

**Issue by lauhub** [ChordPro/chordpro#162]
The 5.980 version does not work on macOS Mojave.

Trying to open the application from Finder indicates it requires macOS 10.15

From command line, I get the following message:

Can't store REGEXP items at /Applications/ChordPro.app/Contents/MacOS/script/../lib/App/Music/ChordPro/Chords/Parser.pm line 708.

I can't migrate to 10.15 because of incompatibilities with other software/hardware I use.

Is there a way to compile/install Chordpro onto Mojave platform ?

**Comment by sciurius** [comment]
Can you paste the 'About' window and the output from `chordpro --about`?

**Comment by lauhub** [comment]
I can't open the application at all so the About window is not available for me.

Here is the output from command line:

```
 /Applications/ChordPro.app/Contents/MacOS/chordpro --about

ChordPro: A lyrics and chords formatting program.

ChordPro will read a text file containing the lyrics of one or many
songs plus chord information. ChordPro will then generate a
photo-ready, professional looking, impress-your-friends sheet-music
suitable for printing on your nearest printer.

To learn more about ChordPro, look for the man page or do
"chordpro --help" for the list of options.

For more information, see https://www.chordpro.org .

Run-time information:
ChordPro version       5.980
Perl version           v5.24.1
Perl program           /Applications/ChordPro.app/Contents/MacOS/chordpro
Resource path          /Applications/ChordPro.app/Contents/MacOS/lib/App/Music/ChordPro/res
Text::Layout           0.021
HarfBuzz::Shaper       0.023
HarfBuzz library       2.6.4i
File::LoadLines        1.02
PDF::API2              2.038
Font::TTF              1.06

```

**Comment by sciurius** [comment]
This is unexplainable on different levels...

ChordPro is compiled with `-mmacosx-version-min=10.7` which should be sufficient for Mojave.

The module that gives the error "Can't store REGEXP items" should have been fixed in the kit. 

Unfortunately I don't have Mojave at hand, so I asked the mailing list for advice.

Please subscribe to the mailing list https://groups.io/g/ChordPro so the community can join in.

**Comment by sciurius** [comment]
Closed for lack of feedback.
