### ISSUE TITLE
Memory leak when compiling a directory full of chords

### ISSUE THREAD

**Issue by jzbor** [ChordPro/chordpro#163]
## Describe the bug
I am trying to create a song book based on a collection of chordpro formatted files.
It worked great with the chordpro version/installation I was using initially.
Now every time I try to compile it with or without my config it doesn't finish, but instead slowly takes up all my memory until my computer freezes.

### To Reproduce
Message me if you need the files, I don't want to make them publicly available, as I don't own the rights and haven't created all of them myself.

### Expected behavior
It should either fail gracefully and report the problem or finish successfully.

### Sample files and screenshots
See above.

## Please complete the following information
 - OS: Up-to-date Arch Linux
 - Perl version: v5.34.0
 - ChordPro version 5.981
 - Using `chordpro-git` from the AUR (effectively 5.981 at my date of installation)

## Additional context
When installing not all tests ran successfully.
I also wasn't able to install it from CPAN.

[output.txt](https://github.com/ChordPro/chordpro/files/7061655/output.txt)

**Comment by sciurius** [comment]
Please send the song source + configs to info@chordpro.org.

**Comment by jzbor** [comment]
> Please send the song source + configs to [info@chordpro.org](mailto:info@chordpro.org).

I send you the mail. Thanks for the support!
