### ISSUE TITLE
Option to omit comments

### ISSUE THREAD

**Issue by xeruf** [ChordPro/chordpro#166]
A command-line or even better config option to omit comments would be nice.

This could alternatively be solved by allowing more generic selectors (e.g. I can specify enabled selectors in the config file as a list and thus use a selector such as `hint` independent of instrument or voice).

**Comment by sciurius** [comment]
Can you provide some use cases why/how this would be useful?

**Comment by xeruf** [comment]
A chord sheet that contains hints/instructions for internal use, which should not be present on the publicly available version.

**Comment by sciurius** [comment]
Seems like an excellent case for 

    {comment-internal Some internal hints.}

Or even

    {start-of-hints-internal}
    {comment Some internal hints}
    {comment Some internal hints}
    {comment Some internal hints}
    {end_of_hints}

**Comment by xeruf** [comment]
Yes I thought so, but then I have to set the username to `internal`, right?

**Comment by xeruf** [comment]
@sciurius is that right, or is there some other mechanism to enable "internal" selectors?

**Comment by sciurius** [comment]
Oops, sorry... Yes, for the time being you'll have to set the user name (or instrument, but I wouldn't advise that) to "internal".
