### ISSUE TITLE
Warning when i preview chordpro file

### ISSUE THREAD

**Issue by Loco1911** [ChordPro/chordpro#168]
## Describe the bug
When I generate a PDF file in the GUI it is generated correctly, but the program gives me the following warning:
` : Use of uninitialized value in string eq at C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/Output/PDF.pm line 319.

 : Problems found!
`

### To Reproduce
1. Open GUI Chordpro
2. Click on preview (Ctrl + P)
3. See error

### Expected behavior
It should not issue any warning since the PDFs are generated correctly

## Please complete the following information
 - OS: 2 Windows 10 PCs
 - ChordPro version: 5.982
 - Where did you get ChordPro from: GitHub Releases

**Comment by Loco1911** [comment]
[myconfig.zip](https://github.com/ChordPro/chordpro/files/7132468/myconfig.zip)

**Comment by sciurius** [comment]
Thanks. In your config, you set `instrument` to `null`. Either remove this (it is set in the instrument file) or set it to a correct value.

You're not the first one to report this. I'll see if I can solve this otherwise.

**Comment by Loco1911** [comment]
Thanks! I was able to fix the problem.
