### ISSUE TITLE
Misleading error when trying to convert nonexistent file

### ISSUE THREAD

**Issue by xeruf** [ChordPro/chordpro#169]
## Describe the bug
When attempting to convert a nonexistent file, I get an unhelpful perl error.

### To Reproduce
```sh
❯ chordpro nonexistent.cho
Undefined subroutine &File::LoadLines::croak called at /usr/share/perl5/vendor_perl/File/LoadLines.pm line 113.
```

### Expected behavior
A clear error such as "No such file: nonexistent.cho"

**Comment by sciurius** [comment]
I assume some of the modules that chordpro depend on are out of date.

Unfortunately you didn't provide the environment details kindly asked by the bug form so I can only guess.

**Comment by xeruf** [comment]
I doubt that, I am on Arch with Chordpro 0.979. Chordpro works fine, as said this happens when trying to convert a nonexistent file. What happens for you in that case?

**Comment by xeruf** [comment]
Wait the version number is off, what's going on here...

**Comment by xeruf** [comment]
Okay the AUR is out of date here, I'll get back later...

**Comment by xeruf** [comment]
You were right here, it was outdated :) I am not even used to checking this on Arch anymore...
