### ISSUE TITLE
Allow Conditionals for chords

### ISSUE THREAD

**Issue by xeruf** [ChordPro/chordpro#176]
## Describe the bug
Some chords may only be relevant to a particular instrument or user.

### Expected behavior
The possibility to add conditionals to chords just as you can for directives, so they are omitted if it doesn't match.

**Comment by sciurius** [comment]
Seems like a suitable case for sections:
````
{begin_of_verse-guitar}
[A]Hello, [Bm]World!
{end_of_verse}
{begin_of_verse-keyboard}
[A]He[A7]ll[C#dim]o [B7add9][Am][Bm9]Wo[C69sus4]rld![C][E♭7][A♭M7][D♭7]
{end_of_verse}

**Comment by xeruf** [comment]
yes, but I am currently duplicating whole verses just to omit some chords in one, which violates DRY, unnecessary inflating the file

**Comment by xeruf** [comment]
Compare this
```
{begin_of_verse-guitar}
[A]Hello, [Bm]World!
[A]Sweet [Bm]Home!
{end_of_verse}
{begin_of_verse-keyboard}
[A]He[A7]llo, [Bm]World![C]
[A]Swe[A7]et [Bm]Home![C]
{end_of_verse}
```
to this:
```
{begin_of_verse}
[A]He[A7-piano]llo, [Bm]World![C-keyboard]
[A]Swe[A7-piano]et [Bm]Home![C-keyboard]
{end_of_verse}
```
the last one is also much quicker to write than duplicating it and then deleting here and there, especially if the song is still in development and changes would then again have to be made in multiple places.

**Comment by sciurius** [comment]
Can you move this to the forum? This may be interesting to other users as well.

**Comment by sciurius** [comment]
As with many things, you can already achieve this ☺.
[Conditional_Chords.zip](https://github.com/ChordPro/chordpro/files/7209040/Conditional_Chords.zip)

**Comment by xeruf** [comment]
Oh wow, didn't know the directives where that powerful ^^ thx

**Comment by xeruf** [comment]
This should go into the currently empty "hints & tips" page ;)

**Comment by sciurius** [comment]
Patches welcome.
