### ISSUE TITLE
Path and file name not handling non English characters!

### ISSUE THREAD

**Issue by david8000** [ChordPro/chordpro#178]
Upgraded from 0.9x to 5,x (latest, windows 10)
Could not open files anymore..

Turns out many unicode characters are now illegal in Path/filename!

Example works:
c:\songs\my file.chopro

Examples does not work:
c:\låtar\my file.chopro
c:\songs\sången om elin.chopro

**Comment by sciurius** [comment]
Can you be more specific what error you get, and when?

**Comment by david8000** [comment]
On File->Open

Luckily these chars works within the song :)

**Comment by sciurius** [comment]
When you file an issue, you get a template to fill in. These details are necessary to find out what is going on.
You cancelled the template and do not supply details, even when asked.

Please supply the details asked so we can try to help you.
