### ISSUE TITLE
Now error on chord/bassnote notation

### ISSUE THREAD

**Issue by david8000** [ChordPro/chordpro#179]
Upgraded from 0.9x to 5,x (latest, windows 10)
Now getting errors on this common chord notation:

On Preview:

 : PDF: Unknown chord Am/B in song starting at line 1 in C:\Users\kalle\AppData\Local\Temp\PjjtgGNTnd.cho

 : PDF: Unknown chord C/E in song starting at line 1 in C:\Users\kalle\AppData\Local\Temp\PjjtgGNTnd.cho

 : Problems found!

**Comment by david8000** [comment]
But it works on transpose after all, so it's just cosmetic : )

**Comment by sciurius** [comment]
Am/B and C/E are not part of the built-in set of chords, so you have to define them.

See https://www.chordpro.org/chordpro/directives-define/ and https://www.chordpro.org/chordpro/chordpro-configuration-generic/#user-defined-chords-string-instruments
