### ISSUE TITLE
Fingers on Built-in Chords

### ISSUE THREAD

**Issue by jrmora** [ChordPro/chordpro#18]
It will be really really good to have the same option : fingers on diagrams (exactly as with the 
User defined chords ) for the built-in chords...  please add it :)

**Comment by sciurius** [comment]
This looks like a perfect issue for users to contribute. 

You can dump all built-in chords with

chordpro --dump-chords-text > allchords.cho

**Comment by neophytte** [comment]
I also wrote an on-line chord generator for those obscure chords here:
http://neophytte.mine.nu/chord/

Add a chord definition to the beginning of your chordpro sheet,
because not every song uses diminished and augmented chords, example
definition for F augmented:

{define: F+ base-fret 0 frets 1 0 3 2 2 1 }
 
-------------------------------
J. R. Mortimer

----- Original Message -----

**Comment by sciurius** [comment]
Cute.
I think for the chordii/chordpro {define}s, you misunderstood the meaning of the base-fret and frets.

**Comment by jrmora** [comment]
OK, so far I have write the 48 "easy chords" and I am putting them in a config file:

  // User defined chords.
  // "base" defaults to 1.
  // "easy" defaults to 0.
  // Use 0 for an empty string, and -1 for a muted string.
  "chords": [
    { "name": "C", "base": 1, "frets": [ -1, 3, 2, 0, 1, 0 ], "fingers": [ 0, 3, 2, 0, 1, 0 ] },
    { "name": "C7", "base": 1, "frets": [ 0, 3, 2, 3, 1, 0 ], "fingers": [ 0, 3, 2, 4, 1, 0 ] },
    { "name": "Cm", "base": 3, "frets": [ -1, 1, 3, 3, 2, 1 ], "fingers": [ 1, 1, 3, 4, 2, 1 ] },
    { "name": "Cmin", "base": 3, "frets": [ -1, 1, 3, 3, 2, 1 ], "fingers": [ 0, 1, 3, 4, 2, 1 ] },
    { "name": "C3", "base": 3, "frets": [ -1, 1, 3, 3, 2, 1 ], "fingers": [ 0, 1, 3, 4, 2, 1 ] },
    { "name": "Cm7", "base": 3, "frets": [ -1, 1, 3, 1, 2, 1 ], "fingers": [ 0, 1, 3, 1, 2, 1 ] },
    { "name": "D", "base": 1, "frets": [ -1, -1, 0, 2, 3, 2 ], "fingers": [ 0, 0, 0, 1, 3, 2 ] },
    { "name": "D7", "base": 1, "frets": [ -1, -1, 0, 2, 1, 2 ], "fingers": [ 0, 0, 0, 2, 1, 3 ] },
    { "name": "Dm", "base": 1, "frets": [ -1, -1, 0, 2, 3, 1 ], "fingers": [ 0, 0, 0, 2, 4, 1 ] },
    { "name": "Dmin", "base": 1, "frets": [ -1, -1, 0, 2, 3, 1 ], "fingers": [ 0, 0, 0, 2, 4, 1 ] },
    { "name": "Dm7", "base": 1, "frets": [ -1, -1, 0, 2, 1, 1 ], "fingers": [ 0, 0, 0, 2, 1, 1 ] },
    { "name": "E", "base": 1, "frets": [ 0, 2, 2, 1, 0, 0 ], "fingers": [ 0, 2, 3, 1, 0, 0 ] },
    { "name": "E7", "base": 1, "frets": [ 0, 2, 2, 1, 3, 0 ], "fingers": [ 0, 2, 3, 1, 4, 0 ] },
    { "name": "Em", "base": 1, "frets": [ 0, 2, 2, 0, 0, 0 ], "fingers": [ 0, 2, 3, 0, 0, 0 ] },
    { "name": "Em7", "base": 1, "frets": [ 0, 2, 2, 0, 3, 0 ], "fingers": [ 0, 2, 3, 0, 4, 0 ] },
    { "name": "F", "base": 1, "frets": [ 1, 3, 3, 2, 1, 1 ], "fingers": [ 1, 3, 4, 2, 1, 1 ] },
    { "name": "F7", "base": 1, "frets": [ 1, 3, 1, 2, 1, 1 ], "fingers": [ 1, 3, 1, 2, 1, 1 ] },
    { "name": "Fm", "base": 1, "frets": [ 1, 3, 3, 1, 1, 1 ], "fingers": [ 1, 3, 4, 1, 1, 1 ] },
    { "name": "Fmin", "base": 1, "frets": [ 1, 3, 3, 1, 1, 1 ], "fingers": [ 1, 3, 4, 1, 1, 1 ] },
    { "name": "Fm7", "base": 1, "frets": [ 1, 3, 1, 1, 1, 1 ], "fingers": [ 1, 3, 1, 1, 1, 1 ] },
    { "name": "F#", "base": 1, "frets": [ 2, 4, 4, 3, 2, 2 ], "fingers": [ 1, 3, 4, 2, 1, 1 ] },
    { "name": "F#7", "base": 1, "frets": [ -1, -1, 4, 3, 2, 0 ], "fingers": [ 0, 0, 3, 2, 1, 0 ] },
    { "name": "F#m", "base": 1, "frets": [ 2, 4, 4, 2, 2, 2 ], "fingers": [ 1, 3, 4, 1, 1, 1 ] },
    { "name": "F#min", "base": 1, "frets": [ 2, 4, 4, 2, 2, 2 ], "fingers": [ 1, 3, 4, 1, 1, 1 ] },
  	{ "name": "F#m7", "base": 1, "frets": [ -1, -1, 2, 2, 2, 2 ], "fingers": [ 0, 0, 1, 1, 1, 1 ] },
    { "name": "Gb", "base": 1, "frets": [ 2, 4, 4, 3, 2, 2 ], "fingers": [ 1, 3, 4, 2, 1, 1 ] },
    { "name": "Gb7", "base": 1, "frets": [ -1, -1, 4, 3, 2, 0 ], "fingers": [ 0, 0, 3, 2, 1, 0 ] },
    { "name": "G", "base": 1, "frets": [ 3, 2, 0, 0, 0, 3 ], "fingers": [ 2, 1, 0, 0, 0, 4 ] },
    { "name": "G7", "base": 1, "frets": [ 3, 2, 0, 0, 0, 1 ], "fingers": [ 3, 2, 0, 0, 0, 1 ] },
    { "name": "Gm", "base": 3, "frets": [ 1, 3, 3, 1, 1, 1 ], "fingers": [ 1, 3, 4, 1, 1, 1 ] },    
    { "name": "Gmin", "base": 3, "frets": [ 1, 3, 3, 1, 1, 1 ], "fingers": [ 1, 3, 4, 1, 1, 1 ] },
    { "name": "Gm7", "base": 3, "frets": [ 1, 3, 1, 1, 1, 1 ], "fingers": [ 1, 3, 1, 1, 1, 1 ] },
    { "name": "G#", "base": 4, "frets": [ 1, 3, 3, 2, 1, 1 ], "fingers": [ 1, 3, 4, 2, 1, 1 ] },
    { "name": "G#7", "base": 1, "frets": [ -1, -1, 1, 1, 1, 2 ], "fingers": [ 0, 0, 3, 2, 1, 0 ] },   
    { "name": "G#m7", "base": 4, "frets": [ -1, -1, 1, 1, 1, 1 ], "fingers": [ 0, 0, 1, 1, 1, 1 ] },
    { "name": "A", "base": 1, "frets": [ -1, 0, 2, 2, 2, 0 ], "fingers": [ 0, 0, 1, 2, 3, 0 ] },
    { "name": "A7", "base": 1, "frets": [ -1, 0, 2, 0, 2, 0 ], "fingers": [ 0, 0, 1, 0, 2, 0 ] },
    { "name": "Am", "base": 1, "frets": [ -1, 0, 2, 2, 1, 0 ], "fingers": [ 0, 0, 2, 3, 1, 0 ] },
    { "name": "Amin", "base": 1, "frets": [ -1, 0, 2, 2, 1, 0 ], "fingers": [ 0, 0, 2, 3, 1, 0 ] },
    { "name": "Am7", "base": 1, "frets": [ -1, 0, 2, 2, 1, 3 ], "fingers": [ 0, 0, 2, 3, 1, 4 ] },
    { "name": "Bb", "base": 1, "frets": [ -1, 1, 3, 3, 3, 1 ], "fingers": [ 1, 1, 2, 3, 4, 1 ] },
    { "name": "Bbm", "base": 1, "frets": [ -1, 1, 3, 3, 2, 1 ], "fingers": [ 0, 1, 3, 4, 2, 1 ] },
    { "name": "Bbmin", "base": 1, "frets": [ -1, 1, 3, 3, 2, 1 ], "fingers": [ 0, 1, 3, 4, 2, 1 ] },
    { "name": "B", "base": 1, "frets": [ 2, 2, 4, 4, 4, 2 ], "fingers": [ 1, 1, 2, 3, 4, 1 ] },
    { "name": "B7", "base": 1, "frets": [ 0, 2, 1, 2, 0, 2 ], "fingers": [ 0, 2, 1, 3, 0, 4 ] },
    { "name": "Bm", "base": 1, "frets": [ 2, 2, 4, 4, 3, 2 ], "fingers": [ 1, 1, 3, 4, 2, 1 ] },
    { "name": "Bmin", "base": 1, "frets": [ 2, 2, 4, 4, 3, 2 ], "fingers": [ 1, 1, 3, 4, 2, 1 ] },
    { "name": "Bm7", "base": 2, "frets": [ 2, 1, 3, 1, 2, 1 ], "fingers": [ 1, 1, 3, 1, 2, 1 ] },
  ]

I'm going to finish the remaining 313  :D, but in the meantime, I suggest another enhancement for you (new issue)... thanks

**Comment by neophytte** [comment]
>I think for the chordii/chordpro {define}s, you misunderstood the
meaning of the base-fret and frets.

Thanks, could you explain further? This was as an add-on to the chord
display part I had already written, so happy to get it working
correctly for others to use ... 

-------------------------------
J. R. Mortimer

----- Original Message -----

**Comment by sciurius** [comment]
@neophytte First, Chordii and ChordPro have exactly the same interpretation of base-fret and frets. Your tool gives different results when base-fret is greater than zero.

Further, I had hoped that the descripion of the directives in https://www.chordpro.org/chordpro/Directives-define.html would be sufficiently clear. In particular, it states that `base-fret` must be 1 or higher (the value 0 is interpreted as 1) and that the positions are relative to the base fret. This has always been the case, for Chordii as well as ChordPro.

**Comment by sciurius** [comment]
@neophytte Also, a plain C chord at base position gives `{define: C @0 base-fret ...` which is invalid (no spaces in chord names allowed).

Also, in the score image, the positions of the notes are one off. For the C chord this should be the notes C E G but it displays the notes B D F.

**Comment by neophytte** [comment]
Thanks for clarifying that - I've updated the tool and fixed the base
fret issue; I've also added a link back to the directives page as when
I started this tool, I didn't have it, and reverse engineered what I
saw). It's late here, I'll address the other issues shortly. Thanks
again.  

-------------------------------
J. R. Mortimer

----- Original Message -----

**Comment by sciurius** [comment]
@jrmora In Bm7, 1st fret must be 1, not 2.

**Comment by jrmora** [comment]
you are right, thanks

**Comment by topchyan** [comment]
Some data for Uke and guitar chord fingering already exists on GitHub

https://github.com/yaph/chords/commit/d2f229dc15907a8d37d6758bd7e0ea5c18e18654

Is it possible to somehow incorporate those fingerings into this project's config files?

**Comment by jrmora** [comment]
@topchyan Are you sure that there are fingers in that code?

**Comment by sciurius** [comment]
In data/ukulele-chords.txt, I see things like

    A  	2,1,0,0

This is just the frets info, no fingerings.

**Comment by topchyan** [comment]
yeah, sorry, let me continue searching

**Comment by topchyan** [comment]
There's this script to iterate through fingerings and map them to chord names.
https://github.com/zimolzak/ukulele
I guess I see the problem with many-to-many mappings: a chord can have multiple fingerings and a single fingering (on a uke, to a less degree on guitar) can easily represent multiple chords.
We're doomed :)

**Comment by topchyan** [comment]
There's hope! Lilypond project has this:

http://lilypond.org/doc/v2.19/Documentation/notation/predefined-fretboard-diagrams#diagrams-for-ukulele

Aparently, there's this elegant script that produces both diagrams and even fingerings (!) by just transposing a given set of chords 12 times:
http://lilypond.org/doc/v2.19/Documentation/09/lily-1eb52495.ly

**Comment by sciurius** [comment]
The script makes use of an extensive list of predefined charts. I can easily turn this into ChordPro configs... stay tuned.

**Comment by sciurius** [comment]
I have checked in three new config files derived from the LilyPond sources. They are currently in the 'dev' branch:

    lib/App/Music/ChordPro/res/config/guitar-ly.json
    lib/App/Music/ChordPro/res/config/mandolin-ly.json
    lib/App/Music/ChordPro/res/config/ukulele-ly.json

I would apperciate your feedback on these chords.
You can produce a chord chart with:

    chordpro --cfg guitar-ly --dump-chords -o chart.pdf /dev/null

**Note:** For the mandolin chords you need the development version of ChordPro otherwise you'll get a JSON load error.

**Comment by topchyan** [comment]
Lovely! 

I cloned the dev branch
`git clone -b dev --single-branch  https://github.com/sciurius/chordpro`

and modified command in SciTE to use lilypond based config:

`command.4.$(file.patterns.chordpro)=chordpro "$(FilePath)" --userconfig=/home/avetik/bin/chordpro_my.json --config=/home/avetik/chordpro/lib/App/Music/ChordPro/res/config/ukulele-ly.json --output="$(FilePath).pdf" && xreader "$(FilePath).pdf"
`
And produced this songsheet:
[Катерок.pro.txt](https://github.com/sciurius/chordpro/files/1467441/pro.txt)
[Катерок.pro.pdf](https://github.com/sciurius/chordpro/files/1467443/pro.pdf)
[chordpro_my.json.txt](https://github.com/sciurius/chordpro/files/1467455/chordpro_my.json.txt)

It looks good to me, very nice, very useful. Unfortunately, wxchordpro does not work yet, but hopefully it will be tweaked to become the IDE for chordpro. But so far so good. I haven't tried guitar yet, will try that later.
