### ISSUE TITLE
Font error on changing config preferences (wxchordpro)

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#182]
## Describe the bug
Error message on de-selecting then re-selecting Custom config:
```
 : Cannot load font: /home/alun/.config/chordpro/fonts/Roboto-LightItalic.ttf
Can't call method "new_obj" on unblessed reference at /usr/local/share/perl/5.32.1/PDF/API2/Resource.pm line 35.
 at /usr/local/share/perl/5.32.1/Text/Layout/FontDescriptor.pm line 93.

 : Fatal problems found!
```

### To Reproduce
1. Open wxchordpro
2. Set config preferences to use 'Chordpro' and own Custom config (referencing Roboto font set in fonts subfolder)
3. Close wxchordpro
4. Restart with sample song and preview: works fine
5. De-select Custom config and preview: works fine (but different styling without Custom config)
6. Re-select Custom config and preview: throws error as above
7. Close wxchordpro and restart (retaining Chordpro and Custom configs): preview works fine again.

### Expected behavior
Expect current config settings to be applied as at first run.

## System information
 - OS: Linux Mint on Debian Bullseye
 - Where did you get ChordPro from? CPAN
 - ChordPro version: 5.985
 - Perl version: 5.32.1

## Additional context
The error message seems font-related, so I wondered whether the GUI might not reload fonts when config changes.
A similar error also occurs with config changes that don't change font settings (e.g. adding 'Ukulele-ly' to selected configs.
Seems like some config/font stuff, which is loaded at startup, isn't re-loaded on config changes?
No comparable problems encountered when using CLI.

## Attachments
Config files attached, but not fonts (which reside in ~/.config/chordpro/fonts)

chordpro.json resides in ~/.config/chordpro
[chordpro.json.txt](https://github.com/ChordPro/chordpro/files/7269211/chordpro.json.txt)

roboto.json resides in ~/.config/chordpro/config
[roboto.json.txt](https://github.com/ChordPro/chordpro/files/7269216/roboto.json.txt)

**Comment by sciurius** [comment]
Can you check (Help > About or `chordpro --about`) the version of module Text::Layout?

**Comment by gwyndaf** [comment]
Modules and libraries:
  Storable               3.21
  Text::Layout           0.021
  File::LoadLines        1.02
  PDF::API2              2.040
  Font::TTF              1.06

**Comment by sciurius** [comment]
Can you send me your roboto fonts?

**Comment by gwyndaf** [comment]
Here's the whole fonts subfolder
[fonts.zip](https://github.com/ChordPro/chordpro/files/7270133/fonts.zip)

If you suspect it might be down to the specific fonts, I know some versions of Roboto can behave a bit oddly because it's often supplied as variable weight fonts, which don't seem to be PDF-friendly (e.g. LibreOffice PDF export). To avoid that, the ones here should all be the static versions, which work fine from the CLI, but perhaps the GUI tries to access system fonts? I'll try disabling the system Roboto fonts to see if that makes any difference.

**Comment by sciurius** [comment]
Thanks for the fonts. I can now reproduce the problem with minimal settings:

cfgpreset=custom
skipstdcfg=1
configfile=.config/chordpro/chordpro.json

Run wxchordpro with a simple song, preview (ok), preview (crash).

**Comment by gwyndaf** [comment]
FWIW I've just tested this with all the system Roboto fonts turned off and (if I've tweaked fontconfig correctly) all variable weight fonts disabled. 

Problem still reproduces, so it doesn't seem to be a clash between those in the fonts folder and any system fonts.

**Comment by sciurius** [comment]
It seems to be a re-entrancy problem in some font cache.
It may go away if you assign Roboto-LightItalic to one of the fonts, e.g.

        "comment_italic" : {
          "description" : "sanslight italic 9"
        },

But it's a bug, and a nasty one...

**Comment by gwyndaf** [comment]
Thanks for the workaround. It's mostly a bug flag, as I don't use the GUI often enough for it to affect my usual process (CLI/script), and have some pretty ambitious design settings, so hopefully it's not something that arises often.

**Comment by sciurius** [comment]
It is a reentrancy problem that can only occur with the GUI, since the GUI calls the ChordPro library each time a preview is made. The command line program calls the ChordPro library only once.

The deadly combination is:

- define a font family, e.g. serif, in the fontconfig. The actual fonts do not matter, builtins are equally hit by this bug.
- use one of the font family members for e.g. title 
- in the title string, use &lt;i> or &lt;b>. This selects the italic or bold member of the serif family.
- if this member of the family is not used otherwise, the ChordPro library will crash when re-entered.

The attached program simple2.pl emulates this by performing two calls on the library, the first succeeds and subsequent calls abort.

[issue0182.zip](https://github.com/ChordPro/chordpro/files/7273419/issue0182.zip)
