### ISSUE TITLE
{$pages} not working in footer

### ISSUE THREAD

**Issue by mebo** [ChordPro/chordpro#184]
If I read the [documentation](https://www.chordpro.org/chordpro/chordpro-configuration-format-strings/) well, I'd expect to be able to use the {$pages} meta data to get the total amount of pages for the current song.

I've put this in my configuration file with regards to the footer

`   "default": {
    "title": null,
    "subtitle": null,
    "footer": ["%{title}", "", "%{page} / %{pages}"],
   },
`

I'd expect to see (for a 2 page pdf) "1 / 2" on the first page and "2 / 2" on the second page, however, it seems that %{pages} is ignored entirely, the output shows "1 /  " on the first page and "2 /  " on the second page.

**Comment by sciurius** [comment]
This is now implemented in the curretn development version.
