### ISSUE TITLE
Newlines in directives

### ISSUE THREAD

**Issue by Ssamm45** [ChordPro/chordpro#187]
Is it possible to put newlines in directives or have line wrapping, so that when you put them in the footer with %{dir} it displays on multiple lines

For example, I have a song with a copyright notice long enough it couldn't possible fit on one line. 
In my config file file I have this

```
"first": {
	"title": ["","%{title}",""],
	"subtitle":["","%{subtitle}","%{artist}"],
	"footer"  : [ "", "%{copyright}", "%{page}" ]
}
```

When I run chordpro on the file the copyright notice just sits on one line extending off
both ends of the page only showing the middle third of the text.

I have tried adding a literal newline, a '\' followed by a literal newline, and '\n' but none
of those make it display the way it should. Is there a way to do this?

**Comment by sciurius** [comment]
No, there is no support for wrapping (or multiple lines) in headings/footers.
Maybe use a smaller font?
````
"first": {
	"title": ["","%{title}",""],
	"subtitle":["","%{subtitle}","%{artist}"],
	"footer"  : [ "", "<span size="25%">%{copyright}</span>", "%{page}" ]
}
````

**Comment by sciurius** [comment]
In the upcoming version you can do something like this:
````
{copyright: first line}
{copyright: second line}
````
With config:
````
"first": {
	"title": ["","%{title}",""],
	"subtitle":["","%{subtitle}","%{artist}"],
	"footer"  : [ [ "", "%{copyright.1}", "%{page}" ],[ "", "%{copyright.2}", "" ] ]
}
````
