### ISSUE TITLE
Feature request: add meta data to exported PDF

### ISSUE THREAD

**Issue by mebo** [ChordPro/chordpro#188]
Would it be possible to add all meta data in a chordpro file (artist, time, key, tempo) into the PDF as custom fields when exporting?

**Comment by sciurius** [comment]
I'm not sure I understand what you mean by custom fields.

You can get the metadata in the PDF with comments, e.g.
````
{comment: Artist: %{artist}}
{comment: Album: %{album}}
````
and so on.

See https://www.chordpro.org/chordpro/chordpro-configuration-format-strings/

**Comment by mebo** [comment]
What I mean is that the information is embedded in the PDF as meta data (open a PDF in Adobe Reader, goto file -> properties -> custom), it's called custom properties in Adobe reader.

With for example [this site](https://www.sejda.com/edit-pdf-metadata) you can add (custom) metadata to PDF's

**Comment by sciurius** [comment]
You mean this:
https://www.chordpro.org/chordpro/chordpro-configuration-pdf/#document-info

**Comment by mebo** [comment]
Yes, but it seems this way you can only add data to the default meta data fields (title, author, subject and keywords). I'd like to add non-default fields.

**Comment by sciurius** [comment]
Ok. I've added the ability to add additional keys to pdf.info, e.g.
````
"pdf" : {
  "info" : {
    "title"    : "%{title}",
    "author"   : "",
    "subject"  : "",
    "keywords" : "",
    "album"    : "%{album}",
    "composer" : "%{composer}",
    "MyAbritraryKey" : "A possibly interesting arbitrary value"
  }
}
````
Note that the custom keys require PDF::API2 version 2.042 or newer. Older versions will include only the standard info in the PDF.
