### ISSUE TITLE
[Feature request] HTML Output to output stream

### ISSUE THREAD

**Issue by lutz** [ChordPro/chordpro#189]
Hey chordpro maintainers,

it is great to see how this tool grows up. So currently the html export is only experimental. So the first question is if there any plan to make it stable? The secound question is more a feature request. Currently the html export supports only exporting in a file. Will it be possible to output the html to the console output stream?

I thought a lot about a better gui support for this command line tool with a preview feature based on the html export. Currently the only way will be to export  the changes every time to a file, load this and remove this file. So a other way could be to run the tool in a process and observe the output stream to load the export in memory .

So the question is if it possible to set a flag to outpit the html export result to the console.

Best regards
Daniel

**Comment by sciurius** [comment]
Currently the primary goals are the PDF and ChordPro backends. The other backends may not always get updated when something changed internally so that's why they are marked experimental. But they are definitely part of the process.

> Currently the html export supports only exporting in a file.

You can direct the output to standard output, but then you need to specify which backend to use. E.g.
````
chordpro --output - --generate HTML ...
````
I'd be interested to hear how that will help.

**Comment by lutz** [comment]
@sciurius thanks for answering. The parameter works as expected. But in .net i have the problem that the standard process works with the builtin terminal which is very old and encoding is not utf. So i had some trouble with encoding. When i export the chordpro file to a local (utf-8 encoded) html file and load it again it works well.  I know that pdf is the main supported backend but i hope in the future the html get more attention. 

In this case the chordpro html export could be a chnace to implement a preview control in som chord pro editors which is easier as show pdf.

Best regards and thank you for your work here,

**Comment by sciurius** [comment]
> works with the builtin terminal which is very old and encoding is not utf.

The standard output is written UTF8 encoded. Is there anything that ChordPro needs to do differently?

**Comment by lutz** [comment]
This has nothing to do with ChordPro. But it seems that i can fix it (i search for this case and found a stackoverflow topic which target this) and check it again. Currently this is only a proof in concept because the html backend has not the same functionality like the pdf backend but in future it will be (maybe) a way.
