### ISSUE TITLE
Annotations output in [brackets] (dev version)

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#192]
I just noticed that the git version (currently 5.985_070) appears to outputting annotations like `[*(slow)]` in square brackets, when the current release version puts no brackets, so what was printed as `(slow)` is now printed as `[(slow)]`. The change might have arisen before 070 but I didn't notice.

It's not a big issue, but puts extra 'ink on the page' so annotations might be marginally less clear to read.

I really like the `inline-chords : [%s]` config option to control how inline chords are displayed (I can see good future use for this).

But, does that also affect the output format of inline annotations?

Is there value in a separate config option for `inline-annotations : %s` or similar?

**Comment by sciurius** [comment]
I assume you're talking about the `inline-chords` case?

Yes, in this case the brackets are now included with the annotations, just like the chords. Do you think that's not ok?
I can add a setting for inline-annotations if that would help.

**Comment by gwyndaf** [comment]
Personally, I like to use annotations without [brackets], as I find that makes them clearer, but that's just my point of view. Other views might differ.

An `inline-annotations` setting (similar to `inline-chords`) would be fantastic, but it's a relatively minor design/readability tweak, and I don't know how much extra work that creates for you. 

If you do build that in, maybe the value should default to same behaviour as current release version, effectively `%s`?

**Comment by sciurius** [comment]
Your wish is my command ☺. It's in git.

**Comment by gwyndaf** [comment]
Oh, you legend! Thank you so much Johan. Makes my designer head very happy :)
