### ISSUE TITLE
Default config for CSV export: name 'sorttitles' should be 'sort title' for MSP

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#193]
Small spot: in default chordpro.json (git v071), I think a column `name` entry for CSV export mapping might be incorrect.

Default column name heading for `sorttitle` values is currently "sorttitles" and I think it should be "sort title" (with a space)

That's assuming Mobile Sheets Pro is the intended target for default CSV column names, as seems the case. Based on MSP documentation, and revised column name of "sort title" works with my own testing on MSP.

**Comment by sciurius** [comment]
Good catch. Fixed in git.
