### ISSUE TITLE
Backslash \ in source treated as escape character in error messages

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#195]
Minor issue, but where I use backslashes (to denote single down-strum), it can occasionally be interpreted as escape character in error messages, when it immediately precedes some characters, e.g. \t or \n, giving odd error message format.

Processing 
[Escape_oblique.cho.txt](https://github.com/ChordPro/chordpro/files/7744870/Escape_oblique.cho.txt)
gives error messages with tab and newline chracters:
```
"Escape_oblique.cho", line 3, Unknown chord: "Gdom"
	Here's [Gdom] a fairly [C]\simple line
"Escape_oblique.cho", line 5, Unknown chord: "Gdem"
	Here's [Gdem] a [C]	est line that could be tab
"Escape_oblique.cho", line 7, Unknown chord: "Gdym"
	Here's [Gdym] a[C]
other line that could be newline

**Comment by sciurius** [comment]
Fixed, thanks!
