### ISSUE TITLE
Strange text wrapping with multiple columns (maybe related to +pdf.spacing directive)

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#199]
I've been exploring 2-column layouts for on-screen/projection use, and get strange text wrap behaviour in second column, as if wrapping around an invisible rectangle. Issue continues on to subsequent page, columns 1 and 2.

Test case:
[2-col.json.txt](https://github.com/ChordPro/chordpro/files/7833505/2-col.json.txt)
[Ain_t_Nobody.cho.txt](https://github.com/ChordPro/chordpro/files/7833506/Ain_t_Nobody.cho.txt)
processed with:
```
chordpro -X --config 2-col.json Ain_t_Nobody.cho.txt
```
Results in
[Ain_t_Nobody.cho.pdf](https://github.com/ChordPro/chordpro/files/7833508/Ain_t_Nobody.cho.pdf)

Behaviour seems to occur with both release v.5.985 and git 082 (on Debian Bookworm).

Behaviour goes away if I comment out spacing settings `{+pdf.spacing.lyrics 1.15}` from source. Same issues experienced with `{+pdf.spacing.chords 1.15}`.

Also tested across a large collection of songs, and behaviour correlates with those songs that have some `+pdf.spacing` setting.

**Comment by sciurius** [comment]
Thanks. Fixed in git (even though formally not supported ☺).

**Comment by gwyndaf** [comment]
Ah, apologies for pushing it too far! 083 works nicely. Much appreciated.
