### ISSUE TITLE
Transcoding doesn't work properly for first file in list

### ISSUE THREAD

**Issue by AdaSur** [ChordPro/chordpro#201]
## Describe the bug

When use file list, transcoding to german doesn't work properly for first file,  if it contains Bb  chord (chord diagrams are O.K. see output.pdf)
If you use only that file, it works O.K. - see output_singlefile.pdf

Filelist.txt content:
test.chopro
test.chopro
test.chopro
test.chopro

out: output.pdf

### To Reproduce
1.  chordpro.exe --config=default.json --filelist filelist.txt -o output.pdf
2.  chordpro.exe --config=default.json test.chopro -o output_singlefile.pdf
3. 
4. 

### Attachments

Test.chopro content:
{title: Test song}

Thi[C#]s is a s[Bm]ample v[Bb]ers[Bbm]e
## System information
 - OS:  Windows 10
 - Where did you get ChordPro from?  GitHub

 - ChordPro version: This is ChordPro core 5.985
 - Perl version: 

## Additional context

[output_singlefile.pdf](https://github.com/ChordPro/chordpro/files/7871713/output_singlefile.pdf)
[output.pdf](https://github.com/ChordPro/chordpro/files/7871714/output.pdf)

**Comment by sciurius** [comment]
A lot has changed in the area or transcoding, and it seems to work fine with the current git version:

`chordpro -X --transcode german --config modern3 --filelist list.txt --output output.pdf`

[output.pdf](https://github.com/ChordPro/chordpro/files/7872393/output.pdf)

**Comment by AdaSur** [comment]
But there is no Hm chord diagram in your output.pdf.

**Comment by AdaSur** [comment]
And B and Bm chords diagrams are wrong, not in german notation (should be displayed Bb and Bbm)

**Comment by sciurius** [comment]
I'm afraid I can't follow you.

As far as I know, the common 'B' is 'H' in german, and common 'Bb' (B-flat) is 'B'. Also, sharp chords get a 'is' suffix and flat chords get a 'es' suffix. So the chords `C# Bm Bb Bbm` become `Cis Hm B Bm` in german. And that is what I see in the output.

![scrot20220115104248](https://user-images.githubusercontent.com/1118804/149617335-addb7baf-92e2-453c-ab63-7286f9909250.png)

**Comment by AdaSur** [comment]
I run 

 

chordpro -X --transcode german --config modern3 --filelist filelist.txt --output d:\output.pdf --debug

 

 

on fresh installation (downloaded from github) and this is debug and output.

 

 

This is ChordPro core 5.985

filelist.txt is ASCII (detected)

Reading: <builtin>

RSC3: config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Config[0]: <builtin>

Config[1]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Config[2]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Process: <builtin>

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Chords: Created parser for common

Processed 418 chord entries

Totals: 573 config chords

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Parsers:

Parsers at start of test.chopro:

Processing song...

Chords: Created parser for common

Processed song...

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/notes/german.json

Chords: Created parser for german

Got transcoder for german

Parser: german

Parser: common

Parsers at start of test.chopro: *common german

Processing song...

Processed song...

Got transcoder for german

Parser: german

Parser: common

Cannot transcode Hm

RSC3: fonts/

Reading: <builtin>

RSC3: config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Config[0]: <builtin>

Config[1]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Config[2]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Process: <builtin>

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Chords: Created parser for common

Processed 418 chord entries

Totals: 573 config chords

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Chords: Created parser for common

PDF: Unknown chord Hm in song starting at line 1 in test.chopro

RSC3: fonts/

Reading: <builtin>

RSC3: config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Config[0]: <builtin>

Config[1]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Config[2]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Process: <builtin>

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Chords: Created parser for common

Processed 418 chord entries

Totals: 573 config chords

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Chords: Created parser for common

PDF: Unknown chord Hm in song starting at line 1 in test.chopro

PDF: Lookup chord B... found

PDF: Lookup chord Bm... found

RSC3: fonts/

Use of uninitialized value $file in -f at C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/Output/PDF/Writer.pm line 593.

RSC3: fonts/

Use of uninitialized value $file in -f at C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/Output/PDF/Writer.pm line 593.

 

 

chordpro -X --transcode german --config modern3 test.chopro --output d:\output_single.pdf --debug

 

 

 

This is ChordPro core 5.985

Reading: <builtin>

RSC3: config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Config[0]: <builtin>

Config[1]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Config[2]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Process: <builtin>

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Chords: Created parser for common

Processed 418 chord entries

Totals: 573 config chords

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Parsers:

Parsers at start of test.chopro:

Processing song...

Chords: Created parser for common

Processed song...

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/notes/german.json

Chords: Created parser for german

Got transcoder for german

Parser: german

Parser: common

RSC3: fonts/

Reading: <builtin>

RSC3: config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Reading: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Config[0]: <builtin>

Config[1]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Config[2]: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Process: <builtin>

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/guitar.json

Chords: Created parser for common

Processed 418 chord entries

Totals: 573 config chords

Process: C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/res/config/modern3.json

Chords: Created parser for common

PDF: Unknown chord Hm in song starting at line 1 in test.chopro

 

 

 

What can be wrong?

**Comment by sciurius** [comment]
I said that this seems to have been solved in the development version (5.985_xxx). You are still running the stable version (5.985).
See https://www.chordpro.org/chordpro/chordpro-run-from-git/

**Comment by AnniePerson** [comment]
With ChordPro-Installer-5-985**-58**-1-msw-x64.exe from https://groups.io/g/ChordPro/message/1136 I get the same result as in Sciurius' screenshot from yesterday. It shows the intended behaviour. ChordPro-Installer-5-985**-31**-2-msw-x64.exe still had issues.

**Comment by AnniePerson** [comment]
@AdaSur: what do you mean with "And B and Bm chords diagrams are wrong, not in german notation (should be displayed Bb and Bbm)" ? 
If you expect C# Hm Bb Bbm you should use "transcode scandinavian" instead of "transcode german"

**Comment by sciurius** [comment]
Closed due to lack of response.
