### ISSUE TITLE
wxchordpro: Could not find abcm2ps when chordpro opened from file.

### ISSUE THREAD

**Issue by Grant-ed** [ChordPro/chordpro#204]
## Bug description

abcm2ps tool is not loaded (reported as missing,, see below) when wxchordpro previews PDF. This bug is only present when wxchordpro is opened by double clicking a chordpro file, not when it is launched through the start menu.

```
 : Could not find abcm2ps.exe in "." "D:\Program Files\ImageMagick-7.1.0-Q16-HDRI" "C:\Program Files (x86)\Common Files\Oracle\Java\javapath" "D:\Program Files\Amazon Corretto\jdk15.0.2_7\bin" "C:\Python39\Scripts\" "C:\Python39\" "C:\Program Files\Oculus\Support\oculus-runtime" "C:\Windows\system32" "C:\Windows" "C:\Windows\System32\Wbem" "C:\Windows\System32\WindowsPowerShell\v1.0\" "C:\Windows\System32\OpenSSH\" "C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR" "C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common" "D:\Program Files\nodejs\" "C:\ProgramData\chocolatey\bin" "C:\Program Files\Microsoft SQL Server\130\Tools\Binn\" "C:\Program Files\dotnet\" "C:\Program Files\CMake\bin" "D:\Program Files\Git\cmd" "C" "C:\Program Files\TortoiseGit\bin" "C:\Program Files\MATLAB\R2021a\bin" "C:\Users\grant\AppData\Local\Microsoft\WindowsApps" "C:\Users\grant\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts" "C:\Users\grant\AppData\Roaming\npm" "D:\texlive\2021\bin\win32" "C:\Users\grant\.dotnet\tools" "C:\Users\grant\AppData\Local\Programs\Microsoft VS Code\bin"

 : Error in ABC embedding: missing 'abcm2ps' tool.

 : Error in ABC embedding: missing 'abcm2ps' tool.

 : Problems found!
```

### To Reproduce on Windows 10/11

1. Open wxchordpro via double clicking on a chordpro file that will open in wxchordpro by default (e.g. my_song.cho)
2. Make sure the file has an embedded abc section
3. Preview the file

## System information

- OS: Windows 10 & Windows 11
- Where did you get ChordPro from? Native install kit
- ChordPro version: 5.986
- ImageMagick Version: 7.0.11
- wxPerl version: 0.9932

## Additional context
This error does not occur when chordpro is launched via the start menu, or directly via 'wxchordpro.exe', and then opening the file through the gui (File --> Open) before previewing.

**Comment by ChordPro** [comment]
Please try installer 5.986-0-**3** from the release page.

**Comment by Grant-ed** [comment]
That fixed it! Thanks so much!
