### ISSUE TITLE
Makefile.PL wants abcm2ps.exe on linux system

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#208]
## Describe the bug

running GNUmakefile on cli , runs Makefile.PL which complains of missing abcm2ps.exe while in a linux OS

### To Reproduce
1. unpack current dev source zipfile
2. execute GNUmakefile in src directory
3.  

## System information
 - OS:  Ubuntu 21.10
 - Where did you get ChordPro from? Github-dev

 - ChordPro version: 5.987.007'
 - Perl version: 5.32.1

## Additional context

 ./GNUmakefile 
perl Makefile.PL
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        pp/windows/abcm2ps.exe
Please inform the author.
Generating a Unix-style Makefile
Writing Makefile for App::Music::ChordPro
Writing MYMETA.yml and MYMETA.json
/bin/make -f Makefile clean
make[1]: Entering directory '/home/timm/ChordPro/chordpro-5.987.007'

**Comment by sciurius** [comment]
Thanks. It's harmless but should be gone now.
