### ISSUE TITLE
Fonts are not being found

### ISSUE THREAD

**Issue by jzbor** [ChordPro/chordpro#214]
## Describe the bug
I get the following error message when trying to use non-builtin fonts:
```
Config error: "/home/jzbor/Desktop/saitensprung/fonts/Lora-Italic.ttf" is not a built-in font
```
It is reproducible with configs known to work before.

### To Reproduce
1.  Set `fontdir`
2. Try to use font in `fontdir`

### Expected behavior
It should work.

### Attachments
The bug is reproducible with the files I send you for #190 . If you can't find that mail just let me know - I will send it again.

## System information
 - OS: Arch Linux
  - Where did you get ChordPro from? AUR - I tried master and dev branch
```
ChordPro: A lyrics and chords formatting program.

ChordPro will read a text file containing the lyrics of one or many
songs plus chord information. ChordPro will then generate a
photo-ready, professional looking, impress-your-friends sheet-music
suitable for printing on your nearest printer.

To learn more about ChordPro, look for the man page or do
"chordpro --help" for the list of options.

For more information, see https://www.chordpro.org .

Run-time information:
  ChordPro core          5.987_014 (Unsupported development snapshot)
  Perl                   v5.34.0 (/usr/bin/perl)
  CHORDPRO_LIB           /home/jzbor/.config/chordpro
  Resource path          /home/jzbor/.config/chordpro
                         /usr/share/perl5/vendor_perl/App/Music/ChordPro/res

Modules and libraries:
  Storable               3.23
  Text::Layout           0.021
  File::LoadLines        1.021
  PDF::API2              2.041
  Font::TTF              1.06
  Image::Magick          6.x?
```

**Comment by jzbor** [comment]
Update: I tried Text::Layout 0.028 just in case it made a difference, but it does not.

**Comment by sciurius** [comment]
Did you use a `"file"` property to designate the Lora-Italic.ttf font? It looks as if you used `"name"`.

Recent versions verify that the name supplied with `"name"` is one of the predefined fonts.

See https://www.chordpro.org/chordpro/chordpro-fonts/ .

**Comment by jzbor** [comment]
Ah ok thanks that works for me.
