### ISSUE TITLE
Adding enviroment directive labels to HTML output

### ISSUE THREAD

**Issue by lordcube777** [ChordPro/chordpro#215]
Is it possible to add enviroment directive labels to HTML output? Adding them between the sections opening div tag and first songline table would be great. Here's an example of what the HTML would look like for a song with one section. These labels could also be formatted like comments instead of giving them their own class. I believe that is how they are treated in PDF output.
```
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="chordpro.css">
<link rel="stylesheet" href="chordpro_print.css" media="print">
</head>
<body>
<div class="song">
<style>
@page {
  @top-center {
      content: counter(song) ". Alive";
  }
}
</style>
<div class="title">Alive</div>
<div class="verse">
<div class="label">Verse 1</div> <<-- THIS IS THE NEW LINE
<table class="songline">
  <tr class="chords">
    <td> </td><td>C# </td><td>E/G# </td><td>A </td><td>A </td><td>C# </td><td>B </td>
  </tr>
  <tr class="lyrics">
    <td>I was </td><td>lost with a </td><td>broken </td><td>heart You picked me up </td><td>now I’m </td><td>set a</td><td>part</td>
  </tr>
</table>
<table class="songline">
  <tr class="chords">
    <td> </td><td>A </td><td>E/G# </td><td>A </td><td>A </td><td>C# </td><td>B </td>
  </tr>
  <tr class="lyrics">
    <td>From the </td><td>ash I am </td><td>born </td><td>again forever </td><td>safe in the </td><td>Saviour’s </td><td>hands</td>
  </tr>
</table>
</div>
</div>
</body>
</html>
```

**Comment by JoeRu** [comment]
actually - this requirement isn't that hard to implement. I did it in a similar way for the new markdown export - and it's also required for the new LaTeX development. 
The HTML output is a bit simple. I was thinking of redesigning it - when done with Latex. One major Problem is the handling of the chords - there is the "table" way - which solves it pretty neat - and the markdown / Tab way - and use a fixed Font-Width (guitar-tab-format).

I'm not done rethinking it - would you like to have it customizable (like a template)? or would you just need the context informations?

**Comment by lordcube777** [comment]
Thank you! That worked perfectly.
