### ISSUE TITLE
Kit is incomplete. Notify Author

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#216]
xxxxxxxxxxx:~/ABC_bin/ChordPro/chordpro-5.987.027$ ..
perl Makefile.PL
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        lib/App/Music/ChordPro/Output/PDF/SVG.pm
        lib/App/Music/ChordPro/res/examples/bgdemo.pdf
        lib/App/Music/ChordPro/res/fonts/abc2svg.ttf
Please inform the author.

I just did a new Linux ubuntu install and got these remarks.

**Comment by sciurius** [comment]
Thanks, fixed in 5.987_028.
