### ISSUE TITLE
ABC notation not printing correctly

### ISSUE THREAD

**Issue by topchyan** [ChordPro/chordpro#217]
## Describe the bug

Rendering of notes is problematic

### To Reproduce
The test file test.cho

```
{title:Test}
{key:Dm}

{start_of_abc}
width:700
scale:0.5
L:1/8
M:3/4
Q:1/4=120
K:Dm
|:"Dm"d2 dd d2 | _ed"Bb"cB "F"c2| "Dm"A2 "Gm"GF "Dm"F2| FEFG D2     :|
|:D2 EF "Gm"G2 | "Gm"GFGA "Dm"F2| "Dm"FEFG "C"E2      |"Dm"EDEF D2  :|
{end_of_abc}

```

To reproduce run:

```
chordpro "/home/avetik/Desktop/test.cho"  --debug  --output="/home/avetik/Desktop/test.pdf" 
  xreader "/home/avetik/Desktop/test.pdf"

```
Console output:

```
ChordPro invoked: /home/avetik/Desktop/test.cho --debug --output=/home/avetik/Desktop/test.pdf
Reading: <builtin>
RSC1: /home/avetik/.config/chordpro/config/guitar.json
RSC3: config/guitar.json
Reading: /usr/local/share/perl/5.30.0/App/Music/ChordPro/res/config/guitar.json
Config[0]: <builtin>
Config[1]: /usr/local/share/perl/5.30.0/App/Music/ChordPro/res/config/guitar.json
Process: <builtin>
Process: /usr/local/share/perl/5.30.0/App/Music/ChordPro/res/config/guitar.json
Chords: Created parser for common
Processed 418 chord entries
Totals: 573 config chords
Parsers:
  common (active)
Processing song /home/avetik/Desktop/test.cho...
Parsers at start of /home/avetik/Desktop/test.cho: *common
Processed song...
Generating PDF /home/avetik/Desktop/test.pdf...
RSC1: /home/avetik/.config/chordpro/fonts/
RSC3: fonts/
Reading: <builtin>
RSC1: /home/avetik/.config/chordpro/config/guitar.json
RSC3: config/guitar.json
Reading: /usr/local/share/perl/5.30.0/App/Music/ChordPro/res/config/guitar.json
Config[0]: <builtin>
Config[1]: /usr/local/share/perl/5.30.0/App/Music/ChordPro/res/config/guitar.json
Process: <builtin>
Process: /usr/local/share/perl/5.30.0/App/Music/ChordPro/res/config/guitar.json
Chords: Created parser for common
Processed 418 chord entries
Totals: 573 config chords
+ /usr/bin/abcm2ps -g -q -m0cm -w515pt -O /tmp/UF8qY6sfby/tmp1.svg /tmp/UF8qY6sfby/tmp1.abc
This is ChordPro core 5.987 
+ /usr/bin/convert -density 600 -background white -trim /tmp/UF8qY6sfby/tmp1001.svg /tmp/UF8qY6sfby/tmp1.jpg
Generated PDF...
Gtk-Message: 21:21:06.583: Failed to load module "appmenu-gtk-module"

(xreader:383036): dbind-WARNING **: 21:21:06.623: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Gtk-Message: 21:21:07.036: Failed to load module "appmenu-gtk-module"

(WebKitWebProcess:383069): dbind-WARNING **: 21:21:07.098: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

```

Expected  output:
![harimon](https://user-images.githubusercontent.com/16518288/165872631-a88c51b2-b45e-4764-8c1f-b33368d9112a.png)

Actual output:
![test](https://user-images.githubusercontent.com/16518288/165872904-72bf7f70-07ef-43d4-87a4-2359c0e3b478.png)

PDF FIle:
[test.pdf](https://github.com/ChordPro/chordpro/files/8587583/test.pdf)

## System information
Linux Mint 20.3 Una
`Linux machine 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

ChordPro installation info:

```
yes | sudo apt install build-essential git cpanminus libpadwalker-perl libsafe-hole-perl libwx-perl
sudo cpanm chordpro

```

Run-time information:

```
  ChordPro core          5.987
  Perl                   v5.30.0 (/usr/bin/perl)
  CHORDPRO_LIB           /home/avetik/.config/chordpro
  Resource path          /home/avetik/.config/chordpro
                         /usr/local/share/perl/5.30.0/App/Music/ChordPro/res

Modules and libraries:
  Storable               3.15
  Text::Layout           0.029
  File::LoadLines        1.021
  PDF::API2              2.043
  Font::TTF              1.06

```

**Comment by sciurius** [comment]
Great and detailed bug report!

Can you try the following: Insert a line `X:1` after scale, and a blank line before `{end_of_abc}`.

[test.cho.txt](https://github.com/ChordPro/chordpro/files/8588514/test.cho.txt)

Then run

    abcm2ps -v test.cho

This should produce `Out001.svg`. Now run

    convert -version Out001.svg test.jpg

Include the console log from both commands here.

Does the resultant `test.jpg` look okay?

**Comment by topchyan** [comment]
Thanks! The SVG file seems to look okay

```
avetik@machine:~/Desktop$ abcm2ps -v test.cho.txt
abcm2ps-8.14.6 (2019-11-05)
File test.cho.txt
Output written on Out001.svg (8356 bytes)

```
![Out001](https://user-images.githubusercontent.com/16518288/165941491-6237c068-880f-4464-b310-61c557c93e1f.svg)

But conversion to JPEG fails miserably.

```
avetik@machine:~/Desktop$ convert -version Out001.svg test.jpg
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

```
![test](https://user-images.githubusercontent.com/16518288/165941494-00ea4089-9679-45b1-8e5a-f683fbeae9c2.jpg)

**Comment by sciurius** [comment]
> Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

As you can see, your version of ImageMagick does not have support for SVG built-in. I don't know why Linux Mint has decided to leave that out. Maybe there are additional packages (e.g. librsvg) required? 
It is probably best to ask this to the Linux Mint community.

**Comment by topchyan** [comment]
Good point. I have just tried to build imagemagick latest version from sources and got into all kinds of configuration issues. Will follow up if any success.

**Comment by sciurius** [comment]
I don't think so.
Actually I have no idea what is going on. ImageMagick (convert) should complain that it cannot handle SVG but apparently it sneaks around... Maybe it invokes some other (external) tool. 
What does
 
    convert -verbose Out001.svg x.jpg

output? And how did you view the SVG file initially?

**Comment by timmbo9** [comment]
This is an issue for Ubuntu also. I just did a fresh install of Ubuntu 22.04. After getting ImageMagick source I had to install distro package for librsvg-dev. Then I had to run from source directory  "./configure --with-rsvg=yes --with-perl=yes".  after make and install I had a functional version for use with chordpro.

**Comment by topchyan** [comment]
> I don't think so. Actually I have no idea what is going on. ImageMagick (convert) should complain that it cannot handle SVG but apparently it sneaks around... Maybe it invokes some other (external) tool. What does
> 
> ```
> convert -verbose Out001.svg x.jpg
> ```
Finally the convert test 
![x](https://user-images.githubusercontent.com/16518288/165991107-3f08c5b2-748e-4895-9904-91abe0877f0b.jpg)
worked after I followed suggestion by timbo9 above
```

convert -verbose Out001.svg x.jpg
'inkscape' '/tmp/magick-L9eSIb6YvIIyBTCX2XVEZVMCFRkA2czH' --export-filename='/tmp/magick-yeNJqEXHK3DG1DdLfceFEjQHEpnzWcJJ.png' --export-dpi='96' --export-background='rgb(100%,100%,100%)' --export-background-opacity='0.99999999999900002212' > '/tmp/magick-DsL--cLZVrINNcrB9sSdkBKdVrqRyFTH' 2>&1
Out001.svg SVG 816x1056 816x1056+0+0 16-bit sRGB 8356B 0.110u 0:00.123
Out001.svg=>x.jpg SVG 816x1056 816x1056+0+0 16-bit sRGB 25660B 0.020u 0:00.023
```
>  And how did you view the SVG file initially?

via Xviewer It didn't look pretty, but enough to understand that it reads the file properly.
 
![Screenshot_2022-04-29_13-09-40](https://user-images.githubusercontent.com/16518288/165991288-dc8f70ad-56a9-408c-a6aa-6313adee6164.png)

**Comment by topchyan** [comment]
So, the solution for me was to build ImageMagick from the source, similar to how described here https://imagemagick.org/script/install-source.php, only with options `./configure **--with-rsvg=yes --with-perl=yes**`. After that build the chordpro produces expected result
[test.pdf](https://github.com/ChordPro/chordpro/files/8592539/test.pdf)

**Comment by sciurius** [comment]
Great, but actually I'm lost...

ImageMagick originally didn't have built-in rsvg support, but somehow managed to produce something (noteheads, chordnames, ...) instead of bailing out.

Now you've built ImageMagich with rsvg support and it works... by calling inkscape to handle the conversion.

Anyway, I'm glad it is working now.

**Comment by topchyan** [comment]
I'm also not sure what does inkscape have to do with anything. But I'm good for now. I suppose this may be an issue that other users might encounter, so we could keep this as a recipe.

**Comment by sciurius** [comment]
Yes, I've added this discussion to the troubleshooting page.
Thanks!

**Comment by Pi4JC** [comment]
I'm not sure if I'm rigth here, as I am new to ChordsPro (V6.070 on macOS):
I am unable to save .chordpro files after editing on my mac (Catalina 10.15).
CHordPro writes a file with 0 bytes but the gives an error message.
Can anybody help me?

**Comment by sciurius** [comment]
It is usually better to open a new issue than adding an (unrelated) topic to an already closed issue...

Anyway, what you describe is a known problem that occurs only with Catalina 10.15. We haven't been able to find a solution or workaround. 

Catalina is very old and out of support for several years. Maybe it is worth considering to upgrade to a newer version of macOS?
