### ISSUE TITLE
Can't use hyphen in instrument.type

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#222]
`instrument.type` of `banjo_open-g` fails, but `banjo_open_g` works, which seems to imply that hyphens can't be used.

No problem with that, and just flagging as maybe worth mention in documentation https://www.chordpro.org/beta/chordpro-configuration-instrument/

I'm guessing this might apply to all selector values, so could be worth flagging elsewhere, in case someone's writing for, say, mezzo-soprano :)

**Comment by sciurius** [comment]
Thanks. Fixed in git.
