### ISSUE TITLE
{start_of_grid} leaves blank line above, even if no label specified

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#223]
Using the example below, PDF output includes a line space between the `{comment}` and the grid.
```
{c: Intro  ( melody:  [f]-[e]-[d]-[c]-[d]-[e]-[d]-[c]  [g]--[f]--[e]--[f]  x2 )}
{start_of_grid: 0+2x4+4}
| C . G . | Fadd2 F Am F | (x2)
{end_of_grid}
```
Output sample:
[I_Could_Never_Take_the_Place_of_Your_Man (ukulele C).pdf](https://github.com/ChordPro/chordpro/files/8834100/I_Could_Never_Take_the_Place_of_Your_Man.ukulele.C.pdf)

This seems to be because `{start_of_grid}` puts a 'label' line above the grid, even if there's no label. In that case, I'd expect no blank line above.

In the example above, it's useful to use a comment rather than a label (so the notes get recognised as such, for transposition etc.). Elsewhere in the same song I use labels on grids, which are placed directly above the grid, as I'd expect.

v5.988

**Comment by sciurius** [comment]
I cannot reproduce this. Can you include the config?

**Comment by gwyndaf** [comment]
[chordpro.json.txt](https://github.com/ChordPro/chordpro/files/8834625/chordpro.json.txt)

You guessed correctly, though. The same issue also arises if `labels.comment` is set to `comment_box` or `comment_italic`. 

git update fixed it nicely, thanks Johan.
