### ISSUE TITLE
Transcode not working - Can't locate object method "agnostic" 

### ISSUE THREAD

**Issue by leun4m** [ChordPro/chordpro#224]
## Describe the bug
I tried to use **Transcode to**  "Nashville".
However, when I try to generate the PDF I get the following error:

`Can't locate object method "agnostic" via package "App::Music::ChordPro::Chord::Nashville" at /Users/xxx/perl5/lib/perl5/App/Music/ChordPro/Chords.pm line 310.`

### To Reproduce

1. Write a basic chordpro file (`example.cho`)
  ```
{title: Example}
{key: C}

[C]This [G]is [Am]an [F]example.
  ```
2. Execute the following command:
  ```
$ chordpro example.cho --output=example.pdf --transcode=nashville
  ```

Result:
> Can't locate object method "agnostic" via package ...

### Expected behavior
I expected to get a PDF with nashville notation (however the error seems to be fatal, so no PDF will be created):
```
Example

1    5  6  4
This is an example
``` 

## System information
 - OS: macOS Monterey (12.3.1) (M1)
 - tried both CPAN and the DMG-installer from the releases page here on GitHub
 - Versions (`chordpro --about`):
 ```
Run-time information:
  ChordPro core          5.988
  Perl                   v5.30.3 (/usr/bin/perl)
  CHORDPRO_LIB           /Users/xxx/.config/chordpro
  Resource path          /Users/xxx/.config/chordpro
                         /Users/xxx/perl5/lib/perl5/App/Music/ChordPro/res

Modules and libraries:
  Storable               3.15
  Text::Layout           0.029
  File::LoadLines        1.021
  PDF::API2              2.043
  Font::TTF              1.06
```

**Comment by sciurius** [comment]
Thanks for finding this!
Fixed in git.
