### ISSUE TITLE
Pango font size issues

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#225]
Just flagging some possible issues with Pango size descriptors: some seem to work and some don't.

Sample source:
[Pango_size.cho.txt](https://github.com/ChordPro/chordpro/files/8872209/Pango_size.cho.txt)

Sample output (using -X option for no config):
[Pango_size.cho.pdf](https://github.com/ChordPro/chordpro/files/8872213/Pango_size.cho.pdf)

Verbal absolute descriptors `x-small` and `small` (and `medium`?) seem to work, but others don't.

Relative descriptors (verbal and percentage), and `small`/`big` shortcuts seem to work.

Points (with unit) seem to work, but not thousandths.

`--about` details:
```
Run-time information:
  ChordPro core          5.988_005 (Unsupported development snapshot)
  Perl                   v5.32.1 (/usr/bin/perl)
  CHORDPRO_LIB           /home/alun/.config/chordpro
  Resource path          /home/alun/.config/chordpro
                         /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/lib/App/Music/ChordPro/res

Modules and libraries:
  Storable               3.21
  Text::Layout           0.029
  File::LoadLines        1.021
  PDF::API2              2.043
  Font::TTF              1.06
  Image::Magick          6.9.11
```

**Comment by sciurius** [comment]
Nice testing work!
ChordPro uses perl module Text::Layout for Pango emulation. This module currently implements a subset of Pango markup. It also provides a convenience mode that makes some behaviour more intuitive. See below.

`xx-small`, `medium`, `large`, `x-large` and `xx-large`: these are supported but were not enabled. This has been fixed.

`<span size="6144">`: this is for Pango compliance only. ChordPro uses convenience mode, and a 6pt size is just `size="6"`. Same for size 24567. To maintain mental sanity, it is best to express that you mean points, so use `6pt`.

The reason why excessive font sizes throw the  `Unclosed markup` errors that you see is the way ChordPro currently handles wrapping. ChordPro processes the font size and then decides that the content will not fit on the line. It breaks the line without taking the markup into account. So the first of the lineparts sees the `<span font` and not the `</span>` and complains. The last linepart sees a lone `</span>` and complains. This can and must be improved but currently it works in practically all realistic situations so I would rather leave it for the time being. It is not fun code ☺.

The fixes are in Text::Layout in git and will be part of the next release.

**Comment by gwyndaf** [comment]
You're welcome. Most of my testing is trying to do odd/interesting things, then getting curious when they don't seem to work!

I can see how convenience mode would make 6144 a pretty huge type size(!), and that remember that Pango doesn't play nicely with line breaks, so that explanation makes perfect sense.
