### ISSUE TITLE
Hyperlinks inactive in added front/back matter PDFs

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#227]
I add two PDFs, as front and back matter, to a collection of songs. Both PDFs include hyperlinks (https:// and mailto:) that link to external resources.

Hyperlinks in the standalone PDFs work fine (i.e. are active), but are inactive on the corresponding pages in final songbook output from ChordPro.

On the other hand, hyperlinks within the songbook (generated using Pango `href`) are ok, i.e. active.

It's a bit odd, since I'd expect merged PDFs would exhibit the same behaviour (all links active, or not). Maybe ChordPro's initial PDF output is treated as a 'master', to which others are appended or prepended, so links get lost in that process, only from the added PDFs, but don't affect the core songs?

Using git version 5.988_014
  Text::Layout           0.029
  PDF::API2              2.043

**Comment by sciurius** [comment]
This is a limitation of the PDF library. I'm not sure if this restriction is permanent, so I have filed an issue there.

https://github.com/ssimms/pdfapi2/issues/51
