### ISSUE TITLE
__table_of_contents__ is calculated incorrectly in csv

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#228]
## Describe the bug
The page numbers for the toc are wrong in the CSV. They seem to be matching the page numbers of the front matter.

### To Reproduce
Download and extract this, run `make`, inspect test.csv (see readme.md for details).
[toc_pages_bug.tar.gz](https://github.com/ChordPro/chordpro/files/9032125/toc_pages_bug.tar.gz)

### Expected behavior
The page numbers for the toc should be calculated correctly.

## System information
 - OS: Ubuntu 22.04 LTS
 - Where did you get ChordPro from? GitHub

Run-time information:
  ChordPro core          5.988_016 (Unsupported development snapshot)
  Perl                   v5.34.0 (/usr/bin/perl)
  CHORDPRO_LIB           /home/nomike/.config/chordpro
  Resource path          /home/nomike/.config/chordpro
                         /usr/local/share/perl/5.34.0/App/Music/ChordPro/res

Modules and libraries:
  Storable               3.23
  Text::Layout           0.029
  File::LoadLines        1.021
  PDF::API2              2.043
  Font::TTF              1.06
  Image::Magick          6.9.11

**Comment by nomike** [comment]
I was just able to figure out that this bug was introduced between versions 5.985 and 5.986.
I'm looking for a more exact commit now.

I think this might warrant a unit-test but I'm not well versed enough in perl for this.

**Comment by nomike** [comment]
The error was introduced in commit ab2517567fbdb8a8bf7f9b6e550318a65db68262 (CSV) Rework CSV generation.

**Comment by nomike** [comment]
As my pull request was just merged, I'm closing this issue.

**Comment by sciurius** [comment]
I've added a series of tests to keep an eye on this. They immedeately revealed yet another cut/paste error ☺.

**Comment by nomike** [comment]
Great. Thank you!
