### ISSUE TITLE
Perl error when setting `notenames:true`

### ISSUE THREAD

**Issue by chriswep** [ChordPro/chordpro#231]
I use version 5.988

When i set `notenames:true` (either config file or command line), i get the following error:

```
Use of uninitialized value $name in hash element at /Volumes/Users/chris/perl5/lib/perl5/App/Music/ChordPro/Chords.pm line 311.
```

**Comment by sciurius** [comment]
Thanks, this has already been fixed in commit da98e737635e04ed0b5e8f285c28078359d5b1bc.
