### ISSUE TITLE
Support lowercase minor chords

### ISSUE THREAD

**Issue by chriswep** [ChordPro/chordpro#232]
In germany we use lowercase letters to write a minor chord, i.e. "e" instead of "Em". I know we can use the `notenames` setting, however as far as i see it doesn't support the usage of those chords with extensions ("e7") or in composed chords ("e/H").

**Comment by sciurius** [comment]
There are very few chord notation systems that use lowercase to denote minor, mostly due to chords becoming ambiguous when (hand-)written (compare e.g. a hand-written "C" with "c"). Also, ChordPro has many german users, but noone has ever complained about this so it doesn't seem an "in germans we use" case.

Anyway, this works:
````
{define e/H frets 0 2 2 0 3 0}

[A]Hello, [e/H]World
````
as long as you do not transpose.

**Comment by chriswep** [comment]
@sciurius i can't say how representative my experience is but most of the (christian) songbooks i know use this notation. i did a quick google search and it at least confirms that it is not super uncommon in Germany.

Anyway, i came up with this `notes` config:
```
    "notes": {
        "sharp": [
            ["C", "c"],
            ["Cis", "cis", "C#", "C♯"],
            ["D", "d"],
            ["Dis", "dis", "D#", "D♯"],
            ["E", "e"],
            ["F", "f"],
            ["Fis", "fis", "F#", "F♯"],
            ["G", "g"],
            ["Gis", "gis", "G#", "G♯"],
            ["A", "a"],
            ["Ais", "ais", "A#", "A♯"],
            ["H", "h"]
        ],
        "flat": [
            ["C", "c"],
            ["Des", "des", "Db", "D♭"],
            ["D", "d"],
            ["Es", "es", "Eb", "Ees", "E♭"],
            ["E", "e"],
            ["F", "f"],
            ["Ges", "ges", "Gb", "G♭"],
            ["G", "g"],
            ["As", "as", "Ab", "Aes", "A♭"],
            ["A", "a"],
            ["B", "b"],
            ["H", "h"]
        ]
    },
```

This somehow seems to work. I don't really understand the implications of this config. Is this the right way to use it?

I assume when transposing +2, `c` would be transposed to `D`?

Also, is this the intended way to make the "H" notation work?I have at least one case when +2 transposes an `A` to `B` with this config, while it correctly transposes to `H` for another file in the same run.

**Comment by sciurius** [comment]
Using `["C","c"]` in the notes config will make `c` work, but it will be treated as a normal (major) chord. If you are printing diagrams you would get a [032010], not [335543].
After transposing, the first of the alternatives is used, so `c` +2 → `D`. 

To obtain `A` +2 → `H` you most supply `--transcode=german`.

I'd suggest you take the original question "Support lowercase minor chords" to the user group for discussion.

**Comment by chriswep** [comment]
thanks for the feedback. before i close this: is overwriting the `notes` config like this the supposed way to make chordpro work with the german `H=B` and `B=Bb` situation? I wondered because i didn't find it documented anywhere.

**Comment by sciurius** [comment]
It is usually best not to clobber config data when presets are available that do the job.
What you are looking for is german style notes. To have ChordPro understand german notation, use the provided config: `--config=notes:german`.
To get german notation in the output, add `--transcode=german`.

From a config, just add 'notes:german' to the includes, and adjust settings.transcode. E.g.
````
{
    "include" : [ "notes:german" ],
    "settings" : {
	"transcode" : "german",
    }
}
````


See e.g.
https://www.chordpro.org/beta/using-chordpro/#transcode
https://www.chordpro.org/beta/chordpro-configuration-instrument/#root
https://www.chordpro.org/beta/chordpro-resource-directory/#notes

**Comment by chriswep** [comment]
ok, so `include: [notes:german]` basically does what i did in the config above, i.e. it replaces the name of the root nodes that chordpro is working with internally, i.e. when i use `B` in a source file, chordpro will interpret it as the flat version of the german `H`, i.e. the Dutch `Bb`.
In contrast, `transcode:german` has the effect on what chords will be printed out, independently from what we use as internal root notes configuration.
So `notes` describes what we want to use in the source file, `transcode` what we want to see in the output. Did i get that right?

**Comment by sciurius** [comment]
Yes. `notes:german` also sets the notes' `system` property which is used internally.
