### ISSUE TITLE
[Documentation] Link not working

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#235]
On page https://www.chordpro.org/chordpro/chordpro-configuration-pdf/#keyboard-diagrams it reads:

---8<---
See [Chords diagrams in a side column](https://www.chordpro.org/chordpro/chordpro-configuration-pdf/#chords-diagrams-in-a-side-column) below.
--->8---

But that section does not exist and thus the link doesn't work.

**Comment by sciurius** [comment]
Thanks. Fixed.
