### ISSUE TITLE
{define "\\" copy "NC"} produces an error for keyboards.

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#239]
Error message

```plaintext
"songs/All Right Now - Free.chopro", line 3, Invalid chord: \: 0 strings
        {define "\\" copy "NC"}
"songs/All Right Now - Free.chopro", line 4, Unknown chord: "\"
        [A] [D] [\] [A] [Dsus2] [A] oh oh
"songs/All Right Now - Free.chopro": No chord diagram defined for "\" (skipped)
```

it works for guitar and ukulele though.

**Comment by sciurius** [comment]
Should be fixed in 5.988_024.

**Comment by gwyndaf** [comment]
Possibly a related issue or side-effect, with `{define ... copy ... }` for keyboards (no other instruments), using v5.990. If not, I'll repost as a separate issue.

This snippet seems to produce errors, but only with keyboard config:
```
{title: The Tears of a Clown}
{define: E/Ab copy E}
[Bb]  ·  [F] Now there's some [G]sad things known to [E/Ab]man,  · •
```
Output chord is still `E/Ab` (not `E` as expected). Messages are the following, six times:
```
Use of uninitialized value in numeric lt (<) at /usr/local/share/perl/5.36.0/App/Music/ChordPro/Chords.pm line 575.
Use of uninitialized value in subtraction (-) at /usr/local/share/perl/5.36.0/App/Music/ChordPro/Chords.pm line 576.
```
Messages don't arise with only the `{define}` line by itself, and only seem to arise when the chord is in the song body, so actually being processed. Seems unrelated to the slash chord `/` and also arises with other chord names.

**Comment by sciurius** [comment]
> Output chord is still E/Ab (not E as expected).

That was changed in 5.989. To obtain the older behaviour, use

    {define: E/Ab copy E display "E"}

I have eliminated the uninitialized value warnings in git.

**Comment by gwyndaf** [comment]
Warnings now gone (git v5.990_001)

After a little thought, I realise the behaviour makes sense, as there's no separate keyboard config file in which `display` values are defined! Other instruments seem to pull the `display` value from the relevant config, so all is good :)

**Comment by gwyndaf** [comment]
Another, possibly related oddity: if it's not, I'll repost as a separate issue...

The line `{define: "\\"}` seems - in some circumstances - to stop processing and trigger error messages:
```
Use of uninitialized value in string eq at /usr/local/share/perl/5.36.0/App/Music/ChordPro/Config.pm line 99.
Use of uninitialized value in bless at /usr/local/share/perl/5.36.0/App/Music/ChordPro/Chords.pm line 484.
Explicit blessing to '' (assuming package main) at /usr/local/share/perl/5.36.0/App/Music/ChordPro/Chords.pm line 484.
```
The circumstances in which this arises seems to depend on the instrument config I'm using (all using `chordpro -X` and release v5.990):

* Arises with `--config=keyboard` (my own keyboard config simply sets `instrument.type` = `keyboard`)
* Doesn't arise with built-in `ukulele` or `ukulele-ly` configs, or my custom `ukulele_c` config
* Arises with `--config=guitar` (built-in), but not my custom `guitar_std`.

I can't identify any clear pattern from those configs. I initially thought it might be whether or not they include `display` values, but there's no correlation.

Even though it arises with release v5.990, I'm pretty sure it's only started appearing recently (I regularly re-process the same collection of songs), so might be related to environmental changes, maybe some Perl updates.

The only reason I have such a line is to prevent error messages when using `\` (my convention for down-strum) in a chord grid, so can easily avoid that if necessary. Right now, it's causing things to stop completely.

**Comment by gwyndaf** [comment]
Ah, thanks, that seems to deal with it, but I'll continue with more robust testing.

The only reason I'd got my own `keyboard.json` was because it seemed to disappear from the release version a while back. It's there in my git version, but I even reinstalled the release version (using `cpanm`) and still don't seem to have it. That's quite odd, because (if I'm navigating github correctly), it seems to be there in the `res/config` folder for the `master` branch.

**Comment by sciurius** [comment]
Ah, that's a bug -- the keyboard config is in git, but not in the release MANIFEST. I've fixed it.
