### ISSUE TITLE
face=dingbats doesn't display unless weight=bold also specified

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#240]
I've been trying unsuccessfully to use the built-in ZapfDingbats font, by specifying the (default) `dingbats` font description, e.g. `<span face=dingbats>a</span>`

I finally discovered that it works successfully if I specify the bold face, i.e. `<span face=dingbats weight=bold>a</span>`

However, `--print-final-config` tells me that no bold variant is defined:
```
         "dingbats" : {
            "" : "ZapfDingbats"
         },
 ```
So, I have a solution, but don't know why it works, so thought it might be worth flagging as a possible issue.

[Dingbats_test.cho.txt](https://github.com/ChordPro/chordpro/files/9439810/Dingbats_test.cho.txt)
[Dingbats_test.cho.pdf](https://github.com/ChordPro/chordpro/files/9439812/Dingbats_test.cho.pdf)

I'm using Debian Bookworm, so my installed ZapfDingbats font is D050000L, and I realise this might be a system/font issue rather than a ChordPro one.

It's a slightly niche case, as I normally use a set of custom fonts, with Unicode characters for special symbols, but I'm also creating a more portable config that gives a similar design without extra fonts, so I can simply share a single `chordpro.json` file.

**Comment by sciurius** [comment]
The D050000L font should not be involved. Can you remove it, and retry?

**Comment by gwyndaf** [comment]
Yes, I'd suspected it might be complex, given system font handling.

I can't actually remove D050000L because of dependencies, but disabled it, so `fc-match ZapfDingbats` returns `Vera.ttf: "Bitstream Vera Sans" "Roman"` and the resulting PDF does then use Bitstream Vera Sans Bold where it was previously using D050000L (i.e. `face=dingbats weight=bold`)
[Dingbats_test.cho.pdf](https://github.com/ChordPro/chordpro/files/9440090/Dingbats_test.cho.pdf)

Interestingly, it doesn't use the regular weight Bitstream Vera Sans Roman for the first three characters, which specify only `face=dingbats` (i.e. not bold), and those are still missing.

That seems to suggest system font substitutions being used if the face/weight isn't defined and known to ChordPro, i.e. `dingbats bold`. If it is already defined, like `dingbats`, there seems to be no system substitution, but no built-in font either.

**Comment by sciurius** [comment]
ChordPro shouldn't call `fc-match` at all. ZapfDingbats is a built-in font. I'm trying to find out what happens.

**Comment by gwyndaf** [comment]
Yes, it was only because the PDF info reported the font D050000L being used, and I know that's a system alternative/equivalent for ZapfDingbats. 

`fc-match` was simply my tool to investigate further how/why system fonts were being used, when none of my configs use system fonts, only built-in ones, or those in my `chordpro/fonts` folder.

**Comment by sciurius** [comment]
Results until now:
`<span face=dingbats>` uses the built-in font ZapfDingbats.
`<span face=dingbats weight=bold>` uses font fallback, and will (most likely) use the D050000L TrueType (or OpenType) font.
The latter shows the glyphs. The former generates `null` glyphs (that result in a small space).
To be continued.

**Comment by sciurius** [comment]
See https://github.com/ssimms/pdfapi2/issues/55 .
ChordPro always provides strings as utf8, so using one of the symbol corefonts (Symbol and ZapfDingbats) results in invisible nulls.

I'm currently not sure at what level the error occurs (PDF::API2, Text::Layout or ChordPro), and whether there is a solution/workaround.

**Comment by gwyndaf** [comment]
Thanks Johan. That's enough for me to find a workaround...

Your utf8 comment made me realise I was thinking in 'old' ZapfDingbats font behaviours (i.e. type an ASCII character to display a dingbat). But I've now experimented with also specifying glyphs using Unicode numbers/characters...
[Dingbats_test2.cho.txt](https://github.com/ChordPro/chordpro/files/9456930/Dingbats_test2.cho.txt)
[Dingbats_test2.cho.pdf](https://github.com/ChordPro/chordpro/files/9456936/Dingbats_test2.cho.pdf)

Conclusion
* When specifying a built-in font _name_ directly, old approach still applies,  i.e. type an `a` and a `❁` displays.
* When specifying a font _description_ (defined in `fontconfig`), Unicode encoding applies, i.e. specify the character required, exactly as with any utf8 font.

BUT
Examining the make-up of the PDF, it actually uses a mixture of ZapfDingbats (not embedded) and D05000L (embedded) fonts:
* face=dingbats and Unicode typed character properly use ZapfDingbats
* face=ZapfDingbats and ASCII character use D05000L (which makes me suspect it's asking the system for the font name, for which D05000L is the available alternative)

So, the approach that gives expected output is 1) using a `fontconfig` name (`dingbats`), _and_ 2) using a Unicode character (not the ASCII character equivalent).

This seems sensible, but was counter-intuitive to me because of prior font experience! I expected to use Postscript fonts the old way, but current behaviour makes sense, and the Dingbats Unicode block gives the corresponding values. A bit more complicated for Symbol, as the available glyphs seem more scattered across Unicode blocks.

I'm having mixed results with specifying Unicode numbers (e.g. `\u2191`), but think that might be down to which ChordPro context they're applicable/functional in. Even though they don't play well in this example, I'm also using them in a config file and can use `\u2191` to get an up arrow ↑ from `symbolps` (`fontconfig` description pointing to Symbol font).

I think this clarifies for me how to use ZapfDingbats and Symbol properly, but there might still be loose ends around why font names used explicitly seem to call system fonts. And it's possibly confusing if the two approaches (description or name) seem to use different encoding approaches.

**Comment by sciurius** [comment]
> face=ZapfDingbats and ASCII character use D05000L (which makes me suspect it's asking the system for the font name, for which D05000L is the available alternative)

That is correct (although not intuitive). `face=` requires a font _family_ (i.e. a _registered_ family name), not a font _name_. So `face=ZapfDingbats` still invokes the font fallback and uses D05000L.

To get back to the main problem: simplified, at a very low level a Perl string can be in native format (single byte, where all characters fall within the ISO-8859-1 (latin1) range) or in UTF8 format (where all characters are one, two or more bytes). Perl tries to keep strings in native format if it can, and uses UTF8 only when needed.
An ASCII (or latin1) string can be represented in either format. Normally, that doesn't matter. For normal fonts the character code for e.g. `A` is 65 (ASCII) or U+0041 (Unicode) which is also 65.
For the built-in Symbol and ZapfDingbats fonts this is different. In short, ZapfDingbats does not have an `A`. U+0041 is a symbol called `a10`. Now when the PDF is produced it matters whether the string is native or UTF8. If it is native, `A` will just take the 65th glyph which gives you an asterisk-like symbol. If, however, the string is UTF8, `A` will be looked up in the encoding table and since it is not there, you get a null. This should yield a `.notdef` glyph, but apparently ZapfDingbats doesn't have one.

When ChordPro processes a string, it is always in UTF8 (I don't know yet why). So you don't get anything printed.
Oddly, when the string comes from the config, e.g. pdf.formats.title, it is only UTF8 when needed.

You can see this demonstrated in the attached zip.
[simple.zip](https://github.com/ChordPro/chordpro/files/9460216/simple.zip)

What you can try is this: locate the file `Text/Layout/PDFAPI2.pm` and add the downgrade line somewhere around line 187:

````
		$text->translate( $x, $y );
		utf8::downgrade( $t, 1 ) if $font->issymbol;
		$text->text($t);
````

As far as I can see this should give intuitive and reproducible results. But I'm not 100% sure if it may have any nasty sideeffects.

**Comment by gwyndaf** [comment]
Thanks. From initial testing, that fix seems to make ASCII dingbat strings work as expected, without changing behaviours for other forms, like UTF8, mixed, or Unicode value strings like `\u2721` (in configs at least).

I find Unicode values like `\u2721` don't seem to work in the document body anyway, only in configs. That doesn't seem a problem as I like to keep song sources human-readable, so any conversion to special characters gets done in configs (e.g. changing / to ↑ with parser preprocessor).

Main thing my testing threw up is more a usage note, to fully specify `<span face=dingbats weight=normal style=normal>` with built-in dingbat/symbol fonts, as they have no bold or italic variants. This helps prevent glyph errors or using fallback fonts if additional bold or italic styling is applied elsewhere. Theoretically, `dingbats` could be redefined with additional variants, but that currently throws up an error: [new issue](https://github.com/ChordPro/chordpro/issues/241)

I'm very happy using UTF8 characters now I understand how they work. My idea of intuitive behaviour for Postscript dingbat/symbol fonts comes from 30 years ago and 255 glyphs per font, so I suspect using ASCII characters might be a niche case. With modern text editors, what's intuitive might be that what appears in the editor as `✡` actually shows up in the PDF as `✡`! However, it's great that the fix seems to make both approaches work equally well :)

**Comment by PhilterPaper** [comment]
Something that may have a bearing on this discussion: core fonts (actually, any fonts but TTF) are supposed to be restricted to single byte encodings (per PDF specs), thus ruling out the use of UTF-8 encoding. If you directly access the TTF file behind the core font, you may be able to use UTF-8. I've had complaints before in PDF::Builder about core fonts failing to properly show UTF-8, and unfortunately, I just don't think it's currently possible. I'm looking (PhilterPaper/Perl-PDF-Builder#81) at the possibility of synthesizing single byte core _subfonts_ from UTF-8 input, but no promises yet.

**Comment by sciurius** [comment]
I'm not sure I fully understand. The following program (full source in zip) runs ok and produces the right glyphs for the UTF-8 characters.
````
my $page = $pdf->page;
my $text = $page->text;
my $font = $pdf->font('Times-Roman');
$text->font( $font, 20 );
$text->translate( 100, 600 );
$text->text("“Hi there!”");
````
[utf.zip](https://github.com/ChordPro/chordpro/files/12015521/utf.zip)

**Comment by PhilterPaper** [comment]
It's using core fonts, with Win ANSI Encoding. Try a character that's not found in the extended Windows punctuation, such as **\x{010E}vorak**. The D+caron is in the text, but doesn't show in the reader.

**Comment by sciurius** [comment]
I see. I usually advise to not use corefonts when you want anything but Latin1.
See e.g. https://www.chordpro.org/chordpro/faq-unicode-characters/

**Comment by PhilterPaper** [comment]
I think most any _single byte_ encoding is OK to use with core fonts, not just **Latin1**. The problem is with multibyte encodings such as **UTF-8**. Core fonts map a byte value 0..255 to a glyph name (and width) which is then used by the Reader to render the desired glyph. It gets confused with multibyte characters.
