### ISSUE TITLE
(False?) error when redefining fontconfig descriptions with additional variants

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#241]
If an existing config file defines a font description in `pdf.fontconfig`, adding extra variants in another config file throws up errors.

Processing the attached with `chordpro -X --config fonts.json --config fonts_redef.json Fontconfig_test.cho`
[Fontconfig_issue.zip](https://github.com/ChordPro/chordpro/files/9462838/Fontconfig_issue.zip)

Gives errors:
```
Config error: unknown item pdf.fontconfig.thisfont.bold
Config error: unknown item pdf.fontconfig.thisfont.bolditalic
Config error: unknown item pdf.fontconfig.thisfont.italic
Config error: unknown item pdf.fontconfig.thisfont.bold
Config error: unknown item pdf.fontconfig.thisfont.bolditalic
Config error: unknown item pdf.fontconfig.thisfont.italic
```
They might be phantom error messages, as the sample PDF shows the (redefined) italic variant looking as expected in practice.

No errors arise when all variants (bold, italic, bolditalic) have already been defined in the original config.

One instance where this could be an issue is attempting to define italic, bold, bolditalic variants for the built-in `dingbats` fontconfig description (which has no variants), to avoid using fallback/substitute fonts, but practical testing suggests the redefinitions seem to be followed, despite the error message suggesting there's a problem.

**Comment by sciurius** [comment]
It is not really an error, as you noticed. It is merely a warning saying "Hey! I see a key in the (new) config that wasn't there before. Are you sure you didn't make a typo?"
In some situations these warnings are already suppressed, I'll look into this particular case.
I any case, it's harmless.
