### ISSUE TITLE
Enhancement: Suppress diagrams for user defined list of chords

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#242]
I saw the comment of not implementing the "hard" and "easy" chords like in chordii.
Unfortunately the layout of 500+ pages of my songs depend on this (e.g. many songs not printing any diagrams or just one row). I understand that I could somehow user define the chords to be displayed in the song. But that again would mean to edit 500 files and scan for the ones I really want.
As the definition of "hard" and "easy" is rather user dependant and I get that you don't want to hardcode it, wouldn't it be possible to add a config option into the json to suppress a list of chords that will simply apply to all songs? Something like:
"suppress-chord-diagrams" : ["A", "B", "C", "D", "E", "F", "G", "Am", "Bm", "Dm", "Em", "Fm", "F#"]

That would also greatly enhance readibilty, when the songs use a lot of chords, but you only need to lookup a few.

**Comment by sciurius** [comment]
Interesting suggestion. Can you take this to the user forum for discussion?
https://groups.io/g/ChordPro

**Comment by bublath** [comment]
I did post in groups.io
As I recently did a bit of perl programming myself, I gave it a try and created a PR. Please feedback :)

**Comment by bublath** [comment]
Tested on dev and looks ok
