### ISSUE TITLE
Error message when there are tab characters in the song

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#247]
When I place a tab anywhere in a song, I get the following error (even a couple of time for one tab):
Use of uninitialized value in pack at /usr/local/share/perl/5.32.1/PDF/API2/Resource/CIDFont.pm line 162.

This seems to be OS specific, probably connected to what fonts are available.
I don't see it on my Raspberry with "bullseye" but on WSL with Debian "Bullseye"
In case of the error I get a "square" at that place - in the other case just a space.

Should the tab character be filtered out or set to space to avoid this potential problem?

**Comment by sciurius** [comment]
I cannot reproduce this.
Please provide a minimal example that shows the error.

**Comment by bublath** [comment]
Seems to be font specific.
I'm using "sans 12" (LiberationsSans-Regular.ttf) as text font.
If I set it e.g. to "times 12" the error disappears.
With that font I can reproduce it by putting a tab anywhere in the songtext.

**Comment by sciurius** [comment]
Ok, got it.
Tabs do not play a role in ChordPro so I'll treat them as single spaces.
Thanks for finding this.

**Comment by sciurius** [comment]
Fixed in 5.988_030.

**Comment by bublath** [comment]
Tried it on dev and looks good.
