### ISSUE TITLE
Error when adding a "nonsense" chord

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#248]
I just copy & pasted a new song that had [Outro] in the text, which resulted in the error:
Can't use an undefined value as a HASH reference at /usr/local/share/perl/5.32.1/App/Music/ChordPro/Song.pm line 1696.
(line numbers refer to current master without any of my modifications)
which also stopped processing (no output file).

This seems to happen with any string in brackets that does not match the regexp for a well defined chord (unknown chords are ok, as long as they look like a chord) and only when diagrams->auto=true

**Comment by sciurius** [comment]
I cannot reproduce this in dev 5.988_032. Did I accidentally fix something?

`foo.cho`:
````
{title: Foo}
[A]Hello, [Bm]'World!
[Outro]Foo
````
and command
    `chordpro -X foo.cho --def diagrams.auto=1`

**Comment by sciurius** [comment]
BTW, `diagrams.auto` is currently broken and I feel very much like removing it. I don't think anyone uses it.

**Comment by bublath** [comment]
Tried it on dev branch and could not reproduce it either, anymore.
I wasn't really using diagrams.auto on purpose and tend to agree that it could be removed.
