### ISSUE TITLE
Missing entries in toc if primary sort criteria undefined for song

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#250]
When adjusting my toc to sort by title and artist (well by subtitle in my case) I noticed that a few entries were missing in the "by artist" toc.
This happened for a few songs, were I did not define the field (traditional songs where I did not know the artist), but it took me a while to realized the reason.

I would have expected them to still be listed instead of silently omitting them.
After spending quite some time to understand the sorting algorithm im common.pm, my solution would be to change this around line 160:
	    push( @split, [ $coreitem, [""] ] ), next unless $meta->{$coreitem};

to still create an empty entry, so "empty" entries would simply be listed at the beginning.

**Comment by sciurius** [comment]
Nice.
If you create a PR using the attached patch, you'll get the credits.

[toc.patch.txt](https://github.com/ChordPro/chordpro/files/9594136/toc.patch.txt)

**Comment by sciurius** [comment]
The patch I gave you included a test case. I don't see that in the PR :(

**Comment by bublath** [comment]
Sorry, overlooked that. I must admit I have not looked into the tests and how they work, yet.
I just added your patch as is to the PR

**Comment by sciurius** [comment]
Merged, thanks.
