### ISSUE TITLE
No "warned chord" in "dev" branch without debug->chords

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#253]
I just noticed that in dev branch, there is no warning anymore for unknown chords as the $warned_chords only gets filled in debug mode. (See line 639 in Song.pm):
	    $warned_chords{$n}++;
only gets executed in debug mode now, though in debug mode you get so many messages that the message "[Song]: No chord diagram defined for [list of chords]" is not really visible anymore.

Was that on purpose? 
I found it useful to find undefined chords. To silence chordpro I'd rather add them as empty user defined chord or have a switch to enable/disable that check.

**Comment by sciurius** [comment]
I recall that I changed this for some reason, but I can't remember why.
Fixed in 5.988_034.
