### ISSUE TITLE
How to define "no chord" in combination with transpose

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#254]
After your latest patches, I'm getting a warning whenever I have [N.C.] in combination with transpose.
"XXXchopro", line 9, Cannot parse/transpose chord "N.C." 
I tried to define it with all "-1" or add it to the supressed chords but that did not help.
This is not seen when not transposing the song and I can't remember seeing that before the latest patches.

Apart from the warning, I see no negative impact. The "N.C." is printed and no grid is created. It's still confusing when you want to get your warnings clean.

Is there a recommended way to define "neutral" chords or is this a bug?

**Comment by sciurius** [comment]
Should be fixed in 5.988_038.

**Comment by bublath** [comment]
Confirmed
