### ISSUE TITLE
t/8*_pages.t fail on some systems

### ISSUE THREAD

**Issue by eserte** [ChordPro/chordpro#256]
On some of my smoker systems the test suite fails:
```
splice() offset past end of array at /home/cpansand/.cpan/build/2022102205/PDF-Builder-3.024-2/blib/lib/PDF/Builder.pm line 1981.
splice() offset past end of array at /home/cpansand/.cpan/build/2022102205/PDF-Builder-3.024-2/blib/lib/PDF/Builder.pm line 1981.
Can't find label 2 at /home/cpansand/.cpan/build/2022102205/PDF-Builder-3.024-2/blib/lib/PDF/Builder/Annotation.pm line 103.
# Looks like your test exited with 255 just after 3.
t/80_pages.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/5 subtests 
Can't find label 2 at /home/cpansand/.cpan/build/2022102205/PDF-Builder-3.024-2/blib/lib/PDF/Builder/Annotation.pm line 103.
# Looks like your test exited with 255 just after 3.
t/81_pages.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/5 subtests 
Can't find label 2 at /home/cpansand/.cpan/build/2022102205/PDF-Builder-3.024-2/blib/lib/PDF/Builder/Annotation.pm line 103.
... etc ...
splice() offset past end of array at /home/cpansand/.cpan/build/2022102205/PDF-Builder-3.024-2/blib/lib/PDF/Builder.pm line 1981.
splice() offset past end of array at /home/cpansand/.cpan/build/2022102205/PDF-Builder-3.024-2/blib/lib/PDF/Builder.pm line 1981.
Can't find label 2 at /home/cpansand/.cpan/build/2022102205/PDF-Builder-3.024-2/blib/lib/PDF/Builder/Annotation.pm line 103.
# Looks like your test exited with 255 just after 3.
t/86_pages.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/7 subtests 
Can't find label 2 at /home/cpansand/.cpan/build/2022102205/PDF-Builder-3.024-2/blib/lib/PDF/Builder/Annotation.pm line 103.
# Looks like your test exited with 255 just after 3.
t/87_pages.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/7 subtests 
```

Statistical analysis does not give any results, but it seems that this happens if PDF::Builder is installed, or maybe depends on a specific PDF::Builder version.

**Comment by ChordPro** [comment]
This seems to be a problem with PDF::Builder. I've forwarded this to its maintainer.

**Comment by PhilterPaper** [comment]
I tried installing ChordPro on Windows 10, PDF::Builder 3.024, and got the same t-test errors. I will have to dive into it (the "splice" errors) tonight and see what's going on. Does it give the same error with PDF::API2? The page() method is almost identical code between the two.

The message about "can't find label 2" in Annotation may be confusion on the part of Perl over invoking a "goto" subroutine. I may have to modify that line to make it clear that "goto" is my local subroutine, and not a Perl goto statement. It's odd that message has never shown up before! Possibly it's linked to the splice error reported before? The fix may be as simple as swapping the definitions in Annotation of 'goto' and 'link'.

The first t-test says "# Using PDF::API2 2.043 and Font::TTF 1.06 for PDF generation". I do have PDF::API2 also installed -- is that message hard coded as API2, or is it really using API2 instead of Builder? The former would be a minor glitch in the t-test.

**Comment by PhilterPaper** [comment]
It gets stranger and stranger. I can confirm that it installs OK on PDF::API2 2.043 (Perl 5.26, Windows 10). I've instrumented it to watch the page insertion activity, and see something odd. For test 80_pages, I see a time with 1 page where it says to insert the new page before page 3, and another with 3 pages where it says to insert the new page before page 5! Can you tell me what the intent is here? Are you counting on page() to insert multiple pages at once? The code in Builder.pm and API2.pm for the page() method only has some minor formatting differences, so they should behave the same, but Builder kicks out an error with the splice() call. It also has that message from Annotation that might be either the cause or an effect of the splice() problem, but I can't tell at this point. I need to sleep on it and will take another crack at it tomorrow.

**Comment by dereksz** [comment]
I'm getting the same issue on openSUSE, and can confirm that uninstalling PDF::Builder (so as to have the app use PDF::API2 instead) worked fine.

The output regarding splice and others appears just to be warnings.

Before I did the uninstall, I tracked it down to PDF::Builder::Outpine.pm:448, where we have:

```perl
sub _destination {
    require PDF::Builder::NamedDestination;
    return PDF::Builder::NamedDestination::_destination(@_);
}
```
but ` PDF::Builder::NamedDestination::_destination` appears not to exist.
PDF::Builder was version 3.024.

Hope this may be of help, Derek

**Comment by sciurius** [comment]
PDF::Builder 3.023 (from CPAN) issues the splice complaints but passes some of the tests. So the failure is introduced in 3.024.

Note that there was a substantial renaming of methods in PDF::API2 release 2.041. 
ChordPro requires PDF::API2 2.036 but some of the pages tests already used some of the new method names. I've fixed this in git but it will be a matter of time that the new method names will actually be used in the code.

**Comment by sciurius** [comment]
I've uploaded `App-Music-ChordPro-5.989_003.tar.gz` to CPAN. Can you try it?
It will use environment variable `CHORDPRO_PDF_API` to select the API. Valid values are `PDF::API2` and `PDF::Builder`.
Default is `PDF::API2`.
This kit passes the tests with Builder 2.033 and fails with 2.034.

**Comment by dereksz** [comment]
Looks like there may be a typo somewhere in `_003`?  Guessing `PAD::API2` below should actually be `PDF::API2`?

```bash
➜  dev git:(main) ✗ sudo cpanm App::Music::ChordPro@5.989_003
! Finding App::Music::ChordPro (== 5.989_003) on cpanmetadb failed.
--> Working on App::Music::ChordPro
Fetching http://cpan.metacpan.org/authors/id/J/JV/JV/App-Music-ChordPro-5.989_003.tar.gz ... OK
Configuring App-Music-ChordPro-5.989_003 ... OK
Building and testing App-Music-ChordPro-5.989_003 ... OK
Successfully installed App-Music-ChordPro-5.989_003
1 distribution installed
➜  dev git:(main) ✗ chordpro Heaven\ Can\ Wait.utf8.cho > Heaven\ Can\ Wait2.pdf
Missing PDF library PAD::API2 (CHORDPRO_PDF_API)
```

**Comment by eserte** [comment]
> I've uploaded App-Music-ChordPro-5.989_003.tar.gz to CPAN. Can you try it?

Looks good on my smokers.

**Comment by sciurius** [comment]
> Perhaps `CHORDPRO_PDF_API` should be tested for supoported values

Maybe, Currently you can provide your own library, e.g. Foo:Bar or PDF::API4 etc.

**Comment by sciurius** [comment]
Phil, FYI: Since the failures are exclusively due to PDF::Builder 3.024, the cpantesters matrix gives an impression on how widely this is installed.
![scrot20221024095225](https://user-images.githubusercontent.com/1118804/197475581-f3116b1e-96b6-4d38-9e75-5fbb1fcca58a.png)

**Comment by sciurius** [comment]
I have eliminated the cause of the splice warnings in 5.989_004.
The "can't find label" problem is still present when using PDF::Builder 3.024.

**Comment by PhilterPaper** [comment]
Was it trying to add multiple pages at once? Perhaps I should add some code in page() to guard against such a thing? (Only allow one page to be inserted, and not beyond the end.)

I need to do some updates on Annotation, Outlines, and NamedDestination to clean up the missing _destination() and fully enable the PDF::API2 changes into PDF::Builder. I suspect that the "label" business may be caused by using "goto" as a subroutine name.

**Comment by sciurius** [comment]
No, I just added a new page with page number that was one too high. No big deal since the page was always last and the slice would neatly insert the page at end. The reason `PDF::API2` did not throw the slice warning is that `PDF::API2` does not have warnings enabled. I've filed [an issue](https://github.com/ssimms/pdfapi2/issues/57) for this.

**Comment by sciurius** [comment]
BTW, if you have both `PDF::API2` and `PDF::Builder` installed, you can select the desired api with environment variable `CHORDPRO_PDF_API`. This makes testing and maintenance easier. ChordPro will default to `PDF::API2`.
It was already possible to select the desired api with a config setting, but the tests do not use configs.

**Comment by PhilterPaper** [comment]
I have made changes to PDF::Builder that _should_ fix the reported build problems, but I'm unable to test the installation with the _005 dev release:
```
C:\Users\Phil\Desktop\chordpro-dev>cpan .
You are visiting the local directory
  '.'
  without lock, take care that concurrent processes do not do likewise.
CPAN: CPAN::SQLite loaded ok (v0.219)
Database was generated on Wed, 26 Oct 2022 12:01:12 GMT
You are visiting the local directory
  'C:/Users/Phil/Desktop/chordpro-dev/.'
  without lock, take care that concurrent processes do not do likewise.
  C:/Users/Phil/Desktop/chordpro-dev/.
  Has already been unwrapped into directory C:/Users/Phil/Desktop/chordpro-dev/.
CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
CPAN: CPAN::Meta loaded ok (v2.150010)
Configuring C:/Users/Phil/Desktop/chordpro-dev/. with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a gmake-style Makefile
Writing Makefile for App::Music::ChordPro
Writing MYMETA.yml and MYMETA.json
Directory 'C:/Users/Phil/Desktop/chordpro-dev/.' not below C:\STRAWB~1\cpan\build, will not store persistent state
  C:/Users/Phil/Desktop/chordpro-dev/.
  C:\Strawberry\perl\bin\perl.exe Makefile.PL -- OK
Running make for C:/Users/Phil/Desktop/chordpro-dev/.
CPAN: Module::CoreList loaded ok (v5.20221020)
perl Makefile.PL
Generating a gmake-style Makefile
Writing Makefile for App::Music::ChordPro
Writing MYMETA.yml and MYMETA.json
C:/STRAWB~1/c/bin/gmake -f Makefile clean
gmake[1]: Entering directory 'C:/Users/Phil/Desktop/chordpro-dev'
"C:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e rm_f -- \
  ChordPro.bso ChordPro.def \
  ChordPro.exp ChordPro.x \
   blib\arch\auto\App\Music\ChordPro\extralibs.all \
  blib\arch\auto\App\Music\ChordPro\extralibs.ld Makefile.aperl \
  *.a *.o \
  *perl.core MYMETA.json \
  MYMETA.yml blibdirs.ts \
  core core.*perl.*.? \
  core.[0-9] core.[0-9][0-9] \
  core.[0-9][0-9][0-9] core.[0-9][0-9][0-9][0-9] \
  core.[0-9][0-9][0-9][0-9][0-9] libChordPro.def \
  mon.out perl \
  perl.exe perl.exe \
  perlmain.c pm_to_blib \
  pm_to_blib.ts so_locations \
  tmon.out
"C:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e rm_rf -- \
  blib dll.base \
  dll.exp
"C:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e mv -- Makefile Makefile.old > NUL
gmake[1]: Leaving directory 'C:/Users/Phil/Desktop/chordpro-dev'
mv Makefile.old Makefile
process_begin: CreateProcess(NULL, mv Makefile.old Makefile, ...) failed.
make (e=2): The system cannot find the file specified.
gmake: *** [GNUmakefile:7: all] Error 2
  C:/Users/Phil/Desktop/chordpro-dev/.
  C:\STRAWB~1\c\bin\gmake.exe -- NOT OK
Stopping: 'install' failed for 'C:/Users/Phil/Desktop/chordpro-dev/.'.

C:\Users\Phil\Desktop\chordpro-dev>dir Makefile*
 Volume in drive C is Windows
 Volume Serial Number is 0EDF-FD28

 Directory of C:\Users\Phil\Desktop\chordpro-dev

10/26/2022  10:49 AM            51,839 Makefile.old
10/26/2022  10:48 AM             2,803 Makefile.PL
10/24/2022  04:50 PM             2,750 Makefile.PL~
               3 File(s)         57,392 bytes
               0 Dir(s)  829,223,723,008 bytes free

C:\Users\Phil\Desktop\chordpro-dev>dir Makefile
 Volume in drive C is Windows
 Volume Serial Number is 0EDF-FD28

 Directory of C:\Users\Phil\Desktop\chordpro-dev

File Not Found
```
Any idea what's happening here? In Makefile.PL I changed the default from PDF::API2 2.036 (!!?) to PDF::Builder 3.023 (also 3.024), but I get the above error even with the PDF::API2 default.

**Comment by PhilterPaper** [comment]
By the way, with my fixes to Builder to handle improper `page(n)` ranges (give warning and correct), and your fix to Writer.pm for `page_labels()`, the original 5.989 version (from CPAN) seems to install OK. However, for some reason the cpan command is telling me that the installed version is "undef". Installing from the CPAN repository doesn't work because the Writer.pm fix `%$opts` is missing.

**Comment by sciurius** [comment]
Thanks to your nice warning I now had a real incentive to check page insertions and I fixed most (hopefully, all).
ChordPro 5.989_007 passes all tests with PDF::Builder 42147c72.
I've upgraded the dependency to PDF::Builder 3.025, hoping to see it on CPAN soon.

**Comment by PhilterPaper** [comment]
PDF::Builder 3.025 isn't out yet, and I was planning on another month or two's work before releasing it. If you want to get the next ChordPro out much sooner than that, I could release 3.025 Real Soon Now, and 3.026 would have my current work in a few months. Let me know if you need 3.025 out soon, and I could do that for you. It's got the _destination() business hopefully cleaned up, and the page(n) warnings.
