### ISSUE TITLE
Warning on PDF export

### ISSUE THREAD

**Issue by Loco1911** [ChordPro/chordpro#257]
Since the last update I am receiving the following warnings:

 : C:\Users\exequ\OneDrive\ChordPro\myconfig.json: Undefined config "pdf.formats.default.subtitle" (using 'false')

 : C:\Users\exequ\OneDrive\ChordPro\myconfig.json: Undefined config "pdf.formats.default.title" (using 'false')

 : C:\Users\exequ\OneDrive\ChordPro\myconfig.json: Undefined config "pdf.formats.first.footer" (using 'false')

 : Problems found!

1. Go to 'File' 
2. Click on 'Preview'

System information:
 - OS: Windows 10
 - Where did you get ChordPro from? Github Releases
 - ChordPro version: ![imagen](https://user-images.githubusercontent.com/17275397/200203790-702f3cdd-5a24-487b-a453-0da4091d5467.png)
 - Perl version: ![imagen](https://user-images.githubusercontent.com/17275397/200203813-62fa49d9-700e-49f0-9833-6bb0a8dd5ad6.png)

My config file:
[myconfig.zip](https://github.com/ChordPro/chordpro/files/9947198/myconfig.zip)

**Comment by ChordPro** [comment]
Apparently you are using `null` values for some of the formats.
````
   "pdf":
       "formats" : {
	  "default" : {
	      "title"     : null,                <==
	      "subtitle"  : null,                <==
````
The value `null` is no longer valid. Please use `[]` instead.
Apologies for the inconvenience.

**Comment by Loco1911** [comment]
After changing those values I am receiving the following error:

 : , or } expected while parsing object/hash, at character offset 4976 (before "] },\r\n        { "n...") at C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/App/Music/ChordPro/Config.pm line 286.

 : Fatal problems found!

**Comment by sciurius** [comment]
Probably a typo. Please include the full config.

**Comment by Loco1911** [comment]
Sorry, I forgotten upload the config file.
[myconfig.zip](https://github.com/ChordPro/chordpro/files/9961494/myconfig.zip)

**Comment by sciurius** [comment]
If you visit your config file in a decent editor and you skip forward from the beginning to character 4976, you can see that the definition of the D/F# chord has an extraneous closing bracket `]`. Removing this gets rid of the error.
BTW, I didn't see any differences in the pdf.formats - did you fix the title, subtitle and footer entries?
