### ISSUE TITLE
truesf on note names

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#259]
The `truesf` feature is great, but seems to treat `b` in note names as a flat, regardless of position.

For instance, `[bb]-[a]-[g]-[f]` outputs as (♭♭)-(a)-(g)-(f)

I guess the process simply replaces lower case b with u266D, regardless of whether or not it's the first character encountered after the `[`.

This is in the song body. It would be a 'nice to have' if truesf operated in comments too, but at least current behaviour for both chord and note names in comments seems consistent.

**Comment by sciurius** [comment]
Fixed in 5.990_004

**Comment by gwyndaf** [comment]
Great, seems to work nicely now, including for note names in chord grids.
