### ISSUE TITLE
Chord grids included in PDF output even when lyrics-only=true

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#260]
Config file has `"lyrics-only" : true,` but PDF output still includes chord grids.

I suspect they probably shouldn't be included?

Doesn't really affect me, but I happened to notice it in the 'lyrics only' songbook that gets generated alongside my instrument-specific ones, and chord grids would probably be confusing in pure lyric sheets.

**Comment by sciurius** [comment]
I think that makes sense, but you never know.

I'm currently inclined to supress the chords when using the command line option `--lyrics-only`. When a user adds `settings.lyrics-only` to her config, I assume she's also capable of adding `diagrams.show:none`.

What do you think?

**Comment by gwyndaf** [comment]
Sorry, maybe a clash of terminology!

I meant chord grids, as defined by `{start_of_grid}`, which show chord names and bar/beat lines, within the body of the song.

My interpretation of `lyrics-only` is that it removes chord names (and, I think, annotations) from the body of the song. If regular chord names like `[G]` aren't in the song body, I also wouldn't expect to see chord grids (`start_of_grid`).

Here's an example: 
[Chord grid sample.pdf](https://github.com/ChordPro/chordpro/files/10206713/Chord.grid.sample.pdf)

Totally agree with you that current `diagrams.show:none` is fine for suppressing fretboard/keyboard chord _diagrams_.

Maybe related: it seems that `lyrics-only` suppresses Lilypond content, but ABC content remains in output. I don't have a strong view, but maybe the same behaviour for both would be more consistent?

**Comment by sciurius** [comment]
Ah, the neverending chords grids versus diagrams clash ☺.

But I'm a bit puzzled now. The file that you included gives a fine example of combining chord grids with lyrics.

Nevertheless I'll add suppression of 'anything that would not matter to singers' to `--lyrics-only`. That includes chords within lyrics, chord diagrams, grids. What about tabs?

**Comment by gwyndaf** [comment]
This is the song source, which includes both `[ ]` chords to accompany (within) the lyrics, and chord grids for instrumental breaks. 
[Dirty_Old_Town.cho.txt](https://github.com/ChordPro/chordpro/files/10207819/Dirty_Old_Town.cho.txt)

That is, the chord grids aren't the chords that _accompany_ the lyrics, but the instrumental breaks _in between_ lyrics (though in this case the chords are pretty similar). 

As you suggest, though, I guess there is a case for sheets that give the basic chord structure (in grid) with the lyrics shown separately. However, I wouldn't think of that as a 'lyrics only' sheet, just a different way of laying out a regular 'chords and lyrics' sheet.

I think tabs aren't lyrics so shouldn't be included with `--lyrics-only`. In my main usage, all tabs are conditional on `instrument.type`, and my lyrics-only config sets that to `none`, so I don't get tabs in output anyway. I think it'd still be useful, though: people creating sheets for a single instrument probably won't have any reason to use conditional directives.

I use the `lyrics-only` layouts only very occasionally, so I'm mainly flagging what seem like odd or inconsistent behaviours. There might be others who use it more regularly and have stronger views on this.

Tricky thing is, if we treat this as 'for singers', it raises questions about whether some way of indicating melody should be included, so I guess I'm being quite literal about the 'lyrics only' idea! :)

**Comment by sciurius** [comment]
'For singers' -- I then think of printed sheets to pass around during a gig so people can sing along. Chords between the lines will be distractive so ChordPro will leave them out. With regard to the other info, it isn't necessary but doesn't really get in the way either.

You can also define an instrument 'singer' that sets lyricsonly and disables chord diagrams. Grids (and anything else) can be suppressed with

    {start_of_grid-singer!}

**Comment by gwyndaf** [comment]
Yes, I think that's my idea of lyric sheets, too, but my 'designer head' is very picky about unnecessary or distracting 'ink on the page'!

Great suggestion for excluding the chord grids for singers, thanks.

**Comment by sciurius** [comment]
I have fixed [ ] handling in comments, just needs some testing. Stay tuned.
