### ISSUE TITLE
"Couldn't open file" message, but PDF file exists

### ISSUE THREAD

**Issue by angus73** [ChordPro/chordpro#264]
## Describe the bug
I have installed chordpro, followed the Getting Started guide but no PDF is shown.

### To Reproduce
- open chordpro gui
- help > insert song example 
- file > preview

### Expected behavior
a pdf file is shown

### Attachments
command-line output:
```
$ wxchordpro 
Gtk-Message: 13:03:02.776: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 13:03:10.120: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:03:10.122: Failed to load module "canberra-gtk-module"
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
I/O Error: Couldn't open file '/tmp/Q_WBm2Yc9Q.pdf': No such file or directory.
** Message: 13:03:10.424: couldn't open the PDF file.

** (org.inkscape.Inkscape:20032): WARNING **: 13:03:10.424: Can't open file: /tmp/Q_WBm2Yc9Q.pdf (doesn't exist)
ink_file_open: '/tmp/Q_WBm2Yc9Q.pdf' cannot be opened!
InkscapeApplication::document_open: Failed to open: /tmp/Q_WBm2Yc9Q.pdf
ConcreteInkscapeApplication::on_open: failed to create document!
```
But actually the file /tmp/Q_WBm2Yc9Q.pdf exists, and I can open and view it fine with the default pdf viewer (evince).

## System information
 - OS: Ubuntu 18.04
 - Where did you get ChordPro from? CPAN
 - ChordPro version: ChordPro core 6.000
 - Perl version:  perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

Thank you very much,
Angus

**Comment by sciurius** [comment]
Smells like an inkscape problem. Can you add the song and the config?

**Comment by sciurius** [comment]
No monger relevant.
