### ISSUE TITLE
Allow access to preset configurations in filelist

### ISSUE THREAD

**Issue by quiddle** [ChordPro/chordpro#265]
## Describe the bug
ChordPro does not recognize preset configurations when referenced in filelists.

### To Reproduce
1. Given a song file, `MySong.cho` with contents:
```
{title: My Song}
{key: C}

[c]Row, row, row your boat
```
2. And a filelist file, `songs.txt` with the following contents
```
MySong.cho
MySong.cho --config keyboard
```
3. Run the command
```bash
$ chordpro --filelist songs.txt --output "My Songs.pdf"
```
4. Get the error: `Missing config: keyboard`

### Expected behavior

When specified at the command line, preset configurations (i.e. modern1, guitar, ukulele, etc.) are available by name.
```
$ chordpro --config keyboard --output MySong.pdf MySong.cho
```

The same behavior should be available in filelists.

### Attachments
*none*

## System information
 - OS: Mac OS 13.1 (Ventura)
 - Where did you get ChordPro from? GitHub, binary install

 - ChordPro version: 6.000
 - Perl version: 5.34.0

## Additional context

*none*

**Comment by sciurius** [comment]
Fixed in 6.043_003.
