### ISSUE TITLE
My user-defined chords aren't recognised in version 6.0 anymore

### ISSUE THREAD

**Issue by Schlosstrunk** [ChordPro/chordpro#266]
Hi,
I'm relatively new to chordpro, so I'm sorry if I did something wrong, but since I updated from 5.9.xxx to 6.00 none of my self-defined chords don't work anymore which used to generate images.
For example
_{define: A5 base-fret 5 frets 1 3 3 x x x}_
or
_{define: D/F# base-fret 0 frets 2 x 0 3 2 x}_

No chord diagram defined for "D/F#" (skipped)

Did the syntax change? I tried out some variants of the syntax without success and I couldn't find information about it in the release notes.

Any help is greatly appreciated!

**Comment by sciurius** [comment]
For help questions, please use [the forum](https://groups.io/g/ChordPro).

Also, it usually helps if you include a small sample that shows the problem.
