### ISSUE TITLE
Feature request: allow placement of images behind / independently of text

### ISSUE THREAD

**Issue by andb0t** [ChordPro/chordpro#268]
Hello there!

I would like to include images on pages but not in-line with text or floating or any of the few options listed in the [chordpro docs](https://www.chordpro.org/chordpro/directives-image/) but independently. This option is called "behind text" in Microsoft word. Below you see a screenshot mock-up of what I would like to have. The currently unavailable feature is bordered in red. In this example I would like to have the Lenny Kravitz image right next to the lyrics, not "inside" the lyrics.

Would it be possible to add a new directive, e.g. 

_position=position_x,position_y
If this option is given, the position of the image is set in absolute relative coordinates of the top left image corner on the current page, given in percentage. E.g. "position=75%,10%" would place the image on the right upper half of the page with a a 75% distance from the left and a 10% distance from the top._

I could achieve this by postprocessing with LateX, superimposing the image, but that's a big mess, compared to a probably small and useful new feature in chordpro! Just imagine, you could also add little snippets of notes or instrument symbols :)

![image](https://user-images.githubusercontent.com/3214115/215766901-86c8fc6a-8d7a-4798-861d-56dcc1fdf181.png)

**Comment by sciurius** [comment]
In version 6.000_006 (in git) I have added x and y values for images. The values are relative to the left margin and the top margin **of the text area**. See https://www.chordpro.org/chordpro/images/layout-large.png .

When x or y values are supplied, the image does not occupy space (behind the text).

Can you give it a try?

**Comment by andb0t** [comment]
Thanks for the tip! It's not in the docs, yet, is it?

I tried it unsuccessfully unfortunately, using chordpro 6.000:
```
{image: src="media/guitar.png" x=0.5 y=0.5}
```
resulting in:
```
DERROR: error in file songs_leadsheets/Bon_Jovi_AH__You_give_love.cho :
"/tmp/tmp.xhcVZrM2Bg", line 10, Unknown image attribute: image: src="media/guitar.png" x=0.5 y=0.5
        {image: src="media/guitar.png" x=0.5 y=0.5}
"/tmp/tmp.xhcVZrM2Bg", line 10, Unknown image attribute: image: src="media/guitar.png" x=0.5 y=0.5
        {image: src="media/guitar.png" x=0.5 y=0.5}
Please fix the 1 above issues!
unknown link uri '(null)'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.00 ms
... repeated 2 times...
```

Here's my `--about` output:
```
Run-time information:
  ChordPro core          6.000
  Perl                   v5.30.0 (/usr/bin/perl)
  CHORDPRO_LIB           /home/andbot/.config/chordpro
  Resource path          /home/andbot/.config/chordpro
                         /usr/local/share/perl/5.30.0/App/Music/ChordPro/res

Modules and libraries:
  Storable               3.15
  Text::Layout           0.030
  File::LoadLines        1.021
  PDF::API2              2.044
  Font::TTF              1.06
```

**Comment by sciurius** [comment]
It is not yet official. You need 6.000_006 (the dev branch).

**Comment by andb0t** [comment]
Oh, is there any indication when this might make it to a main release? Will this be weeks (then I can wait) or months (then I might chose to use the dev branch locally)? I'd definitely not want to include a dev branch on my CI/CD pipeline which currently compiles all the chordpro files to a 250 page songbook

**Comment by sciurius** [comment]
The images placement will not be released shortly, since there are some more things to tackle. For example, I want to be able to attach an image to a chord or lyrics syllable. It will need some more experimenting (suggestions welcome).

OTOH, it would be more than interesting to run your pipleline through the dev version. Helps early detecting of anomalities.

**Comment by sciurius** [comment]
This, and more in 6.030 and 6.04x.
