### ISSUE TITLE
PDF outlines issues (nesting and 'letter' setting)

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#270]
I've noticed a few small issues with PDF Outlines: one functional, one maybe documentation, and one maybe only partially a ChordPro issue...

## 1. Multiple outline definitions get nested (when letter index generated)
I have a set of outlines defined as
```
      "outlines" : [
      { "fields"   : [ "sorttitle", "artist" ],
        "label"    : "By Title",
        "line"     : "%{title}%{artist| – %{}}",
        "collapse" : false,
        "letter"   : 0,
        "fold"     : false,
        "omit"     : false,
      },
      { "fields"   : [ "artist", "sorttitle" ],
        "label"    : "By Artist",
        "line"     : "%{artist|%{} – }%{title}",
        "collapse" : true,
        "letter"   : 0,
        "fold"     : false,
        "omit"     : false,
      },
      { "fields"   : [ "year", "sorttitle" ],
        "label"    : "By Year",
        "line"     : "%{year|%{} – }%{title}",
        "collapse" : true,
        "letter"   : 0,
        "fold"     : false,
        "omit"     : false,
      },
      ],   
```
Outlines are produced as expected, except that each group of outlines is nested in the one above, i.e. 'By Year' within 'By Artist' within 'By Title'. I expected each to become a top-level heading. This might be my usage, but I don't know if there's a way to make each outline definition a top-level one.

I'm not sure if this counts as a 'fix' or 'enhancement.' There might be legitimate reasons for wanting either nested or non-nested groups of outlines.

On further testing, this issue seems to arise only when a letter index is created (see below). If there's no letter index, each group comes out as top-level with no problem.

## 2. 'letter' behaviour not as documented
[Documentation](https://www.chordpro.org/chordpro/chordpro-configuration-pdf/#outlines) suggests that `letter : 0` disables the addition of alphabetic sub-headings, but they're actually generated. I normally use `letter : 99` to prevent such sub-headings, so no functional problem, but documentation might need clarifying.

## 3. Outline group and letter index entries have active link and display (wrong) page number
The top-level outline groups and letter index entries have active links, but all seem to link back to the PDF's first page, which doesn't seem particularly useful. On PDF readers that add page numbers (e.g. xreader), that also manifests visually as 'i' in my case (first front matter page), adjacent to each letter index entry, which can be confusing, i.e. that's not where each letter starts, even if songs are organised alphabetically.

I think the numbering is added automatically (or not) by some PDF readers, based on the destination of each link, but the group headings and letter index don't have meaningful destinations.

So, it might be useful that outline group and letter index entries _don't_ have active link destinations (if that's possible), i.e. the only active links are those to specific song pages. In turn, I think that might also prevent numbers being added automatically by some PDF readers.

**Comment by sciurius** [comment]
A quick and dirty test (see the attached files) with 10 songs/artists/years shows the following index:

![scrot20230304215336](https://user-images.githubusercontent.com/1118804/222928261-4024d6d3-399c-403e-8ce4-16478b4a0f6b.png)

Looks okay to me. There are three main headings.

[outlines.zip](https://github.com/ChordPro/chordpro/files/10889661/outlines.zip)

2. You are right about the `letter:0` description. I shall fix it in the code.

3. Outline group and letter index entries do not have active links. What PDF viewer are you using?

**Comment by sciurius** [comment]
With xreader 3.6.3 it displays fine.

**Comment by sciurius** [comment]
BTW: I use `atril` (MATE version of `evince`). This does not use poppler.

**Comment by gwyndaf** [comment]
Apologies. I think 1 and 3 were caused by the ghostscript/pdfmark process I use after PDF production, to add an internal 'Home' destination with links from all pages, and restore the front/batter matter links that get lost on merging (I think an issue with PDF::API2, so outside ChordPro scope).

**Comment by sciurius** [comment]
6.000_011 should fix (and document) the behaviour of `letter` and sorting prefixes.

**Comment by gwyndaf** [comment]
That tests out nicely for the `letter` setting of `0`.

It looks like a value of `1` adds the letter index when there's at least one song with that letter (which seems sensible behaviour), so [documentation](https://www.chordpro.org/beta/chordpro-configuration-pdf/#outlines) might need slight clarification: maybe something like "If the number of outline items is at least the value given here..." (i.e. not "more than").

Numeric sorting now works great, thanks! :)

**Comment by gwyndaf** [comment]
Ah yes, I was using the beta site when I posted but, as you say, maybe it was an older cached image. Thanks.
