### ISSUE TITLE
Unable to build docs

### ISSUE THREAD

**Issue by xeruf** [ChordPro/chordpro#271]
https://github.com/ChordPro/chordpro/tree/master/docs
-> there is no target called `production`, and the target I thought does not build:
```sh
❯ make site
cp ../lib/App/Music/ChordPro/res/config/chordpro.json assets/pub/chordpro_json.txt
hugo --environment=stable --baseURL=https://www.chordpro.org/chordpro/
hugo: downloading modules …
hugo: collected modules in 7082 ms
Start building sites … 
hugo v0.110.0+extended linux/amd64 BuildDate=unknown
Error: Error building site: "/home/janek/data/1-projects/aur/chordpro-git/src/chordpro/docs/content/Home.md:8:1": failed to extract shortcode: template for shortcode "yell" not found
Total in 7104 ms
make: *** [Makefile:13: site] Error 255
```
I would like to make the docs available offline via the AUR package I maintain: https://aur.archlinux.org/packages/chordpro-git

**Comment by sciurius** [comment]
Thank you for making the docs available offline via the AUR package.
Currently, a couple of files were missing in the git. I've added them. Can you pull and checkout the `dev` branch and try if it works now?

I'm not familiar with AUR packages, but shouldn't a package `chordpro-git` be built from the `dev` branch?

**Comment by sciurius** [comment]
Stale.

**Comment by xeruf** [comment]
For that there is the `chordpro-dev-git` package ;)
Looks good now!
