### ISSUE TITLE
Uneven column layouting

### ISSUE THREAD

**Issue by xeruf** [ChordPro/chordpro#272]
I have a song where I put the song in the left column and put the order of song elements in the right - thus I want the right column to be slimmer.

Right now I am hacking this by reducing the right margin, but this is quite limited - would be good to be able to configure either the column widths, or priorities, or an auto layout that adjusts the widths itself.

**Comment by sciurius** [comment]
I've added experimental column layouting in 6.000_013.

In the config file, `settings.columns` can now be a number (the number of columns) or an array with column widths. Column widths can be a number (PDF points), a percentage of the total width, or `0` (or `*`) to distribute the available width.

These are the same:
````
"columns": 2
"columns": [ "50%", "50%" ]
"columns": [ 0, 0 ]
"columns": [ "50%", "*" ]
````

Note that the final columns always uses the remaining width. Its value is therefore bogus unless you have columns with `0` (or `*`).
