### ISSUE TITLE
Error when using "transpose": Can't store REGEXP items

### ISSUE THREAD

**Issue by andb0t** [ChordPro/chordpro#274]
## Describe the bug
When executing `chordpro` on Ubuntu 18.04.4 I get the following error whenever there's a "transpose" directive in the song:

```
ERROR: error in file songs_songbook/Elvis_Presley__Jailhouse_rock.cho :
Can't store REGEXP items at /opt/chordpro/script/../lib/App/Music/ChordPro/Chords/Parser.pm line 797.
```

### To Reproduce
1. use a  Ubuntu 18.04.4 image, install chordpro 6:
   ```
   Run-time information:
   ChordPro core          6.000
   Perl                   v5.26.1 (/usr/bin/perl)
   CHORDPRO_LIB           /root/.chordpro
   Resource path          /root/.chordpro
                                 /opt/chordpro/lib/App/Music/ChordPro/res

   Modules and libraries:
   Storable               2.62
   Text::Layout           0.030
   File::LoadLines        1.021
   PDF::API2              2.044
   Font::TTF              1.06
   ```
2. use this minimal example and save it in "minimal.cho":
   ```
   {title:Jailhouse rock}
   {artist:Elvis Presley}
   {transpose: -2}
   {key: E}

   {start_of_verse: Strophe 1}
   [D#]The [E]warden threw a party in the county jail
   The prison band was there and they began to wail
   The band was jumpin' and the joint began to swing
   You should've heard those knocked out jailbirds sing
   {end_of_verse}

   {start_of_chorus: Refrain}
   Let's [A7]rock, everybody, let's [E]rock,
   every[B7]body in the whole cell [A7]block
   Was [E]dancing to the jailhouse rock
   {end_of_chorus}
   ```
3. Execute `chordpro minimal.cho`
4. Get the error
5. Repeat but remove the "transpose" line
6. Success!

### Expected behavior
I expect this to just create the PDF since the chords are also super simple and should be standard to transpose.

### Additional observations

On my other machine it works using the exact same versions as above except for:
* a different Ubuntu version: Ubuntu 20.04.5 LTS
* a different perl version: v5.30.0
* a different Storable version: 3.15

Unfortunately, the former is the server where I cannot easily upgrade, the latter is my local machine. But I need it to work on the server :/

**Comment by sciurius** [comment]
Thanks for the report. This is a problem with a very old version of Storable. It was fixed in Storable version 3.06 (2018!).

Please urge your server administrator to upgrade at least this component.

**Comment by andb0t** [comment]
Wow thank you for the quick and detailed reply! Always a pleasure with you 🥇

**Comment by sciurius** [comment]
Feel fee to [buy me a coffee](https://ko-fi.com/chordpro) :heart_eyes:
