### ISSUE TITLE
New font setting for chorus #featurerequest

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#275]
Might it be possible to add a means of specifying chorus typography, i.e. for chorus lyrics within `{soc}...{eoc}`?

It might mean a new `pdf.fonts.chorus` setting, which could default to `pdf.fonts.text` (to continue current behaviour).

Rationale is that I've been thinking about how to make chorus repeats easier to locate visually at a quick glance. Indent does that to an extent, but the text itself looks the same as the song body, so it's not a strong visual cue in the way that, say, bold or colour text for the chorus might be.

**Comment by sciurius** [comment]
Per-section configs are on the [ROADMAP](https://chordpro.org/beta/roadmap/).

**Comment by gwyndaf** [comment]
Ah, sorry. I didn't notice this is a duplicate (or sub-set of) #174
