### ISSUE TITLE
Broken links to chordpro.org in `.md` files

### ISSUE THREAD

**Issue by josephmturner** [ChordPro/chordpro#276]
Hello! Some links to https://chordpro.org in the `.md` files in this repo are broken. The pattern seems to be that the real paths are capitalized and require the `.html` extension. For example, the opening paragraph of `README.md` contains the following broken link:

https://www.chordpro.org/chordpro/chordpro-installation

The actual link should be:

https://www.chordpro.org/chordpro/ChordPro-Installation.html 

Thank you for maintaining ChordPro!!

Joseph

**Comment by sciurius** [comment]
Thanks for the report. I've checked and fixed the links in the dev branch.

**Comment by josephmturner** [comment]
Thank you!
