### ISSUE TITLE
Defining a "|" chord in config causes a parse error 

### ISSUE THREAD

**Issue by RichTeaTime** [ChordPro/chordpro#279]
## Describe the bug

Some ChordPro users, notably Songselect.com use `[|]` in some songs as a way of indicating a number of bars repeats of a pattern.
In order to support this, a user of ChordPro can add the following to a preset config file:

	"chords" : [
		{
			"name"  : "|",
			"copy" : "NC"
		},
    ],

This current results in an error in Chords\Parser.pm:233 where the $chord value is not defined. This is due to Chords.pm trying to split the 'name' value on the '|' character as if it was an alternate chord marking (e.g. [G|Csus4]) and producing two empty strings.

### To Reproduce
1. Create a preset file with a "chords" entry,
```
"chords" : [
		{
			"name"  : "|",
			"copy" : "NC"
		},
],
```
2. Run Chordpro specifying this preset file as a --config
3. Regex error is returned from Chords\Parser.pm:233

### Expected behavior
The file should be parsed correctly, and ```[|]``` in source files should be treated the same way as NC.

### Attachments
Attached a config file containing the chords definition
[SongSelect.txt](https://github.com/ChordPro/chordpro/files/11405529/SongSelect.txt)

## System information
 - OS: Windows 10
 - Where did you get ChordPro from?  ChordPro.org

 - ChordPro version: 5.987
 - Perl version: 5.30.1

**Comment by sciurius** [comment]
Thanks for the report and PR.
This has already been implemented in the current development version.
