### ISSUE TITLE
Command-line option to list available metadata

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#284]
Possible useful enhancement: a command-line parameter to list all available metadata keys/variables (given the specified config file/s).

Might be useful to include scope of each (e.g. relating to chord, song or songbook), and maybe whether built-in or user-defined.

I don't know whether this is something that could be easily generated from existing code, or might be more effort than it's worth.

One approach might be simply to use the existing `--meta` parameter, but with no argument.

Rationale: some are [documented](https://www.chordpro.org/chordpro/chordpro-configuration-format-strings/), while there are others that I use in configs on a 'set and forget' basis (e.g.` key_actual`), so tend to forget any I haven't already used!

**Comment by sciurius** [comment]
I think I'll take the documentation route -- document all the metadata available to substitutions. At least the data that is guaranteed to work ☺.

**Comment by sciurius** [comment]
Please take a look at https://www.chordpro.org/beta/chordpro-configuration-format-strings/ .

**Comment by gwyndaf** [comment]
Fantastic: thanks Johan! :)
