### ISSUE TITLE
Link to installation instructions yields a 404 file not found

### ISSUE THREAD

**Issue by kjcole** [ChordPro/chordpro#286]
## Describe the bug
`README.md` has a broken link to installation instructions.

### To Reproduce

1. Download and untar [the current release, R6.010](https://github.com/ChordPro/chordpro/releases/tag/R6.010)
2. `cd chordpro-R6.010`
3. Open `README.md`
4. Follow the link referred to by the text:  

> _Check  https://chordpro.org/chordpro/ChordPro-Installation.html for installation instructions..._

5. See:

```
Not Found
The requested URL was not found on this server.

```

### Expected behavior
I expected to see installation instructions. I assume the intended URL has become:

https://chordpro.org/chordpro/chordpro-installation/

**Comment by sciurius** [comment]
Yes... I use Hugo for site building and apparently it has changed its opinion on document links.
I've made a symlink to (temporarily) fix this.

Thanks for reporting!
