### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#289]
## Describe the bug
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        t/122.pdf
        t/143_chords.t
Please inform the author.
chordpro-6.010.017

### To Reproduce
1. 
2. 
3. 
4. 

## System information
 - OS:  ubuntu studio 22.04.2
 - Where did you get ChordPro from? 

 - ChordPro version: 
 - Perl version:

**Comment by sciurius** [comment]
Thanks, this should be fixed in 2.010_018.
