### ISSUE TITLE
ChordPro under Linux does not export greek unicode characters into the PDFs

### ISSUE THREAD

**Issue by psifidotos** [ChordPro/chordpro#292]
## Describe the bug
When a song contains lyrics, title etc with greek characters, these characters are not shown at all at the exported pdf file. This issue does not exist when exporting to .txt or .html files.

### To Reproduce
1. Write a song with greek lyrics
2. use chordpro command to export it in pdf
3. open the pdf file, all greek characters are missing

### Expected behavior
greek text should look just fine inside PDF Files

### Attachments
```
{title: Greek Text Inside PDF}
{subtitle: Test Δοκιμή}

Good Morning, Καλημέρα, Good Morning
```

In above example, words "Δοκιμή" and "Καλημέρα" are not shown at all inside the pdf file

screenshot from exported pdf:
---
![εικόνα](https://github.com/ChordPro/chordpro/assets/2216474/6c0ec641-8b3b-48a8-97bf-8af560f2e89a)
---

## System information
 - OS: OpenSUSE Tumbleweed
 - Where did you get ChordPro from? CPAN
 - ChordPro version: 6.010
 - Perl version: 5.36.1

**Comment by sciurius** [comment]
Did you read https://www.chordpro.org/chordpro/faq-unicode-characters/ ?

**Comment by psifidotos** [comment]
> Did you read https://www.chordpro.org/chordpro/faq-unicode-characters/ ?

Oh, sorry.... Thank you!! It worked !! :)
