### ISSUE TITLE
[feature] - improve chord diagrams aesthetics

### ISSUE THREAD

**Issue by psifidotos** [ChordPro/chordpro#294]
Hello, I recently started to use Chordpro. In the past I was just using .doc files and chord images produced from: https://chordgenerator.net/#G6.png?p=55576x&f=11132-&s=2&b=false . I have helped in the past the chordgenerator.net maintainers in order to update their chord diagram visuals. 

In my local system I have updated files `Output/PDF/StringDiagrams.pm` and `Output/PDF/Writer.pm` in order to be able to provide the following diagram visuals:

![εικόνα](https://github.com/ChordPro/chordpro/assets/2216474/bd4a82ba-26b5-4e22-887c-907f3c7bf89b)

The differences from current default diagram visual are:

- [ ] fingers are moved at the bottom of the diagram
- [ ] base fret text is moved at the right side and text "fr." is added
- [x] ~~zero base fret is thicker in order to distinguish when the cord is at the top of the fretboard~~ [902829b89d343]
- [ ] all circles for frets are drawn even when they belong inside a bar
- [ ] the bar line has changed into an arced bar line which is also the way to demonstrate bars in classical guitar notation.

Are you interested in such diagrams? I can provide you with PRs if you want.

regards,
michail

**Comment by sciurius** [comment]
Nice! Looking forward to the PRs.
