### ISSUE TITLE
defined chords for keyboard start too far on the right

### ISSUE THREAD

**Issue by spakarl** [ChordPro/chordpro#297]
I am defining a chord for Bm7-5 (Bsemidim, Bm7b5) for a keys instrument.
The definition looks like this:
~~~
{define Bm7-5 keys 6 10 12 15}
~~~

This should produce  a diagram with the following notes (starting from bottom): F, A, B, D
which is a inversion of the chord.
However it produces a diagram with the following notes (starting from left): D, F, A, B
I guess it wraps round, because it starts too far on the right.

![Example](https://github.com/ChordPro/chordpro/assets/29946075/6874ba9b-ecf9-4393-93ca-65ffbfcc97ef)

**Comment by sciurius** [comment]
Thanks. Improved in 6.020_001.
