### ISSUE TITLE
Why doesn't ChordPro need to use same font ? 

### ISSUE THREAD

**Issue by Rexadev** [ChordPro/chordpro#299]
Ultimate Guitar always use RobertoMono if you were you copy it and use different  font Chords and Lyrics will not Sync.

---------------------------------------------------------------------------------

### To Reproduce
1. 

## System information
 - OS: 
 - Where did you get ChordPro from? 

 - ChordPro version: 
 - Perl version:

**Comment by sciurius** [comment]
Your report is incomplete and I cannot understand what you want to say.

**Comment by timmbo9** [comment]
Use any MONO font to resolve your issue.

**Comment by Rexadev** [comment]
> Your report is incomplete and I cannot understand what you want to say.

ChordPro can any font user want but when font is changed lyrics-chord don't match.

Is there a standard ?
Can I set is per file ?

**Comment by sciurius** [comment]
You can set both the lyrics font and the chord fonts independently.
You can do this in the config file, see https://www.chordpro.org/chordpro/chordpro-configuration-pdf/#fonts .
Alternatively, on the command line with (chordii compatibility) options https://www.chordpro.org/chordpro/using-chordpro/#text-font and https://www.chordpro.org/chordpro/using-chordpro/#chord-font .

Does this answer your question?

**Comment by Rexadev** [comment]
@sciurius Is there a font standard ? Most online use RobotoMono

**Comment by sciurius** [comment]
If you install the RobotoMono font on your system, you can use it as described in https://www.chordpro.org/chordpro/chordpro-fonts/ .

But apparently this is not a bug report, but you are asking questions on how to use ChordPro. Please join the user community on https://groups.io/g/ChordPro - a lot of people are there that can help you with your questions, or learn from them.

**Comment by Rexadev** [comment]
Screen of txt chords in 2 fonts

### Calibri
![image](https://github.com/ChordPro/chordpro/assets/62152714/b5689ce5-08c4-4b21-a38a-bfecb53e0855)

### Cansolas
![image](https://github.com/ChordPro/chordpro/assets/62152714/cf1d57b2-af7d-4ac0-a0eb-2f3707f24220)


https://ultimate.ftes.de/ uses monospaced

ultimate-guitar.com uses robotomono





@sciurius @timmbo9

**Comment by sciurius** [comment]
I get the feeling you are not referring to the standard ChordPro from https://chordpro.org .

**Comment by Rexadev** [comment]
@sciurius ChordPro has it's own ASCII to ChordPro converter. How does it handle Fonts and it's alignment with Lyrics/Chords

**Comment by sciurius** [comment]
An ASCII text document has characters only, there is no such thing as fonts in ASCII text. If you **view** an ASCII text a font is used **by the viewer** to render it.

For the conversion of ASCII text to ChordPro each character is assumed to be the same width to line-up the chords and lyrics. This corresponds to viewing the text with a monospace font.

**Comment by Rexadev** [comment]
> An ASCII text document has characters only, there is no such thing as fonts in ASCII text. If you **view** an ASCII text a font is used **by the viewer** to render it.
> 
> For the conversion of ASCII text to ChordPro each character is assumed to be the same width to line-up the chords and lyrics. This corresponds to viewing the text with a monospace font.

### Screen of txt chords in 2 fonts

### Calibri
![image](https://github.com/ChordPro/chordpro/assets/62152714/b5689ce5-08c4-4b21-a38a-bfecb53e0855)

### Cansolas
![image](https://github.com/ChordPro/chordpro/assets/62152714/cf1d57b2-af7d-4ac0-a0eb-2f3707f24220)

**Comment by sciurius** [comment]
Your screenshots nicely illustrate this. When viewed with Calibri, a proportional font, the chords do not line up as they should. 
When viewed with Cansolas, a monospace font, the line-up is ok. ChordPro converts ASCII text as if viewed with a monospace font so you get the expected results.

When you try to visually line up the chords (by insertibng/removing spaces) while viewing with a proportional font you'll find your chords misplaced after conversion.

Does this answer your question?

**Comment by Rexadev** [comment]
https://www.e-chords.com/chords/taylor-swift/back-to-december uses Arial which is a proportional font how does ChordPro's ASCII to ChordPro Converter https://www.chordpro.org/chordpro/chordpro-configuration-a2crd/ handle's it

**Comment by sciurius** [comment]
It depends on how you get the info from the site into a text document that you can feed to ChordPro.
I assume that when you are premium member and download the song, you get an ASCII document that will do fine.

Even though the site displays the chords misplaced, when you select/copy the text and paste it in a notepad with monospace chords it looks ok:

````
D 
I'm so glad you made the time to see me 
Bm 
How's life, tell me how's your family 
G                        D   A 
I haven't seen them in a while 
D 
You've been good, busier than ever 
Bm 
We small talk, work and the weather 
G                              D  A 
You're guard is up, and I know why 
````
