### ISSUE TITLE
Hangs, possibly due to  {transpose} with [N.C.]

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#301]
Using 6.020_017, some issues with hanging, e.g.
```
{title: Grid special character?}
{transpose: -10}
{define: \\ copy N.C. format "<span face=mono weight=regular color=navy size=95%>↓</span>" }
{start_of_grid: 0+4x4+0 }
| Cm~\ |
{end_of_grid}
```
and
```
{title: N.C. transpose} 
{transpose: +3}
No chord [N.C.]
```
No errors messages produced, but processing hangs.

Based on the pared back samples above, it seems related to `{transpose}` and `[N.C.]`. In the first example, I can prevent hanging by removing the `copy N.C.` part in `{define}`. That seemed necessary in earlier versions but now seems obsolete. But it does point to `[N.C.]` as being a cause.

Past versions have given warning messages about being unable to parse/transpose `[N.C.]`, so I think it's a known challenge, but the latest version seems like maybe it's not trapping that situation and causing a hang somewhere.

**Comment by sciurius** [comment]
As of 6.020_15 the non-transposed chord is stored with "xp" prefix. However, if there was no actual transpose (because it is N.C.) then a reference to itself was stored, causing a circular reference and endless loop.

6.020_018 should prevent this.

**Comment by gwyndaf** [comment]
Is that on github yet?

I've done a pull, but still getting 6.020_017

**Comment by sciurius** [comment]
Sorry, forgot to push.

**Comment by gwyndaf** [comment]
Great. _018 moves along nicely with no hanging.
