### ISSUE TITLE
Defining a Bass note throws an error of Unknown Chord

### ISSUE THREAD

**Issue by ovenwerks** [ChordPro/chordpro#302]
Using wxchordpro and defining a chord like [C/G] gives an "Unknown Chord" error.  This should not happen. While there are some common combinations like [D2/F#] I would expect a chord diagram for, in general, a slash should not throw an error but rather print the chord diagram for the whole thing if present and just print the diagram for the part preceding the slash otherwise.

If there is a setting to turn this bad behaviour off, it should be the default setting. It should also be shown in the manual on https://www.chordpro.org/chordpro/chordpro-chords/

Having to close dialogs for a non-error is a break in the user workflow that is not needed in this case. 

## System information
 - OS: buntu 23.04
- from cpan
 ChordPro core version 6.020
  Perl version v5.36.0 (/usr/bin/perl)
  CHORDPRO_LIB /home/len/.config/chordpro
  Resource path /home/len/.config/chordpro
   /usr/local/share/perl/5.36.0/ChordPro/res

Modules and libraries:
  wxPerl version 0.9932
  wxWidgets version 3.002002
  Storable version 3.26
  Object::Pad version 0.78
  Text::Layout version 0.031
  File::LoadLines version 1.021
  PDF::API2 version 2.044
  Font::TTF version 1.06
  Image::Magick version 6.9.11

**Comment by sciurius** [comment]
> defining a chord like [C/G] gives an "Unknown Chord" error.

I assume you are not _defining_ the chord, but _using_ it, e.g.
````
[A]Hello [C/G]World!
````
This throws a warning that chord `C/G` does not have a built-in diagram. ChordPro has over 400 built-in diagrams but there will always be other chords that some users consider common. Currently the set of built-in diagrams does not contain any slash chords mostly since users seem to disagree whether e.g. `C/G` is a C chord with added bass G, or an 2nd inversion, or a power chord.

The best way to solve this is to define the chord before using it:
````
{define: C/G}
[A]Hello [C/G]World!
````
This will silence the warning. If you'd like to have a chord diagram you can include the appropriate frets in the define, e.g.
````
{define: C/G frets 3 3 2 0 1 0 fingers 3 4 2 0 1 0}
````
Alternatively, you can store the chord definition in your config files, see https://www.chordpro.org/chordpro/chordpro-configuration-generic/#user-defined-chords-string-instruments .

**Comment by ovenwerks** [comment]
I am fully aware I could create such a fingering.
That is not at all the point. Using C/G as our example. [C] is well known and does not throw an error. [C/G] does not require the guitarist to play anything different than [C]. The bass player is interested in the [/G] however but it is just a note. Therefore, so long as [C] is known by the program already, [C/G] should be treated as the same chord as [C] unless the user has explicitly made a fingering for [C/G]. Those who also play bass may very well also play the bass note (I do) but they do not think of it as an alternate fingering so much as adding the bass note.
So, if the root chord is known in a [root/bass] situation, there is no error  if [root] is known, that is the proper fingering (or at least a proper fingering).
There is no reason to create fingerings for these chords that includes the the bass note unless the user desires. It is not error worthy that a fingering that includes the bass note is missing.

If it is log worthy might be another question but in that case, another menu option to open the logging window might be a better plan. I note that the status bar at the bottom already alerts the user anyway.

**Comment by sciurius** [comment]
I suggest to take this proposal to the [community forum](https://groups.io/g/ChordPro/) so other users can participate in the discussion.

**Comment by AnniePerson** [comment]
I play the accordion so I dont bother about chord diagrams. But I frequently use slash chords to specify specific chord / bass note combinations. 
e.g. bass runs like G G/F# G/E G/D 
or accordion specific fingerings for jazz chords like Gm/E for Em7b5 or Am/C for C6
I would not expect that ChordPro is able to detect automatically that G/F# shall cause a warning message and G/D won't need that. How about non-standard guitar tunings like drop D?

**Comment by ovenwerks** [comment]
After much thinking about all uses of the GUI, I think it is easiest to leave things as is. I can think of slicker ways of doing things but I am not sure it is warranted. Certainly there will be times when having a list of things to add or change will be very useful. Thank you for considering this.
