### ISSUE TITLE
Feature request: one time options menu. For wxchordpro

### ISSUE THREAD

**Issue by ovenwerks** [ChordPro/chordpro#303]
There are a few styles of output that I find myself switching back and forth for. It is possible to switch back and forth by switching config files but this is tedious. Being able to print one copy with chords and the next with lyrics only is one example. This is not really a "Preferences" thing but a "this time do this" kind of thing. I would suggest that including chord grids is the same as well. Include them in this song "because I am not familiar", for example. Key change is not a preference but a per song setting as well. Hmm, maybe a non-printed comment with the chosen key could be added back to the original file or a {playkey: *} directive used.
Perhaps a toolbar sort of thing that has some of these settings for this song. A user config would still set the default action as it does now.

**Comment by sciurius** [comment]
Currently the best way for "this time do this" kind of things is to use the chordpro command line tool.
````
$ chordpro mysong.cho --output mysong.pdf
$ chordpro --lyrics-only mysong.cho --output mysong_lyrics.pdf
$ chordpro --no-chord-grids mysong.cho --output mysong_nochords.pdf
````

Your suggestion for something similar to a toolbar menu is interesting, I'll take it into consideration.

Your remark about the key change is not clear to me. Can you elaborate?

**Comment by sciurius** [comment]
This is in 6.020_019 and will be in the next release.

![Screenshot Task menu](https://github.com/ChordPro/chordpro/assets/1118804/55bcd1a8-d158-43a3-815d-327f6f5ad4e6)

The first three are according to your suggestions. The rest are custom tasks that can be created by putting config files in a folder named `tasks` in your personal ChordPro library.

**Comment by ovenwerks** [comment]
The idea above looks good. I might suggest check boxes so they can be cumulative but in this case lyrics only is already no chord boxes.

About key change, I have a few android apps I run using waydroid, guitarpro is one of them. They have a "Key" drop down with 12 choices A, A#, etc. to G#. The key the song is in has the text (default) after it. The next render would use the selected key. I often find myself printing out more than one key before a practice. It is true this is not as capable as the key change mechanism in preferences. However, preferences should be settings that remain stable over time. Things that change from render to render should be more accessible. I have not used wxglade, so I don't know the limitations it has as compared to glade. I am not a great GUI designer so I should not complain ;)

**Comment by sciurius** [comment]
Originally the ChordPro GUI was a simple wrapper just to make the program accessible to Windows and Mac users. It has grown a bit since... Nevertheless I always advice to use it for simple things only, and use the command line tool for anything more demanding. It provides everything and more. It can be scripted, etc..

Back to the GUI: You have a point that some of the preferences are more useful as "decide when you render" instead of being static. I'll see what I can do.

As for printing in more than one key: I use MobileSheets on Android that can show ChordPro files (it even supports the markup extensions) and handles transposition itself. On linux I use the Android emulator that comes with Android Studio.

**Comment by AnniePerson** [comment]
A great idea!
By now I used a workaround to achieve similar things: I copied small config files into 
c:\Program Files (x86)\ChordPro.ORG\ChordPro\lib\ChordPro\res\config\ that show up as checkboxes in preferences.
This new tasks menu simplifies that a lot and saves many additional clicks that were required with my solution. 

Trying to test 6.030_019 by copying the files from \chordpro-dev\lib\ into the respective folder of my installed 6.020 on Win10 I'm facing some issues: calling File - Preview says 
"Can't locate Capture/Tiny.pm in @INC (you may need to install the Capture::Tiny module)"

What's that missing Capture::Tiny module and how can I install it? Thanks in advance for your support

**Comment by sciurius** [comment]
You can create a folder Capture in lib and install the attached file Tiny.pm.
[capture.zip](https://github.com/ChordPro/chordpro/files/12395979/capture.zip)

PS: 6.020_020 will be even nicer...
![scrot20230821143904](https://github.com/ChordPro/chordpro/assets/1118804/8719a7be-e8a5-4ccd-a422-aca7a1e71399)

**Comment by AnniePerson** [comment]
Great. Adding Tiny.pm fixed the bug.
6.020_020 is not yet available. When I download again I still get 6.020_019
Moving "Transpose" to the tasks menu is great. "Notation" and "Transcode to" imho could stay in "Preferences". For me Notation=Common and Transcode to=Scandinavian was a one time decision that will probably never change. What do other users think about that?
I miss one more option: Suppress ABC 
I have a number of songs with small snippets of standard notation for intros, special licks and so on. To create real "lyrics only" sheets, e.g. for sing-along occasions I need to remove not only chords and chord diagrams, but also the ABC sections.

**Comment by ovenwerks** [comment]
>Moving "Transpose" to the tasks menu is great. "Notation" and "Transcode to" imho could stay in >"Preferences". For me Notation=Common and Transcode to=Scandinavian was a one time >decision that will probably never change. What do other users think about that?

Notation =Common seems to be the same a "Auto". That is, in the config file it is the same as "Notation=". So the only time it is needed is if the input file  has a notation that is "not what I normally use". That is one file once in a while. So tasks would be correct.

Transcode to, I am less sure of. I am also likely to leave this set to one setting. However, Consider the band where most people use nashville notation but one person needs Common.


> I miss one more option: Suppress ABC I have a number of songs with small snippets of standard >notation for intros, special licks and so on. To create real "lyrics only" sheets, e.g. for sing-along >occasions I need to remove not only chords and chord diagrams, but also the ABC sections.

I am not sure what that is, perhaps a snip here of the source file would clarify.

**Comment by sciurius** [comment]
> 6.020_020 is not yet available.

I said 6.020_020 **will be** even nicer. It is not ready yet.

> Suppress ABC

Good suggestion. If I add ABC suppressing to lyricsonly, do you still think it has its use as a distinct task?

> Transcode to, I am less sure of. I am also likely to leave this set to one setting. However, Consider the band where most people use nashville notation but one person needs Common.

Doesn't sound like a common thing to happen, so this can be dealt with a custom task should it be relevant to someone.

BTW, the settings for notation, transpose and transcode remain in the Preferences. The settings in the Tasks dialog are one-time overrides.

**Comment by sciurius** [comment]
> [ABC] I am not sure what that is, perhaps a snip here of the source file would clarify.

https://www.chordpro.org/chordpro/directives-env_abc/

**Comment by AnniePerson** [comment]
> Suppress ABC
>> Good suggestion. If I add ABC suppressing to lyricsonly, do you still think it has its use as a distinct task?
I think, the most flexible solution would be a separate setting.
Think of a songbook like this http://cjam.lassecollin.se/ that somebody might publish in various flavours.

**Comment by sciurius** [comment]
I'll add ABC suppressing to lyricsonly. Daily use will reveal if a separate setting is still needed.
