### ISSUE TITLE
Add support for Non-Monospace fonts for converting to ChordPro

### ISSUE THREAD

**Issue by Rexadev** [ChordPro/chordpro#304]
Add support for Non-Monospace fonts for converting to ChordPro

Example -
 https://www.e-chords.com/chords/taylor-swift/back-to-december uses `Arial` for chords and `Poppins Puritan` for title
unlike https://ultimate.ftes.de/ uses monospaced, ultimate-guitar.com uses robotomono, https://www.guitaretab.com uses monospace
### Calibri
![image](https://github.com/ChordPro/chordpro/assets/62152714/b5689ce5-08c4-4b21-a38a-bfecb53e0855)

### Cansolas
![image](https://github.com/ChordPro/chordpro/assets/62152714/cf1d57b2-af7d-4ac0-a0eb-2f3707f24220)

**Comment by sciurius** [comment]
Please take this to the [user forum](https://groups.io/g/ChordPro/topics).
