### ISSUE TITLE
Diagram colour odd behaviour

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#307]
With _027 and `-X` for no config on Linux (Debian testing)

```
{title: Diagram colour}
{define: Bbsus4* copy Bbsus4 diagram #cccccc}
[Bb] [Bbsus4*] 
```
gives
![Screenshot from 2023-09-06 14-12-16](https://github.com/ChordPro/chordpro/assets/1415754/e45be63d-bac0-4a18-9f5c-8b9182ad55d2)

While (chord sequence reversed)
```
{title: Diagram colour}
{define: Bbsus4* copy Bbsus4 diagram #cccccc}
[Bbsus4*] [Bb] 
```
gives
![Screenshot from 2023-09-06 14-12-43](https://github.com/ChordPro/chordpro/assets/1415754/785f21d8-1a8f-42d4-aa03-1661ad63a56d)

Expected behaviour: Bbsus4 diagram all in grey and Bb all in black. The only thing I'd expect to change between examples is the order in which diagrams are displayed.

**Comment by sciurius** [comment]
LOL!

Fixed in  6.020_028.
