### ISSUE TITLE
Testing of chorus style settings ( {chordfont} etc. )

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#310]
Great new feature in _034. Very useful, and seems to test out nicely, mostly.

One observation, and I'm not sure whether or not this is by design.

If `{textfont}`, `{textcolor}` or `{textsize}` are set in the song (to vary from general config settings), chorus styling seem to ignore them, even if no chorus styling has been set explicitly. This seems to break existing chorus behaviour in cases where `{text` directives are used. For instance, if text is smaller (to fit on page), chorus reverts to config defaults (i.e. larger/normal size).

Test sample, with no additional config (`-X`),
```
{textfont: Helvetica bold}
{textsize: 120%}
{textcolor: blue}
Basic song line
{start_of_chorus}
Basic chorus line
{end_of_chorus}
```
gives
![Screenshot from 2023-09-12 15-07-07](https://github.com/ChordPro/chordpro/assets/1415754/9e934b5e-10ea-4945-b4ad-78d63094b42c)
I think I'd expect chorus styling to follow verse text, unless explicitly specified in `{chorus` directive/s.

Alternatively, if I try `{+pdf.fonts.text.size 10}`, this also leaves the chorus unchanged, but  `{+pdf.fonts.chorus.size 10}` will change that. This suggests that

1) New `pdf.fonts.chorus` config settings also exist, which correspond to the new `{chorus` directives.
2) `pdf.fonts.chorus` settings inherit from `pdf.fonts.text` just once, when processing the config, but are not re-defined if a song subsequently redefines the `text` settings, with directives or `+pdf.fonts.text`.

Might more intuitive behaviour (and continuity) be that default chorus styling mirrors/inherits any additional `text` styling within a song, after the configs have been processed?

One complicating factor is: if `fonts.chorus` have been set explicitly in config, should additional `{text` directives in song still affect chorus styling? Perhaps not, because separate `fonts.chorus` settings seems to imply a 'disconnection' from `text` settings.

**Comment by sciurius** [comment]
As it is implemented now, the chorus font is initialized to the text font when the song starts. From then on the two are independent. As you noticed, changing the text font no longer changes the appearance of the chorus, which breaks compatibility.

Would this be intuitive: There is a chorus font and a lyrics font, and {textsize/font/colour} implies chorus **and** lyrics? So

{chorussize 14}{lyricscolour blue} → chorus 14/black; lyrics 12/blue ?

{chorussize 14}{textcolour blue} → chorus 14/blue; lyrics 12/blue ?

**Comment by gwyndaf** [comment]
Yes, I think so, certainly given existing behaviour.

Do you think `{lyricscolor}` etc. are necessary, as that would be implied by `{textcolor}` in the absence of any `{chordcolor}` setting?

I wonder if that would duplicate functionality, and maybe be a bit confusing? I don't have a strong view, but guess each new directive should have a good reason.

**Comment by gwyndaf** [comment]
But, if you think it's necessary, maybe `{versecolor}` is clearer, since it wouldn't affect all lyrics.

Of course, there's then the bridge etc. but I think `lyrics` might imply all lyrics.

**Comment by sciurius** [comment]
With `lyrics` it is easy to explain that this is everything but the `chorus`. With `verse` you do, indeed, run into problems since there can be a `start_of_verse` (and `start_of_anything`, etc.).
Ultimately you would need a distinct config for each environment.

Let's see if we can do without. So there's only {chorusfont/size/colour}.

````
{textcolor: blue}
Basic song line in blue
{start_of_chorus}
Basic chorus line in blue due to {textcolour}
{end_of_chorus}
````

So far, so good.

````
{textcolor: blue}
{chordcolor: red}
Basic song line in blue
{start_of_chorus}
Basic chorus line in red due to {chordcolour}
{end_of_chorus}
````

Good. But:

````
{chordcolor: red}
{textcolor: blue}
Basic song line in blue
{start_of_chorus}
Basic chorus line in blue, {textcolour} overrides {chordcolour}
{end_of_chorus}
````

And to make it complex:

````
{textcolor: blue}
{chordcolor: red}
Basic song line in blue
{textcolor green}
Basic song line in green
{textcolour}
Basic song line in blue
{start_of_chorus}
Basic chorus line in ??? -- I think it should be red
{end_of_chorus}
````

**Comment by sciurius** [comment]
You can try this in _035.

**Comment by gwyndaf** [comment]
OK, I'll test _035 when you've pushed it to github.

Good point about repeated `{textcolor}`/`{choruscolor}` use. I suppose it's a question of how far it's sensible for `{choruscolor}` to track `{textcolor}`. My normal usage is once per song (along with line spacing) to fit a long song to one page. Very occasionally around specific text as a temporary `{textsize: 90%}`...`{textsize}` pair to squeeze long lines.

I'm aware that per-section configuration is on the roadmap for future development, so wondered if achieving bold chorus functionality without extra settings like `{lyricscolor}` might avoid getting locked into an approach that could limit future flexibility.

**Comment by gwyndaf** [comment]
Tested with _038, and looking good, with both test and (most) real song samples.

As far as I can see, any change with `{textfont: }`, `{textsize: }` or `{textcolor: }` is also reflected in corresponding chorus settings. Using `{textcolor}` to reset to previous seems to work ok, and be reflected in chorus setting.

However, `{textsize}` and `{textfont}` resets seem to throw up errors:
```
{textsize: 80%}
Long line that needs shrinking
{textsize}

{start_of_chorus}
Basic chorus line
{end_of_chorus}
```
gives errors:
```
Use of uninitialized value $size in multiplication (*) at /usr/local/share/perl/5.36.0/Text/Layout/PDFAPI2.pm line 356.
Use of uninitialized value $size in multiplication (*) at /usr/local/share/perl/5.36.0/Text/Layout/PDFAPI2.pm line 361.
Use of uninitialized value $size in multiplication (*) at /usr/local/share/perl/5.36.0/Text/Layout/PDFAPI2.pm line 362.
Use of uninitialized value in multiplication (*) at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/Output/PDF.pm line 2561.
PDF: Font chorus should have a size!
A font size is required at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/Output/PDF/Writer.pm line 204.
```
Similar, but with `{textfont: Helvetica}`...`{textfont}` gives
```
Can't use an undefined value as a HASH reference at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/Output/PDF.pm line 1372.

```

**Comment by sciurius** [comment]
Good catch. Both errors are the result of forgetting to correctly restore the properties for the chorus font.

There is (was) another cute case... 

````
Basic text (Times Roman, 12pt)
{textfont Helvetica 20}
Basic text (Helvetica, 20pt)
{textfont}
Basic text (Times Roman, 12pt)
{textsize 14}
Basic text (Times Roman, 14pt)
{textsize}
Basic text (Times Roman, 20pt!)
````

`{textfont Helvetica 20}` basically adds an extra operation, `{textsize 20}`. But `{textfont}` only restores the font. Since there is nothing stacked for the font it resets to the config values. But the saved value for the size is still on the stack. Setting a size and popping it reveals the stacked value.

_039 should fix all this.

**Comment by gwyndaf** [comment]
_039 looks good.

I did wonder if the dual (face/size) functionality of `{textfont}` might make things interesting!

**Comment by sciurius** [comment]
You can still confuse it with
````
Basic text (Times Roman, 12pt)
{textfont Helvetica 20}
{textsize 18}
Basic text (Helvetica, 18pt)
{textfont}
Basic text (Times Roman, 12pt)
{textsize 14}
Basic text (Times Roman, 14pt)
{textsize}
Basic text (Times Roman, 20pt!)
````
