### ISSUE TITLE
abc2svg testing with QuickJS

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#313]
Please excuse adding this here, as it seems more appropriate than the user discussion group.

As reported, success with `chordproabc.js` and `qjs` executable in `res/abc` folder and abc2svg files in `res/abc/abc2svg` folder, when tested on individual songs.

However interesting messages (and missing ABC output) when batch processing songbooks:
```
ABC: ReferenceError: could not load 'toxhtml.js/abc2svg-1.js'
ABC:     at loadScript (native)
ABC:     at load (/media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js:19)
ABC:     at <eval> (/media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js:69)
ABC: 
ABC: =100=> /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//qjs --std /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//abc2svg/ toxhtml.js /tmp/inyEH2q_XS/tmp3.abc
Error in ABC embedding (ret = 0x100)
```
As far as I can tell, this occurs for each song containing ABC sections, and no ABC output is included in those songs.

This is with `delegates.abc.handler` set to default of `abc2svg`.  If I set it to `abc2svg_qjs`, the errors go away and expected ABC output is included on page.

Not sure if it's a major issue, as the config setting offers a solution, but it might be useful information.

**Comment by sciurius** [comment]
Does 'batch processing' mean `chordpro song1 song2 ...` or `chordpro song1; chordpro song2;...`?

Assuming you're on linux, what is the output of
````
which abc2svg
which node
which qjs
````

**Comment by gwyndaf** [comment]
Ah, sorry: no, simply using `--filelist` to process a file that lists songs.

I think I have one fewer sets of messages than scores in the collection, e.g. where 3 songs in the book have abc scores, I get 2 sets of messages. Perhaps it's something to do with 'resetting' something between new songs.

`which abc2svg` gives nothing, as expected: the executables in the Linux package are `abcnode` and `abcqjs` (both in `/usr/bin`).
`which node` gives `/usr/bin/node`.
`which qjs` gives `/usr/bin/qjs`.

I also tried uninstalling the `quickjs` package (leaving only the executable copied to ChordPro), but that doesn't seem to make a difference.

**Comment by sciurius** [comment]
Thanks, I'll try to reproduce this tomorrow.

**Comment by sciurius** [comment]
Can you add `--def debug.abc=1` and share the output?

**Comment by gwyndaf** [comment]
```
%%scale 0.55
%%pagewidth 446.6px
%%leftmargin 0cm
%%rightmargin 0cm
%%topspace 0
%%titlespace 0
%%musicspace 0
%%composerspace 0
%%infospace 0
%%textspace 0
%%leftmargin 0cm
%%rightmargin 0cm
%%staffsep 0
%%textfont pdf.fonts.text
%%gchordfont pdf.fonts.chord
X:1
K:D
M:4/4
L:1/8
("D"A8 | A4) ABcd | "Bm"e2 d(B B4 | B4) afdB | ("Em"G8 | G4) bgec | ("A"A8 | A8) |
+ /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//qjs --std /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js /tmp/f0_A4lVr1Z/tmp1.out /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//abc2svg/ toxhtml.js /tmp/f0_A4lVr1Z/tmp1.abc
script = /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js
output = /tmp/f0_A4lVr1Z/tmp1.out
path   = /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//abc2svg//
SVG: 81 lines (raw)
SVG: 58 lines (33015 bytes)
%%scale 0.49
%%pagewidth 446.6px
%%leftmargin 0cm
%%rightmargin 0cm
%%transpose 10
%%topspace 0
%%titlespace 0
%%musicspace 0
%%composerspace 0
%%infospace 0
%%textspace 0
%%leftmargin 0cm
%%rightmargin 0cm
%%staffsep 0
%%textfont pdf.fonts.text
%%gchordfont pdf.fonts.chord
X:1
K:A octave=-1
M:6/8
L:1/8
| "A"c3 B3 | d3 c3 | "Bm"d3 c3 | e3 d3 | "E"A3 G3 | F3 G3 | "A"c3 B3 | d3 c3 |
| "D"f3 e3 | =g3 f3 | "Em"e3 ^d3 | f3 e3 | "A"d3 c3 | B3 c3 | "D"f3 e3 | =g3 f3 |

+ /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//qjs --std /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//abc2svg/ toxhtml.js /tmp/f0_A4lVr1Z/tmp2.abc
ABC: ReferenceError: could not load 'toxhtml.js/abc2svg-1.js'
ABC:     at loadScript (native)
ABC:     at load (/media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js:19)
ABC:     at <eval> (/media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js:69)
ABC: 
ABC: =100=> /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//qjs --std /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//abc2svg/ toxhtml.js /tmp/f0_A4lVr1Z/tmp2.abc
Error in ABC embedding (ret = 0x100)
%%scale 0.6
%%pagewidth 446.6px
%%leftmargin 0cm
%%rightmargin 0cm
%%topspace 0
%%titlespace 0
%%musicspace 0
%%composerspace 0
%%infospace 0
%%textspace 0
%%leftmargin 0cm
%%rightmargin 0cm
%%staffsep 0
%%textfont pdf.fonts.text
%%gchordfont pdf.fonts.chord
X:1
M:4/4
L:1/8
K:D
A | "D"dc Bc"G"d2 B2 | "D6"A2 B2"D"F2 A2 |"G"BA G2"D"d2 cd | "A"A6 GF |
 "G6"E2 B2"D"A2 G2 | "A"A>G FG"D"A2 dB | "G"G2 FG"A"A2 A2 | "Dsus2"D8 | D4 |
+ /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//qjs --std /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//abc2svg/ toxhtml.js /tmp/f0_A4lVr1Z/tmp3.abc
ABC: ReferenceError: could not load 'toxhtml.js/abc2svg-1.js'
ABC:     at loadScript (native)
ABC:     at load (/media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js:19)
ABC:     at <eval> (/media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js:69)
ABC: 
ABC: =100=> /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//qjs --std /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//chordproabc.js /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/res/abc//abc2svg/ toxhtml.js /tmp/f0_A4lVr1Z/tmp3.abc
Error in ABC embedding (ret = 0x100)
```

**Comment by sciurius** [comment]
Can you retry the above with the attached ABC module ?
[ABC.pm.txt](https://github.com/ChordPro/chordpro/files/12681676/ABC.pm.txt)

**Comment by gwyndaf** [comment]
That seems to work nicely.

Tested with `delegates.handler.abc` values of default, and explicit `abc2svg` and `abc2svg_qjs`.

**Comment by sciurius** [comment]
Interesting... The only change was an added debugging statement.

Anyway, I restructured the ABC delegate to use:
1. A program `abc2svg` in PATH, that writes the SVG to standard out, or
2. The QuickJS program, either in PATH or in our `abc` resource directory. In this case, packaged abc2svg files are used.

Using nodeJS (`npm`, `npx`) turned out to have some complications since it was not possible to stop it from using foreign javascript files.

**Comment by sciurius** [comment]
Please try 6.030_001 at your convenience.

**Comment by gwyndaf** [comment]
Ah, maybe version confusion. I was testing on dev version _039, with manual addition of internal abc2svg handling: `qjs` and `abc2svg` files in `res/abc`, and your revised `ABC.pm` delegate.

With the new release version 6.030_001, I'm back to `Error in ABC embedding: need 'abc2svg' tool.` messages, with my external abc2svg support disabled (tested with both default and `abc2svg_qjs` handlers). That seems to be as expected, since I see no `res/abc` folder in the latest release installation.

If I enable external abc2svg support (just an `abc2svg` script than runs `abcnode`), release version seems to work ok. As far as I can see, Debian installation provides no `abc2svg` executable, and this is an easy workaround, but probably still an unnecessary complication for many users.

If I modify my `abc2svg` script to use `abcqjs` instead, I get ChordPro errors:
```
ABC: Cannot read file toxhtml.js
ABC:   ReferenceError: could not load '/usr/bin/toxhtml.js'
```

I notice that the ChordPro abc2svg package includes a file `toxhtml.js` file, but my external installation has `tohtml.js`. If ChordPro expects to find `toxhtml.js` in my external installation, I can see that it won't. If I copy `/usr/bin/tohtml.js` to `/usr/bin/toxhtml.js`, works with no problem.

I'm now wondering if my abc2svg installation is out of date. Although I downloaded the `abc2svg_1.22.9-1_all.deb` Debian installer from the recommended abcplus.sourceforge link, perhaps it's not the latest. I'll try to update my abc2svg installation manually...

**Comment by sciurius** [comment]
For this reason I now restrict the tools to either an independent `abc2svg` tool (that does **not** use `res/abc`), and QuickJS.

Are you sure you do not have `res/abc`? There should be a file `res/abc/chordproabc.js` . 
And you still need to unpack the `abc2svg_qjs.tar.gz` in `res/abc`.

**Comment by gwyndaf** [comment]
My mistake. Not only was I looking in the installed release folder, but I'd also got an older version with ChordPro still in `../perl/5.36.0/App/Music/ChordPro`, so I just did a big tidy up.

It now seems to be working nicely, using dev version 6.030_001, plus abc2svg files added into `res/abc/abc2svg`, with external (installed) QuickJS `qjs` executable.

**Comment by sciurius** [comment]
That is good to hear!
