### ISSUE TITLE
Chordpro 6.030.001 fails with Perl 5.34

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#314]
Perl v5.36.0 required--this is only v5.34.0, stopped at /usr/local/share/perl/5.34.0/ChordPro/Delegate/ABC.pm line 3.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.34.0/ChordPro/Delegate/ABC.pm line 3.
Compilation failed in require at (eval 60) line 1.

I am on Ubuntu 20.04.

**Comment by sciurius** [comment]
Sorry... Please try again ☺.

**Comment by timmbo9** [comment]
new message:
The signatures feature is experimental at /usr/local/share/perl/5.34.0/ChordPro/Delegate/ABC.pm line 28.
The signatures feature is experimental at /usr/local/share/perl/5.34.0/ChordPro/Delegate/ABC.pm line 36.
The signatures feature is experimental at /usr/local/share/perl/5.34.0/ChordPro/Delegate/ABC.pm line 72.
The signatures feature is experimental at /usr/local/share/perl/5.34.0/ChordPro/Delegate/ABC.pm line 102.
The signatures feature is experimental at /usr/local/share/perl/5.34.0/ChordPro/Delegate/ABC.pm line 303.
ABC: Please remove handler "abc2image" from your ABC delegates config at /usr/local/share/perl/5.34.0/ChordPro/Output/PDF.pm line 1129.

I went to my  config.json and commented out line with abchandler and then got:
ReferenceError: could not load '/usr/local/share/perl/5.34.0/ChordPro/res/abc/abc2svg/abc2svg-1.js'
    at loadScript (native)
    at load (/usr/local/share/perl/5.34.0/ChordPro/res/abc/chordproabc.js:19)
    at <eval> (/usr/local/share/perl/5.34.0/ChordPro/res/abc/chordproabc.js:69)

=100=> /usr/local/bin/qjs --std /usr/local/share/perl/5.34.0/ChordPro/res/abc/chordproabc.js /usr/local/share/perl/5.34.0/ChordPro/res/abc/abc2svg /tmp/wRE0Z_PDEK/tmp1.out /tmp/wRE0Z_PDEK/tmp1.abc
Error in ABC embedding (ret = 0x100)

i have latest abc2svg  from chiselapp , it is in my path. I run from script abctopdf for my abc files.

**Comment by sciurius** [comment]
> The signatures feature is experimental at /usr/local/share/perl/5.34.0/ChordPro/Delegate/ABC.pm

I'll fix that.

> ReferenceError: could not load '/usr/local/share/perl/5.34.0/ChordPro/res/abc/abc2svg/abc2svg-1.js'

This means that ChordPro cannot find a `abc2svg` executable program or script in PATH.

What is the result from
````
which abv2svg
````

**Comment by timmbo9** [comment]
there is no abc2svg executable. That is the package name. I have abcqjs , abcnode, abcjsc, abctopdf, abc2odt. Perhaps I do not understand  how to designate the handler in my config.

**Comment by sciurius** [comment]
There are two things you can do (I really should write this down in the docs but it is still a work-in-progress).

Preferred is to install Quickjs (so that the `qjs` command is available through `PATH`). Also, you need to download 
https://chordpro.org/dl/abc2svg_qjs.tar.gz
and unpack it in the `ChordPro/res/abc` directory.

Alternatively, if you want the chiselapp kit, you can create a simple script `abc2svg` that executes the desired abcXXX script. The script should take one argument, the ABC file to process, and write the SVG output to standard output. And it should be available through `PATH`.

**Comment by sciurius** [comment]
See https://groups.io/g/ChordPro/message/1854

**Comment by timmbo9** [comment]
with my abc2svg script, as per message 1854 above I get: Error in ABC embedding (ret = 0x100). 
If I make abc2svg script non-executable then
With abc2svg_qjs archive unpacked in ChordPro/res/abc/abc2svg I finally get correct results.

**Comment by sciurius** [comment]
Ah, I see. Please pull the dev branch and retry.

**Comment by timmbo9** [comment]
Closer.  It processes with no error messages but the resultant score has only stems and beams. No notes or clef or time signature.

**Comment by sciurius** [comment]
Can you run with `--def debug.abc=2 --def debug.images=1` ans share the log.
Also, in the log you can see it generates some /tmp files (for abc and svg), can you include these as well?

**Comment by sciurius** [comment]
Good (with log file I meant the screen output).
Can you share the song and the config?

**Comment by timmbo9** [comment]
[others.zip](https://github.com/ChordPro/chordpro/files/12702074/others.zip)
Being prooactive and giving you a few other pieces that might help.

**Comment by timmbo9** [comment]
Both abc2svg and chordpro seem to work better without using Bravura as a musicfont.  My results with current development versions of both.  I will leave %%musicfont entry empty.

**Comment by timmbo9** [comment]
thanks

**Comment by timmbo9** [comment]
Thanks

**Comment by sciurius** [comment]
ChordPro should not have problem using Bravura. The only requirement is a registration in the config:

````
	"fontconfig" : {
            ...
	    "bravura" : {
		"" : { "file" : "...wherever the font resides..." }
	    },
            ...

````

There was a buglet that caused lookup failure when the font name is mixed case, this has been fixed in 6.030_003.

**Comment by timmbo9** [comment]
That works nicely. I would not have ever fathomed out that config listing on my own.

**Comment by sciurius** [comment]
There are some docs now. Comments welcome.
https://www.chordpro.org/beta/chordpro-configuration-delegates/

**Comment by timmbo9** [comment]
These docs look good.  I just bookmarked beta/home, didn't know about that.  Thanks
