### ISSUE TITLE
uninitialized value with 6.03.014

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#317]
trying to process a source file and get a pile of these messages:
Use of uninitialized value in string eq at /usr/local/share/perl/5.34.0/ChordPro/Output/PDF/Writer.pm line 170.

**Comment by sciurius** [comment]
Can you share an example song + config?

**Comment by timmbo9** [comment]
https://www.dropbox.com/scl/fi/wj8fvi1yeh3vz8ykhd2ux/uninit.zip?rlkey=i12pmeg9pugxqrjbbugexnivc&dl=0

**Comment by sciurius** [comment]
Thanks.
ChordPro depends heavily on the newest features of the Text::Layout module. I've tried to work around but that is apparently not complete.
I have uploaded Text-Layout-0.031_007.tar.gz to CPAN. Can you try install it? E.g.

    cpan J/JV/JV/Text-Layout-0.031_007.tar.gz

You make nice looking songs! A couple of hints.
* Keep your config small. Include only the changes.  
The config you sent is a copy of the complete config of an older version of ChordPro. 
* Use the `"fontlib"` to locate fonts and avoid absolute filenames. Absolute filenames make it harder for me to reproduce isses.
* You use `"description"` **and** `"file"`. Be aware that `"description"` overrules `"file"`.  

I hope this helps a bit.
Usually it is best to use filenames so you can be sure you get the right fonts.

**Comment by timmbo9** [comment]
I tried to install but get this:
allow_installing_module_downgrades: JV/Text-Layout-0.031_007.tar.gz (called for J/JV/JV/Text-Layout-0.031_007.tar.gz) contains downgrading module(s) (e.g. 'Text/Layout.pm' would downgrade installed '0.031' to 'undef'). Do you want to allow installing it? [no] no
Testing/Installation stopped: allow_installing_module_downgrades: JV/Text-Layout-0.031_007.tar.gz (called for J/JV/JV/Text-Layout-0.031_007.tar.gz) contains downgrading module(s) (e.g. 'Text/Layout.pm' would downgrade installed '0.031' to 'undef')
  JV/Text-Layout-0.031_007.tar.gz
  [testing] -- NOT OK

tried to force it, still stops.

**Comment by sciurius** [comment]
Can you try 6.030_015 instead? It is tagged `D6.030_015` in git.

**Comment by sciurius** [comment]
Even better: 6.030_016.

**Comment by timmbo9** [comment]
_016 works just fine. 
Thanks for the tip on the config file, I'll start trimming it back.
