### ISSUE TITLE
In {define}, diagram colour doesn't change colour of diagram_base font for base fret

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#318]
```
{define: Dmaj7 base-fret 7 frets x x 1 1 1 3 fingers 0 0 1 1 1 3 diagram #6666FF}
```
Gives me
![Screenshot from 2023-11-09 20-27-15](https://github.com/ChordPro/chordpro/assets/1415754/d142961d-05c4-4be6-9021-64f1e284d835)

I think I'd expect the base fret number to follow the diagram colour, just like the chord name above it.

I discovered the `pdf.fonts.diagram_base.color` config setting, which is reflected in output. However, I'd expect that to be overwritten by the value of `{define... diagram}` if specified in a song, in the same way that `pdf.fonts.diagram.color` is.

A maybe related query or issue: `fonts.diagram_base` size seems to get ignored, whether specified with `size` value, or as part of `description`.

**Comment by sciurius** [comment]
This little snippet:
````
{t Diagram Base}
{define: Dmaj7 base-fret 7 frets x x 1 1 1 3 fingers 0 0 1 1 1 3 diagram #6666FF}
[A]hi [Dmaj7]Hello [Bm]Bye
````
gives me
![scrot20231109222124](https://github.com/ChordPro/chordpro/assets/1118804/9f51734f-ea1c-4069-85f3-eff81e86efcb)

So there must be something in your config that causes this.

> `fonts.diagram_base` size seems to get ignored

Yes, that is intentional.

**Comment by gwyndaf** [comment]
Thanks Johan.

I just updated Text::Layout to 0.032, and that seems to have fixed it.
