### ISSUE TITLE
Increase in vertical spacing between chord diagrams with 6.030_021

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#319]
Not sure whether this is an issue, or an intentional change of behaviour...

With dev version 6.030_021 I'm suddenly getting much more vertical space between chord diagrams, as per these release and git examples. They're an extreme example, but similar behaviour with regular songs.
[zzz1_chord_table (ukulele C).pdf](https://github.com/ChordPro/chordpro/files/13318568/zzz1_chord_table.ukulele.C.pdf)
[zzz1_chord_table (ukulele C) git.pdf](https://github.com/ChordPro/chordpro/files/13318569/zzz1_chord_table.ukulele.C.git.pdf)

Horizontal spacing appears to be unchanged.

The source file does include some manual setting of `{pdf.diagrams.vspace}`, but latest git version seems to interpret them differently.
[zzz1_chord_table.cho.txt](https://github.com/ChordPro/chordpro/files/13318641/zzz1_chord_table.cho.txt)

From a bit of experimentation, a `vspace` setting of `0.2` with git version seems to produce the same output as a value of `2.7` with the release version. That may or may not offer some insight.

**Comment by sciurius** [comment]
Interesting...
Can I have the config?

**Comment by gwyndaf** [comment]
Sure. My config setup's a bit complex, with multiple files (for flexibility), but this the aggregated one from `--print-final-config`.

They're slightly different from release and dev versions - I don't think the differences are significant, but both are here for completeness:
[config_dev.txt](https://github.com/ChordPro/chordpro/files/13322507/config_dev.txt)
[config_release.txt](https://github.com/ChordPro/chordpro/files/13322508/config_release.txt)

I couldn't think of anything except `diagrams.vspace` that might affect this, but you might spot something.

**Comment by sciurius** [comment]
I cannot precisely reproduce your layout but there was, indeed, a mistake in the calculation of the vertical spacing.
Can you try 6.030_022?

**Comment by gwyndaf** [comment]
Sorry, it's quite a complex layout and config, and uses a few additional fonts. I should probably have switched to a simpler config for testing purposes.

In any case, 6.030_022 seems to resume expected behaviour :)

**Comment by sciurius** [comment]
Great!

> it's quite a complex layout and config,

I hope you can benefit from some of the new facilities to make complex situations better maintainable. For example:
````
##include: src="filename"
````
This inserts the contents of the given filename as source lines. Useful for recurring pieces of text, or series of defines, etc. Stationary items?
And yes, you can do:
````
##include-ukulele: src="ukulelespecificfile"
````

Also, see attachment.

[De_Luister_Van_De_Maan.cho.txt](https://github.com/ChordPro/chordpro/files/13323406/De_Luister_Van_De_Maan.cho.txt)
