### ISSUE TITLE
Option render chord notations with superscripts?

### ISSUE THREAD

**Issue by JohannesWiesner** [ChordPro/chordpro#320]
Hi! Does ChordPro offer the possibility to render Chords with superscripts? Something like:

C <sup>maj6</sup> instead of Cmaj6?

**Comment by JohannesWiesner** [comment]
Ah I saw there's a discussion on that here:

https://groups.io/g/ChordPro/topic/rfd_formatting_of_chords/71726073

but the thread is quite old. Was this ever implemented? There's a proposed solution that uses the .config file but it seems you have to do this for every posssible chord?

```json
    "chords" : [
	{ "name"    : "A7",
	  "base"    :  1,
	  "frets"   : [ -1,0,2,0,2,0 ],
	  "fingers" : [  0,0,1,0,3,0 ],
	  "display" : "A<sup>7</sup>"
	},
    ],
```

**Comment by sciurius** [comment]
Yes, this (and more) has all be implemented some time ago.
See e.g. https://www.chordpro.org/chordpro/chordpro-configuration-format-strings/#chord-format-string
and https://www.chordpro.org/chordpro/chordpro-configuration-generic/ (search for `chord-format`).

**Comment by JohannesWiesner** [comment]
Ah perfect, thanks so much!

**Comment by JohannesWiesner** [comment]
Sorry, I struggle with the implementation. What exactly do I have to put in the config file to modify the appearance? 

In the [default config file](https://www.chordpro.org/chordpro/pub/chordpro_json.txt) there's this section:


```json
      // Format to show chord names. May contain markup.
      // "chord-format" : "%{root}%{qual|%{}}%{ext|<sup>%{}</sup>}%{bass|/%{}}",
    "chord-formats" : {
        "common" :    "%{root|%{}%{qual|%{}}%{ext|%{}}%{bass|/%{}}|%{name}}",
        "roman" :     "%{root|%{}%{qual|<sup>%{}</sup>}%{ext|<sup>%{}</sup>}%{bass|/<sub>%{}</sub>}|%{name}}",
        "nashville" : "%{root|%{}%{qual|<sup>%{}</sup>}%{ext|<sup>%{}</sup>}%{bass|/<sub>%{}</sub>}|%{name}}",
    },
```

what's the difference between "chord_format" and the outcommented "chord_formats"? It's seem that with the latter I can somehow choose between "common", "roman" and "nashville notation"?

**Comment by sciurius** [comment]
`chord-format` is a left over from earlier times. `chord-formats` is the right one to use. In your case,
````
"chord-formats" : {
        "common" :    "%{root|%{}%{qual|%{}}%{ext|<sup>%{}</sup>}%{bass|/%{}}|%{name}}",
        ...
    },
````
The relevant part is `%{ext|<sup>%{}</sup>}` which means: if the chord has an extension (i.e. `maj7`), show it as a superscript (i.e. `<sup>maj7</sup>`).

I hope this will get you going.

**Comment by JohannesWiesner** [comment]
> `chord-format` is a left over from earlier times. `chord-formats` is the right one to use. In your case,

Ah okay, good to know!

I am currently trying out this config file 

```json
{
  "pdf": {
    "chorus": {
      "indent": 12,
      "bar": {
        "width": 0
      }
    },
    "fontdir": [
      "/fontdir"
    ],
    "fontconfig": {
      "serif": {
        "": "OpenSans-Regular.ttf",
        "bold": "OpenSans-Bold.ttf",
        "italic": "OpenSans-Italic.ttf",
        "bolditalic": "OpenSans-BoldItalic.ttf"
      }
    },
    "fonts": {
      "title": {
        "description": "serif bold 20"
      },
      "text": {
        "description": "serif 12"
      },
      "chord": {
        "description": "serif italic 8"
      }
    }
  },

  "chord-formats" : {
        "common" :    "%{root|%{}%{qual|%{}}%{ext|<sup>%{}</sup>}%{bass|/%{}}|%{name}}",
        "roman" :     "%{root|%{}%{qual|<sup>%{}</sup>}%{ext|<sup>%{}</sup>}%{bass|/<sub>%{}</sub>}|%{name}}",
        "nashville" : "%{root|%{}%{qual|<sup>%{}</sup>}%{ext|<sup>%{}</sup>}%{bass|/<sub>%{}</sub>}|%{name}}"
    }

}

```

with the docker version `chordpro/chordpro:v6.020.0`. But I get:


`Config error: unknown item chord-formats`

**Comment by sciurius** [comment]
`chord-formats` was introduced in 6.030. Try docker version `chordpro/chordpro:v6.030.0` instead

**Comment by JohannesWiesner** [comment]
Solved it, thanks!
