### ISSUE TITLE
ABC delegate causes output failure

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#322]
## Describe the bug
see err,txt. Fails to create pdf output.
[chordpro.json](https://github.com/ChordPro/chordpro/files/13416899/chordpro.json)
[err.txt](https://github.com/ChordPro/chordpro/files/13416900/err.txt)
[chordpro.json](https://github.com/ChordPro/chordpro/files/13416916/chordpro.json)

### To Reproduce
Steps to reproduce the behavior: chordpro --config=./chordpro.json --output=test.pdf test.pro
1. 
2. 
3. 
4. 

### Expected behavior
see test.pro

## System information
 - OS: Ubuntu 22.04, latest abc2svg from chiselapp, chordpro 6.030.032
 - Where did you get ChordPro from?  github

 - ChordPro version: 
 - Perl version: v5.34.0

**Comment by sciurius** [comment]
Is there an `abc2svg` script accessible via PATH? I seem to recall it is nowadays called `abcnode`. 
I have a symlink abc2svg -> abcnode.

**Comment by timmbo9** [comment]
i have ~/bin/abc2svg/abcnode in my path.following your suggestion I added a symlink to abcnode as~/.local/bin/abc2svg.  output now reads:Error in ABC embedding (return=0x7f00)Can't call method "width"  on unbessed reference in PDF.pm line 1850 ?TimmOn Nov 20, 2023, at 11:44 AM, Johan Vromans ***@***.***> wrote:﻿
Is there an abc2svg script accessible via PATH? I seem to recall it is nowadays called abcnode.
I have a symlink abc2svg -> abcnode.

**Comment by sciurius** [comment]
Does `abcnode some.abc > some.html` produce good output (view in browser)?
Does `abc2svg some.abc > some.html` produce good output (view in browser)?

**Comment by sciurius** [comment]
What is the log when you add `--def debug.abc=2` to the command line?

**Comment by timmbo9** [comment]
no success with either . command runs, no pdf.error message:  line 13:node: command not foundTimmOn Nov 20, 2023, at 1:10 PM, Johan Vromans ***@***.***> wrote:﻿
Does abcnode some.abc > some.html produce good output (view in browser)?
Does abc2svg some.abc > some.html produce good output (view in browser)?

**Comment by timmbo9** [comment]
chordpro --config=./chordpro.json --def debug.abc=2 --output=./test.pdf 
./test.pro >  debug.out 2>&1

debug.out:
ABC: abc2svg (tool = <undef>)
%%pagescale .75
%%staffscale 1.0
%%stretchstaff 0
%%stretchlast .45
%%pagewidth 587px
%%topspace 0
%%titlespace 0
%%musicspace 0
%%composerspace 0
%%infospace 0
%%textspace 0
%%leftmargin 0cm
%%rightmargin 0cm
%%stretchstaff 1
%%stretchlast 0
%%trimsvg 1
%%staffsep 0
%%textfont pdf.fonts.text
%%gchordfont pdf.fonts.chord
X:1
M:4/4
L:1/8
K:G octave=-1
G,2 G2 A,>B, (3DEG|

+ /home/timm/.local/bin/abc2svg /tmp/WXKCtQsoDa/tmp1.abc
Error in ABC embedding (ret = 0x7f00)
Can't call method "width" on unblessed reference at 
/usr/local/share/perl/5.34.0/ChordPro/Output/PDF.pm line 1850.



On Mon, 20 Nov 2023 10:12:01 -0800
  Johan Vromans ***@***.***> wrote:
> What is the log when you add `--def debug.abc=2` to the 
>command line?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/ChordPro/chordpro/issues/322#issuecomment-1819571498
> You are receiving this because you authored the thread.
> 
> Message ID: 
>***@***.***>

Timm Reasbeck

**Comment by sciurius** [comment]
> error message:  line 13:node: command not found

So the script fails because it cannot find `node`.
Did you install `node`, and it is accessable via PATH?

**Comment by timmbo9** [comment]
I am running on a recently new OS installation. I have a functioning installation of abc2svg from source using abcqjs. 
I have a functioning chordpro installation from source, or so I thought. Installing Ubuntu package node-core did fix the issue.
Thank you. 

I just wonder where I missed the requirement for node in the build and install process ? 
My old setup had node because that was used in my first foray into abc2svg  coming from abcm2ps.  
I finally ended up using abc2svg with abcqjs and QuickJS. 
Again, thank you for your patience in pointing out the answer which I could not see.
