### ISSUE TITLE
ABC.pm : observations

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#324]
1:
in abc2svg the file default.abc is sought out in the current directory and in the directories listed in environment variable $ABCPATH. 
Chordpro's use of abc2svg does not seem to utilize  $ABCPATH.

2:
Johan recently advised me to create a link called abc2svg pointing to abcnode in order to get ABC delegate working with node. Curiously within the text of ABC.pm there is reference to NOT using node.

3:
My usual use of abc2svg utilizes qjs so I changed my handler in chordpro to abc2svg_qjs. After eliminating the prior abcnode<>abc2svg link I  linked my installed abc2svg directory to a link in Chordpro/res/abc called abc2svg. This allowed ABC.pm to verify the existence of abc2svg/tohtml.js and not bail out.
ABC.pm looks for an executable called qjs on the system path but it restricts search for abc2svg resources to its own res/abc directory. It verifies abc2svg by looking for tohtml.js, but in actuality qjs uses an executable script called abcqjs. If ABC.pm used the same process to find abcqjs as it did to find qjs ($qjs = CP->findexe("qjs");) then the artifice of creating the link res/abc/abc2svg could possibly be eliminated and abc delegate could work out of the box with a local installation of abc2svg.

I am grateful that these two programs can work together as they do. 
I make these observations as a user and not as a programmer. 
My suggestion may not be at all practical or workable.

Thank you Johan for all your dedicated work.

**Comment by sciurius** [comment]
Well, thank **you** Timm for your valuable investigations.

The ChordPro - ABC facility still has some rough edges but it is getting better.

Basically, there are two ways ChordPro can do ABC. First is a script `abc2svg` that must be executable in PATH. It is called with a single argument, a file with ABC data, and must produce the resultant SVG on standard output. There is no script `abc2svg` in the official abc2svg kit (from Jean-François Moine) so the user must install the abc2svg kit and create the `abc2svg` script. This can be as easy as creating a symlink, as we've discussed.

The handling of environment variable `ABCPATH` is done by the calling script, i.e., `abc2svg`. If this is a symlink to `abcnode` then lookup of `default.abc` works as expected (I verified).

The other way is using QuickJS `qjs`. This requires that specially adapted abc2svg files are included in the ChordPro resource directory. This also uses a `default.abc` in the current directory but does not use `ABCPATH`.
(Personally I find it a design flaw that it is not possible to prevent abc2svg from using whatever `default.abc` it finds.) Also note that for ChordPro GUI there is no 'current directory', or it may be another directory than you expect.

Why not, as you state in point 3, use an out of the box install of abc2svg. There are two reasons. First is that the installed abc2svg may be too old. As you may have seen on the ABC list Jean-François made some urgently needed fixes that are not yet part of an official install. The other reason is that 'writing the SVG to standard output' breaks the GUI on Windows. My solution is to include a version of the abc2svg kit that is known to work, and use a special call script. The installers for Windows and MacOS have complete support for ABC embedded. For the CPAN installs I haven't worked out a satisfactory approach.

But, while on the topic, let's get constructive. In the case of an `abc2svg` script everything works as expected but it is the responsibility of the user to make sure the right tools (and desired `default.abc`) are installed.

In the embedded case it is ChordPro responsibility to provide the files and tools. What would you want ChordPro to do with `default.abc` and `ABCPATH`? As Jean-François mentioned on the list you can also use `%%abc-include` in your ABC data, or in the delegate preamble. Search for a `default.abc` and include its contents in the preamble?
Where would you use the `default.abc` for?

**Comment by timmbo9** [comment]
I knew there was no default in the current directory and I could tell the default.abc in ABCPATH was not being used.  When embedding abc in chordpro I personally do not require the tweaks I use in my abc files with my primary default.abc, so I do not have need of a default.abc in chordpro.  As you and Jean-François have pointed out there are always other ways to achieve similar results.  I am glad to have that latitude in use and I am grateful to have your your feedback and direction.  Thank you for explaining things to me.
