### ISSUE TITLE
Feature request: ability to exclude song title from TOC

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#326]
Quite a minor suggestion, but might be useful if simple to develop.

Perhaps `{sorttitle:}` with a null value could exclude a song title from the Contents page/s?

I don't think a null `sorttitle` currently has any function, so perhaps that's a way to add functionality without needing any new directive.

There might also be implications for other 'song lists', such as PDF outlines and CSV export, and I guess maybe it should also be excluded from those for consistency, but the implications might need more thinking through.

__Rationale/use case__
At the end of my songbook, I provide an appendix of chord diagrams for the current instrument, derived from the instrument config.

It occupies two pages, but my 'inventive' approach means I need to use `{new_song}` to start the 2nd page (not `{new_page}`).

However, as it's just an appendix, I want it to occupy only a single entry in the TOC, however many pages/songs it includes.

I can achieve that visually by setting a blank `{title: }` for the second 'song'. However, that still produces an empty TOC entry, but I know it's there because it still hyperlinks to the 2nd appendix page.

In this instance, that's not a huge problem, because it's sorted last, so the blank entry comes at the end of the TOC. It would be a more obvious gap if it fell in the middle of the TOC. However, it does occupy page space, which means a new TOC page would get created unnecessarily (with no visible content), if the blank entry falls right at the end of a full page.

It's an approach that maybe has wider potential, e.g. several versions of the same song on successive pages, but listed only once in the TOC/outlines. And it means songs can have a proper `{title}`, even if they're excluded from TOC.

It's not at all pressing, but seems an idea worth posting for consideration.

**Comment by sciurius** [comment]
Good points. (Ab)using `{sorttitle}` is nifty, I'll run some experiments tomorrow.
Slightly related, there has been a request some time ago for a way to get multiple songs on a page i.e., with real title/subtitle but no new page. What do you think?

**Comment by gwyndaf** [comment]
The idea of multiple songs on one page is a good one. I could imagine some simple folk songs being quite short, so having several on one page is a good use of space.

I guess each song would need a `{title}` to ensure they're all listed on the Contents page. Maybe provision for `{sorttitle}` too. Everything else that comes after the new title, like `{subtitle}`, `{key}`, `{tempo}`, would simply be standard metadata as for any new song, but I don't think they have any functional role.

Some implications that I see:

**Display implications**
I guess each new song would need a 'header bar' part-way down the PDF page, with the same sort of information as is currently shown in the page header for a new song (`formats.title`). That could probably use the existing settings for `title` and `subtitle` lines, so maybe no change needed there.

**Layout implications**
_How much space to allow above a header bar after the previous song?_ Three thoughts:

1) None, so the header bar simply occupies `pdf.headspace` and could fall immediately after the previous song, unless user adds space manually. That might need automatic trimming of blank top/bottom lines of a song to be suppressed, so maybe not ideal.
2) Space between first song and second song header bar is `margintop - headspace`, so space above header bar would be same as gap between page top and header. That seems better, but space might be too much.
3) Add a new layout value for custom space above header bar, something like `marginsong`.

_Multiple columns will be an interesting question._ With a two-column page, the sensible behaviour would be for each song to flow across two columns, below the relevant header bar. Otherwise, the page could be meaningless or confusing. Possibly not something to attempt at this stage? On the other hand, it could maybe be solved with multiple 'sub-pages' (one per song), each topped with a header bar, and within which columns could flow sensibly. That might need a big overhaul, though.

**In operation**
I see three possible approaches that might be worth considering:

* Change functionality of `{new_song}` so that it _doesn't_ force a new page. That might break some users' song collections, if they have many songs in a single file. So probably not ideal.
* Change functionality of `{title}` so it also implies a new song, but doesn't force a page break. This seems a useful approach without needing new directives. Might need to ensure that `{new_song}` followed by `{title}` doesn't somehow get treated as two songs.
* Add a new directive, like `{new_song_same_page}`, but a less clumsy name! This is probably clearer and more explicit, but adds another directive, when it might not be strictly necessary.

_Should ChordPro intelligently fit multiple songs to pages?_ For instance, if I have a file of 12 songs, each starting with a new `{title}` or `{new_song_same_page}` directive, should ChordPro try to fit whole songs to pages, as tightly as possible? Probably not, and maybe simpler that it just flows the 12 songs continuously over as many pages as they require, with the user option to add `{new_page}` or `{new_song}` to force pagination.

**Interactive navigation (contents and PDF outlines)**
So, if three songs on one page are all listed in the Contents, should clicking on the Song 2 contents (or outline) entry take me directly to Song 2, not just the top of the page on which Song 2 is in the middle.

The PDF format supports that functionality, with bookmarks, but I don't know whether it's feasible to create them from ChordPro (or the relevant Perl modules). I vaguely recall some discussion on this topic, but forget the details.

**CSV export, e.g. to MobileSheets**
Not really a ChordPro issue, but this also raises a question of how CSV export might work. I guess the CSV would contain three song entries, all with the same page number. I think MSP should handle that ok: three song entries in MSP database, which would all look the same by default, but user could manually crop each one down the the relevant song.

**Comment by gwyndaf** [comment]
It also has interesting implications for chord diagrams. For instance, I tend to have them on the right, but also song title on the right, so that could be messy and confusing if the page is split into, say, three songs, with a new header for each.

I guess my underlying assumption is that several songs per page would be organised vertically, one below another, so each song occupies a 'band' across the page. Putting chords below each song might not be an efficient use of space. However, I could see short/simple songs with just 3-4 chords work (use space efficiently) with the chords on the right. Obviously that would be a user choice.

Perhaps the 'sub-page' concept I mentioned for columns could also serve for chord diagrams? So the existing ChordPro layout processes operate on a small 'page'  (e.g. ~ 99x210mm for A4, depending on song length), and then get assembled somehow on the regular A4 page? On the other hand, this sort of approach might go against the idea that long songs could flow automatically from one page to the next. Not sure I have any conclusive view on this, just trying to articulate the challenges!

Also footers:  should they be per-song, like 'header bars'? Layout-wise, it's probably sensible to have one per page, otherwise they'd eat into available song space. Although I have some song-specific information displayed in the footer, it's not essential. More important is maybe that footer would contain the page number, which seems a persuasive argument to keep them as per-page (not per-song).

**Comment by sciurius** [comment]
I considered sorttitle but it is not trivial to set it to empty. Neither of these work:
````
{sorttitle}
{sorttitle:}
{sorttitle:""}
````
I can make the latter work by checking for a sorttitle that is the literal string `""` but that feels awkward.

Maybe later we can find other song properties that are eligable to specify in the `{new_song}`.

**Comment by gwyndaf** [comment]
Nice one, thanks Johan. That approach seems more elegant and clear than my suggested (ab)use of `{sorttitle}`.

Tested with small collection, and it works as expected. Sample song is now omitted from TOC and outlines, while still appearing in CSV output. For me, that's the best of both worlds :)

Testing with a larger collection is causing a high system load and very slow processing, which suggests it's being caused by some specific song/s, so I'll try to narrow that down.

**Comment by gwyndaf** [comment]
Off the top of my head, two further properties that `{new_song}` could take:

* `csv=no` to exclude song from CSV output. It actually suits me to have songs _included_ in CSV, so they're listed in MSP, even if not in PDF TOC/outlines, but others might have a use for this.
* `toc_title=Alternate title for TOC entry` might have an application. In my current use case, it would allows me to title some pages with meaningful names like '12-bar blues patterns` and 'Common chord diagrams', but simply have a TOC entry of 'Appendices' that points to the first of them. It could also allow brief TOC entries for songs with very long titles.

**Comment by gwyndaf** [comment]
Ok, it seems like the performance issue is unrelated to the enhanced `{new_song}` feature.

If I process a collection of ~150 song files as individual songs (i.e. output to ~150 separate PDFs), no problem. So, it doesn't seem like any individual song is causing problems.

If I process the same collection of songs as a `--filelist` for a single PDF songbook (which is what I usually do), Perl memory usage starts climbing as ChordPro works through the songs. After ~30 songs, Perl memory usage has climbed to ~95% and system almost at a halt.

I don't know exactly what happens in that first processing stage. Perhaps all the songs are being gathered into a single file for processing. By way of example, this is the last `--verbose` message before I give up and interrupt processing:
```
Processing song ../songs/City_Of_New_Orleans.cho...
Parsers at start of ../songs/City_Of_New_Orleans.cho: *common
Processed song...
```
Is there any debug option I can apply to get more informative messages?

**Comment by sciurius** [comment]
There's an array in the config that gets doubled a couple of times per song, and persists. After 20+ songs this already requires gigabytes of memory...
I know the cause of the problem and try to fix it. There is nothing you can do about it. Sorry.
