### ISSUE TITLE
Unexpected font replacement [6.030_046]

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#328]
A tiny change (adding two commas in the first lyric line) seems to result in a changed font:
[A_Pair_Of_Brown_Eyes (guitar) git A.pdf](https://github.com/ChordPro/chordpro/files/13536142/A_Pair_Of_Brown_Eyes.guitar.git.A.pdf)
[A_Pair_Of_Brown_Eyes (guitar) git B.pdf](https://github.com/ChordPro/chordpro/files/13536143/A_Pair_Of_Brown_Eyes.guitar.git.B.pdf)

First PDF uses Roboto, as per my config; second is using Helvetica for some reason, in both lyrics and chords (the shape of the letter 'G' is a useful indicator).

Song lyrics uses `sans` and chords use `sans bold`. My `fontconfig` sets these to use the Roboto family.

Interestingly, title, subtitle lines and footnote (`{cb}`) comments are unchanged. These use `sanslight bold` (Roboto Medium) and `sanslight` (Roboto Light), so the behaviour doesn't seem font descriptions I've added myself.

So, it seems like the built-in definition of `sans` (=Helvetica) might somehow be overwriting my own config in some cases.

I can't identify any consistent trigger for this behaviour. I originally thought it was slight edits but, even if I re-run ChordPro repeatedly with the same song file, output seems to shift 'randomly' between the two fonts. Quite baffling.

This is my config, although it might not be relevant because behaviour occurs with no changes to config.
[config.txt](https://github.com/ChordPro/chordpro/files/13536194/config.txt)

**Comment by sciurius** [comment]
Looking at the config I see multiple definitions for `sans` and `sans-serif`:
````
         "helvetica, sans, sans-serif" : {
            "" : "Helvetica",
            "bold" : "Helvetica-Bold",
            "boldoblique" : "Helvetica-BoldOblique",
            "oblique" : "Helvetica-Oblique"
         },
        ...
         "sans, sans-serif" : {
            "" : "Roboto-Regular.ttf",
            "bold" : "Roboto-Bold.ttf",
            "bolditalic" : "Roboto-BoldItalic.ttf",
            "italic" : "Roboto-Italic.ttf"
         },
````

When perl processes these hashes, the order is undetermined (even [randomized](https://perldoc.perl.org/perlsec#Algorithmic-Complexity-Attacks)) so it is kind of russian roulette which gets processed last (and remains).

This an unforeseen and definitely unwanted sideeffect of #327.

I can revert that commit and add a preset 'webfonts'. Alternatively I can disallow splitting (i.e., not `"sans, sans-serif"`) and require separate specs for each font / alias.

What do you think?

**Comment by sciurius** [comment]
I think I found a way... Stay tuned.

**Comment by sciurius** [comment]
Can you try 6.030_048?

**Comment by sciurius** [comment]
> I'll keep testing, just in case any randomness has simply reduced in frequency! :)

I'm quite confident that this randomness has gone. 

How exactly are you trying to make the changes that cause the errors?

**Comment by gwyndaf** [comment]
The errors were already arising with my own config, with no changes.

My changes were exploratory, to see if I could fix the errors by changing `oblique` to `italic` (to match my own `sans` variants) in the `fontconfig` of `lib/ChordPro/res/config/chordpro.json`, but that didn't seem to fix them.

**Comment by gwyndaf** [comment]
Are you proposing to implement that decoupling of `helvetica` and `sans, sans-serif` in the default config?

That seems a useful way to retain compatibility for `helvetica.oblique` while allowing the `italic` and `bolditalic` variants to be used consistently for all other font descriptions.

I tried that in my user config, but it doesn't remove the error messages or random behaviour. That seems to make sense because the current default config seems to define `helvetica`, `sans` and `sans-serif` all with `oblique` and `boldoblique` variants, so we get the errors random behaviour if I try to redefine `sans` with an `italic` in my user config.

I can confirm that changing my user config's `"sans, sans-serif"` definitions to `oblique` (instead of `italic`) and `boldoblique` variants _does_ solve the random typography and error messages as a workaround. Although it's inconsistent with other variants, which are all `italic` or `bolditalic`, so potentially confusing in general use.

**Comment by sciurius** [comment]
As I have it now (6.030_049):

Decoupling of aliases is handled when the config is loaded. There is no difference anymore between 
````
          "sans, sans-serif" : { ... }
````
and
````
          "sans" : { ... }
          "sans-serif" : { ... }
````
This solves one part of the problem.

The other is that there are now separate entries for helvetica and sans, as shown in my previous message. This allows for:

The third part of the solution is removing the suggestion to use alternatives, like "b" for "bold" and "oblique" for "italic". So for the fontconfig definition in the config the only keys are `""`, `"bold"`, `"italic"` and `"bolditalic"`. Only helvetica uses oblique for legacy reasons.

This should avoid having duplicate definitions for the same fonts (see message 2 of this thread) and duplicate definitions for font styles (e.g. oblique and italic). So there should be no more russian roulettes.
