### ISSUE TITLE
{start_of_ly: Foobar} Does not print the label

### ISSUE THREAD

**Issue by nixternal** [ChordPro/chordpro#330]
## Describe the bug
When using {start_of_ly: Label}, it does not output the label in the PDF.

### To Reproduce
See attachments for cho file. I am building it with `chordpro attachment.cho -o attachment.pdf`

### Attachments
[chordpro.json](https://github.com/ChordPro/chordpro/files/13639942/chordpro.json)
[attachment.cho.txt](https://github.com/ChordPro/chordpro/files/13639956/attachment.cho.txt)
[attachment.pdf](https://github.com/ChordPro/chordpro/files/13639959/attachment.pdf)

## System information
 - OS: KDE Neon (Ubuntu 22.04)
 - Where did you get ChordPro from? Install process for Linux on website with cpan
 - ChordPro version: 6.030
 - Perl version: 5.34.0

## Additional context
```
Run-time information:
  ChordPro core          6.030     
  Perl                   v5.34.0    (/usr/bin/perl)
  CHORDPRO_LIB           /home/rich/.config/chordpro
  Resource path          /home/rich/.config/chordpro
                         /home/rich/.perl5/lib/perl5/ChordPro/res

Modules and libraries:
  Storable               3.23      
  Object::Pad            0.806     
  Text::Layout           0.032     
  File::LoadLines        1.041     
  PDF::API2              2.045     
  SVGPDF                 0.070     
  Font::TTF              1.06
```

**Comment by sciurius** [comment]
Thanks. This is already fixed in the development version.

**Comment by nixternal** [comment]
Well that was easy. Installed dev and it works like a charm. Thank you!
