### ISSUE TITLE
Unknown chord: G#6

### ISSUE THREAD

**Issue by JohannesWiesner** [ChordPro/chordpro#331]
Hi, I am using the following script to generate a .pdf:

```bash
#!/bin/bash

# set a directory to fonts of choice
fontdir="./OpenSans"

# chord pro settings
config_file="./config_custom.json"

# run chordpro to generate pdf
docker run -ti --rm \
--env HOME=$HOME \
--env USER=$USER \
--volume $HOME:$HOME \
--volume $fontdir:/fontdir \
--workdir $(pwd) \
chordpro/chordpro:v6.030.0 chordpro --config $config_file test.cho
```

`test.cho` only contains:

[G#6]

But I am getting:

```
Converting test.cho to ChordPro format
"test.cho", line 1, Unknown chord: G#6
        {comment:[G#6]}
"test.cho": No chord diagram defined for "G#6" (skipped)
```

What exactly is wrong with this notation?

**Comment by sciurius** [comment]
What the message tells you is that ChordPro does not know the frets and fingers for the G#6 chord.

By default ChordPro uses a built-in set of chord diagrams. These include all major chords, minor, seventh and most other common chords, buth these do not include **every possible** combination. 

The easy solution is to define the chord in your song. See the [define directive](https://www.chordpro.org/chordpro/directives-define/).

**Comment by JohannesWiesner** [comment]
Ah, I see! You're right, it's only the diagram that couldn't be rendered but the chord rendering itself worked. I was confused by `Unknown chord: G#6` and thought ChordPro generally wasn't aware of this chord
