### ISSUE TITLE
Fatal problem when custom config has .prp extension

### ISSUE THREAD

**Issue by mlos100** [ChordPro/chordpro#336]
## Describe the bug
A fatal problem fount error dialog appears if a custom configuration file has the file extension, .prp.  No error message appears if the same configuration file is renamed with a .json file extension

### To Reproduce
1. Start Windows GUI
2.  Create a new custom configuration file with file extension, .prp (e.g, anewconfig.prp)
3. Ensure the new custom configuration file is selected
4. Run a PDF Preview.
5. An Error dialog with a message like the following appears:
: No properties F:\hp-e9150T-documents\hobby\Guitar\Chords\chordPro\config\anewconfig_6040.prp in . at C:/Program Files/ChordPro.ORG/ChordPro/script/../lib/ChordPro/Config.pm line 292.
 : Fatal problems found!
6. Change the file extension of the config file to .json
7. Run PDF Preview. No error dialog appears.

### Expected behavior
The file extension, .prp, is accepted as a valid file extension for a custom configuration file.

## System information
 - OS: Windows 10
 - Where did you get ChordPro from? GitHub Release Page
 - ChordPro version: 6.040
 - Perl version: v5.30.2    (C:/Program Files/ChordPro.ORG/ChordPro/wxchordpro.exe)

## Additional context
The error message states the file wasn't found in '.'.  I tried moving the config file to the following locations, yet the error occurred in each case
1. the same location as the chordpro file
2. the same folder as the default, installed config files
3. the ChordPro installation directory

**Comment by sciurius** [comment]
From the description (points 6 and 7) it looks you have a config file with name `anewconfig.prp` (or `anewconfig_6040.prp`?) with JSON content.

The file extension `.prp` is accepted as a valid file extension for a custom configuration file but these files must have config data in properties format, e.g.
````
diagrams.show: none
````

Also (point 3): When the file is selected its absolute path is used and there is no searching in directories.

**Comment by mlos100** [comment]
Your explanation makes sense to me and I can see my confusion is due to the program creating the initial configuration file content (json) for me while I also let it set the initial file extension (prp). That is, I only entered anewconfig_06040 in the save dialog.
