### ISSUE TITLE
Base fret text is out of proportion to chord diagram

### ISSUE THREAD

**Issue by rcook** [ChordPro/chordpro#337]
I am overriding a number of `pdf.diagrams` properties in my configuration file to produce nice, big chord diagrams. Unfortunately, the base fret number's resulting font size is out of proportion to the chord diagram itself.

Here's my config:

```json
{
  "diagrams": {
    "show": "none"
  },
  "pdf": {
    "diagrams": {
      "height": 20,
      "vspace": 0.75,
      "width": 16
    },
    "fonts": {
      "diagram_base": {
        "name": "Times-Roman",
        "size": 0.1
      }
    },
    "spacing": {
      "diagramchords": 2
    }
  }
}
```

Here's my input file:

```cho
{define: Bb base-fret 6 frets 1 3 3 2 1 1 fingers 1 3 4 2 1 1}
{chord: Bb}
```

This results in the following output:

![result](https://github.com/ChordPro/chordpro/assets/425396/fda9f817-3099-4edc-ad5c-7f7b07ea0275)

As you can see, the "6" is a bit on the large size. Note how I am successfully able to override the font (`pdf.fonts.diagram_base.name`) but not the size. This behaviour is intentional (see comment in thread on https://github.com/ChordPro/chordpro/issues/318).

Is there a way to adjust the size of this numeral?

[chordpro.json](https://github.com/ChordPro/chordpro/files/13800143/chordpro.json)
[Example.cho.txt](https://github.com/ChordPro/chordpro/files/13800145/Example.cho.txt)

**Comment by sciurius** [comment]
It seems something went wrong in the new implementation of the string diagrams. I'll check.

**Comment by sciurius** [comment]
You have `spacing.diagramchords` set to a rather high value, is that intentional?

**Comment by rcook** [comment]
Yes, it was intentional. I increased the `diagramchords` value to increase the spacing between the chord name and the top of the grid, particularly to handle the case when there string mute ("X") or string open ("O") marks:

```cho
{define: Bb base-fret 6 frets 0 3 3 0 1 1 fingers x 3 4 x 1 1}
{chord: Bb}
```

If I use a lower value for `diagramchords` with the following configuration:

```json
{
  "diagrams": {
    "show": "none"
  },
  "pdf": {
    "diagrams": {
      "height": 20,
      "vspace": 0.75,
      "width": 16
    },
    "fonts": {
      "diagram_base": {
        "name": "Times-Roman",
        "size": 0.1
      }
    },
    "spacing": {
      "diagramchords": 1.2
    }
  }
}
```

I get the following:

![result2](https://github.com/ChordPro/chordpro/assets/425396/8def471a-76c5-422d-831c-2777c781c513)

Now the base fret numeral is a pretty good size, but the chord name seems to be a little too close to the grid. So, I tweaked `diagramchords` to make the diagram look a little less cramped.

**Comment by sciurius** [comment]
I see. 

I don't know where it came from but `spacing.diagramchords` should not play a role in the size of the base fret numeral. I'll fix that.

BTW, wouldn't it look better if you increase the chord names as well, e.g.
````
    "fonts": {
      "diagram_base": {
        "name": "Helvetica",
        "size": 0.1		// ignored
      },
      "diagram": {
        "name": "Helvetica",
        "size": 30
      }

````

**Comment by rcook** [comment]
Yes, increasing the size of the chord name does look better. Thanks!

**Comment by gwyndaf** [comment]
I think this might be related. 6.040_010 now seems to use a smaller font size for `diagram_base` and I believe that value can't be changed (`spacing.diagramchords` now doesn't seem to affect the base fret font size).

Previously, base fret numbers were about the height of the fret spacing. Now, they're closer to the fingering number sizes.

In my usage, diagrams are fairly small (ChordPro default), which are clear enough for someone to take in the dots and (ideally) base fret at a quick glance. If they want fingering suggestions, they can zoom in or look closer. The new size seems a bit hard to read when looking at the overall page.

Previously:
![Screenshot from 2024-01-09 09-27-27](https://github.com/ChordPro/chordpro/assets/1415754/aac450b9-c464-4829-a52f-c1568c3e16ff)
Now:
![Screenshot from 2024-01-09 09-27-03](https://github.com/ChordPro/chordpro/assets/1415754/9ec6d8bc-524d-440c-b00f-0b964d1fd682)

**Comment by sciurius** [comment]
Is _011 better?

**Comment by gwyndaf** [comment]
Yes, thanks. Previous font size now restored.

I also notice a bit more space between base fret number and diagram, compared with previous (and release) version. That makes the number a bit clearer when it's adjacent to a dot or barre, especially when using a bold `diagram_base` font.

**Comment by sciurius** [comment]
Yes, in de previous version I used the width of a font space to offset the basefret number. This width is sometimes not well-defined. I now use the width of 'x'.
