### ISSUE TITLE
t/72_mma.t fails with perl 5.39.6 ("Missing comma after first argument to return")

### ISSUE THREAD

**Issue by eserte** [ChordPro/chordpro#338]
The test suite fails with the latest bleadperl:
```
# Testing 7 cho files
No backend for MMA
Missing comma after first argument to return at /home/cpansand/.cpan/build/2023123110/App-Music-ChordPro-6.040-0/t/../lib/ChordPro/Output/MMA.pm line 40, near "undef unless"
Compilation failed in require at (eval 48) line 1.
t/72_mma.t ................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```
Probably it's caused by the following changes (one or both) mentioned in perldelta:
> Incompatible Changes
  "return" no longer allows an indirect object
    The "return" operator syntax now rejects indirect objects. In most cases
    this would compile and even run, but wasn't documented and could produce
    confusing results, for example:
[...]

and

>    New Errors
    *   Missing comma after first argument to return
        (F) While certain operators allow you to specify a filehandle or an
        "indirect object" before the argument list, "return" isn't one of
        them.

**Comment by sciurius** [comment]
Thanks. fixed in 6.040.1.
