### ISSUE TITLE
In {define}, wrong(?) display name when using `copyall`

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#345]
I have a convention of using a * suffix to designate optional or passing chords, so they can be output smaller, but without the *, as in this cut-down example:
```
{title: copyall test}
{define-guitar: D copy D@5}
{define-guitar: G copy G@3}
{define-guitar: F copy F@1}
{define: G* copyall G format "<small>\%{formatted}</small>" diagram #444444}
{define: F* copy F display F format "<small>\%{formatted}</small>" diagram #444444}

[D]    [G*] [F*]
```
Using default (`-X`) config and my own guitar config, I get [copyall+format.pdf](https://github.com/ChordPro/chordpro/files/14323796/copyall%2Bformat.pdf)

This gives me an unexpected asterisk on G* in output.

If my understanding is correct, `copyall G` should copy both `frets`/`fingers` _and_ `display` values from the previous `{define-guitar: G}`, whether in the song, the instrument config, or a chain of both, as here.

But, `F*` displays as expected, and differs from the `G*` definition only in using an explicit `display`, rather than `copyall`. That seems to suggest that the `display` value for `G*` isn't being copied from the `{define-guitar G}` directive above, and the value from the current `{define} used instead.

I realise there's no explicit `display` in `{define-guitar G}`, but _think_ that's assigned automatically, based on the name of the chord being defined (_i.e._ G).

v6.050, but I don't think it's specifically a new issue. I've experienced it before, but simply worked around by using an explicit `display` name.

**Comment by sciurius** [comment]
> I realise there's no explicit display in {define-guitar G}, but think that's assigned automatically, based on the name of the chord being defined (i.e. G).

No, there is no automatically assigned `display`. 

If there were a `display G` in the definition of `G` it would have be pulled in by the `copyall`.

**Comment by gwyndaf** [comment]
Ah ok, thanks. I tried using `copyall` instead of `copy` in `{define-guitar}` and it outputs as expected, presumably because that creates `display` values by copying them from the config.

However, I think I'm now starting to favour explicit `display` values in `define`, as the better solution.

Longer-term, that means I can move away `display` values in my configs, which seem to cause trouble if I try transcoding to Roman notation.
