### ISSUE TITLE
"class" feature not supported by Perl < 5.38

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#347]
You seem to use the pretty brand new feature "class" that to my understanding only becomes available with Perl 5.38, yet you only require 5.26 ( and 5.38 is not included in any Linux distro I use)

Global symbol "$class" requires explicit package name (did you forget to declare "my $class"?) at /usr/local/share/perl/5.32.1/ChordPro/Paths.pm line 15.

Am I missing something? How can I run ChordPro without compiling my own Perl version?

(And sorry for accidentially creating a pull request. I'm struggling to have git properly include your dev branch into my fork and wanted to find out why it was still giving me "commits ahead")

**Comment by sciurius** [comment]
The class feature is supported in older perls by the module `Object::Pad`. Did you install it? 
ChordPro's `make test` will not pass without it.

**Comment by bublath** [comment]
I did install it with apt and it seems that version was too old (actually did not do "make test" and when I did, the important information about the missing modules was lost right at the beginning of pages and pages of text. Not sure if missing modules could stop the process, so you really see them right away.
So my mistake, after installing the latest with cpan ist worked.
