### ISSUE TITLE
Issues with {image} labels and placement

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#348]
I'm just exploring use of recent `{image}` functionality, which seems really neat for putting short ABC riffs side by side :)

A couple of issues I've encountered:

__1) Documentation refers to `title` parameter__
`title` parameter yields no useful results, but `label` does work. TBH that seems a better name, as styling is consistent with other labels. I notice that labels within `{start_of_abc}` get ignored, but that's fine because they can be created in `{image}` instead. However...

__2) Label location doesn't follow image location__
It seems that label position reflects the directive's position in the song, not where the corresponding image is placed, which I think might be the expected behaviour.

For example
```
{start_of_abc-keyboard}
id=riff1
scale=0.76
%%singleline 1
X:1
K:C# octave=-1
M:4/4
L:1/8
"C#"z4 cG AE | "C#"G2 

{end_of_abc}
{start_of_abc-keyboard}
id=riff2
scale=0.76
%%singleline 1
X:1
K:C# octave=-1
M:4/4
L:1/8
"F#"z4 AG E2 | "D#m"G2 

{end_of_abc}
{image id="riff1" align="left" label="riff 1" anchor="page" x="0%" y="95%"}
{image id="riff2" align="center" label="riff 2" anchor="page" x="50%" y="95%"}
```
gives
![Screenshot from 2024-02-25 17-46-45](https://github.com/ChordPro/chordpro/assets/1415754/2035f148-2a52-489d-bcda-edd30addc28b)

Although this is with using ABC images with `id`, similar behaviour seems to arise when using image files via `src`.

Even if the label location reflects the image location, it does then raise the question of how it should be positioned relative to the image. For my usage, I'm happy for labels to be just above and left-aligned with the image.

**Comment by sciurius** [comment]
1) Documentation refers to title parameter

That's a remnant from the past. It was never implemented. I've removed the info and added label instead.

2) Label location doesn't follow image location

The label gets placed where the image would have been without anchor coordinates. Pretty useless, indeed.
I'll take a look if I can find a better solution.

BTW, did you consider something like

````
<b>riff1</b> <img id="riff1"/> <b>riff2</b> <img id="riff2"/>
````
(yes, it needs some raises...)

**Comment by gwyndaf** [comment]
Thanks Johan.

`<img>` gets the job done for now, thanks to your example. My earlier, failed attempt had missed the terminating `/`.
