### ISSUE TITLE
"Not a SCALAR reference" with image directive when generating song twice

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#349]
This is an issue I encountered, when trying to re-apply my patches for page sorting. All in all they worked pretty well, but I have one song that just contains of a jpg image:

{t:something}
{st:something}
{image:something.jpg}

When I apply my patch, I get

Not a SCALAR reference at /usr/local/share/perl/5.32.1/IO/String.pm line 31.
 at /usr/local/share/perl/5.32.1/IO/String.pm line 31.
        IO::String::open(IO::String=GLOB(0x558e7dca8630), PDF::API2::Resource::XObject::Image::JPEG=HASH(0x558e7d3d7798)) called at /usr/local/share/perl/5.32.1/IO/String.pm line 20
        IO::String::new("IO::String", PDF::API2::Resource::XObject::Image::JPEG=HASH(0x558e7d3d7798)) called at /usr/local/share/perl/5.32.1/ChordPro/Output/PDF.pm line 2880
        ChordPro::Output::PDF::prepare_assets(ChordPro::Song=HASH(0x558e7b754578), ChordPro::Output::PDF::Writer=HASH(0x558e7c4939b0)) called at /usr/local/share/perl/5.32.1/ChordPro/Output/PDF.pm line 939
        ChordPro::Output::PDF::generate_song(ChordPro::Song=HASH(0x558e7b754578), HASH(0x558e7c5497b8)) called at /usr/local/share/perl/5.32.1/ChordPro/Output/PDF.pm line 117
        ChordPro::Output::PDF::generate_songbook("ChordPro::Output::PDF", ChordPro::Songbook=HASH(0x558e7c32d450)) called at /usr/local/share/perl/5.32.1/ChordPro.pm line 264
        ChordPro::chordpro() called at /usr/local/share/perl/5.32.1/ChordPro.pm line 102
        ChordPro::main() called at /usr/local/share/perl/5.32.1/ChordPro.pm line 95
        main::run() called at /usr/local/bin/chordpro line 43

I reduced it to a very simple reproducer:

If you add this code at line 50 of PDF.pm (right after "    $ps = $config->{pdf};")

	my $pri = ( __PACKAGE__."::Writer" )->new( $ps, $pdfapi );
	foreach my $song ( @{$sb->{songs}} ) {
			$song->{meta}->{pages} =
				generate_song( $song, { pr => $pri, startpage => 1 } );
		if ( $options->{verbose} ) { print $song->{meta}->{pages}." "; STDOUT->flush(); } 
		}

The issue appears. All I'm doing here is doing a "dry run" to generate the song, in order to find out, how many pages the individual songs will actually need. That is a prerequisite to sort them in a way, that you always see both pages of a 2 page song when printed in a booklet (and don't need to turn the page while playing).

I know this is not an actual bug of the current version, but maybe you have an idea how to mitigate this. Note that line numbers in the stacktrace for PDF.pm correspond to the version with the small patch above with an empty line before and after.
Looks like something gets screwed up when generating a page with an image twice.

**Comment by sciurius** [comment]
Try adding ` && $elt->{subtype} ne "xform"` somewhere around line 2840.

````
	if ( $elt->{type} eq "image" && $elt->{subtype} ne "xform" ) {
	    warn("PDF: Preparing $elt->{subtype} image\n") if $config->{debug}->{images};
	    if ( ($elt->{uri}//"") =~ /^chord:(.+)/ ) {
		my $chord = $1;
````

**Comment by bublath** [comment]
Did not work for me. I believe I found that the issue is, that after processing the image for the first time, the "uri" is gone.
One solution is to make a deep copy of the {assets} structure and restore it afterwards.
Less ugly seems to me to have prepare_assets check if the {uri} still exists (or maybe better if {data} exists?) and skip processing (assuming processing was already done previously)

So after
	my $elt = $sa{$id};
add
	if (!defined $elt->{uri}) {
		next;
	}

**Comment by sciurius** [comment]
I see. My fix applied to the case of delegate images.

Does 

    if ( $elt->{type} eq "image" && !$elt->{subtype} ) {

(instead of 

    if ( $elt->{type} eq "image" && $elt->{subtype} ne "xform" ) {

) fix it?

**Comment by bublath** [comment]
No. That just avoids the error, but the result is wrong.
Instead of the image I'm getting a box saying "Unhandled image type: asset=_Image001"

**Comment by sciurius** [comment]
Ok, I'll need to dive a bit deeper then.

**Comment by bublath** [comment]
I think it really should be ok to just skip the image if it already was processed - and that was done for sure if {data} exists.
So just doing
	next if defined $elt->{data};
looks to me like a nice approach.

**Comment by bublath** [comment]
Btw. my fork can be found at https://github.com/bublath/chordpro/tree/dev
I shows some strange "11 commits ahead and 8 commits behind" your dev branch, but if I compare it just shows my changes

**Comment by sciurius** [comment]
This seems to fix it for me, please try:
````
+	if ( $elt->{type} eq "image" && $elt->{subtype} eq "xform" ) {
+	    # Ready to go.
+	    next;
+	}
+
+	if ( $elt->{type} eq "image" && $elt->{data} ) {
+	    # Ready to go.
+	    next;
+	}
+
 	if ( $elt->{type} eq "image" ) {
 	    warn("PDF: Preparing $elt->{subtype} image\n") if $config->{debug}->{images};
 	    if ( ($elt->{uri}//"") =~ /^chord:(.+)/ ) {
````

**Comment by bublath** [comment]
Works for me as well. Thanks for looking into it.
Feel free to include my page sorting and 2-page alignment ideas. For me it's an essential functionality to create a good songbook.

**Comment by sciurius** [comment]
Can you make a new PR?
