### ISSUE TITLE
textsize and chordsize are not included when using transpose to generate a new chordpro file

### ISSUE THREAD

**Issue by terevos** [ChordPro/chordpro#353]
## Describe the bug
When using the transpose feature of chord pro and generating a new chordpro file, it excludes the texdtsize and chordsize blocks. 

I use these all the time to adjust the size of PDF printouts so that they always fit on 1 page (as a guitarist, I can't easily switch pages).

In the chord pro file, I usually do something like this near the top:

{textsize: 93%}
{chordsize: 93%}

But the output file does not contain these. Here's an example of a command that I run:

chordpro "Some Song.chopro" --transpose 10 --generate ChordPro -G -o "Some Song.t10.chopro"

### To Reproduce
1. Use a chordpro file that contains textsize and chordsize blocks
2. Use chordpro command line to transpose and generate a new ChordPro file (eg. chordpro "Some Song.chopro" --transpose 10 --generate ChordPro -G -o "Some Song.t10.chopro" )
3. Look at the newly produced file. It does not contain textsize or chordsize

### Expected behavior
textsize and chordsize should be included

### Attachments
{t:Some Song}
{st:Subtitle}
{key:C}
{textsize: 93%}
{chordsize: 93%}
{sov: Verse 1}
[C] Some[Dm/C] words [C]and stuff [Dm/C] and moo[C]
Be some lyrics [G2/B]to show[Am] [G2/B]the bugs
{eov}

{soc: Chorus}
[F] Here we have[Dm7] a chorus
[G] But it doesn't rhyme[C/E] or even have a rythem
{eoc}

{artist: Words and Music by Some Guy}
{copyright: ©2024 Some Guy Publishing Random Stuff}

## System information
 - OS: Mac OS Ventura 13.6.4
 - Where did you get ChordPro from? CPAN

Run-time information:
  ChordPro core          6.050
  Perl                   v5.38.2    (/opt/homebrew/Cellar/perl/5.38.2_1/bin/perl)
  Resource path          /opt/homebrew/Cellar/perl/5.38.2_1/lib/perl5/site_perl/5.38/ChordPro/res
  ABC support            QuickJS_XS (ABC2SVG version v1.22.12 of 2023-12-22)

Modules and libraries:
  Storable               3.32
  Object::Pad            0.808
  Text::Layout           0.032
  File::LoadLines        1.045
  PDF::API2              2.045
  SVGPDF                 0.083
  Font::TTF              1.06
  JavaScript::QuickJS    0.19

**Comment by sciurius** [comment]
Fixed in the upcoming release.
