### ISSUE TITLE
Inconsistent chord definition between json and inline

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#360]
In the JSON file I need to specifify "-1" when defining a chord for empty strings, while that leads to an error when using the {define} clause inside of a song. Here I have to use "x".
Would be good to make this consistent (or accept both "-1" and "x" in both places)

**Comment by sciurius** [comment]
Good suggestion. I'll add `-1` for muted strings to the `{define}` command.

**Comment by sciurius** [comment]
Fixed in 6.050_098.
