### ISSUE TITLE
incomplete kit:missing files

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#363]
## Describe the bug

with chordpro-6.050.021:
perl Makefile.PL
Checking if your kit is complete...
Warning: the following files are missing in your kit:
	lib/ChordPro/res/abc/abc2svg/cmdline.js
	lib/ChordPro/res/abc/abc2svg/README.FIRST
	pp/macos/ppl.c
	script/rrjson.pl
Please inform the author.

### To Reproduce
1. 
2. 
3. 
4. 

## System information
 - OS: 
 - Where did you get ChordPro from? 

 - ChordPro version: 
 - Perl version:

**Comment by sciurius** [comment]
Should be fixed in _023.

**Comment by timmbo9** [comment]
thanks
