### ISSUE TITLE
pdf.fonts.label and pdf.fonts.annotation configs are being ignored

### ISSUE THREAD

**Issue by polvoazul** [ChordPro/chordpro#367]
## Describe the bug
... 
     "label": {
        "size": 20,
        "color": "red"
      },
      "annotation": {
        "color": "black",
        "size": 20
      }
...
These font configs are broken, specified colors and font sizes are being ignored.

### To Reproduce
chordpro --config=[config.json](https://github.com/ChordPro/chordpro/files/14896662/config.json) "[Johnny Cash - Ring of Fire.cho](https://github.com/ChordPro/chordpro/files/14896672/Johnny.Cash.-.Ring.of.Fire.txt)"
Open resulting PDF

### Expected behavior
Labels should be red

### Attachments
PDF with --debug 
[Johnny Cash - Ring of Fire.pdf](https://github.com/ChordPro/chordpro/files/14896685/Johnny.Cash.-.Ring.of.Fire.pdf)

## System information
 - OS: Mac
 - Where did you get ChordPro from? Brew
  ChordPro core          6.050.7
  Perl                   v5.38.2

**Comment by sciurius** [comment]
Good catch. There's a bug that a derived font (e.g. `annotation` is derived from `chord`) is ignored unless it has either a `name`, `file` or `description`.

It is fixed in 6.050_031. In the mean time you can add a font name to `label` and `annotation`:
````
      "label": {
        "name": "Times-Roman",
        "size": 20,
        "color": "red"
      },
      "annotation": {
        "name": "Helvetica-Oblique",
        "color": "black",
        "size": 20
      }
 ````

BTW I notice your config reads "AUTO GENERATED FROM YAML". Do you have your own config generators?

**Comment by polvoazul** [comment]
Thanks for the quick response!
Yes, I've converted the whole default config to YAML (as i find it easier to work with and it also supports comments natively). I have my own config in yaml as well and i run it through a filter to turn it into json. (It is definitely over-engineering and ridiculous, but this is not my day job so I will do what I want dammit!). Unfortunately I dont know perl, if i did i could do a pull request to support yaml config files. One nice thing is that json is valid yaml, so I can keep it json-like in parts where it makes sense.

[chordpro-defaults.yaml](https://github.com/ChordPro/chordpro/files/14898183/chordpro-defaults.yaml.txt)

this file is not  _exactly_ the default config as I have made some changes in there already, but you get the point.


Here is my yaml config:  [chordpro-config.yaml.txt](https://github.com/ChordPro/chordpro/files/14898192/chordpro-config.yaml.txt)

Here is the bash script that converts it to json:

```
#!/bin/bash -ex
to_json(){
    if [[ ! -f $1 ]]; then
        >&2 echo need to provide an existing file to convert
        exit 1
    fi
    cat $1 | python -c 'import yaml; import json; import sys; print(json.dumps(yaml.safe_load(sys.stdin)));' 
}
echo "// THIS IS AUTO GENERATED FROM YAML. DO NOT EDIT!" > chordpro-config.json
to_json chordpro-config.yaml | jq >> chordpro-config.json
```

**Comment by sciurius** [comment]
I personally dislike JSON but at the time there was no real alternative.

You may be pleased to know that the latest (development) releases include support for rrjson (really [relaxed JSON](https://www.relaxedjson.org) which is even easier to write and maintain than YAML.

**Comment by polvoazul** [comment]
This looks really nice. Good to know of its existence. I've always felt that there was something missing between json and yaml, and this might be it.
