### ISSUE TITLE
read a list of songs from a separate file

### ISSUE THREAD

**Issue by Gajusbonus** [ChordPro/chordpro#37]
I want to ask for an enhancement: to read all files to be processed from a file-list.
Files could be in different folders and all files need to be processed in a certain order, as given in the file-list.

**Comment by topchyan** [comment]
I also think this feature would be helpful. Results from same set of files running on different machines can vary in the way files get sorted (on Linux sort order seemed okay, but on Mac it was completely chaotic for me). Having a list would make files go in a particular manageable order.

**Comment by sciurius** [comment]
Git 0.930_004 adds a --filelist option:

`--filelist=`_FILE_

Read the names of the files to be processed from the named _file_.

This option may be specified multiple times.

Song file names listed on the command line are processed _after_ the files from the filelist arguments.
