### ISSUE TITLE
Unicode handling - change/issue for high code points?

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#371]
I notice some different behaviour in v6.050_042, possibly in handling higher Unicode code points.

I have a 'manual' chord grid:
```
¦ †[D]        ¦      [*%]      ¦ †[D]        ¦      [*%]      ¦
```
To output a proper 'repeat bar' 𝄎 symbol in bars 2 and 4, I have a preprocessor line:
```
{ "target" : "[*%]", "replace" : "[*<span face=symbol size=150% rise=15% color=#000000>\uD834\uDD0E</span>]"},
```
This has previously allowed me to reference the `1D10E` code point (𝄎 character) in a way that ChordPro can handle, as `\uD834\uDD0E`.

Now, my output is 
![Screenshot from 2024-04-23 15-00-50](https://github.com/ChordPro/chordpro/assets/1415754/d99038d0-a39b-4617-b219-415858241b24)

If I put `<span face=symbol>𝄎</span>` directly in my source, it outputs 𝄎, as expected (I don't usually do this, to keep song sources to a limited character set, for portability), so Unicode _output_ seems to be working.

Interestingly, output shows _two_, not one, unknown characters. `D834` and `DD0E` glyphs don't exist in my symbol font, which might suggest that `\uD834\uDD0E` is now being _interpreted_ as two Unicode characters, which are unknown.

**Comment by gwyndaf** [comment]
Ah, maybe not Unicode handling. `\uD83C\uDF6A`, which I also use from the higher Unicode range (in footer string), seems to be interpreted successfully.

Maybe that suggests a change in preprocessor handling?

In any case, it seems like I can successfully put the 𝄎 character into my `replace` string (instead of Unicode value), so immediate symptom solved for me, but maybe still useful to understand the underlying cause/change.

**Comment by sciurius** [comment]
I think I have this fixed in 6.050_044.
As a bonus, you can now also use extended unicode escapes, e.g. `\u{1d10e}` instead of having to fake them with surrogates `\uD834\uDD0E`.

**Comment by gwyndaf** [comment]
That seems to fix it. Certainly for the 'double' form `\uD834\uDD0E`

Nice touch with the extended `{ }` form.  That seems to work ok on a single song sample, but I'm seeing some issues with a `filelist` batch, so I'll try to narrow down what's causing it.

**Comment by gwyndaf** [comment]
Batch issues caused by my own carelessness (calling release version in batch script).

So, with correct dev version, extended Unicode form working nicely :)
