### ISSUE TITLE
Issue when previewing PDF files with foreign keyboard

### ISSUE THREAD

**Issue by Hoccanrock** [ChordPro/chordpro#374]
### To Reproduce
1. 
2. 
3. 
4. 

## System information
 - OS: 
 - Where did you get ChordPro from? 

 - ChordPro version: 
 - Perl version:

**Comment by sciurius** [comment]
I'm missing the issue description...

**Comment by Hoccanrock** [comment]
I need a config file to use system fonts so that I can print in foreign languages.  I tried generating on my own, but either it doesn't print and gives errors, or it prints but still with error messages.
Please help
ThanksHoc
    On Tuesday, June 11, 2024 at 07:07:27 AM PDT, Johan Vromans ***@***.***> wrote:  
 
 


I'm missing the issue description...

**Comment by sciurius** [comment]
There are a number of example configs described in https://www.chordpro.org/chordpro/chordpro-fonts/ .
Did you try one of these?

If you try something and get errors, please include the song, the config, and the error message.

**Comment by sciurius** [comment]
The upcoming release will have decent fonts bundled, and ChordPro will use these instead of the limited built-in fonts.
