### ISSUE TITLE
Add Syntax Highlighting to ChordPro UI

### ISSUE THREAD

**Issue by terevos** [ChordPro/chordpro#379]
## Describe the feature request
Add Syntax Highlighting to ChordPro UI

### To Reproduce
1. In the main editor, it's all white on black or black on white text. It'd be great if the editor supported syntax highlighting.

### Attachments
See example attachment from Visual Studio Code's chordpro extension (ricardomfmsousa)

https://marketplace.visualstudio.com/items?itemName=ricardomfmsousa.chordpro

## System information
 - OS: MacOS Sonoma 14.4.1
 - Where did you get ChordPro from? GitHub test build 2024-06-09

## Additional context

![Screenshot 2024-06-10 at 1 03 48 PM](https://github.com/ChordPro/chordpro/assets/8345872/ed9696ad-94eb-4ff8-955d-2d431f1c0bd2)

**Comment by sciurius** [comment]
Replacing the default text editor widget by the Scintilla editor widget is planned for a future version. This widget supports syntax highlighting (and more).

@Desbeers, I assume MacOS has a similar text widget?

**Comment by Desbeers** [comment]
Yes, there are widgets for that (we call them Swift Packages), however, I don’t want to depend on external packages :-)

While replacing the SwiftUI Editor with an AppKit editor, because of the ‘quotation issue’, I added some basic highlighting as well. It looks so much better!

It’s very buggy so not committed yet...

<img width="651" alt="Screenshot 2024-06-11 at 14 31 26" src="https://github.com/ChordPro/chordpro/assets/58348935/a1d1a28c-c36e-49f0-a9a5-589095476bba">

**Comment by sciurius** [comment]
I'm inclined to say that this probably sufficient already.

Would it help if I add a special call to the chordpro tool that yields a JSON file with setings, list of known directives, ...?

**Comment by Desbeers** [comment]
Yes, that would help for sure! Not something I will implement right-away but for future updates to make it even more fancy!

Meanwhile, I build a new TestBuild with the fresh editor... I will test it some more before I send you a new PR.

**Comment by terevos** [comment]
That looks great.  I would definitely take it as is.   But I would also love if there was some highlighting for the pango stuff, too, if that is possible.

![Screenshot 2024-06-11 at 10 40 04 AM](https://github.com/ChordPro/chordpro/assets/8345872/5aaf2565-be4b-472f-a131-563eb9cfab00)

(Also note that this TestBuild (2024-06-11) broke the Preview rendering, if you didn't already know)

**Comment by Desbeers** [comment]
One step at the time :-)

I noticed preview is broken sometimes when it is a new file… Not always… I try to fix it but it is clearly a Mac-bug with macOS 14 when using a `NSViewRepresentable`… in a SwiftUI app… It is fine on macOS 12...

**Comment by terevos** [comment]
It's all good.  A work in progress.

**Comment by Desbeers** [comment]
Well, I think I fixed the QuickView issue... Meant I had to go back to `AppKit` again and leave the easy world of `SwiftUI` behind (again).

However, maybe this was meant to be :-)

- Preview is inside the document window now.
- It will update when you change settings.
- If you have the preview open and update the document, you will get a very friendly popup in the preview to update it.
- I like it!

`Live updates` is a no-go. Don’t even try to suggest it :-D

While at it, I added some very basic highlighting for ‘pango’.

<img width="848" alt="Screenshot 2024-06-11 at 21 25 33" src="https://github.com/ChordPro/chordpro/assets/58348935/57e2d0bb-63b3-4bfb-b991-d19873e161b1">

**Comment by terevos** [comment]
Oh man. That's awesome!  I love the Preview side by side

***@***.***

**Comment by sciurius** [comment]
Nice!

For the pango highlighting, I'd suggest to highlight the markers only, e.g.

![scrot20240611214806](https://github.com/ChordPro/chordpro/assets/1118804/fe680afb-94c5-4a70-a3f9-cda54c589597)

**Comment by Desbeers** [comment]
I agree, but it was just a small addition while doing more important stuff :-) Regex is art!

**Comment by Desbeers** [comment]
> Nice!
> 
> For the pango highlighting, I'd suggest to highlight the markers only, e.g.

I've updated the regex to be a bit smarter and now it highlights as you suggested

**Comment by Desbeers** [comment]
This issue can be closed :-)
