### ISSUE TITLE
Problem rendering a transposed song in nashville notation

### ISSUE THREAD

**Issue by svillacreses** [ChordPro/chordpro#384]
## Describe the bug

I want to use the nashville notation to show my chords, and it works great! Until I add the "transpose" directive, if I uncomment the line#4 of song.cho (see attachment) I get this error:
`Too many arguments for subroutine 'ChordPro::Chord::Nashville::transpose' (got 3; expected 1) at .../5.38/ChordPro/Song.pm line 1876.`

### To Reproduce
1. `chordpro --config config.json song.cho -o result.pdf`
2. Verify it is working well
3. Uncomment line#4 of song.cho file
4. Get the error :(

### Attachments

[config.json](https://github.com/user-attachments/files/15891568/config.json)
[song.txt](https://github.com/user-attachments/files/15891575/song.txt) -> Change extension to **.cho**
[result.pdf](https://github.com/user-attachments/files/15891591/result.pdf)

## System information
 - OS: macOS Sonoma 14.5
 - Where did you get ChordPro from? **CPAN**
 - ChordPro version: This is ChordPro core 6.050.7 
 - Perl version: 5.38.2

_I was told that this indeed was an issue in the [groups.io group](https://groups.io/g/ChordPro/topic/106746065)_

**Comment by sciurius** [comment]
The fix for issue #384 fixed this as well.

**Comment by svillacreses** [comment]
I found out that there's a similar issue when rendering a song with 'capo' and nashville notation:

Error log:
```
Too few arguments for subroutine 'ChordPro::Chord::Nashville::transpose' at /root/libs/chordpro/script/../lib/ChordPro/Song.pm line 1739.
1|chordpro_api  |     at genericNodeError (node:internal/errors:983:15)
1|chordpro_api  |     at wrappedFn (node:internal/errors:537:14)
1|chordpro_api  |     at ChildProcess.exithandler (node:child_process:421:12)
1|chordpro_api  |     at ChildProcess.emit (node:events:520:28)
1|chordpro_api  |     at maybeClose (node:internal/child_process:1105:16)
1|chordpro_api  |     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
1|chordpro_api  |   code: 255,
1|chordpro_api  |   killed: false,
1|chordpro_api  |   signal: null,
1|chordpro_api  |   cmd: ...,
1|chordpro_api  |   stdout: '',
1|chordpro_api  |   stderr: "Too few arguments for subroutine 'ChordPro::Chord::Nashville::transpose' at /root/libs/chordpro/script/../lib/ChordPro/Song.pm line 1739.\n"
1|chordpro_api  | }
```

**Comment by sciurius** [comment]
I think this is also fixed.

**Comment by svillacreses** [comment]
I just pulled the last changes on the dev branch and it is still not working :(

**Comment by lanecsistemas** [comment]
Any updates on this? It is still not working when having **ANY** 'capo' definition and trying to get nashville notation, I get the same error.

> I found out that there's a similar issue when rendering a song with 'capo' and nashville notation:
> 
> Error log:
> 
> ```
> Too few arguments for subroutine 'ChordPro::Chord::Nashville::transpose' at /root/libs/chordpro/script/../lib/ChordPro/Song.pm line 1739.
> 1|chordpro_api  |     at genericNodeError (node:internal/errors:983:15)
> 1|chordpro_api  |     at wrappedFn (node:internal/errors:537:14)
> 1|chordpro_api  |     at ChildProcess.exithandler (node:child_process:421:12)
> 1|chordpro_api  |     at ChildProcess.emit (node:events:520:28)
> 1|chordpro_api  |     at maybeClose (node:internal/child_process:1105:16)
> 1|chordpro_api  |     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
> 1|chordpro_api  |   code: 255,
> 1|chordpro_api  |   killed: false,
> 1|chordpro_api  |   signal: null,
> 1|chordpro_api  |   cmd: ...,
> 1|chordpro_api  |   stdout: '',
> 1|chordpro_api  |   stderr: "Too few arguments for subroutine 'ChordPro::Chord::Nashville::transpose' at /root/libs/chordpro/script/../lib/ChordPro/Song.pm line 1739.\n"
> 1|chordpro_api  | }
> ```

**Comment by sciurius** [comment]
It works for me using current dev (6.050_115).
[song.zip](https://github.com/user-attachments/files/16641154/song.zip)

**Comment by svillacreses** [comment]
The problem is not when using the "transpose" directive, but when using the **"capo"** directive...

Also, after updating the dev branch (6.050_115) I'm getting an error after exporting the same PDF twice, this wasn't happening before... :(

```
Error: Command failed: perl ~/libs/chordpro/script/chordpro --config custom-config.json result.cho -o "./generated/setlists/qMaSIJIqL4OP48HyjR6M.pdf"
1|chordpro_api  | Can't call method "isvirtual" on an undefined value at /usr/local/share/perl/5.30.0/PDF/API2/Content.pm line 1622.
1|chordpro_api  |     at genericNodeError (node:internal/errors:983:15)
1|chordpro_api  |     at wrappedFn (node:internal/errors:537:14)
1|chordpro_api  |     at ChildProcess.exithandler (node:child_process:421:12)
1|chordpro_api  |     at ChildProcess.emit (node:events:520:28)
1|chordpro_api  |     at maybeClose (node:internal/child_process:1105:16)
1|chordpro_api  |     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
1|chordpro_api  |   code: 255,
1|chordpro_api  |   killed: false,
1|chordpro_api  |   signal: null,
1|chordpro_api  |   cmd: 'perl ~/libs/chordpro/script/chordpro --config custom-config.json result.cho -o "./generated/setlists/qMaSIJIqL4OP48HyjR6M.pdf"',
1|chordpro_api  |   stdout: '',
1|chordpro_api  |   stderr: `Can't call method "isvirtual" on an undefined value at /usr/local/share/perl/5.30.0/PDF/API2/Content.pm line 1622.\n`
1|chordpro_api  | }
```

**Comment by sciurius** [comment]
It usually helps to include a small song + config that shows the problem.

6.050_116 should fix the capo problem. As for "exporting any PDF twice" I don't have a clue what you are doing. Can you describe your setup?
The `Can't call method "isvirtual" on an undefined value` is usually a crude way of letting know there is something wrong with the fonts.

When you run the command from the shell, does it work?
