### ISSUE TITLE
Errors possibly triggered by `+pdf.spacing` adjustments in song

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#388]
I've just updated to the latest `dev` version (6.050_074) and getting some repeated errors, like:
```
Use of uninitialized value in multiplication (*) at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/Output/PDF.pm line 2225.
Use of uninitialized value in multiplication (*) at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/Output/PDF.pm line 2258.
Use of uninitialized value in multiplication (*) at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/Output/PDF.pm line 2231.
Use of uninitialized value in multiplication (*) at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/Output/PDF.pm line 2221.
```

Basic diagnostic suggests I can eliminate the errors by removing per-song spacing adjustments such as:
```
{+pdf.spacing.lyrics 1.1}
{+pdf.spacing.chords 1.1}
{+pdf.spacing.empty 0.6}
{+pdf.spacing.tab 0.84}
```

Practical output impact seems to be that the relevant spacing value is set to `0`, which renders some songs harder to read, and some squeezed down to a single line!

I don't know if this is specifically related to line spacing tweaks, or more generally using `+pdf.` for ad hoc config adjustments. Let me know if there's anything I can test further.

**Comment by sciurius** [comment]
This is fixed in git.
