### ISSUE TITLE
Rendering text in the chords line Bug

### ISSUE THREAD

**Issue by RoadRangerX** [ChordPro/chordpro#40]
In the following example non-chord text above the lyric line at the
beginning of a line doesn't render. I can work around it by inserting
a "[]" at the beginning of the affected lines. I'm trying to add
timing information to some chordpro songs.
Also my reading of the chordpro "standard" would make non-chord text like this a warning at best, not an error?
Thanks!
Ron

{soc}
[(][|]['][']['][)]This [']land is [|][G]your [']lan-[']d, this [']land
is [|][D]my [']lan-[']d
From [']Cali-[|][A7]forni-[']a-[']a to the [']New York [|][D]Is-[']lan-[']d
From the [']Redwood [|][G]For-[']e-[']st to the [']Gulf Stream
[|][D]wa-[']a-[']ter-[']s
[|][A]This lan-[']d was [']made for [']you and [|][D]m-[']e-[']e.[(]['][|][)]
{eoc}

{start_of_verse}
As [']I went [|][G]wal-[']kin-[']g that [']ribbon of [|][D]high-[']wa-[']y
I [']saw a-[|][A]bove [']me-[']e that [']endless [|][D]sky-[']wa-[']y
I [']saw be-[|][G]low [']me-[']e that [']golden [|][D]va-[']l-[']le-[']y
[|][A]This lan-[']d was [']made for [']you and [']me-[']e-[']e.
{end_of_verse}

**Comment by sciurius** [comment]
Good catch. This is fixed in the dev branch.

The non-chord text will cause warnings but will otherwise be processed normally
