### ISSUE TITLE
Inconsistent referencing of `bold italic` font

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#401]
Minor observation, and I'm not sure if it merits a documentation or software tweak.

I have a variety of font faces, styles and weights defined in `pdf.fontconfig`, including
```
        "sanslight" : {
          ""            : "Roboto-Light.ttf",
          "italic"      : "Roboto-LightItalic.ttf",
          "bold"        : "Roboto-Medium.ttf",
          "bolditalic"  : "Roboto-MediumItalic.ttf"
          },
```
If I reference these in `pdf.fonts.annotation` as 
```
        "annotation" : {
          "description" : "sanslight bolditalic 11",
          "color" : "#006600"
        },
```
I get annotations in the italic (not bolditalic) font.

However, `"description" : "sanslight bold italic 11"` (space between bold and italic) creates the expected behaviour.

As this is different from `fontconfig` naming, it's a bit counter-intuitive. It might simply need a mention in [documentation](https://www.chordpro.org/beta/chordpro-fonts/#method-2-using-a-font-description) to include a separating space for bold italic font references, or maybe a tweak to maybe `pdf.fonts` so it recognises `bolditalic`.

**Comment by sciurius** [comment]
Thanks. This will be fixed in the next version of `Text::Layout`.
