### ISSUE TITLE
Documentation: Config field  `settings.chord-format` has moved to `chord-formats.*`

### ISSUE THREAD

**Issue by devnibo** [ChordPro/chordpro#403]
## Describe the bug

The documentation page https://chordpro.org/chordpro/chordpro-configuration-generic/ mentions the field `settings.chord-format`. But when I set the field like in the following config file:
[chordpro.conf.json](https://github.com/user-attachments/files/16440529/chordpro.conf.json)

and then run it like this `chordpro --config chordpro.conf.json test.cho` I get this error:
```
Config error: unknown item settings.chord-format
```
Looking at the output of `chordpro --print-default-config` and then setting it through `chord-formats.common` works fine.

_I didn't provide additional info as this seems like outdated documentation and not more._

**Comment by sciurius** [comment]
Thanks, fixed.

Please use the [beta documentation](https://chordpro.org/beta/chordpro-configuration-generic/) for the latest version of the docs.
