### ISSUE TITLE
[Linux] Unable to open wxchordpro

### ISSUE THREAD

**Issue by joshpetit** [ChordPro/chordpro#406]
### To Reproduce
1. Install `chordpro`
2. Install `Wx`
3. Run `wxchordpro`

### Expected behavior

The Gui opens
## System information
 - OS: Arch
 - Where did you get ChordPro from? Cpan

 - ChordPro version: 6.050.7
 - Perl version: perl 5 version 38

## Additional context
The error:

```
Can't locate Wx.pm in @INC (you may need to install the Wx module) (@INC entries checked: /home/joshu/perl5/lib/perl5/5.38.2/x86_64-linux-thread-multi /home/joshu/perl5/lib/perl5/5.38.2 /home/joshu/perl5/lib/perl5/x86_64-linux-thread-multi /home/joshu/perl5/lib/perl5 /usr/lib/perl5/5.38/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.38/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.38/core_perl /usr/share/perl5/core_perl) at /home/joshu/perl5/bin/wxchordpro line 12.
BEGIN failed--compilation aborted at /home/joshu/perl5/bin/wxchordpro line 12.
```

**Comment by sciurius** [comment]
Hard to comment on without the exact logs of "install chordpro" and "install Wx". In general installing Wx using cpan will fail, leading to the error you get.

Please use the [prebuilt kit](https://chordpro.org/dl/ChordPro-Installer-6-50-10-2-msw-x64.exe) instead.

**Comment by joshpetit** [comment]
Thank you for the quick response! Do you have the prebuilt kit in an ELF? Something Linux compatible?

**Comment by sciurius** [comment]
Most Linux distributions provide prebuilt packages for several of the requirements for ChordPro, most notably Wx and PDF::API2. See https://www.chordpro.org/beta/chordpro-install-on-linux/#installation-on-linux.
