### ISSUE TITLE
Treatment of *^ in chord grid text

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#409]
If I have `*^` in the 'comment area' left of a chord grid, it's still treated as a memorised chord, although I'd expect it to be treated as an annotation, same as in the body of the chord grid.

**Example**
```
{start_of_grid: 2+4x3+2}
*^ Soft Inst | *^~Eb~~ . . | Gm/D . . | Ab/C . . | Bb . . |
| Eb . . | Gm/D . . |
{end_of_grid}
```
gives error
```
"It_s_Oh_So_Quiet.cho", line 58, No chords memorized for grid
	*^ Soft Inst | *^~Eb~~ . . | Gm/D . . | Ab/C . . | Bb . . |
Can't call method "chord_display" without a package or object reference at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/Output/PDF/Grid.pm line 50.
```
It's only the _first_ instance of `*^` that triggers the error, which goes away if I delete that instance. The second (within the grid body) causes no error. Same thing happen if it's in the comment area _right_ of the grid body. Arose originally with my complicated custom configs, but the same issue arises running ChordPro simply with `-X` config option.

**Rationale**
My editorial convention uses `^` (in pairs) to designate 'cue points' for BVs or where the end of a verse overlaps the start of an instrumental (as here). I accept that it could conflict with the chord memory feature, so - if there's a risk of that - I treat `^` as an annotation by preceding it with `*`. That approach seems to break for `*^` used in comments left or right of a chord grid.

**Solution?**
My expectation was that this usage of `*^` should also be treated as an annotation. However, I then thought that it's arising within an area used for text, not chords. So, that might offer two possible solutions:

1. Treat `*anything` as an annotation and ignore any chord memory or other chord processing features (just as in grid body).
2. Interpret _everything_ left or right of the chord grid body as literal text and don't apply chord processing.

But, there might be legitimate cases where a chord is used in that comment area, and should be, say, transposed, so maybe there's still some need recognise and process possible chords in the comments area, in which case 1. might be the safer solution.

It's not an urgent issue, as I ended up taking a different approach, but maybe worth noting for low-priority tidy-up work.

**Comment by sciurius** [comment]
> but the same issue arises running ChordPro simply with -X config option.

Nope. Unless you explicitly enable `settings.memorize`.

In _115 I've disabled memorize in grid sections.

**Comment by gwyndaf** [comment]
Sorry, my bad. Strictly, it was `-X --define settings.memorize=true` to enable the chord memory feature, but avoid the complexities of my own configs.

I can confirm that the issue goes away with _115
