### ISSUE TITLE
textblock background causes invalid (but functional) PDF

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#411]
No practical impact on output but, when I put ChordPro PDF output through ghostscript (to add/reinstate hyperlinks), I get a PDF validity error:
```
The following warnings were encountered at least once while processing this file:
	invalid operator used in text block

   **** This file had errors that were repaired or ignored.
   **** The file was produced by: 
   **** >>>> PDF::API2 2.047 (linux) <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.
```
Sample PDF is [Make_Me_Feel_Again.pdf](https://github.com/user-attachments/files/16645102/Make_Me_Feel_Again.pdf) using default config from [Make_Me_Feel_Again.cho.txt](https://github.com/user-attachments/files/16645114/Make_Me_Feel_Again.cho.txt)

I think I've narrowed it down to the textblock:
```
{start_of_textblock-guitar: id="introtab" textstyle="tab" textspacing=0.9 padding=3 border=0.25 background=#cccccc}
```
Specifically, if I remove the `background` setting, the problem goes away.

No such problem for an ABC score using `%%bgcolor #f8f8f8`, so I don't think it's backgrounds in general, but maybe something to do with how the textblock background get written to PDF, and possibly a `PDF::API2` issue rather than ChordPro.

**Comment by sciurius** [comment]
Does this issue still exist? I cannot reproduce it anymore.

FYI: Did you consider tools like `pdftk` or `cpdf` to do the PDF mangling?

**Comment by sciurius** [comment]
What do I need to produce the error using the [Make_Me_Feel_Again.pdf](https://github.com/user-attachments/files/16645102/Make_Me_Feel_Again.pdf) you sent earlier? Things like ps2ps and ps2pdf seem to be happy with it.

**Comment by gwyndaf** [comment]
Just ChordPro processing with `-X` default config of https://github.com/user-attachments/files/16645114/Make_Me_Feel_Again.cho.txt

Then `gs -o /dev/null -dNODISPLAY` on the output PDF file.

**Comment by sciurius** [comment]
Ok, I see. The problem is not visible in de PS files, but in the PDF there is:
````
BT
-3 -3 234 170 re
0.8 0.8 0.8 rg
f
...
````
`BT` means: begin text. `re` draws a rectangle, filled (`f`) with the bg colour (`rg`). Drawing is not allowed in text mode (although many viewers and printers seem to accept it).

I've changed the textblock code in 6.060_121 to not issue the `BT` until after the background is written:
````
-3 -3 234 170 re
0.8 0.8 0.8 rg
f
BT
...
````

This is really advanced stuff ☺.

**Comment by gwyndaf** [comment]
Ah, fantastic. My ability to cause advanced issues sadly isn't matched by my ability to diagnose them!

I can confirm that the warning has now gone away with 6.060_121, while PDF output remains unchanged and as expected.

**Comment by sciurius** [comment]
> My ability to cause advanced issues sadly isn't matched by my ability to diagnose them!

Do not underestimate yourself. You often provide detailed and to the point analysis, with experiments, test results, etc. It makes it easier for me to fix it.
