### ISSUE TITLE
Random font replacement

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#412]
Processing the same song repeatedly (using dev _115) results in randomly different PDF fonts, sometimes using Roboto (as per design/config), and sometimes FreeSans (unexpected).
[It_s_Oh_So_Quiet (Ukulele C) git_GOOD.pdf](https://github.com/user-attachments/files/16645291/It_s_Oh_So_Quiet.Ukulele.C.git_GOOD.pdf)
[It_s_Oh_So_Quiet (Ukulele C) git_BAD.pdf](https://github.com/user-attachments/files/16645290/It_s_Oh_So_Quiet.Ukulele.C.git_BAD.pdf)

From this source: [It_s_Oh_So_Quiet.cho.txt](https://github.com/user-attachments/files/16645303/It_s_Oh_So_Quiet.cho.txt)
with this config: [config.json](https://github.com/user-attachments/files/16645308/config.json)

This feels like a repeat of a previous issues, I think #328.

I noticed that GNU core fonts are now bundled, maybe to replace Postscript default fonts, so it feels like some random switching between custom and default font configurations.

**Comment by sciurius** [comment]
The PDF is definitely not generated from this config. Apparently, `--print-final-config` is buggy ☹. Can you fix a config?

**Comment by sciurius** [comment]
But I can already confirm that we seem to have de #328 russian roulette again. See also https://groups.io/g/ChordPro/message/2448.

**Comment by gwyndaf** [comment]
> Apparently, `--print-final-config` is buggy

Ah, ok. That was my attempt to simplify matters!

In this instance, the three constituent configs are:

* Core: [chordpro.json](https://github.com/user-attachments/files/16646360/chordpro.json)
* Typography: [roboto.json](https://github.com/user-attachments/files/16646361/roboto.json)
* Instrument: [ukulele_c.json](https://github.com/user-attachments/files/16646363/ukulele_c.json)

I think my next step, hopefully tomorrow, is to test tweaking the `fontconfig` in `roboto.json`. I noticed similar behaviour in the tab font for another song, so now realise it may lie in the `sans, sans-serif` and `mono, monospace` entries, as with #328.

For ChordPro native purposes, I can use just `sans` and `mono`, but needed to include `sans-serif` and `monospace` for Lilypond and/or ABC delegates.

**Comment by sciurius** [comment]
I think I found the problems. Okay, I've said that before...

Please try `6.050_117` but **IMPORTANT** You also have to upgrade `Text::Layout` to `0.038`. It is on its way to the CPAN but you can also get it from git.

**Comment by gwyndaf** [comment]
Updated ChordPro to `_117` and `Text::Layout` to `0.038` from git, and looking good so far, with no sign of Free Sans turning up unexpectedly in PDFs.

That's with a batch run of several songbooks. I'll give it some stress-testing on individual songs tomorrow, and monitor it for a while.

**Comment by gwyndaf** [comment]
OK, I've spent most of the morning doing lots of work on songs and books, with regular ChordPro processing, and this doesn't seem to have returned, so it's probably resolved.
