### ISSUE TITLE
Remove ChordPro from presets

### ISSUE THREAD

**Issue by sciurius** [ChordPro/chordpro#413]

**Comment by Desbeers** [comment]
Now the ‘chordpro’ preset is hidden from the GUI, hardcoded. It would be nice if it is moved out of `config`. Like in a new `defaults` for example? Then (in *Config.pm*):

		my $config = CP->findres( "chordpro.json", class => "config" );
		
would be:
		
		my $config = CP->findres( "chordpro.json", class => "defaults" );

Looks like a nice solution but I did not really looked into the code and it might break custom configs in `~/.config`?

**Comment by sciurius** [comment]
Yes, that may be something that is worth to consider. However for the time being I would like to keep it as it is now. The config stuff is already far too complex and it may need a more thorough overhaul.

**Comment by sciurius** [comment]
Good point. 6.060_004 adds dark and removes the other files.
