### ISSUE TITLE
Feature request: Header (text above title)

### ISSUE THREAD

**Issue by daysm** [ChordPro/chordpro#43]
Or is there any way I can add text above the title that I'm missing?

**Comment by sciurius** [comment]
If it is a single line, you can use any {meta} item and configure it to appear above the title.

Can you give an example of what you are trying to achieve?

**Comment by daysm** [comment]
I'm trying to put artist & composer above the title. Ideally in a way analogue to the footer (with three parts). If that's not possible, how would I go about configuring a {meta} item to appear above the title? Would I have to add it to formats in the config file? I'm getting a config error `Config error: unknown item pdf.formats.title.header` when trying to add a new item there.

**Comment by sciurius** [comment]
If all you need are composer and artist, there are two easy steps involved.

In the configuration (see https://www.chordpro.org/chordpro/ChordPro-Configuration-PDF.html#page-headers-and-footers), copy the current title contents into the subtitle parts and place your desired information in the title parts.

For example, this:

        "title" : {
            // Title and subtitle.
            "title"     : [ "", "%{title}", "" ],
            "subtitle"  : [ "", "%{subtitle}", "" ],

would become

        "title" : {
            // Title and subtitle.
            "subtitle"  : [ "", "%{title}", "" ],
            "title"     : [ "%{artist}", "", "%{composer}" ],


(See https://www.chordpro.org/chordpro/ChordPro-Configuration-PDF.html#fonts): Exchange title and subtitle fonts, or add a subtitle font.

For example, this:

        "fonts" : {
            "title" : { "name" : "Times-Bold", "size" : 14 },

would become

        "fonts" : {
            "title" : { "name" : "Times-Roman", "size" : 11 },
            "subtitle" : { "name" : "Times-Bold", "size" : 14 },


So the first line on a page, title, will contain artist and composer, and shown using the (smaller) subtitle font.
The second line, subtitle, will show the title using the title font.

**Comment by daysm** [comment]
Thank you. This works.
