### ISSUE TITLE
Error from PDF.pm line 2743

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#437]
Seems a very niche case, but I'm getting this error with dev _057:
```
Not an ARRAY reference at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/ChordPro/Output/PDF.pm line 2743
```
Test song: [Empty.cho.txt](https://github.com/user-attachments/files/17266947/Empty.cho.txt)

Processed with configuration of default (`-X`) plus [no_footer.json](https://github.com/user-attachments/files/17266949/no_footer.json).

With the test samples, the error goes away if I remove the newlines following `{title: }` in the file. So perhaps it's something to do with the extra newlines.

The error originally occurred on this song (processed with same config as above)
[Wombling_Merry_Christmas.cho.txt](https://github.com/user-attachments/files/17266961/Wombling_Merry_Christmas.cho.txt)
and continues to occur even when the song's stripped back to just
```
{title: Wombling Merry Christmas}
{meta: vocalnote e}
```
_But_ if I process that same two-line song with my custom config (where the `{meta}` are defined, I get no error. Maybe an unknown `{meta}` gets replaced with a blank line, i.e. another newline character after `{title}`. That might confirm it's about extra newlines somehow.

However, it doesn't explain why the error occurs with the full form of the song (or many others), where the `{title}` line is simply followed by my usual `{artist}` etc. lines.

Sorry I can't seem to narrow it down more precisely, but hope that's useful information.

**Comment by sciurius** [comment]
The problem arises when the page footer is produced. 

The value `false` for the footer was not properly handled. This is fixed in _059.

I can't explain the (perceived) relation to the meta definitions...

**Comment by gwyndaf** [comment]
Great, issue now seems to have gone with _060.
