### ISSUE TITLE
Support for other notations than english

### ISSUE THREAD

**Issue by d3jv** [ChordPro/chordpro#438]
Hi,

I'd like for my saved songs to be in german notation but it seems like this is not possible to do in ChordPro. Chords like `[Hmi]` are simply not recognised even with the `--transcode=german` flag.

Is the only option here to write the chords in english notation and have it be transcoded to a different notation (essentially having to remember what the chords are in english so that they are displayed correctly)?

I tried defining new chords by putting the following into the config file, but I cannot override the display name of the copied chord and I would have to manually enter a huge amount of chords anyways.

```json
"chords" : [{
      "name"    : "Ami",
      "copy"    : "Am",
      "display" : "Ami",
  }],  
```

**Comment by sciurius** [comment]
Did you read [this](https://www.chordpro.org/chordpro/chordpro-configuration-instrument/#root)?

**Comment by d3jv** [comment]
> Did you read [this](https://www.chordpro.org/chordpro/chordpro-configuration-instrument/#root)?

I did not. I wasn't able to find this guide on the website (and I still can't, does the sidebar menu contain all the links?).

Thanks, now I understand it a little better.

It seems like having `mi` as the suffix for minor instead of `m` is not possible with the config?

**Comment by sciurius** [comment]
> It seems like having mi as the suffix for minor instead of m is not possible with the config?

Correct, this can not yet be handled in the config.

I've added `mi` as an allowable minor quality in the parser code.

**Comment by sciurius** [comment]
So, should `mi` stay or should it go?

**Comment by AnniePerson** [comment]
mi should stay. It is common and recommended by Brandt / Roemer. I just wondered why d3jv insisted in using Hmi, the combination of German H with mi is very unusual.

**Comment by sciurius** [comment]
Ok.
