### ISSUE TITLE
Error in wiki?

### ISSUE THREAD

**Issue by funkydan2** [ChordPro/chordpro#44]
In the wiki regarding the PDF configuration options, should the example for [Chord Diagrams](https://www.chordpro.org/chordpro/ChordPro-Configuration-PDF.html#chord-diagrams) say that the keyword is *diagram* or *diagram**s***? 

i.e. does the json need to read
```
{"pdf" : 
  "diagrams" : {"show" : "right"}
}
```
When I used *diagram* as the keyword, ChordPro gave an error.

**Comment by sciurius** [comment]
Fixed the docs, thanks!

**Comment by funkydan2** [comment]
Great. I would have fixed the wiki myself, but I wasn't sure where the problem lay!

**Comment by sciurius** [comment]
No problem...!
