### ISSUE TITLE
CSV data for non-song entries (TOC, front/back matter) - used for MobileSheets import

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#440]
Fairly niche and low-priority (and a bit complicated to describe), but I noticed a couple of possible issues or improvements. These relate only to _non-song_ pages, like TOC and front/back matter, in CSV output.

Here's an example
```
title;pages;sort title;artists;composers;collections;keys_orig;keys;key_record;chord_count;chord_list;years;tempos;signatures;albums;youtube;edit_contributor;edit_source;source types
__table_of_contents__;1-2;Table of Contents;ChordPro;;;;;;;;;;;;;;;biscuit
All I Want For Christmas Is You;3;;Mariah Carey;Mariah Carey & Walter Afanasieff;TEST collection;G;G;;8;G|Em|C|D|Cm|B7|E7|Am7;1994;75;4/4;TEST album;https://youtu.be/yXQViqx6GMY;;;biscuit
Deck The Halls (Nos Galan);4;;;trad. C16 Welsh|Talhaiarn, Thomas Oliphant;TEST collection;F;G;G;6;C|G|D|Am|Em|A7;1862;108;4/4;TEST album;https://youtu.be/lWAm_sz9y4s;Alyn;;biscuit
```
**1. `title` and `sort title` data reversed?**
a. My CSV output has "\_\_table_of_contents\_\_" in the `title` column, and "Table of Contents" in `sort title` (no custom config settings affect those fields). In MobileSheets, for instance, that means the human-friendly title isn't actually the one displayed. Equally, using "Front Matter" to sort puts it part-way into an album or collection, not at the start. Should these data items be the other way around?

b. As a secondary point, should the `sort title` values be such that pages sort (in MobileSheets etc.) in the order that reflects PDF page order?

* front matter sort value (e.g. '\_\_front_matter\_\_')
* TOC sort value (e.g. '\_\_table_of_contents\_\_')
* [all the songs, according to `sorttitle`]
* back matter sort value (e.g. '\_\_back_matter\_\_') ← maybe the main issue

I'm sure it's impossible to be absolutely sure that the leading characters sort lower or higher than the `sorttitle` of all songs, especially considering digits, different languages and character sets in titles, but could help ensure that entries in MobileSheets have a reasonable chance of being sorted in the same order as the original PDF.

**2. `meta` value from command line not translating into non-song CSV entries**
If I have a `csv.fields` entry defined using `name=albums, value=MyAlbum`, that value appears as expected in CSV output for all entries (song and non-song). However, if it's defined in the config with e.g. `name=albums, meta=album`, and I pass `--meta album=MyAlbum` via the command line, that _doesn't_ appear in `albums` field for non-song CSV entries, but it's there for song entries.

Because I create the each songbook in editions for different instruments, my current approach is a batch process that uses songbook-specific layout/design configs, with different instrument configs (only chord diagrams). For data that relates to both songbook _and_ instrument (e.g. "MyAlbum for Guitar"), it seems simplest to set that metadata via the command line (otherwise I need a separate config for each songbook/instrument combination). This approach translates the `album` metadata into CSV data for song entries, but not for non-song entries.

**Background/scenario**
MobileSheets will split my songbook PDFs into individual songs, based on CSV data. This works nicely, and I've had no need to include non-song pages, so config has had `csv.songsonly=true`. My ChordPro batch processing sets the `album` (->`albums`) meta value via CLI, to reflect both the songbook name and instrument, so a songbook imports automatically into MSP in a single album name, which reflect both songbook and instrument (for guitar, piano, ukulele etc.).

Since most users have just regular PDF reader apps, each page has a 'home' hyperlink back to the TOC, added in ghostscript post-processing of PDFs. In technical PDF terms, the 'home' link's destination is a "Contents" bookmark, which my annotation script defines as the first page after my front matter (_i.e._ first ChordPro output page), which is usually p.4.

If (in MSP) I load all songs in an album (_i.e._ songbook), and tap the 'home' link on a song, it takes me to another song in the loaded album. Seems weird at first, then I realise it's jumping to the 4th (one-page) song, so essentially p.4 of the loaded album. I'm guessing that MSP doesn't handle PDF bookmarks directly but - when importing PDFs - maybe converts them into specific page numbers. So it's _trying_ to jump to where it thinks the TOC page should be. That would be really neat if the pages and order in my MSP album exactly match the whole PDF, but they don't so navigation gets confused.

So, I set `csv.songsonly=false` in ChordPro, to include TOC and front/back matter in the album, but then discover that they're not automatically included as entries in the MSP album (2. above) and, when I find them amongst the general body of songs, they're not displayed with human-friendly titles or sorted by "\_\_" sort titles (1. above).  If I manually edit the album's sort order in MSP, so Front Matter then Table of Contents come first, the 'home' link behaves as expected (because TOC now starts on p4, which is probably the link's destination within MSP). So, it seems like MSP's handling of internal songbook links could be really useful, if CSV data put songbook sections in the expected order.

The back matter sort order isn't a direct issue in this scenario, _except_ if sorted on the existing "\_\_back_mater\_\_" value, it would come first, and push up the page numbers of front matter and TOC in MSP,  so TOC doesn't start on p4, and 'home' links instead jump to somewhere in the front or back matter.

None of this is essential. I can work around 2. by manually editing song data in MSP import, to set the album name for all pages (not just songs), although it adds a little friction to the process each time I import a songbook update. I can also work around 1. by manually editing each CSV file exported by ChordPro, but that adds quite a lot more friction to the process.

**Comment by sciurius** [comment]
Long story, thanks for taking the time and effort to compile it.

1.a. You are right about the table of contents titles. They have a title, so this should be used in the CSV.
Front- and back matter do not have titles, so `__front_matter__` or (better?) `(Front Matter)` would be suitable substitutes.

1.b. I'm not sure. I seldom see songbooks that have all their songs in sorting order. Realbooks often insert newer material at the end, so the first 90% is in sort order and the rest is not.

When you load a PDF+CSV in MSPro you are basically working with individual songs and the relative order does not matter. Or should not.

2. Fixed in 6.060_119.

Note that the numbering is (still) off when there is more than one table of contents.

I need to experiment with the MSPro page number business. Stay tuned.

**Comment by gwyndaf** [comment]
OK, with 6.060_121:

1.a. Display titles are now in the form 'Table of Contents', 'Front Matter, 'Back Matter', and the same values used for sort title. I like your idea of parentheses for (Front Matter) and (Back Matter), because they're not strictly page titles.

1.b. Fair enough. I agree that, for most normal usage, once individual songs are split out from a songbook PDF, 'navigational control' then falls to MSP. However, it seems that MSP still tries to respect hyperlinks on imported pages, which then creates both possibilities and challenges!

A more general example than my 'Home' button is the hyperlinked titles in the PDF's Table of Contents, which MSP tries to honour. If I split my PDF songbook into a single album, then 'load all' pages in that album (including TOC/Front/Back), TOC hyperlinks still jump to a song, but the wrong one. Probably because pages aren't in the same order as the PDF, and the discrepancy is largely explained by TOC/Front/Back pages not falling in the same sequence as in the PDF, on which page order the hyperlinks are based.

_I've now solved this, though._ In an MSP album, the 'Sort: Manual' option seems to default to sorting by the original page numbers (from CSV), which is exactly what I need. So, if the whole album is loaded, my ToC and Home hyperlinks behave exactly like the original PDF, and link the right page. It's not a major use case, but just squeezes a bit more value out of the ChordPro/MSP combination :)

2. Metadata passed via command line now gets included in CSV for TOC and Front/Back matter (as well as songs). In my case, that's `album`, so this ensures that TOC/Front/Back Matter are included alongside the songs.

I get no problem with page numbering for multiple TOC sections. I have two - a one-page quick contents, then full contents listed over four pages. CSV shows pp1-3 for Front Matter, pp4-8 for Table of Contents, which is exactly what I expect.

**Comment by sciurius** [comment]
Good to hear!

> pp4-8 for Table of Contents, which is exactly what I expect.

With two ToCs, I would expect e.g. pp5-6 for "Table of Contents", and pp7-8 for "Contents by Artist". But as long as you're happy ☺.

**Comment by gwyndaf** [comment]
Yes that works nicely for me, thanks!

Essentially, it means I can get the benefits of my PDF design (compact TOC and Home button) for quick navigation, combined with MSP benefits like using BPM to set the metronome, so it's a neat combination.

I don't have any particular need to itemise different TOCs, so I think this is probably done.
