### ISSUE TITLE
[N.C.] and {transpose}  (for keyboard) cause warnings; and error in ChordPro output format

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#441]
Flagging as a possible bug, though I can work around it. Don't know if this relates to #254 

Generating ChordPro output with `keyboard` config, when a song includes `[N.C.]` and `{transpose}` directive gives no output and and this error:
```
Can't call method "has_diagrams" on an undefined value at /usr/local/share/perl/5.38.2/ChordPro/Output/ChordPro.pm line 369.
```
I can easily avoid the error, and generate output, by adding `--diagrams=none` to the command, as I don't need diagrams defining in this case.

With PDF output, I'm fairly used to those same conditions generating just a warning:
```
Cannot parse/transpose chord "N.C."
```
That doesn't trouble me, but I thought an error and processing failure worth mentioning.

**Comment by sciurius** [comment]
I changed the way NC are handled in 6.060_120, can you check?

**Comment by gwyndaf** [comment]
My apologies, Johan. I think my previous testing for fretted instruments might have been too limited (i.e. guitar only). No problem for keyboard, as the main focus of this issue.

This still works nicely with `N.C.` entries removed from my config for guitar, but I've also removed `N.C.` entries from other instrument configs and they now throw up "No chord diagram defined" and transposition errors.

I'm guessing the reason I don't get errors with guitar is that my custom config builds on the defaults, including the built-in `guitar.json`, which has entries that define `N.C.`. 

It's not really a problem, as I can just continue to include `N.C.` in my custom configs for fretted instruments, but just noting the observation, if only as a correction to my previous over-optimistic test results!
