### ISSUE TITLE
Chordpro 6.060.073 from github : failed make

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#446]
~/ABC_bin/ChordPro/chordpro-6.060.073$ ../do-cpro
make -C lib/ChordPro/Wx
make[1]: Entering directory '/home/timm/ABC_bin/ChordPro/chordpro-6.060.073/lib/ChordPro/Wx'
make[1]: *** No rule to make target 'PreviewPanel.wxg', needed by 'PreviewPanel_wxg.pm'.  Stop.
make[1]: Leaving directory '/home/timm/ABC_bin/ChordPro/chordpro-6.060.073/lib/ChordPro/Wx'
make: *** [GNUmakefile:91: wxg] Error 2

**Comment by sciurius** [comment]
That should be fixed in _074.

**Comment by timmbo9** [comment]
Thanks
