### ISSUE TITLE
"sudo cpan chordpro" under MacPorts may result in "chordpro: command not found"

### ISSUE THREAD

**Issue by bradgrantham** [ChordPro/chordpro#45]
After "sudo cpan chordpro" on my MacOSX 10.13.4 installation, "chordpro" from bash results in "command not found".

```
ganymede:~ grantham$ sudo cpan chordpro
...
  /usr/bin/make install  -- OK
ganymede:~ grantham$ chordpro
-bash: chordpro: command not found

```

Further, here are the places a "chordpro" file was located on my machine after what looks like a successful installation:
```
ganymede:~ grantham$ find / -name chordpro 2>/dev/null
/opt/local/libexec/perl5.26/sitebin/chordpro
/Users/grantham/.cpan/build/App-Music-ChordPro-0.94-0/blib/script/chordpro
/Users/grantham/.cpan/build/App-Music-ChordPro-0.94-0/script/chordpro
```

I would guess "/opt/local/libexec/perl5.26/sitebin/chordpro" is probably the tool and I'm not sure why it wouldn't have been installed in "/opt/local/bin".

Note that I have MacPorts installed, and I have /opt/local/bin in my path before /usr/bin in order to pick up the MacPorts installation for a bunch of utilities.  "cpan" is "/opt/local/bin/cpan"

After running "sudo /usr/bin/cpan chordpro", I'm able to run "chordpro" from the command line.

Probably this could be resolved by
1. noting in the wiki that MacPorts users should run the system "cpan", which is probably "/usr/bin/cpan", and possibly
2. Trying to diagnose why installing chordpro in MacPorts doesn't result in a binary in /opt/local/bin

Thank you for the hard work!  I'm looking forward to rendering all my old chord transcriptions!

**Comment by sciurius** [comment]
Thanks for your valuable input. Not having an OSX system means that I'm dependent on user inputs.

If you need to manually add paths to use MacPorts, I guess that you need to add `/opt/local/libexec/perl5.26/sitebin` as well as `/opt/local/bin` to your execution path. 

When running `/usr/bin/cpan` you use the system provided tool, which will install in locations already accessible from your path.

I've modified the docs in the wiki, feel free to further enhance the page!
https://github.com/ChordPro/chordpro/wiki/ChordPro-Install-on-Mac-OSX

**Comment by bradgrantham** [comment]
Your changes to the wiki look good!

I think I'll close the issue and continue as if I have a nonstandard macports installation.  With this issue on the record, if someone else has a problem, maybe in the future this can precipitate another look into the details.

Thank you!
