### ISSUE TITLE
Words get split with long chord names

### ISSUE THREAD

**Issue by spakarl** [ChordPro/chordpro#453]
The following fragment splits the word bad and had. Is there a way to avoid the big gap?
```
{start_of_verse: Verse 2}
[C]All the time I th[G/B]ought [Gm/Bb]  that I was wr[A7sus]ong [A7]
[Dmadd9]Wanting to believe but ne[Dm7]eding to belo[G7sus]ng[G/F]                      
[Em7]  If I'had j[E7]ust believed in a[Am]ll [G]I h[Fm7][F6]ad
If s[C/E]omeone would have s[Am7]aid "you're not so ba[D7sus][D7]d" [F/G]
{end_of_verse}
```
[Test.pdf](https://github.com/user-attachments/files/17679602/Test.pdf)

**Comment by sciurius** [comment]
Take `h[Fm7][F6]ad`. You have an `h`. then an `Fm7` chord, then an `a` with chord `F6` and a `d`. To make room for the `Fm7`, space is added between the `h` and the `a`.

This already looks better:
````
in a[Am]ll [G]I [Fm7]ha[F6]d
````
Even better with a split marker, e.g.
````
pdf.split-marker: [ "", "-", ""]
````
![scrot20241108172850](https://github.com/user-attachments/assets/9c1f0a0a-c783-4599-83f5-0cd0a195a5d4)

Documentation in the default config:
````
  // Split marker for syllables that are smaller than chord width.
  // split-marker is a 3-part array: "start", "repeat", and "final".
  // "final" is always printed, last.
  // "start" is printed if there is enough room.
  // "repeat" is printed repeatedly to fill the rest.
  // If split-marker is a single string, this is "start".
  // All elements may be left empty strings.
  split-marker : [ "" "" "" ]
````

**Comment by spakarl** [comment]
Thanks for the tip!
