### ISSUE TITLE
Unable to use italic font in embedded Lilypond section

### ISSUE THREAD

**Issue by edonv** [ChordPro/chordpro#455]
## Describe the bug
I'm trying to use an italic font for chord names in an embedded Lilypond section, so it can mirror the rest of my ChordPro file, but I can't get it to render italics, no matter what font. I've tested with multiple fonts, and though different font weights work, italics in any of the fonts is either ignored or causes it to reject the font altogether.

I've also tested the exact same Lilypond content (with the intended font) directly through `lilypond` CLI and italics work without issue. I even tested this with the temp `.ly` file ChordPro creates to embed the section, and it works without issue.

Additionally, embedded Lilypond actually does read the font from the ChordPro config `pdf.fontconfig` (in this case I'm using `sans`), but it still won't take the italic version.

### To Reproduce
I've tested:
- Directly setting the `font-name`, which overrides font family, weight, slant, etc.
- Overrides the font used for the `sans` font `font-family`, paired with `font-series = #'bold` and `font-shape = #'italic`.

#### Lilypond formatting (setting font name directly)
```
\layout {
  \context {
    \ChordNames
    \override ChordName.font-name = "Roboto Bold Italic"
  }
}
```

#### Lilypond formatting (setting font family)
```
\paper {
  #(define fonts
    (set-global-fonts
     #:sans "Roboto"
    ))
}
\layout {
  \context {
    \ChordNames
    \override ChordName.font-family = #'sans
    \override ChordName.font-series = #'bold
    \override ChordName.font-shape = #'italic
  }
}
```

#### Lilypond content:
```
\score {
  <<
    \chords {
      g1 e:m c d
    }
    \new TabStaff \relative {
      \omit Staff.Clef
      \numericTimeSignature
      \repeat volta 2 {
        \bar ".|:"
        a8\glissando b4.\3~ b4\3 \grace { \once \omit Stem \stemDown e8\2 \glissando \stemNeutral } fis4\2 |
        e1\2 |
        a,8\3 ( g4.\3)~ g4 a8\glissando d\3~ |
        d\3 d\3( c\3) c\3( b\3) b\3( a\3) a\3 |
      }
    }
  >>
}
```

### Attachments
```
{start_of_ly}
\layout {
  \context {
    \ChordNames
    \override ChordName.font-family = #'sans
    \override ChordName.font-series = #'bold
    \override ChordName.font-shape = #'italic
  }
}

\score {
  <<
    \chords {
      g1 e:m c d
    }
    \new TabStaff \relative {
      \omit Staff.Clef
      \numericTimeSignature
      \repeat volta 2 {
        \bar ".|:"
        a8\glissando b4.\3~ b4\3 \grace { \once \omit Stem \stemDown e8\2 \glissando \stemNeutral } fis4\2 |
        e1\2 |
        a,8\3 ( g4.\3)~ g4 a8\glissando d\3~ |
        d\3 d\3( c\3) c\3( b\3) b\3( a\3) a\3 |
      }
    }
  >>
}
{end_of_ly}
```
Lilypond directly:
<img width="533" alt="Lilypond directly" src="https://github.com/user-attachments/assets/aa80a2f0-dbeb-4fd3-a964-23571847f5bf">

Embedded in ChordPro file:
<img width="566" alt="Embedded in ChordPro file" src="https://github.com/user-attachments/assets/ad4b55b9-9591-4971-8032-15f1563be693">

## System information
- OS: macOS Sonoma 14.5
- Where did you get ChordPro from? macOS build
- ChordPro version: 6.060
- Perl version: 5.30.3

## Additional Notes
Looks like the tablature font is different, but that's not a big deal, I actually am very happy with the font that ChordPro provides for Lilypond's tablature.

**Comment by sciurius** [comment]
You have found a subtile but nasty bug in the SVG renderer that ChordPro uses. I will fix that for the next version.

In the mean time, you can try the following workaround:

-- config file:
````
pdf.fontconfig.sansbolditalic {
      ""         : Helvetica-BoldOblique
      bold       : Helvetica-BoldOblique
      italic     : Helvetica-BoldOblique
      bolditalic : Helvetica-BoldOblique
}
````

and in the LilyPond fragment:
````
  \context {
    \ChordNames
    \override ChordName.font-name = "sansbolditalic"
  }
}
````

**Comment by sciurius** [comment]
https://github.com/sciurius/perl-SVGPDF/issues/10

**Comment by edonv** [comment]
That workaround worked! Thanks!

**Comment by sciurius** [comment]
Fix will be included in the next release.
