### ISSUE TITLE
make error 6.060.138

### ISSUE THREAD

**Issue by timmbo9** [ChordPro/chordpro#457]
~/ABC_bin/ChordPro/chordpro-6.060.138$ ../do-cpro
make -C lib/ChordPro/Wx
make[1]: Entering directory '/home/timm/ABC_bin/ChordPro/chordpro-6.060.138/lib/ChordPro/Wx'
make[1]: *** No rule to make target 'ColourSettingsDialog.wxg', needed by 'ColourSettingsDialog_wxg.pm'.  Stop.
make[1]: Leaving directory '/home/timm/ABC_bin/ChordPro/chordpro-6.060.138/lib/ChordPro/Wx'
make: *** [GNUmakefile:91: wxg] Error 2

**Comment by sciurius** [comment]
Thanks. Fixed in_140.
