### ISSUE TITLE
Directive arguments question/discussion

### ISSUE THREAD

**Issue by Desbeers** [ChordPro/chordpro#465]
I’m currently writing a (Swift) parser for a **ChordPro** song and got a bit confused about the (most?) ‘correct’ syntax for adding arguments to directives.

Take `{start_of_chorus}` for example (all works well in the official ChordPro parser):

1. {start_of_chorus Refrein}
2. {start_of_chorus: Refrein}
3. {start_of_chorus label=Refrein}
4. {start_of_chorus: label=Refrein}
5. {start_of_chorus label="Refrein"}
6. {start_of_chorus: label="Refrein"}

The documentation is not always consistent and the song *cases* in the source use all kinds of variations (but I think that’s where the *cases* are for).

Anyway, for me, only no. 2 and 6 are truly correct. Correct?

My current ‘rule of thumb’:

- Any argument to a directive should start with a ‘:’ after its directive. Always.
- When using the more advanced `key=value` style, any value that is a *string* must be surrounded by brackets (") and any value that is an *integer* should not.

The GUI in ‘dev’ already gives very nice warnings for incorrect syntax in the source. My goal is to make it more strict for arguments (and lines without a specific environment). It should not *break* current documents, but it should give a warning.

Then my *final* goal would be a GUI option to ‘clean’ a document in the most correct **ChordPro** style.

Cleaning will:

- Replace ‘short’ directives for ‘long’ ones (I just don’t like ‘short’ ones; **ChordPro** should be readable as source).
- Wrap sections (group of lines) without a defined environment into the most fitting environment. So, lines with words and chords should be a ‘verse’, surrounded by `{start_of_verse}{end_of_verse} for example.

My personal preference is to be *strict* with the implementation. There should not be too many ways to add arguments. Its either very simple (no 2 in my list) or with `key=value` (no 6 in my list), different for *strings* and *integers*.

Thoughts?

**Comment by sciurius** [comment]
Part1a.

I intend to maintain old and new syntax as alternatives. For example, these are equivalent:
````
{start_of_verse: Eerste couplet}
{start_of_verse label="Eerste couplet"}
````
But while you can have
````
{start_of_verse label="Eerste couplet" chords="Am C/E C D7 F"}
````
this will be disallowed
````
{start_of_verse: Eerste couplet chords="Am C/E C D7 F"}
````
because it will quickly get confusing.

**Comment by sciurius** [comment]
Part 2.

As for your goal to write a ChordPro cleanifyer, ChordPro already does this with `--generate ChordPro`. Well, mostly. There is an internal provision to _structurize_ the ChordPro AST but this is lagging behind in the current ChordPro output backend. It is functional in the HTML and LaTeX backends that, as you know, are mory strictly structure-based.

I already wrote about turning the ChordPro GUI inside-out so that the GUI runs in the exact same context as the CLI. This makes it possible for the GUI to use all kinds of ChordPro core functions like chord parsing and recognition, transposition, and incremental updating preview.

Your dedication to ChordPro is great and valuable. Together we made a decent GUI product for macOS and I liked the way we did it. I hope you enjoyed it, too.

If you ask my personal opinion I would like you to embrace Perl (it is more fun than Swift) and join the team (me ☺) to help improving the core, extending backends, and the user documentation.

**Comment by Desbeers** [comment]
(on topic)

Thanks for your long reply, constructive!

> Also, there is no syntactic reason for the colon except being *visually pleasing*. Just syntactic sugar.

Good point. I like it for a simple argument, *because* it is **visually pleasing**. I’m a GUI guy; also in source ☺.

For the `key=value` not anymore; because you are correct. *HTML style* does not have *sugar* and once you make your **ChordPro** directive advanced (so `key=value` style) you get no *sugar*.

> Also, values should always be quoted, even simple strings and numbers

You are correct again. I looked at it from a *programmer* point of view; *not* as an *HTML style* user.

So, my new preference:

(ignoring ‘meta’ for now)

- Number 2 (simple with an ‘:’)
- Number 5 (advanced, no ‘:’, with `key=value`)

We have to make choice for the *preferred* **ChordPro** style sooner or later and document it.

(off topic)

I’m a [Swiftie](https://en.wikipedia.org/wiki/Swifties) ☺. I like the language very much, its *strong typed* nature and its verbose *chained* methods. I’m truly in love with its `enum`s as well.

While `Perl` is not my thing that does not mean I cannot contribute to the *core*. The Linux kernel is welcoming `Rust` and there is a bit of `Swift` code in ‘dev’ already.

I see myself already part of the team; the GUI was just the beginning and I very much enjoyed it.

Thinking about JSON and AST stuff makes my brain boil in a very pleasant way. It is an universal language.

**Comment by sciurius** [comment]
Main reason for not discarding the colon is that it has been there from day 1.

[chord-3.6.pdf](https://github.com/user-attachments/files/17996004/chord-3.6.pdf)

**Comment by Desbeers** [comment]
> Main reason for not discarding the colon is that it has been there from day 1.

They should still be supported but not *encouraged* anymore. It is the evolution of a format.

While I (still) *do* like the visual pleasant colon for simple directives, consistency has a higher priority in my opinion.

The colon makes no sense in front of `key=value` stuff.

Anyway, my *Swift* parser does not like them anymore and gives a warning. I’m used to it now and when I ‘clean’ a document I actually don’t miss them.

Mainly because the colour-highlighting, that is also in wxChordPro now. Evolution :-)
