### ISSUE TITLE
allow base-fret > 11

### ISSUE THREAD

**Issue by OldGuit** [ChordPro/chordpro#47]
In a chord 'define:', currently, entering a base-fret value of 11 is fine. But a base-fret value of 12 or more causes the preview and the GUI to crash. Why can we not define chords formed on or above the 12th fret?

**Comment by sciurius** [comment]
Legacy, I think.
I've increased the limit to 23.

**Comment by OldGuit** [comment]
Brilliant -- thanks muchly.
