### ISSUE TITLE
Uppercase letter in fingers values in chord diagram for string instrument results in error

### ISSUE THREAD

**Issue by devnibo** [ChordPro/chordpro#471]
## Describe the bug

The documentation at `https://chordpro.org/beta/directives-define/#defining-chords-for-string-instruments` states that you can provide the fingers values in a chord diagram for a string instrument as uppercase letters in the range A-Z.
When I do that by defining a chord diagram like this ...
```
{define: E base-fret 1 frets 0 2 2 1 0 0 fingers - B C A - -}
```
... I get the following error ...
```
[~] chordpro test/fingers-with-letters.cho.txt
Argument "B" isn't numeric in numeric gt (>) at /usr/share/perl5/site_perl/ChordPro/Output/PDF/StringDiagram.pm line 297.
Argument "C" isn't numeric in numeric gt (>) at /usr/share/perl5/site_perl/ChordPro/Output/PDF/StringDiagram.pm line 297.
Argument "A" isn't numeric in numeric gt (>) at /usr/share/perl5/site_perl/ChordPro/Output/PDF/StringDiagram.pm line 297.
[~]
```

### To Reproduce
1. Download the provided test file
2. Run `chordpro fingers-with-letters.cho.txt`

### Expected behavior

I'm not sure what exactly should happen based on the documentation, but I thought an `A` would mean `1`, `B` means `2`, etc.

### Attachments

[fingers-with-letters.cho.txt](https://github.com/user-attachments/files/18022525/fingers-with-letters.cho.txt)

## System information
 - OS: Arch Linux
 - Where did you get ChordPro from? CPAN

 - ChordPro version: 6.060
 - Perl version: v5.40.0

**Comment by sciurius** [comment]
Thanks, fixed.
Values `1` .. `9` and `A` .. `Z` will be printed, everything else will be ignored.
