### ISSUE TITLE
Inline chord directive alignment is wrong inside sections that have descriptions.

### ISSUE THREAD

**Issue by polvoazul** [ChordPro/chordpro#473]
## Describe the bug
Inline chord directive alignment is not consistent with sections that have description.

### To Reproduce
```
{sov: Verse 1}
Hello darkness my old friend[Am]
{chord: Am}
{eov}

{sov: Verse 2}
Blablablabla[E]
Blablablabla
Blablablabla
balblalbab
{eov}
```

Results in:
<img width="260" alt="image" src="https://github.com/user-attachments/assets/0b402548-25b3-4abb-b4a1-fad79a0bf907">

### Expected behavior
![image](https://github.com/user-attachments/assets/bc29a5e7-4026-419d-8d62-66079eb8e3f9)

Notice that the chord is aligned on the left with the text (not using the space for section labels).

## System information
 Mac 
Run-time information:
  ChordPro core          6.060     
  Perl                   v5.40.0    (/opt/homebrew/Cellar/perl/5.40.0/bin/perl)
  Resource path          ~/.config/chordpro
                         /opt/homebrew/Cellar/perl/5.40.0/lib/perl5/site_perl/5.40/ChordPro/res
  ABC support            QuickJS_XS (ABC2SVG version v1.22.18_9b12853f66 of 2024-07-08)

Modules and libraries:
  Storable               3.32      
  Object::Pad            0.816     
  Text::Layout           0.038     
  File::LoadLines        1.046     
  PDF::API2              2.047     
  SVGPDF                 0.087     
  Font::TTF              1.06      
  JavaScript::QuickJS    0.21      
  JSON::Relaxed          0.097     
  JSON::XS               4.03

**Comment by sciurius** [comment]
This is a bug in 6.060 and already solved in the upcoming version.

As a work-around, move the `{chord}` out of the section:
````
{sov: Verse 1}
Hello darkness my old friend[Am]
{eov}
{chord: Am}

{sov: Verse 2}
Blablablabla[E]
Blablablabla
Blablablabla
balblalbab
{eov}
````

Currently this does not take the label margin into account. I'll fix that as well.

**Comment by polvoazul** [comment]
Thanks for the quick response and the workaround 👍. I have no rush, will wait for the new version.
