### ISSUE TITLE
3rd song lyrics lines overlap the label

### ISSUE THREAD

**Issue by DrCostas** [ChordPro/chordpro#482]
## Describe the bug

I have a .cho file with 3 songs. The 3rd song, regardless which one it is, has an issue where the lyrics lines have moved to the left and overlap the label. This happens with defaults (ie "ignore defaults" and "presets" being unchecked) and with presets. The position of the lyrics lines on the 1st and 2nd songs are also slightly different. Same issue with v 6.050.7 on a different computer.  Thanks for checking!

### To Reproduce
1. Open my chordpro file (had to rename it to txt to upload)  or copy-paste my song list (it is at the end)
2. Click "Tasks" then "Default Preview" (or control+p) 
3. Examine the last song
4. See how the lyrics line overlaps the label

### Expected behavior

All songs should appear identical.

### Attachments

Song attached, 1 PDF file with the "3rd song" showing the bug, and 1 PDF where i moved the 3rd song first so now the "2nd song" has the bug.
[test.txt](https://github.com/user-attachments/files/18138518/test.txt)
[Bug 1.pdf](https://github.com/user-attachments/files/18138515/Bug.1.pdf)
[Bug 2.pdf](https://github.com/user-attachments/files/18138516/Bug.2.pdf)

## System information
 - OS:  Linux Mint 22
 - Where did you get ChordPro from?  Debian sid https://packages.debian.org/sid/chordpro

I also had to get the latest libtext-layout-perl from there, too https://packages.debian.org/sid/all/libtext-layout-perl

 - ChordPro version: core 6.060
 - Perl version: v5.38.2   

Run-time information:
  ChordPro core          6.060     
  Perl                   v5.38.2    (/usr/bin/perl)
  Resource path          /usr/share/perl5/ChordPro/res

Modules and libraries:
  wxPerl                 0.9932    
  wxWidgets              3.002004  
  Storable               3.32      
  Object::Pad            0.808     
  Text::Layout           0.038     
  File::LoadLines        1.046     
  PDF::API2              2.045     
  PDF::API2::XS          1.002     
  SVGPDF                 0.087     
  Font::TTF              1.06      
  JSON::Relaxed          0.097     
  JSON::XS               4.03    

## Additional context

This chordpro text will produce the error on my system. Note that the songs are identical except the title. I have not installed any config files (nor changed them, I have no idea where they are)

{new_song}
{title: 1st song}
{start_of_chorus}
Swing [D]low, sweet [G]chari[D]ot,
Comin’ for to carry me [A7]home.
Swing [D7]low, sweet [G]chari[D]ot,
Comin’ for to [A7]carry me [D]home.
{end_of_chorus}
{start_of_test: label="Testing"}
I [D]looked over Jordan, and [G]what did I [D]see,
Comin’ for to carry me [A7]home.
A [D]band of angels [G]comin’ after [D]me,
Comin’ for to [A7]carry me [D]home.
{end_of_test}

{new_song}
{title: 2nd song}
{start_of_chorus}
Swing [D]low, sweet [G]chari[D]ot,
Comin’ for to carry me [A7]home.
Swing [D7]low, sweet [G]chari[D]ot,
Comin’ for to [A7]carry me [D]home.
{end_of_chorus}
{start_of_test: label="Testing"}
I [D]looked over Jordan, and [G]what did I [D]see,
Comin’ for to carry me [A7]home.
A [D]band of angels [G]comin’ after [D]me,
Comin’ for to [A7]carry me [D]home.
{end_of_test}

{new_song}
{title: 3rd song}
{start_of_chorus}
Swing [D]low, sweet [G]chari[D]ot,
Comin’ for to carry me [A7]home.
Swing [D7]low, sweet [G]chari[D]ot,
Comin’ for to [A7]carry me [D]home.
{end_of_chorus}
{start_of_test: label="Testing"}
I [D]looked over Jordan, and [G]what did I [D]see,
Comin’ for to carry me [A7]home.
A [D]band of angels [G]comin’ after [D]me,
Comin’ for to [A7]carry me [D]home.
{end_of_test}

**Comment by sciurius** [comment]
Good catch!

The problem was that the size used to calculate the label width was the last size used for this font in the previous song. 
So for the first song the width was based on Times 12, as desired, for the second song Times 14 (the last font used in the 1st song, for the title), for the third and subsequent songs it was Times 7.2 (the size used for the page number on the preceeding page).

This has been fixed now.

As a (temporary) workaround, you can set `pdf.labels.width` to a fixed value, e.g. `50`, instead of `auto`.

**Comment by DrCostas** [comment]
Thanks for the quick reply! That is a weird bug :) 

I found where to set that value. I changed the chordpro.json in /usr/local/share/perl/5.38.2/ChordPro/res/config as follows
  labels {
    **width : 50**
    align : left
    comment : ""
  }

Main issue is I have 3 places where this file exists, time to clean up my installations...
