### ISSUE TITLE
Preview Panel Behavior

### ISSUE THREAD

**Issue by mlos100** [ChordPro/chordpro#484]
Please consider the following:
- Change function of Preview button so that:
  - The preview is refreshed (same as Ctrl-P)
  - Presents the Preview panel if it is currently hidden
I found myself confused by the function of the View | Show Preview menu and Preview button being different.

- Change the menu items under View:
  - from "Show Preview" to "Preview Panel"
  - from "Show Messages" to "Message Panel"
The checkmark on the View menu items makes it clear that the action will cause the panel to be displayed or removed.

- If it is a high interest item to quickly show/hide the Preview Panel from the tool bar, consider making two buttons: one to Generate the Preview and one to show/hide the panel.

ChordPro Filename: 6-69-1-1
Windows 10

**Comment by sciurius** [comment]
@Desbeers Opinions?

**Comment by Desbeers** [comment]
> from "Show Preview" to "Preview Panel"

The ‘Show...’ wording is typical macOS style but normally its chancing  it label to ‘Hide...’ instead of showing a toggle. So I’m fine with a ‘... Panel’ label instead if that is more common on other platforms.

> If it is a high interest item to quickly show/hide the Preview Panel from the tool bar, consider making two buttons: one to Generate the Preview and one to show/hide the panel.

I think the tooltip is good enough for now. I don’t really like two ‘Preview’ related buttons in the toolbar. The three current buttons have a very clear goal. Show/hide stuff. Maybe a ‘notification’ when the preview is open and the content of the text has changed as alternative?

**Comment by mlos100** [comment]
> The three current buttons have a very clear goal. Show/hide stuff. 

Except the first time one clicks the Preview button. It's at that point the user (me, in this case)  is "trained" to expect it also generates the PDF representation. This is different from the first time View | Show Preview is selected and the Preview panel being shown with the chordpro logo filling the panel. (i.e., The user needs to identify the separate function to generate the PDF preview.

**Comment by Desbeers** [comment]
Oh, that seems like a (Windows?) bug to me. On my Mac (and Linux) the preview is also rendered when opening the preview panel for the first time. I never saw the chordpro logo filling the panel...

**Comment by mlos100** [comment]
It sounds like you understand. Since it seems like it might be Windows only, here's a screen shot of what I see when I select View | Show Preview immediately after opening a chord pro file.

<img width="659" alt="ViewShowPreviewFirstTime" src="https://github.com/user-attachments/assets/a4350010-9a61-49d9-a81a-f2ff213fc7ee" />

**Comment by sciurius** [comment]
This is on all platforms.
If you open the preview panel without having ganerated a preview, i.e. from the menu and not from the toolbar button, you get this image.

**Comment by Desbeers** [comment]
Ah, interesting!

It **only** does not render the PDF when opening an existing file and directly use `View -> Show Preview`.

If I use the big button, keyboard ‘command-P’ or `Task->Default Preview’ all works as expected.

All platforms behave different when directly go to `View -> Show Preview`:

- Windows gives the ‘ChordPro’ logo
- macOS gives a blank page
- Linux gives a ‘The URL can’t be shown’ message

**Comment by sciurius** [comment]
6.060_228 should give the logo on all platforms.

**Comment by sciurius** [comment]
6.060_229 will automatically generate a preview if there is none. No logo display.

**Comment by Desbeers** [comment]
Great! I build _229 and **all** seems fine.

@mlos100
Thanks for reporting this issue; you found a really good inconstancy and one of those cases that makes the difference between a *nice* GUI and a *great* GUI.

Keep on bug-hunting!

**Comment by mlos100** [comment]
Thank you for the encouragement.  And thank you all for this great update to the GUI!
