### ISSUE TITLE
RC2: Syntax Highlighting Quirk

### ISSUE THREAD

**Issue by mlos100** [ChordPro/chordpro#485]
**Severity**: Minor

When an existing chordpro file is opened and a directive is not at the start of a line (e.g., there is whitespace before the opening brace), no syntax highlighting is applied to the line. 
  - If the preceding whitespace is deleted, syntax highlighting is applied.
  - Adding whitespace before a directive that is highlighted has no effect during the current editing session. However, that line will not have syntax highlighting if the the file is saved, closed, and reopened.

Here's a forced example.
<img width="242" alt="spaceBeforeDirective" src="https://github.com/user-attachments/assets/b6323350-1e2e-4f97-bfbe-49123d00d1dc" />

If the argument is the lack of highlighting is a hint to delete preceding whitespace, then I counter that the highlighting should go away if whitespace is added before the start of the directive.

6.069_001 (RC2) (Filename: 6-69-1-1
Windows 10

**Comment by sciurius** [comment]
Thanks. Fixed in  6.060_223.

**Comment by Desbeers** [comment]
Build a fresh dev and after this fix, the editor shows some strange behaviour. Opening a fresh song gives red labels on empty lines.  When start typing, the red label moves in front of the cursor until I press 'enter'

Versions before 6.060_223 did not have this behaviour. It's both on macOS and Linux.

<img width="1012" alt="Screenshot 2024-12-22 at 15 02 21" src="https://github.com/user-attachments/assets/d17e4385-3183-4799-a661-b8bac0938a5e" />

**Comment by sciurius** [comment]
This should be fixed. Please check.

**Comment by mlos100** [comment]
Dev Version: : 6-60-233-1
Very nice. 
Directive is highlighted if there happens to be preceding whitespace.
Any preceding whitespace is highlighted with red in real-time.
Blank lines are not highlighted.
Closing as Resolved.
