### ISSUE TITLE
2 beta documentation suggestions

### ISSUE THREAD

**Issue by mlos100** [ChordPro/chordpro#486]
Page: [https://chordpro.org/beta/chordpro-getting-started-gui](https://chordpro.org/beta/chordpro-getting-started-gui/)
Section # Settings
- 2nd Para, 1st sent.: Change "are just start." to "just a start."

Page: [https://chordpro.org/beta/chordpro-gui-songbook/](https://chordpro.org/beta/chordpro-gui-songbook/)
Section: Editing Songs for the Songbook
- 1st Para, 1st sent: Change "If you crated" to "If you created"

**Comment by sciurius** [comment]
Thanks. Fixed in 6.060_224.

**Comment by mlos100** [comment]
Confirming resolution of pages at the links in the issue text.
