### ISSUE TITLE
RC2:  View | Show Preview menu selection and PDF Preview not clearing

### ISSUE THREAD

**Issue by mlos100** [ChordPro/chordpro#488]
**Severity:**  Minor

## Describe the bug
PDF Preview is not cleared when opening a new song

### To Reproduce
1. Steps to reproduce the behavior:
2. Start ChordPro GUI
3. Click Open an Existing Song.
4. Select an existing chordpro file and click Open.
5. Press the Preview button; the PDF preview appears.
6. Select File | Open and open another chord pro file  (or File | New to create a new song
7. Press No to save the preview.
8. Select an existing chordpro file and click Open.
9. The second song appears in the edit window; the Preview Panel is closed.
10. Select View from the menu bar.  The Show Preview menu item is SELECTED.
11. Select View | Show Preview. The Preview Panel appears and presents the PDF preview of the PREVIOUS SONG.

### Expected behavior
After opening a second song, I expect the PDF preview to be of the current song.

## System information
 - OS: Windows 10
 - ChordPro (filename) version: 6-69-1-1

## Additional context
1.  The Show Preview menu item selection is cleared if you go to the Start Screen and Create a New Song or Open an Example Song instead of an existing song.
2. The behavior in Step 11 may have been resolved by recent changes. Please check if the behavior in step 10 is still applicable.

**Comment by Desbeers** [comment]
Another excellent finding! I can reproduce it all on latest *dev* as well.

Its problem is again only in the `View` menu (both checkbox and old PDF issue). The ‘big buttons’ are doing fine.

@sciurius
I suggest just to remove the whole `View` menu part (for now) and let the ‘big buttons’ do the work. The keyboard shortcut for preview is in `Tasks` anyway so still available.

**Comment by sciurius** [comment]
Fixed in 6.060_232. Please check.

**Comment by mlos100** [comment]
Dev Version: : 6-60-233-1
1. After the second song is opened the preview panel is not displayed and the View | Preview Panel menu item is NOT selected.
2. When selecting View | Preview Panel on the second song, the PDF preview is generated and then displayed.
Closing as Resolved.
