### ISSUE TITLE
RC2: Nothing happens if Export to PDF selected before creating a PDF preview.

### ISSUE THREAD

**Issue by mlos100** [ChordPro/chordpro#489]
**Severity:** Minor

## Describe the bug
Nothing appears to happen if one tries to Export to PDF before creating a PDF preview on a song.

### To Reproduce

1. Start ChordPro GUI
2. Open an Example Song
3. Open the Messages Panel
4. Select File | Export to PDF
5. Nothing appears to happen.
6. Press the Preview button to create a PDF Preview.
7. The PDF Preview appears in the Preview Panel. A message that states preview file location is written.
8. Select File | Export to PDF
9. The Choose Output File dialog box appears.
10. Enter a file name; click OK.
11. The PDF file is written

### Expected behavior
I may want to just create a PDF for a chordpro file created in the past. Since File | Export to PDF is selectable (i.e., not greyed out), I expected to be able to generate the PDF file without having to create a PDF preview first.

## System information
 - OS: Windows 10
 - ChordPro version: 6-69-1-1

**Comment by sciurius** [comment]
Fixed in 6.060_232. Please check.

**Comment by mlos100** [comment]
Dev Version: : 6-60-233-1
When File | Export to PDF is selected prior to generating a PDF preview, a warning dialog appears with the message, No preview to save.
Closing as Resolved.
