### ISSUE TITLE
Inline comments, tempo

### ISSUE THREAD

**Issue by fechdj1** [ChordPro/chordpro#49]
Hi,

I'm new to Chordpro.
It's a fantastic tool - thanks for doing this.

I'm wondering about 2 things.
1. I'd love to be able to enter inline comments.
Something like this ...
[A]This is the Chorus [D]Isn't it wonderful      {C: With distortion}

2. I'm trying to display tempo in a couple of charts and I'm not sure how to do it.
I've tried {tempo: 80} and {meta: tempo 80}, neither displayed anything on the chart.
Are you able to give some guidance in how to do that?

Great tool for creating charts.

Cheers

**Comment by sciurius** [comment]
1. Inline comments are not yet possible. This will change in the near
future. In the mean time, use ordinary comments.
Sometimes you can get interesting results by fakings a chord, e.g.

[A]This is the Chorus [D]Isn't it wonderful [With distortion]

2. The tempo and many of the other meta data is not included in the output
by default. You can adapt the page headings to include this information.

https://www.chordpro.org/chordpro/ChordPro-Configuration-PDF.html#page-headers-and-footers
