### ISSUE TITLE
RC2: Problem Found warning when Debugging in PDF is enabled

### ISSUE THREAD

**Issue by mlos100** [ChordPro/chordpro#491]
**Severity:** Unknown

## Describe the bug
I apologize in advance if this warning is expected behavior.  When I generate a PDF preview when Help Enable Debugging in PDF is selected, a Problem found warning message is printed.

### To Reproduce

1. Start Chordpro
2. Open an Example Song
3. Click the Messages button to open the Messages panel.
4. Click th Preview button generate a PDF preview and open the Preview Panel.
5. Note a message a appears with the location of the Preview file.
6. Select File | Export to PDF and save the PDF
7. Select Help | Enable Debugging in PDF
8. Enter Ctrl-P to regenerate the PDF preview.
9. Note a Warning message appears in the messages panel
10. Select File | Export to PDF and save the PDF
11. Deselect Help | Enable Debugging in PDF
12. Note a message a appears with the location of the Preview file and no warning.

The Message Panel content from the above follows:
```
10:35:27: Preview file:///C|/Users/mlos1/AppData/Local/Temp/t2WOMv5JPs.pdf
10:38:19: Warning: ChordPro invoked: --nodefaultconfigs --config F:\hp-e9150T-documents\hobby\Guitar\Chords\chordPro\config\mel-1col-textArial14-LeftTitle.json --output C:\Users\mlos1\AppData\Local\Temp\t2WOMv5JPs.pdf --generate PDF --define diagnostics.format=Line %n, %m C:\Users\mlos1\AppData\Local\Temp\t2WOMv5JPs.cho --progress_callback CODE(0x15fa97b8)
10:38:21: Preview file:///C|/Users/mlos1/AppData/Local/Temp/t2WOMv5JPs.pdf
10:38:21: 1 message
10:38:21: Warning: Problems found.
10:39:02: Preview file:///C|/Users/mlos1/AppData/Local/Temp/t2WOMv5JPs.pdf
```
### Expected behavior
I don't expect a Problem found warning. An informational message that PDF debugging is enabled (and thus being included in the PDF) is reasonable.

## System information
 - OS: Windows 10
 - ChordPro version: filename: 6-69-1-1

### Attachments
PDF without debugging information - [example.pdf](https://github.com/user-attachments/files/18231172/example.pdf)
PDF with Debugging Information enabled - [example+debug.pdf](https://github.com/user-attachments/files/18231173/example%2Bdebug.pdf)

**Comment by sciurius** [comment]
The message "ChordPro invoked: ..." is generated by the core and issued as a warning. I've made an exception for this case.

**Comment by mlos100** [comment]
Dev Version: : 6-60-233-1
There is no longer a Problems Found warning after generating the PDF Preview when PDF Debugging Info is enabled.
Closing as Resolved.
