### ISSUE TITLE
Specification of file extensions 

### ISSUE THREAD

**Issue by Jon-Salmon** [ChordPro/chordpro#50]
In the old version of the specification there was a section giving guidance on what file extensions to use for ChordPro files. I've typically used the .cho extention in the past, but recall having seen several alternatives used in the past.

Would it be possible to have a section in the new ChordPro specification giving guidance on the recommended file extension?

**Comment by Jon-Salmon** [comment]
Thanks, that clears things up nicely

**Comment by Richard-KRSP** [comment]
Casn I just point out, it should read "advise": 

https://dictionary.cambridge.org/us/grammar/british-grammar/advice-or-advise

**Comment by sciurius** [comment]
Fixed, thanks.
