### ISSUE TITLE
uninitialized value

### ISSUE THREAD

**Issue by mtarenskeen** [ChordPro/chordpro#52]
I am always getting this error since version 0.960_042:

```
Use of uninitialized value in string eq at /home/m.tarenskeen/perl5/lib/perl5/App/Music/ChordPro/Config.pm line 736, <$fd> chunk 1.
Invalid tuning in config: Invalid tuning (not array)
Can't call method "parse" on an undefined value at /home/m.tarenskeen/perl5/lib/perl5/App/Music/ChordPro/Chords.pm line 325.
```

**Comment by sciurius** [comment]
Yes, the current dev branch is a bit unstable at certain points due to the gross rework of the configs, chords and notes handling. I hope to finalize the changes today.
Sorry for the inconvenience.
I have pushed 0.960_043 to github, does this work better?

**Comment by mtarenskeen** [comment]
> Sorry for the inconvenience.
> I have pushed 0.960_043 to github, does this work better?

I am afraid not, same error messages.

**Comment by mtarenskeen** [comment]
Clicked on "close" by accident ... but issue should be still open. Don't know how to re-open?

**Comment by mtarenskeen** [comment]
found button saying "reopen" :-)

**Comment by sciurius** [comment]
Please pull again (0.960_044).
If the issue persists please send me a song/config to reproduce.
