### ISSUE TITLE
Use of uninitialized value in File "Interpolate/Named.pm"

### ISSUE THREAD

**Issue by beckthomas** [ChordPro/chordpro#54]
After updating to the newest Version of ChordPro I get the following Error (several Lines) when trying to chordify a .cho-file:
`Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm `

I am Using Linux (actual Ubuntu Version), 
ChordProVersion 0.972
Perl Version 5.26.1

**Comment by sciurius** [comment]
Can you append the .cho file?

**Comment by beckthomas** [comment]
I have added a .cho-File (the error occurs to all my .cho-Files I have tested):
[Test.cho.txt](https://github.com/ChordPro/chordpro/files/2569467/Test.cho.txt)

the pdf will be generated, but the error message is irritating because I don't know what's wrong
here is the complete stacktace:
`beckthomas@beckthomas:/media/beckthomas/MediaDaten/Songs/chordpro_Songs$ chordpro Test.cho --config=beckthomas_config.json
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 102.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 103.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 104.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 105.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 108.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 109.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 113.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 125.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 126.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 127.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 128.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 131.
Use of uninitialized value $tpl in substitution (s///) at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 132.
Use of uninitialized value $prev in string eq at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 134.
Use of uninitialized value $tpl in string eq at /usr/local/share/perl/5.26.1/String/Interpolate/Named.pm line 134.
Use of uninitialized value $f in string ne at /usr/local/share/perl/5.26.1/App/Music/ChordPro.pm line 172.
Use of uninitialized value $of in string ne at /usr/local/share/perl/5.26.1/App/Music/ChordPro.pm line 172.
`
my config.json - File is the print-out of the default config (with only changing the color of the chords)

**Comment by sciurius** [comment]
Just specify an output file and the messages will disappear. I will fix it in the next version.

**Comment by beckthomas** [comment]
specifying the outputfile with "--output=Test.pdf" worked fine, the error doesn't show up 
Thank you
