### ISSUE TITLE
[Feature request] 'Chunk' chord support

### ISSUE THREAD

**Issue by dogfishmoon** [ChordPro/chordpro#59]
Would it be possible to add support for 'chunk' chords (i.e. played with all strings muted)? I can't see anything about this in the documentation. I tried adding chords like [X] and I get a bunch of messages like this:

`
Use of uninitialized value $a0 in hash element at /Library/Perl/5.18/App/Music/ChordPro/Chords.pm line 54.
Use of uninitialized value $b0 in hash element at /Library/Perl/5.18/App/Music/ChordPro/Chords.pm line 55.
`

It outputs Xs in the final PDF anyway, but it would be nicer if this were a documented fetaure without the messages...

**Comment by sciurius** [comment]
I can't reproduce the warnings, apparently this has already been fixed in the development version.

**Comment by dogfishmoon** [comment]
Thanks for the fast response!

I can't see any reference to 'NC' in the documentation, but maybe I'm just looking in the wrong place. I don't think it's quite the same thing, though. NC seems to indicate that nothing should be played where there's normally a chord. Chunking is common in ukulele playing, where the strings are muted but you still play for a percussive effect. When writing strumming patterns this is often written with an 'X' (DUXU) but there are songs where I just want a reminder to use this technique when I would normally play chords, and so it would be useful to write an X here.

I guess if chordpro just writes the 'X' as-is and doesn't have a problem if I transpose the song then it's fine, it would be nice to know that this is officially supported and won't break in a future version.

**Comment by sciurius** [comment]
I see what you mean.
You can define a X chord with all strings muted. It will not give warnings when used, and not show up in the diagrams. This is equivalent to a NC chord.

**Comment by dogfishmoon** [comment]
OK, thanks, then I'll close the issue
