### ISSUE TITLE
No chord diagrams created for unknown chords

### ISSUE THREAD

**Issue by dogfishmoon** [ChordPro/chordpro#61]
I just upgraded from an older version, and it seems that empty chord diagrams are no longer created if a chord is unknown, even though my configuration is unchanged:

`    "diagrams" : {
        "auto" : true,
        "show" : "all",
        "sorted" : true
    },`

from the documentation:

> // "auto": automatically add unknown chords as empty diagrams.

**Comment by sciurius** [comment]
Good catch. Fixed in the dev version in Git.
