### ISSUE TITLE
CLI on Windows 10 not working

### ISSUE THREAD

**Issue by stu-b-doo** [ChordPro/chordpro#62]
No output (stdout messages or files) from CLI on Windows 10.

The GUI version I installed works fine but the CLI just hangs for any commands. Would be useful if someone could replicate this result or suggest anything I could try to fix it!

CLI downloaded from [sourceforge](https://sourceforge.net/projects/chordii/files/chordii/5.0/) as linked from [this page](https://github.com/ChordPro/chordpro/wiki/Install-Windows-Native)

CLI Version downloaded (doesn't work): ChordPro-CLI-0-972-0-1-msw-x64.zip

GUI version downloaded (works fine): ChordPro-GUI-installer-0-972-0-1-msw-x64.exe

chordpro just hangs until terminated with Ctrl-C:

```
$ ./chordpro.exe --about
Terminating on signal SIGINT(2)
```

perl
```
$ perl --version
This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-msys-thread-multi
```

os
```
 Microsoft Windows 10 Home
 10.0.17134 N/A Build 17134
```

**Comment by sciurius** [comment]
Does `./chordpro.exe --version` produce a result?

Note that the binaries downloadable from SourceForge are self-contained executables and do not use the system installed perl.

**Comment by stu-b-doo** [comment]
@sciurius, thanks for getting back to us. Apologies for wasting your time. Everything appears to be working fine now! Neat program :)
