### ISSUE TITLE
Labels are lost when a new song is found

### ISSUE THREAD

**Issue by dogfishmoon** [ChordPro/chordpro#63]
The labels for a song are lost when a new song is subsequently found in the input file. When the song is the last song in the input file then the labels are created correctly.

The following patch seems to fix this by making a copy of the labels rather than reusing the same array reference:

```
--- a/lib/App/Music/ChordPro/Songbook.pm
+++ b/lib/App/Music/ChordPro/Songbook.pm
@@ -185,7 +185,7 @@ sub parse_song {
       if $in_context;

     if ( @labels ) {
-       $song->{labels} = \@labels;
+       $song->{labels} = [ @labels ];
     }

     my $diagrams;
```

**Comment by sciurius** [comment]
Thanks. Fixed in git.
