### ISSUE TITLE
How do I do diminished chords in roman numerals?

### ISSUE THREAD

**Issue by wolftune** [ChordPro/chordpro#64]
The standard is to use a symbol like °

But that doesn't render right when I try it. And something like [vdim] isn't really right or look good.

Is there any other clarity about how to do this?

**Comment by sciurius** [comment]
A small o [vo] should do the trick.

**Comment by wolftune** [comment]
Thanks for the fix! The `vo` option didn't really look right at all.

Would it also be possible to make ø not just work (it works right now) but be rendered superscript?

**Comment by sciurius** [comment]
This should be part of the fix I mentioned.
If you can run from the development git you can try it.

**Comment by sciurius** [comment]
Thanks for the feedback... I'm not familiar with Roman notation so I depend on your findings.

**Comment by wolftune** [comment]
How do I run the development git version? I didn't find instructions about that looking through the wiki or repo.

One quirk: I can get ° to render as desired because it *looks* like superscript in the natural not-actually-superscript font rendering. But ø is not like that. However, the symbol for "half-diminished" is a superscript version of ø and I'm not aware of how to get that besides making it superscript, in the same way that any character can be — however the ° should not be superscript as that would exaggerate the already superscript look.
