### ISSUE TITLE
display tuning

### ISSUE THREAD

**Issue by feurry** [ChordPro/chordpro#66]
I can display the Tempo and Capo in the pdf output by adding the following to my ChordPro song and my custom config, but I can't figure out how to display the tuning in the title. How can I show the tuning in the title?

ChordPro song file
{title: Song Name}
{artist: Artist Name}
{instrument: Guitar}
{tuning: E A D G B E}
{tempo: 120}
{capo: 2}

"title" : {
	        // Title and artist.
	    	"title"     : [ "", "%{title}", "" ],
	    	"subtitle"  : [ "%{tuning}", "%{artist}", "%{tempo|Tempo: %{}}%{capo|, Capo: %{}}" ],

**Comment by sciurius** [comment]
Did you add tuning and instrument to the metadata keys?

    "metadata" : {
        "keys" : [ "append", "tuning", "instrument" ],
    },

Are you using 0.972 or newer?

**Comment by feurry** [comment]
ChordPro version 0.972
No, I did not add tuning to the metadata keys. I added it and it works. Thank you.

"metadata" : {
      "keys" : [ "title", "subtitle",
                 "artist", "composer", "lyricist", "arranger",
                 "album", "copyright", "year",
                 "key", "time", "tempo", "capo", "duration",
                 "tuning", "instrument" ],
      "strict" : true,
      "separator" : "; ",
    },

I saw this section of the config, and thought this was responsible for it.

    // Instrument settings. These are usually set by a separate
    // config file.
    //
    "instrument" : null,

    // Note (chord root) names.
    // Strings and tuning.
    "tuning" : [ "E2", "A2", "D3", "G3", "B3", "E4" ],

**Comment by sciurius** [comment]
Actually you have a point.
I'll turn the instrument and tuning settings into meta data so you do not have to set it explicitly. Thanks!
