### ISSUE TITLE
Recalled quoted chorus is recalled also in other song with {Chorus} tag

### ISSUE THREAD

**Issue by stueja** [ChordPro/chordpro#68]
Creating a songbook using
```
chordpro --config=gitarre.cfg --output=songbook.pdf *.txt
```
will recall the {Chorus} of Song#1 in Song#3, if Song#2 does not have a {Chorus} tag, and Song#3 has one.

gitarre.cfg:
```
    "chorus" : {
      // Indentation of the chorus.
      "indent"     :  0,
      // Chorus side bar.
      // Suppress by setting offset and/or width to zero.
      "bar" : {
           "offset" :  8,
           "width"  :  1,
           "color"  : "black",
      },
      // Recall style: Print the tag using the type.
      // Optionally quote the lines of the preceding chorus.
      "recall" : {
           "tag"   : "Chorus",
           "type"  : "comment",
           "quote" : true,
      },
    },
```

[Budapest (George Ezra).txt](https://github.com/ChordPro/chordpro/files/3271407/Budapest.George.Ezra.txt)
[I'm yours (Jason Mraz).txt](https://github.com/ChordPro/chordpro/files/3271408/I.m.yours.Jason.Mraz.txt)
[Listen To The Man (George Ezra).txt](https://github.com/ChordPro/chordpro/files/3271409/Listen.To.The.Man.George.Ezra.txt)
[songbook.pdf](https://github.com/ChordPro/chordpro/files/3271410/songbook.pdf)

**Comment by sciurius** [comment]
What I see is that if a song has a `{chorus}` without preceding `{start_of_chorus}` section, it will use the last chorus of the preceding song. Is that what you mean?

**Comment by stueja** [comment]
Aah, so the `{start_of_chorus}` does not need to be prepended by `{Chorus}` to make this work. This looked different to me in the wiki. 
Tried with 'only' `{start_of_chorus}`, works as expected. Thanks for your swift reply!
