### ISSUE TITLE
How do I get more info about --transcode= option? 

### ISSUE THREAD

**Issue by Gajusbonus** [ChordPro/chordpro#69]
Need to transcode to nashville numbers, but can't find the cli options in documentation.
Seems to be working in wxchordpro, but using the json config in chordpro does not output in expected nashville.

This is ChordPro version 0.973
--transcode=SYS  -xc          Transcodes to notation system

![prefs](https://user-images.githubusercontent.com/7600670/59496743-67d6a380-8e92-11e9-9642-e150b1f8c977.png)
~/Dropbox/My Songs $ chordpro --config=nash-conf2.json --transcode=r "Greensleeves - Traditional.pro" --output=out.pdf

**Comment by sciurius** [comment]
You are right, this is currently missing from the docs.

Not suprisingly, the cli options is `transcode`, so:

    chordpro --transcode nashville mysong.cho

**Comment by Gajusbonus** [comment]
solved
