### ISSUE TITLE
[question] Optional chords

### ISSUE THREAD

**Issue by Drieger** [ChordPro/chordpro#70]
How can I add a list of chords in parenthesis, for example (F C G C)?. I didn't find anything in the docs.

**Comment by sciurius** [comment]
You can put virtually anything between chord braces so I think you can do

      ...[(][F]...[C]...[G]...[C][)]...

Does this help?

**Comment by Drieger** [comment]
@sciurius Yes it does. Thank you very much!

**Comment by sciurius** [comment]
A user community discussing ChordPro can be found at
https://groups.google.com/forum/#!forum/chordpro
