### ISSUE TITLE
Trouble defining chords with "don't play" strings in config file

### ISSUE THREAD

**Issue by keithdr00** [ChordPro/chordpro#71]
I am trying to add D2 as a chord in my custom config file. I have tried the following:

	{
		"name"  : "D2",
		"base"  : 1,
		"frets" : [ x, x, 0, 2, 3, 0 ],
	},
But this results in some sort of parsing error:
>  : malformed JSON string, neither array, object, number, string or atom, at character offset 2954 (before "x, x, 0, 2, 3, 0 ],\r...") at App/Music/ChordPro/Config.pm line 618.
>  : Fatal problems found!

So then I tried

	{
		"name"  : "D2",
		"base"  : 1,
		"frets" : [ 'x', 'x', 0, 2, 3, 0 ],
	},

Which resulted in the same error.

Finally I tried:

	{
		"name"  : "D2",
		"base"  : 1,
		"frets" : [ "x", "x", 0, 2, 3, 0 ],
	},
Which resulted in:
>  : Argument "x" isn't numeric in numeric ge (>=) at App/Music/ChordPro/Output/PDF.pm line 1633.
>  : Problems found!

In this last case the chord was printed but with the "don't play" strings shown as open strings.

Is this a bug, or is there something I'm doing wrong in my definition? Thanks!!!!

**Comment by hongjes1** [comment]
I'm looking through the config.pm file, and when searching for "mute", it
says to use the integer value -1. Try that?

**Comment by sciurius** [comment]
I'd say it is right here in the docs: "Use 0 for an empty string, and -1 for a muted string."

https://www.chordpro.org/chordpro/ChordPro-Configuration-Generic.html#user-defined-chords

**Comment by keithdr00** [comment]
It sure is right there in the docs. Man I looked all over that wiki page multiple times, but never looked closely at the comments in code block. Sorry for the noise, using -1 certainly does work fine. Sorry for the noise. Thanks for the quick response.
