### ISSUE TITLE
Eadd4 chord not transposed

### ISSUE THREAD

**Issue by keithdr00** [ChordPro/chordpro#72]
I have a song in the key of A which has an Eadd4 chord. When using chordpro to transpose from the key of A to the key of G this Eadd4 does not get transposed to Dadd4 as it should. There are some Asus chords that do get properly transposed to Gsus, so the problem seems to be specific to the Eadd4. I have tried both Eadd4 and E(add4), and both fail.

**Comment by sciurius** [comment]
The reason is that `add4` is not a known chord type. I'll add it to the list in the next release.

**Comment by keithdr00** [comment]
If I've added that chord in my custom config file, should the transposition work, or does transposing only work with the built-in list of chords?

**Comment by sciurius** [comment]
Currently, yes. Automatically adding chord types is on the TODO list.
