### ISSUE TITLE
User chord not drawn completely

### ISSUE THREAD

**Issue by lauhub** [ChordPro/chordpro#74]
Defining a user chord does not work.

```
{chord: Eb base-fret 4 frets N 6 5 0 4 6 }
```

Chordpro draws the little grid without any finger position. The base fret is drawn.

<img width="77" alt="chordEb" src="https://user-images.githubusercontent.com/3216214/66198001-c91dbf00-e69b-11e9-88a0-f8c1e75ce19b.png">

Tested on both Linux (Elementary OS 5.0) and macOS Mojave with  ChordPro version 0.973

**Comment by sciurius** [comment]
You need to specify the finger positions relative to the base fret.

**Comment by lauhub** [comment]
Sorry, but this does not work either. The examples given in the documentation do not work:

```
{chord: Bes base-fret 1 frets 1 1 3 3 3 1 fingers 1 1 2 3 4 1}
{chord: As  base-fret 4 frets 1 3 3 2 1 1 fingers 1 3 4 2 1 1}
```

The definition above print empty grid without any dot drawn.

**Comment by sciurius** [comment]
Interesting... The chords come out fine at the end of the page but not when used in a {chord} directive... I'll take a look.

**Comment by sciurius** [comment]
Turns out to be a remnant of the last rework of the chords code. Sorry for that.

If you are able to modify the sources, change line 1011 of lib/App/Music/ChordPro/Songbook.pm to read
`                         frets => $res->{frets},`

(it currently has `strings => $res->{frets}` instead).

**Comment by lauhub** [comment]
Nice job, it works now 😃 
Turns out it is a great tool for all the songs I have
Thank you for your work 🥇

**Comment by sciurius** [comment]
Thanks.
May I invite you to join the user community at https://groups.google.com/forum/#!forum/chordpro ?
