### ISSUE TITLE
Page break directive

### ISSUE THREAD

**Issue by kylemhall** [ChordPro/chordpro#76]
It would be really nice if we could have something like `{pagebreak}` for formatting printed materials.

For example, I often find my PDF output splits a verse. Right now I have to manually find the correct number of newlines to push it into the next page in full. Not only is this a manual add-and-rebuild effort until I get the right number of breaks, but those extra lines show up in chordpro reading software like SongBook where the final destination is a screen and not a PDF.

**Comment by sciurius** [comment]
You did read https://www.chordpro.org/chordpro/ChordPro-Directives.html#output-related-directives, did you?

**Comment by kylemhall** [comment]
Nope! Thanks! My google-fu failed me!
