### ISSUE TITLE
Read from ~/.config/chordpro/foobar.json ?

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [ChordPro/chordpro#77]
Given that I, for one, as someone whose language uses the Devanagari script, have to use `--config myconfig.json` all the time (basically), I was wondering if it'd be easier if chordpro read from ~/.config/chordpro/foobar.json by default or something. I could alias `chordpro` to `chordpro --config myconfig.json` as a work-around, but still just a thought.

**Comment by sciurius** [comment]
ChordPro processes several config files, one of them is ~/.config/chordpro/chordpro.json. I suggest you put your settings in that file.
See e.g. https://groups.google.com/d/msg/chordpro/jo83cI6XeCc/BX6IbVckDgAJ.

**Comment by peanutbutterandcrackers** [comment]
Thank you. That makes sense. I wasn't aware of this. Sorry for the false alarm.
