### ISSUE TITLE
Conditional metadata in config file: doubled escape character (\ \) issue

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#78]
My chordpro.json config file has a line to include key, time, tempo etc in the title line, separated by a vertical line (|), if those values exist:
`title"     : [ "%{key|%{}  \\|  }%{time|%{}  \\|  }%{tempo|~%{}bpm  \\|  }%{capo|capo %{}}", "", "%{title}" ],`

This was previously working as documented at [https://www.chordpro.org/chordpro/ChordPro-Configuration-Format-Strings.html](url) and placed a | separator between key, time and tempo (if present), in response to `\\|` in the conditional substitution. I'm not sure what version I was using previously, but hadn't updated for a while. Possibly .93 or .94.

With the latest update (0.974), output (between key, time, tempo etc) is `\|` (not `|` as expected).

 Changing `\\|` to `\|` in the conditional substitution returns an error:
`illegal backslash escape sequence in string, at character offset 7491 (before "\\|  }%{time|%{}  \\...") at /usr/local/share/perl/5.24.1/App/Music/ChordPro/Config.pm line 618.`
Changing `\\|` to `|` in the conditional substitution seems to simply treat | as a true/false separator (as expected), so no errors, but no | in output.

Platform is Linux (LMDE3, based on Debian Jessie).

**Comment by sciurius** [comment]
This error was introduced in 0.972, when ChordPro started to use CPAN module String::Interpolate::Named for substitution. Sorry for the inconvenience!
Please upgrade to String::Interpolate::Named version 1.00 or later.
