### ISSUE TITLE
Indent of chorus indents the lable too

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#81]
If you put the following into the pdf section of the config:
`	"chorus" : {
	    "indent"     :  12,
	    "bar" : {
		"width"  :  0.5,
	    },
	},
`

The lyrics part of the chorus gets indented, as expected. But also the title (e.g.`{start_of_chorus: Title}`) which makes it look odd on the page as it doesn't line up with other section titles (e.g. `{start_of_verse: Verse 1}` or `{start_of_bridge: Bridge}`).

But when you increase the indent to something high (e.g. 120) it becomes apparent that the current behaviour actually makes sense.

Maybe it would be nice to have a way to achieve both, either to indent the title or not, configurable via a setting.

Ideas in my head right now:

1. **indent-title-column-with-chorus:** _{true/false; default: true}_
This solution has little flexibility. It would however retain the current behaviour.

2. **indent-title-column-at-chorus:** _{float; default: 0}_
This would allow for a fine grained adjustment but would break current behaviour. You would have to set it to the same value as the indent to look as bevor. It could however default to being the same value as the chorus indent. But that would be more implicit and less obvious.

3. **indent-title-column-at-chorus-relative:** _{float; default: 0}_
Allows for a fine grained adjustment too but it would retain current behaviour. If you indent the chorus by 20 but want to title to stay aligned with the other titles, set this value to -20.

The names of the settings should be something clearer and easier than my examples.

**Comment by sciurius** [comment]
All labels for verses and choruses are supposed to be in the left margin, so it is a bug that chorus labels are offsetted with the chorus offset. This has been fixed in the dev branch (all PDF backends).

I like the ideas you offer but implementing would require reworking some essential parts of the PDF backends, and I do not think that is currently worth it.

**Comment by nomike** [comment]
Cool. So it's fixed in the dev-branch. That's suitable for me.
