### ISSUE TITLE
How do I format a chord that is informational but not actually a chord?

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#82]
This for example of course gives me an error during PDF output complaining about an unknown chord:

{start_of_intro: Intro}
[Am][C][G][Am]
{end_of_intro}

{start_of_verse: Verse 1}
[(nothing)]Ain' no sunshine when she's [Am]gone [C][G][Am]
It's not warm when she's away[C][G][Am]
Ain' no sunshine when she's [Em]gone
And she always gone too [Dm]long
Anytime she goes [Am]away[C][G][Am]
{end_of_verse}

So how to do that right?

**Comment by sciurius** [comment]
Please ask questions on how to use ChordPro on the ChordPro user group, https://groups.google.com/forum/#!forum/chordpro

This issue tracker is for bugs and issues.

Thanks!
