### ISSUE TITLE
Title on "{chord: title}" directive makes title column larger

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#83]
With the example chordpro file attached you can see that the title column is getting proportionally wider with the length of the text in the "{chord}" directive.

IMHO the length of the text shouldn't have any effect on that column.

```
nomike@max:~$ chordpro -version
This is ChordPro version 0.974
nomike@max:~$ perl --version
This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi
...

nomike@max:~$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
...
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01

nomike@max:~$ uname -a
Linux max 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

nomike@max:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
```
[test.chopro.gz](https://github.com/ChordPro/chordpro/files/3952456/test.chopro.gz)
[test.pdf](https://github.com/ChordPro/chordpro/files/3952453/test.pdf)

**Comment by sciurius** [comment]
The 'labels' (the text after start_of_verse, start_of_chorus etc) are placed in the left margin, that is set to be as wide as needed for the longest label. 
A bug in 0.974 causes the label for chorus to be displayed in the text area instead of the margin. This bug was recently fixed in the development branch in git.
The correct (but admittingly ugly) output is attached,

[test.pdf](https://github.com/ChordPro/chordpro/files/3952756/test.pdf)

**Comment by nomike** [comment]
What semantics does the "{chorus}" directive carry?
Because if it's just about how it looks like in the PDF I might just use the "{c:} directive (question there is: Does the comment directive except from the rule that labels are printed in the margin?).

And another thing to consider:

Let's say I have a "{start_of_chorus}" and a "{start_of_bridge}" section and want the bridge to be repeated. Do I write "{chorus: Bridge}"?
That doesn't make sense. And you can't just introduce a "{bridge}" section. What about intro's, breaks, etc.?

**Comment by sciurius** [comment]
A chorus has a distinguised look from ordinary song lines. Also, by using `{chorus}` you can have the whole content of the chorus repeated (see https://www.chordpro.org/chordpro/ChordPro-Configuration-PDF.html#chorus-style).

If you want to repeat a `bridge` or any other verse you must write it again. There are no provisions to repeat/quote anything but `chorus`.
