### ISSUE TITLE
Feature Request: Make TOC entries more flexible

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#86]
I'm proposing a feature to make TOC entriesmore flexible.

A config value should be introduced which allows the user to specify a format string for the TOC.

The string could contain literal text:
```
Hello world!
```

Special commands exist to put dynamic content into the template:
```
%print{artist}
%print{artist} - %print{title}
```
In order to use a literal "%" it could be escaped by prepending it with a "\":
```
This is a literal %%{ and neither it nor the { have syntactical value
```

In order to be able to print the artist only if it is specified, an "if" command is also available:
```
%if{artist:true:false}   --> This will just print "true" or "false" based on whether artist is defined and is not an empty string. Parameters are separated by colons.
```
The else clause is optional and defaults to an empty string:
```
%if{artist:The artist}
```
If you want to add a literal ":" or "}" to the if, it can be escaped with a backslash:
```
%if{artist:Artist\:}
```

Things can be nested, so the if starts to make sense:
```
%if{artist:\%\{title\} - \%\{artist\}:\%\{title\}}
```
which requires things to be escaped of course.

It can be nested to an arbitrary level:
```
%if{artist:\%{title\} - \%\{artist\}:\%if\{subtitle:\\\%\\\{title\\\} - \\\%\\\{subtitle\\\}:\\\%\\\{title\\\}\}}
```
This makes escaping more difficult, but in C and other programming languages it's the same, so I think this is acceptable.

As shown in previous examples, the command name could be ommited, in which case it defaults to "print":
```
%{artist}
```

#### %print{<metadataname>}
inserts the value of <metadataname>

#### %if{<if>:<then>:[<else>]}
checks if <if> is an existing metadata entry and it's value is not the empty string.

If True, the content of the "<then>" parameter is inserted. If not, the content of the "<else>" parameter is inserted if it is specified. Otherwise nothing is inserted.

### Example script
I've written a simple statemachine in python to parse the proposed format and will attach it to this issue.

It's not tested thoroughly enough I'm afraid, but I've tested for some edge cases.
Feel free to use or modify it under the terms of either the GPLv3 or the artistic license.

Unfortunately I don't have much experience in writing perl code, but it shouldn't be that hard to convert. I'm using no library functions at all.

**Comment by nomike** [comment]
Python 3 sourcecode:
[parser.py.txt](https://github.com/ChordPro/chordpro/files/4019106/parser.py.txt)

**Comment by sciurius** [comment]
Did you look at https://www.chordpro.org/chordpro/ChordPro-Configuration-Format-Strings.html ?

**Comment by nomike** [comment]
Oh. No, I didn't.
So there is already a feature like that.

Cool.

Then it should be even easier to implement.

**Comment by sciurius** [comment]
The current development version (in git) now supports a new config `toc.line`. This is a string that can contain `%{`...`}` meta keywords. It may also contain `\n` (backslash-n) to obtain multi-line toc entries.
Default value for `toc.line` is `"%{title}"` (same behaviour as until now).

Note: Not supported in the Legacy PDF version. You'll need the Pango or Markup versions (which you are problably using already).

**Comment by nomike** [comment]
The existing branches are a bit confusing.
There is "pango" and "markup" which as far as I read in the google group in some comment, are representing the pango and markup version accordingly.
But they are both several commits behind master, so maybe some merging is due.

But then there is the "dev" branch, which contains your commit, and I'm not sure if this is using "pango" or "markup" or even the legacy rendering engine. Or is there a config flag now for choosing?

Regardless: I checked out the latest "dev" branch, and did a "make install" and when I now create my songbook, it says "No support for cover pages in this version." which is fine, most likely you haven't come around implementing this with the new version just yet.

A few things I noticed:
1. the "dev" version says "No support for cover pages in this version.". I guess you haven't come around implementing this within the new version yet. So it's fine. I will use an external tool to stick those two together for the moment. And page numbering is screwed up anyway at the moment, so it's not that big of a deal.
2. the TOC is now appended to the end of the PDF, right after two empty pages instead of being at the start of the page. I assume this is unrelated to this new change.I can provide an example to reproduce, but I just called chordpro with two chopro files and the default config, so it shouid be easy to reproduce.
3. I could use "%{page}" as part of the TOC string. This allows for having the page number be behind the entry (as it is usual with TOCs). The issue with that is, that there is still the page number in front of the entry. So instead of having the page numbers hardcoded in the TOC, they should be part of toc.line and it should default to `"%{page}. %{title}"`.
4. As you can put the page-number to the end of the TOC entry now, it would be nice to be able to right-justify it. But this might be harder to implement (like what should I write in toc.string to have something right-justified? How to deal with RTL Text, etc?). So maybe it would just be nicer to have a config setting toc.numbercolumn which defaults to "left" to maintain backwards compatibility but can also be "right".
5. If you implement it like I mentioned in 3., the page numbers will no longer be that nicely right-justified, so the rendering will look different. It would be possible to compensate a bit by defaulting to `"%{page}.\\t%{title}"` but this would still look different and will only work if the page numbers don't get too big (I've seen a PDF once with over 1000 songs in it, but it was not created using chordpro).
6. The `%{page}` variable is slightly off most of the time. I will check if I can identify a pattern. But this might warrant a new issue (see screenshot below for an example).
7. The old approach of having the page numbers hardcoded in the TOC seem to use a table or columns or something, so you can not simply copy paste single or multiple entries from it: ![toc-selection.png](https://user-images.githubusercontent.com/1063307/72096207-05eff680-331a-11ea-9f1e-1fecf4f9f720.png).
8. With this new version, TOC entries are no longer clickable links pointing to the songs when within a PDF reader. But I guess that's due to the new rendering engine as well.
9. Putting variables in toc.line works as expected. So the implementation of this new feature is great. It's other things or additional enhancements which I mentioned.

Just comment a list of points I should create a separate issue for if you'd like me to do that. I'm happy to help.

**Comment by nomike** [comment]
So, I had a look at my songbook again and `%{page}` contains the last page of a song and not the first one. If this is intended, then it's un-intuitive. But I rather assume it's a bug.

**Comment by sciurius** [comment]
Sorry for the confusion. The pango and markup branches are remnants of the
status before the code was merged into the dev branch. So, as you
concluded, the dev branch is the one and only development branch.

I've renamed the pango and markup branches as OBSOLETE.

> But then there is the "dev" branch, which contains your commit, and I'm
> not sure if this is using "pango" or "markup" or even the legacy
> rendering engine. Or is there a config flag now for choosing?

The `dev` branch is all three... See
https://groups.google.com/d/msg/chordpro/X8wBjsX-nHA/hMahGw-FCwAJ

> Regardless: I checked out the latest "dev" branch, and did a "make
> install" and when I now create my songbook, it says "No support for cover
> pages in this version."

So you are using Pango. Good.

Cover support in the Pango version will be added later.

If you install module Text::Layout and set environment variable CHORDPRO_PDF
to PDF::API2 then the non-Pango version (with cover support) will be used.

> And page numbering is screwed up anyway at the moment, so it's not that
> big of a deal.

Yes, that's the next step I'm working on.

> the TOC is now appended to the end of the PDF,

That is a temporary restriction in the Pango driver. Please try the
non-Pango version.

> I could use "%{page}" as part of the TOC string. This allows for having
> the page number be behind the entry (as it is usual with TOCs). The issue
> with that is, that there is still the page number in front of the entry.

Yes, that needs to be dealt with. Currently do not use %{page} since it has
no usable value.

> As you can put the page-number to the end of the TOC entry now, it would be
> nice to be able to right-justify it.

Also on the list of things to do.

> How to deal with RTL Text, etc?).

Later. Later. Maybe...

> The old approach of having the page
> numbers hardcoded in the TOC seem to use a table or columns or something,
> so you can not simply copy paste single or multiple entries from
> it: 

Ah! Needs rework.

You can consider the current implementation a 'phase 1'. More will follow.

First I like to tackle the page ordering and page alignment, as per issue
#87.

**Comment by sciurius** [comment]
The table of contents handling has been revamped. Multiple tables can now be generated, with flexible ordering criteria and layout.

Please see https://groups.io/g/ChordPro/message/162 for some details.
Documentation at https://www.chordpro.org/beta/chordpro-configuration-generic/ .
