### ISSUE TITLE
File-Save dialog is not shown when you close the wxchordpro window

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#93]
**Describe the bug**
When a chord file is being edited and it has unsaved changes, closing the wxchordpro window via the window manager (<alt>+<f4>, <command>+<q>, the close button in the window decoration, etc.) it does not ask if the user wants to save the file.

**To Reproduce**
1. Start wxchordpro and open a file
2. Change something
3. Close the window

**Actual behavior**
wxchordpro closes and the changes to the file are lost

**Expected behavior**
A dialog should pop up asking the user if they want to save the changes to the file.

**Comment by nomike** [comment]
I assume an EventHandler for wxCloseEvent needs to be added.

**Comment by sciurius** [comment]
Fixed in 0.977.
