### ISSUE TITLE
Feature: Show the filename and whether a file is dirty in the window title of wxchordpro

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#94]
If you open a file in an editor, it shows the filename in the window title. wxchordpro should do the same.

In addition, most programs visually indicate if a file being edited has been changed (in other words is dirty).
The most common thing in use is to add a "*" to the window title.
There doesn't seem to be a consensus about whether ro append or prepend the star.

gedit's window title looks like this (note that the program name is not used, I don't like that personally):
`*blah.txt`

KeePass2 on the other hand appends the star, so it becoms:
`personal.kdbx* - KeePass`

**Comment by sciurius** [comment]
Implemented in the dev version.
