### ISSUE TITLE
wxchordpro: Undo is not working

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#95]
**Describe the bug**
Undo is not working. Most likely redo as well, but there is no way to tell without a working undo.

**To Reproduce**
1. Open a file in wxchordpro
2. Change something
3. Try to undo either with pressing <ctrl>+<z> or using the menu option

**Actual behavior**
Nothing visibly happens.

**Expected behavior**
The last edit should be undone.

**Please complete the following information:**
![image](https://user-images.githubusercontent.com/1063307/73031211-c78b2900-3e3b-11ea-8862-8434a49a39db.png)

**Comment by sciurius** [comment]
The WxChordPro main window is not intended to be a full blown editor, it provides a view on the ChordPro file and allows basic changes only.

If you require more than what the basic interface provides please use the command line version in combination with your favourite text editor.

**Comment by nomike** [comment]
Yeah, I fully understand that. I've never actually used the GUI myself, just tried it out recently out of curiosity.
But if undo and redo are not working, then the entries should be removed from the menu at least.

**Comment by ChordPro** [comment]
It's slightly more complex. Depending on the underlying platform undo/redo is or is not available. I've added code to detect this, and disable the menu entries if the functionality is not present.

**Comment by sciurius** [comment]
The next version will have a more powerful editor, with decent Undo capabilities.
