### ISSUE TITLE
Add "T" for thumb in chord diagrams

### ISSUE THREAD

**Issue by sciurius** [ChordPro/chordpro#97]
Add "T" for thumb in chord diagrams.

**Comment by lpinner** [comment]
Thumbs up for this issue hehe :)

**Comment by sciurius** [comment]
How is this, as a compromise?
![scrot20211210093549](https://user-images.githubusercontent.com/1118804/145543044-f30a7831-30d6-4c03-a519-c64f34e78ed3.png)

**Comment by lpinner** [comment]
I already either use `"fingers" : [5, etc... ]` or a non-numeric value so the circle gets left empty as a workaround. Doesn't really matter, just thought a `"fingers" : ["T", etc...]` outputting a circle with a T might be easy. If not, I wouldn't worry

**Comment by sciurius** [comment]
The "circles with 1" etc. are actually glyphs from the ZapfDingbats font. I originally tried to write the white digit on the black circle but that turned out the be quite hard due to imperfect font metrics and roundings. With letters it is even worse.

**Comment by lpinner** [comment]
Perhaps a font with circled letter as well as numbers glyphs like NotoSans Symbol (Open Font License)? 🅣

**Comment by sciurius** [comment]
Yes, but that would mean that ChordPro needs to provide its own fonts, something I am not really looking forward to.

But who knows... one day...?

**Comment by lpinner** [comment]
Fair enough, I'm happy enough with my workaround.

**Comment by sciurius** [comment]
It turned out to be less a hassle than I feared...
In the upcoming version you can use digits 0..9 and letters A..Z.
Note that in the `{define}` directive` the values `-`, `x`, `X`, and `N` are used to designate a string without finger setting.

**Comment by lpinner** [comment]
Fantastic, thankyou.
