### ISSUE TITLE
make clean leaves stuff behind

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#98]
**Describe the bug**
If you run "make" and then "make clean", the following files are left behind:
        Makefile.old
        script/chordpro
        script/wxchordpro

**To Reproduce**
1. Run "make"
2. Run "make clean"
3. Check modified files with "git status"

**Expected behavior**
After running "make clean" no untracked files should be reported by "git status".

**Comment by sciurius** [comment]
This is intentional. You can use `make realclean` to make real clean.
