### ISSUE TITLE
Question: Regarding Text Layout

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [ChordPro/chordpro#99]
I was wondering if chordpro could be used to generate something [similar to this](https://hymnchords.net/files/Come%20Thou%20Fount%20of%20Every%20Blessing.pdf).

If yes, how would one go about doing it?

**Comment by sciurius** [comment]
The [user community](https://groups.google.com/forum/#!forum/chordpro) is a better place to discuss this.
The issue tracker is for bugs and issues.

Anyway, the answer is no, ChordPro cannot do this.

**Comment by peanutbutterandcrackers** [comment]
I am sorry. I wasn't aware of this. (I was helping out in another project that uses GitHub for questions too - and used the label `question` for such issues and hence the error. I will use the user community for questions from now on.)

Are there any plans for chordpro extensibility (in the same vein as lilypond and/or emacs) so that things like this could be possible?

Closing because this isn't the right place. But I would appreciate any information.
